### ISSUE TITLE
UnitOfWork problem due to spl_object_hash collision

### ISSUE THREAD

**Issue by AronSzigetvari** [doctrine/mongodb-odm#1017]
I have run into a very strange problem at flushing, getting the following warnings and exceptions:
 * array_map(): An error occurred while invoking the map callback in  doctrine\mongodb-odm\lib\Doctrine\ODM\MongoDB\Persisters\CollectionPersister.php on line 219
 * Cannot create a DBRef without an identifier. `UnitOfWork::getDocumentIdentifier()` did not return an identifier for class

I have tracked down the problem using bisect to the commit when `DocumentManager::createDBRef()` started to throw an exception if `$this->unitOfWork::getDocumentIdentifier()` doesn't return with an identifier. The problem was there before that, but it was silent.

Finally I could find the root cause of this. UnitOfWork uses an array `documentIdentifiers` to store document ID's indexed by the result of function `spl_object_hash`. There is another array `documentStates`, also indexed by the same values. However the *`spl_object_hash` values are not completely unique*: once an object is not referenced anywhere and gets garbage-collected, the same hash value is reused, this is clearly stated in the documentation of the function (see  http://php.net/manual/en/function.spl-object-hash.php)

Probably it is less of a problem with full documents, but EmbeddedDocuments don't have an ID and therefore not stored in `identityMap`, but their managed state is still stored. See the following scenario (an actual one that happened in my case):
 1. An EmbeddedDocument is persisted 
 2. The EmbeddedDocument is replaced by another instance by a setter in its parent document, 
 3. The old instance is destroyed by garbage collection, but the value `STATE_MANAGED` is still there in `documentStates`.
 4. A new document is persisted, unfortunately its `spl_object_hash` value is the same as the object hash of the already deleted EmbeddedDocument. `UnitOfWork` finds the status STATE_MANAGED for it and thinks that the new document is already managed, its identifier is not written into `documentIdentifiers` causing inconsistency. 
 5. `DocumentManager::getDocumentIdentifier()` is called, unitOfWork doesn't return a document identifier for it, so an Exception is thrown
 6. If documentIdentifier is referenced in a referenceMany association, the map callback fails because of the exception.

The solution I can think of is preventing garbage collection of the documents whose state is stored. 
Since real documents are already stored in identityMap anyway, this could be done by putting persisted documents in a new array in UnitOfWork named something like `embeddedDocumentsKnown`, indexed by `spl_object_hash`. This needs to be done in doPersist for sure, but it may be necessary on other places too, we have to guarantee that all embeddedDocuments that have a state state are stored here, too.
Of course, this means that these EmbeddedDocuments will still occupy memory even if they would be deleted by gc, but probably it is not too much memory, only if we replace a lot of embeddedDocuments and flush too frequently.

The other way would probably be explicitly creating an event in the destructor of the embeddedDocuments and bindig on that event in UnitOfWork, removing the hash from documentStates, but this would require everyone adding extra code to embeddedDocument classes themselves, and I don't think that is a good option.

I am working on this in a forked repo, so I will push a PR when I am ready.

**Comment by mdjaman** [comment]
Any Update? Have same issue when try persist document with referenceMany

**Comment by AronSzigetvari** [comment]
I have a Pull Request for this (https://github.com/doctrine/mongodb-odm/pull/1023 ) that works in our case, however @jwage has another PR that refactors a large part of UnitOfWork logic and it might also solve this problem. 
I should now create an unit test that fails with the current BETA, and test if his fix solves it or not.

**Comment by malarzm** [comment]
#782 has been merged in https://github.com/doctrine/mongodb-odm/commit/b1089b723df8ae2230694a3899941e05d560c41f

**Comment by amirmab** [comment]
please re open:
https://github.com/doctrine/doctrine2/issues/5847

**Comment by AronSzigetvari** [comment]
Thank you for your message, we have just upgraded to PHP7 and got the impression that the problem might have reoccurred, although after someone else's pull request made my test pass.
Since you already have a reproducible error case, maybe your issue should be the one that stays open.

I had a different solution at the time, that prevents SPL object hashes from colliding, but that keeps all the "unnecessary" objects in an array until the UnitOfWork is cleared, and that surely solves the problem, but the doctrine core developers didn't like the idea, because it wastes memory. (I hated the fact too, but didn't see other solution)
You may check it out here: https://github.com/doctrine/mongodb-odm/pull/1023
but I'm afraid that there has been too much rework done to be able to merge it directly now.

**Comment by malarzm** [comment]
@amirmab did the issue hit you or you're just cross linking ORM's issue? If latter then at a time (as @AronSzigetvari correctly recalls) we merged #782 which addressed all reported issues by then. Also there were tests merged (namely [here](https://github.com/doctrine/mongodb-odm/commit/4817908f95ff98bb59242d16ca6e4d53a9082504) and in #1159) which are still passing on both PHP 5.x and 7 (according to [Travis](https://travis-ci.org/doctrine/mongodb-odm)). Saying all that, if somebody comes up with a failing unit tests in ODM we'll try to take another look, although I'd still hope to find better approach than #1023 if the issue indeed persists :)

**Comment by alcaeus** [comment]
@AronSzigetvari which version of ODM are you using? 1.0.5 or dev-master?

I noticed a problem after upgrading to dev-master in one of the larger ODM projects I work with but I haven't been able to pinpoint the change causing it. A seemingly  way to generate conflicts is refreshing a document that contains an `EmbedOne` or `EmbedMany` relationship, as refreshing a document will just throw away the previously contained embedded documents while keeping their spl_object_hash in the identityMap, leading to the collisions.

**Comment by amirmab** [comment]
It hit us in production, please check the attached test case in
https://github.com/doctrine/doctrine2/issues/5847

**Comment by AronSzigetvari** [comment]
My colleague has traced back our problem to a test case, he has already posted an issue: https://github.com/doctrine/mongodb-odm/issues/1428 but now there is a failing test, too: https://github.com/doctrine/mongodb-odm/pull/1429

Since we are trying to move to PHP 7, we were trying to use master, since 1.0.5 doesn't support the mongodb driver that is available for PHP7
