### ISSUE TITLE
getFirstResult nulls Cursor's Limit

### ISSUE THREAD

**Issue by baileylo** [doctrine/mongodb-odm#1018]
## Issue
Running `Doctrine\ODM\MongoDB\Cursor::getSingleResult()` will clear limit from Cursor.

## Example Code
```
<?php

$objects = $myObjectRepo->createQueryBuilder()
    ->limit(10)
    ->getQuery()
    ->execute();

// Access First Result:
$firstObject = $objects->getSingleResult();

// limit has been removed from $objects.
```

## Reason

This is the implementation of `getSingleResult` from `Doctrine\MongoDB\Cursor`.

```
    public function getSingleResult()
    {
        $originalLimit = $this->limit;
        $this->reset();
        $this->limit(1);
        $result = current($this->toArray(false)) ?: null;
        $this->reset();
        $this->limit($originalLimit);
        return $result;
    }
```
It's retrieving the cursors value using `$this->limit`. Since `Doctrine\ODM\MongoDB\Cursor` extends `Doctrine\MongoDB\Cursor`, it has a `cursor` property. `Doctrine\ODM\MongoDB\Cursor` acts as decorator for `Doctrine\MongoDB\Cursor` and should return all values from `Doctrine\ODM\MongoDB\Cursor::$baseCursor`. Accessing the property breaks or ignores this design and returns the null `$limit` value of `Doctrine\ODM\MongoDB\Cursor`.  

This could be fixed by creating a protected accessor `$this->getLimit()` on both Cursors, the ODM cursor though would return the result of `$this->baseCursor->getLimit()`.

**Comment by baileylo** [comment]
For now, I've begun using

```
$firstObject = $objects->getNext();
$objects->reset();
```
Is there a better way to do this?

**Comment by austinh** [comment]
+1 Im running into this as well.

**Comment by malarzm** [comment]
I'm sorry, I must have overlooked this issue before, tagged it to get back here shortly.

**Comment by jmikola** [comment]
@alcaeus: Can you confirm if #1206 will resolve this?

**Comment by alcaeus** [comment]
For the record, yes: https://github.com/doctrine/mongodb-odm/pull/1206/files#diff-6185b26bc6e25640395c937523d4e113R61
