### ISSUE TITLE
Is there support for handling redundant fields for referenced documents?

### ISSUE THREAD

**Issue by luttkens** [doctrine/mongodb-odm#1021]
I have a Contract documents which references the User document associated with the contract using the annotation @ReferenceMany.

To be able to efficiently search the Contract's collections for all contracts referenced to all Users with name "mike" I want to **redundantly** save the User's name in the Contract. This means that whenever a User document is updated it should trigger updates to all Contracts referencing the updated User.

In previous projects (not using mongodb-odm) I have just created custom events to ensure the logic, but I wonder if this behavior is automated or somehow supported mongodb-odm?

**Comment by malarzm** [comment]
As far as I know there's no such feature available out of the box, it'd be the best to implement it using event listeners I believe :)

**Comment by malarzm** [comment]
@luttkens if there's something more you'd like to ask please reopen this issue

**Comment by smolinari** [comment]
Could this also be made a custom mapping type in some way? 

My contemplation is a "formulaFieldType" and depending on what the formula is asking for, it could recursively store or gather information into the documents or even related documents depending on what happens, like when the formula changes or when the data changes. The changing of data on the data source means we'd need to trigger the updates for the referenced side. Adding a simple field from another related document would be the easiest of formulas to do. 

name = user.name

And possibly as annotations.

 ´´´PHP /** @Field(type="formularFieldType", formula="user.name") */ ´´´

Obviously you'd need some sort of interpreter for the formula too.

A formula field could also collect data out of the same or related documents to "formulate" the data stored in this new field type, with a predefined calculation, like changing a birthdate to an age in years or aggregating some data together to sum it up.

I also realize, some formulas must be calculated in real time (like the age in years example and thus can't be searchable with any accuracy and shouldn't be), but the formula to store a field value or other calculated values from related documents could be done with the event listener and stored successfully for searching. I understand, this could get hairy too, depending on the number of documents needing updating....hmm... but an update of the related field data or the formula itself isn't something that should happen too often. It is more than not probably an administrative task.

I don't know. Just throwing out an idea here for a generic new field type, with some very useful utility purposes.:) 

Scott

**Comment by jwage** [comment]
I think this can be accomplished using the event system. preUpdate() prePersist(), etc. The events are there to handle this type of custom functionality without having to have a feature to handle every scenario.

**Comment by smolinari** [comment]
Thanks Jonathan. I'll look into it. I have to.;)

Scott

**Comment by alcaeus** [comment]
@smolinari I've thought about this one multiple times because it would be quite useful. I'd be very interested in whatever you come up with :)

**Comment by smolinari** [comment]
Certainly! It will take a bit though. I am still learning to be honest.:)

Scott
