### ISSUE TITLE
UnitOfWork::getClassNameForAssociation() must be an array, null given

### ISSUE THREAD

**Issue by markrunaway** [doctrine/mongodb-odm#1027]
I get exceptions when loading ReferenceMany and EmbedMany collections containing Null items in the array. The error looks like:
`Argument 2 passed to Doctrine\ODM\MongoDB\UnitOfWork::getClassNameForAssociation() must be an array, null given`

We have tracked down that Null items are being generated in the array when I use "removeElement" from the collection. The ArrayCollection calls PHP's unset function:
[[http://www.doctrine-project.org/api/common/2.1/source-class-Doctrine.Common.Collections.ArrayCollection.html#131-148 ]]

From the mongo documentation [[http://docs.mongodb.org/manual/reference/operator/update/unset/]]
>When used with $ to match an array element, $unset replaces the matching element with null rather than removing the matching element from the array. This behavior keeps consistent the array size and element positions.

So unless there is something wrong with the way I am working with Doctrine, if Null items are going to be generated in arrays, the UnitOfWork needs to be able to handle them. Otherwise the way "removeElement" is being used should not unset the item from the array.

This has happened as far as I can tell since upgrading this repo
From: 1.0.0-BETA9 4aae9b0151b6661567873700be6ac52877822d6e 
To: Dev (1.0.0-BETA11+) 29bdaa310f791fc0ec439fe2935348dfce4797c3

And https://github.com/doctrine/DoctrineMongoDBBundle.git 
From: V3.0.0-BETA5 ba17a288ae0f2f2cb4ef1bac667710a5f3b7151e 
To: Dev (V3.0.0-BETA5+) 1595d14845fc48ef59c8cc1ae496305964ac0f0a

**Comment by malarzm** [comment]
@markrunaway would you mind creating a failing test case? As far as I can tell ODM [unsets leftover null values](https://github.com/doctrine/mongodb-odm/blob/d305acad9307a9f7419ec8a6f904de2fae38f770/lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php#L228)

**Comment by malarzm** [comment]
Now you could also use one of [atomic strategies](http://doctrine-mongodb-odm.readthedocs.org/en/latest/reference/collection-strategies.html#atomicset). Please feel free to reopen if you believe something is still off.
