### ISSUE TITLE
Question: When will the ODM come out of beta?

### ISSUE THREAD

**Issue by smolinari** [doctrine/mongodb-odm#1035]
Just wondering.:-)

Scott

**Comment by maschmann** [comment]
Better question : How alive is the project (when having a look at all the PRs not merged) :-(

**Comment by smolinari** [comment]
Agreed. Maybe this project needs better, more dedicated leadership?

Scott

**Comment by jmikola** [comment]
This has taken a back-seat to working on the MongoDB driver for me, and ODM has admittedly suffered for it. I'm not against bringing more folks aboard to keep on top of the PRs.

Offhand, @malarzm comes to mind as someone that has been very active across issues/PRs. I don't think @jwage would object.

**Comment by smolinari** [comment]
Hey Jeremy. You work directly on the MongoDB driver for MongoDB Inc.? If yes, nice and good to know.;)

I wish I could help out, but my level of knowledge is admittedly a bit lacking. I am working on that though!

Scott

**Comment by jmikola** [comment]
@smolinari: Indeed. I work alongside @derickr and @bjori on the driver. We're currently juggling a few things (2.0 driver, HHVM support, and a new [PHP library to abstract them](https://github.com/10gen-labs/mongo-php-library-prototype)), which is why it's been so hard to sneak time to work on ODM. [Doctrine MongoDB](https://github.com/doctrine/mongodb) has been easier to justify, as it closely relates to the changes we've been making to the 1.x driver.

**Comment by jwage** [comment]
I would gladly welcome contributions from others. Right now we don't really have many contributors so the project is suffering a bit.

**Comment by malarzm** [comment]
@jmikola @jwage I'll be happy to help :)

**Comment by smolinari** [comment]
@jmikola - Oooohhh! HHVM support.:)

I am sort of confused about what PHongo and the PHongo libraries are all about. Is PHongo the Version 2.0 driver? Will any of this "new stuff" be breaking the ODM? 

Scott

**Comment by bjori** [comment]
@smolinari Yes, PHongo is the current developmental version of the MongoDB driver for PHP, which aims to become the 2.0 release of it.

It will be totally backwards breaking.
We may however provide userland compatabilty layer if needed (debatable benefits..).

The PHongo driver does have a ["ODM like" implementation](http://10gen-labs.github.io/mongo-php-driver-prototype/ods/), although I'd imagine we will add support for PHongo in mongodb-odm at later time.

**Comment by smolinari** [comment]
Thanks @bjori for the explanation. Although I think I can see benefits to this new approach, they are actually still, as a whole, quite vague for me. Can you explain why it was decided to completely break BC with PHongo (I like the name btw.:-)) or rather what (extreme?) benefits will be gained to outweigh the BC loss through the direction change? My own experience level, unfortunately, doesn't allow me to see them. Is it purely to increase performance?

Also, concepts/ patterns like the Unit of Work and the DocumentManager built into the ODM, I would think, are also quite important for a decent persistence layer.

One last question.:-) How far is the development of PHongo? Will the 1.X driver be continued to be developed in parallel for a while? Oops. That was two questions. :-D

Scott

**Comment by bjori** [comment]
@smolinari I think you are overly worried.

Quoting the project website I linked above: http://10gen-labs.github.io/mongo-php-driver-prototype/
> Phongo is written ontop of libmongoc and libbson, and is meant to be as basic as possible. Core MongoDB concepts are implemented, but everything else is left for other toolkits to come in and provide pretty and flexible bindings that make sense for their ecosystem.
> 
> This makes the driver exceptionally fast, and really easy to work with and provide first class experience in your framework, library or application.
> 
> The plan is to provide an example bindings, which you may chose to use - or ignore and make your own.


The current release series (1.x) will continue to be maintained until we've some ecosystem around phongo.
We plan on having a soft-release of phongo by end of March.

**Comment by smolinari** [comment]
Thanks, I read that part. I am not worried at all.:-) I'm very happy actually, because people are thinking about a better future for PHP with Mongo and working for it. That is very cool! I am just not "getting it" completely. I guess it is my inexperience causing me to not get it from a practical usage standpoint. Maybe I will, when I dig a bit more. 

However, I do get "more performance, simplicity and yet actually more flexibility" out of that explanation, as being the benefits, which are great. So, this direction let's you guys concentrate more on the essentials needed for the driver and it let's other developers do more on the abstraction side of things. 

Would that be a correct statement?

Scott

**Comment by smolinari** [comment]
For a little chuckle...http://www.urbandictionary.com/define.php?term=phongo

Scott

**Comment by bjori** [comment]
Yes, thats fairly accurate.
And since it reduces the complications we have more free time to work on other things - like integration with frameworks and libraries... :)

**Comment by jmikola** [comment]
@smolinari: [this blog post](https://github.com/jmikola/jmikola.net/blob/master/source/_posts/2015-02-05-next-gen-mongodb-php-driver.md) might help explain things. It should be published on the MongoDB blog within a month or so, but it's currently a draft in my personal repo :)

And in unrelated news, we just added @malarzm to the ODM team!

**Comment by malarzm** [comment]
Thanks! :+1:

**Comment by smolinari** [comment]
@jmikola - Nice blog. Thanks for that! And I guess I can say congrats to @malarzm?!:-)

I think I can understand the direction change better now. I can't wait to get my hands on the new ODM, whenever it is finished. Hopefully it can be a drop in replacement or the migration to it will be relatively painless though, as our project is now underway with the current Doctrine ODM version (and the reason why I asked the question that started this thread to begin with:-)). Thanks for all the info. I appreciate it a lot!

Scott

**Comment by jmikola** [comment]
Going to close this out, but for the record, the milestones are up-to-date with issues I hope to have resolved for a stable release:

 * https://github.com/doctrine/mongodb-odm/milestones/1.0.0
 * https://github.com/doctrine/mongodb-odm/milestones/1.0.0-BETA13

Issues in the next beta milestone were simply rolled over from the last beta.
