### ISSUE TITLE
When removing an item from an embedded collection it is not in the changeset

### ISSUE THREAD

**Issue by simensen** [doctrine/mongodb-odm#1039]
I'm working on DoctrineExtensions Loggable and running into a problem trying to enable support for collections of Embedded Documents. It looks like when I remove an element from a collection it does not show up in the changeset. However, if I remove *and* add an element then *both* the addition and removal are reflected in the changeset.

Is this a known issue that has already been reported? I'm not even sure how to describe this behavior so maybe this is confusing. :-/

**Comment by gruberro** [comment]
Maybe the same problem addressed in #1034?

**Comment by simensen** [comment]
@gruberro It is possible it is related. I'm trying to see if I can find out the best place to make a test case for this in the test suite so that I can better show it.

Here is a chunk of `Article`:

```php
/**
 * @ODM\Document(collection="articles")
 */
class Article
{
    /**
     * @ODM\String
     */
    private $title;

    /**
     * @ODM\EmbedMany(targetDocument="Tag")
     */
    private $tags;

    public function __construct($title)
    {
        $this->title = $title;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        return $this->title;
    }

    public function addTag(Tag $tag)
    {
        $this->tags[] = $tag;
    }

    public function removeTagByName($tagName)
    {
        foreach ($this->tags as $idx => $tag) {
            if ($tagName === $tag->getName()) {
                unset($this->tags[$idx]);

                break;
            }
        }
    }
}
```

Here is a chunk of `Tag`:

```php
/**
 * @ODM\EmbeddedDocument
 */
class Tag
{
    /**
     * @ODM\String
     */
    private $name;

    public function __construct($name)
    {
        $this->name = $name;
    }

    public function __toString()
    {
        return $this->getName();
    }

    public function getName()
    {
        return $this->name;
    }
}
```

Given the following:

```php
$article = new Article('First');
$article->addTag(new Tag('one'));
$article->addTag(new Tag('two'));
$article->addTag(new Tag('three'));
$this->dm->persist($article);
$this->dm->flush();
$this->dm->clear();
```

In an onFlush listener, the changeset includes `title` ('First') and `tags` with an object of type `Doctrine\ODM\MongoDB\PersistentCollection` that contains:

 * 0 => new Tag('one')
 * 1 => new Tag('two')
 * 2 => new Tag('three')

If I both add and remove an element:

```php
$article = $this->dm->find($article->getId());
$article->setTitle('Second');
$article->removeTagByName('two');
$article->addTag(new Tag('four'));
$article->flush();
$this->dm->clear();
```

I get a changeset that includes `title` ('Second') and `tags` with numeric indexes from which I can derive useful information:

 * 0 => new Tag('one')
 * (index 1 is missing; shows that it was deleted)
 * 2 => new Tag('three')
 * 3 => new Tag('four')

If instead I just remove an element:

```php
$article = $this->dm->find($article->getId());
$article->setTitle('Third');
$article->removeTagByName('two');
$article->flush();
```

I get a changeset that includes `title` ('Third') but *does not* include any `tags` at all.

It does look like the collection is still persisted correctly? If things are removed, they are removed correctly. The problem appears (at least at this point) to be that I have no way to tell, from the `UnitOfWork` changeset, that the collection has changed.

Though, at this point, I don't know. It is entirely possible that simply removing one element from an EmbedMany many not actually be persisting? In my local tests I was actually setting other data before the flush as well. If I run my code w/o any other changes, my onFlush handler isn't even called...

This code:

```php
$article = $this->dm->find($article->getId());
$article->removeTagByName('two');
$article->flush();
```
... results in no onFlush event being triggered at all.

**Comment by jmikola** [comment]
@simensen: I don't believe UnitOfWork has any knowledge of the changesets within PersistentCollection objects. `UnitOfWork::computeAssociationChanges()` simply checks that a collection is dirty and schedules it for updates. The actual updating is done in `CollectionPersister::update()`, which gets the insert and delete changesets from PersistentCollection.

If I understand the above correctly, you're not actually losing changes to the collection in the database and this is just a matter of being able to detect what changes are taking place?

**Comment by simensen** [comment]
@jmikola Yes, you understand correctly.

---

I just spent some time trying to see if I could verify that we are not losing changes to the collection and it looks like we are indeed *not* losing changes. This appears to be a matter of not being able to detect that certain types of changes are taking place.

**Comment by jmikola** [comment]
Does the changeset (from UnitOfWork's perspective) at least tell you that the field containing the PersistentCollection has changed, or is that only when the collection is first being created or deleted (from/to an empty field)? Given the constraints of the current API, you may also be able to get by with the `isCollectionScheduledForUpdate()` and `isCollectionScheduledForDeletion()` methods on UnitOfWork. When you're examining a document for changes, you can manually check if any PersistentCollections within it are scheduled via those public methods.

**Comment by simensen** [comment]
I don't think so but I can explore more. The big problem I have right now is that if the only change for a document at all is removing an element from a collection the on flush event isn't even fired at all. do you have ideas or suggestions for getting around that?

**Comment by malarzm** [comment]
I think that changes proposed in #985 could be handy as pre/postUpdate event will be fired even if ``PersistentCollection`` is the only thing that has changed

**Comment by simensen** [comment]
@malarzm It is possible that #985 would help. Does that mean I'd be able to at least see onFlush events when a persistent collection has changed in *any way*, including when an element is removed from the collection?

**Comment by malarzm** [comment]
@simensen you will be able to catch preUpdate or postUpdate for ``Article`` document. I'm not quite sure why you don't get onFlush event since it's [always dispatched](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L418-L421) when something will be updated

**Comment by simensen** [comment]
@malarzm @jmikola would either of you be abel to point me in a clear path for creating some simple test cases to try and show the behavior I'm seeing so that I can get it into the test suite? it will also help me better figure out if some of the problems i am seeing are unique to our environment or not.

@malarzm as far as i can tell i am not seeing the on flush event firing *at all* in the case that i'm only removing an item from a collection. the change *is* being persisted but there is no on flush being fired if removing the element from the collection is the only change.

**Comment by malarzm** [comment]
@simensen I've pulled together a quick test https://gist.github.com/malarzm/2779d871da6703c3f731 and it is passing on current master, can you take a look if it indeed does what it's supposed to?

**Comment by simensen** [comment]
@malarzm thanks, i'll see if i can get this to work and bring back my findings.

**Comment by simensen** [comment]
Ran *my* code again this morning to make sure on flush was still broken and it was. phpunit was still giving me the same broken responses it has been since yesterday. Then I ran your code and it worked. So I started tweaking your script so it looked a little more like mine thinking there was maybe some minor difference. I could never get it to NOT fire the flush. So I went back to my code and ran phpunit again only to find that flush is now firing?! Will keep looking at this to see if I can figure out why my event magically started firing after running your script. The only thing that changed was that I ran "composer install" in vendor/doctrine/mongodb-odm directory so that I could use the test case (the autoloader wasn't finding it otherwise).

**Comment by malarzm** [comment]
@simensen any news regarding magic happening recently?

**Comment by simensen** [comment]
@malarzm Thanks for checking in. I've moved off of Doctrine Extensions in order to try and implement this myself. I have completed two different styles of implementations, one using changesets in onFlush and one using a combination of things (and maintaining a whole lot of state) and doing a direct write to collections in on postFlush (as suggested by @jmikola).

I still wasn't able to find a way to find changes to objects that had changes to their collections except by tracking `getScheduledCollectionUpdates` and `scheduledCollectionDeletions` in `onFlush`.

At best the `postPersist`, `postUpdate`, and `postRemove` were approximations of what was created, updated, or removed. This is because each object (including embeds) was triggering these events

```php
    public function postPersist(LifecycleEventArgs $eventArgs)
    {
        $documentManager = $eventArgs->getDocumentManager();
        $document = $eventArgs->getDocument();

        $this->changes->recordCreatedDocument($documentManager, $document);
    }

    public function postUpdate(LifecycleEventArgs $eventArgs)
    {
        $documentManager = $eventArgs->getDocumentManager();
        $document = $eventArgs->getDocument();

        $this->changes->recordUpdatedDocument($documentManager, $document);
    }

    public function postRemove(LifecycleEventArgs $eventArgs)
    {
        $documentManager = $eventArgs->getDocumentManager();
        $document = $eventArgs->getDocument();

        $this->changes->recordRemovedDocument($documentManager, $document);
    }

    public function onFlush(OnFlushEventArgs $eventArgs)
    {
        $documentManager = $eventArgs->getDocumentManager();
        $unitOfWork = $documentManager->getUnitOfWork();

        $scheduledCollectionUpdates = $unitOfWork->getScheduledCollectionUpdates();
        $scheduledCollectionDeletions = $unitOfWork->getScheduledCollectionDeletions();

        $this->changes->recordPersistentCollectionsChanged(
            $documentManager,
            $scheduledCollectionUpdates
        );
        $this->changes->recordPersistentCollectionsChanged(
            $documentManager,
            $scheduledCollectionDeletions
        );
    }

    public function postFlush(PostFlushEventArgs $eventArgs)
    {
        $snapshotCalculations = $this->changes->calculateSnapshots(
            $eventArgs->getDocumentManager()
        );

        $this->changes->clear($eventArgs->getDocumentManager());

        $takeSnapshot = new TakeSnapshot(
            $eventArgs->getDocumentManager(),
            $this->username
        );

        foreach ($snapshotCalculations->getCreatedDocuments() as $document) {
            $takeSnapshot('create', $document);
        }

        foreach ($snapshotCalculations->getUpdatedDocuments() as $document) {
            $takeSnapshot('update', $document);
        }

        foreach ($snapshotCalculations->getRemovedDocuments() as $document) {
            $takeSnapshot('remove', $document);
        }
    }
```

... and then in `calculateSnapshots` I resolve the owners of embedded documents and persistent collections and remove duplicates. The last step is to exclude objects that were removed from the added object list and to exclude objects that were removed or added from the updated objects list. This is where I am making the determination of what should actually be considered a create, update, or remove from the list of all possible creates, updates, and removes.

```php
    /**
     * Calculate snapshots given all that we think may have happened.
     *
     * @param DocumentManager $documentManager
     */
    public function calculateSnapshots(DocumentManager $documentManager)
    {
        $this->prepareForDocumentManager($documentManager);
        $documentManagerId = $this->getDocumentManagerId($documentManager);

        $removedDocuments = $this->removedDocuments[$documentManagerId];
        $createdDocuments = $this->createdDocuments[$documentManagerId];
        $updatedDocuments = array_merge(
            $this->updatedDocuments[$documentManagerId],
            $this->documentsWhosePersistentCollectionChanged[$documentManagerId]
        );

        $removedDocuments = $this->resolveEmbeddedObjectsToNonDuplicatedOwners(
            $documentManager,
            $removedDocuments
        );
        $createdDocuments = $this->resolveEmbeddedObjectsToNonDuplicatedOwners(
            $documentManager,
            $createdDocuments
        );
        $updatedDocuments = $this->resolveEmbeddedObjectsToNonDuplicatedOwners(
            $documentManager,
            $updatedDocuments
        );

        $createdDocuments = $this->excludeDocumentsThatExistInAnotherSet(
            $createdDocuments,
            $removedDocuments
        );
        $updatedDocuments = $this->excludeDocumentsThatExistInAnotherSet(
            $updatedDocuments,
            array_merge($removedDocuments, $createdDocuments)
        );

        return new SnapshotCalculations(
            $createdDocuments,
            $updatedDocuments,
            $removedDocuments
        );
    }
```

I guess it is the stuff in `onFlush` that I'm doing to account for the fact that collection changes are not being reflected in the other events. Is there an easier way to do what I'm doing here? Should it be considered a bug that changes to collections is not triggering an `onUpdate` for the objects that own them?

**Comment by malarzm** [comment]
> Should it be considered a bug that changes to collections is not triggering an onUpdate for the objects that own them?

It is, #883 is the issue and mentioned before PR #985 aims to fix it

> Is there an easier way to do what I'm doing here?

Not from top of my head unfortunately

**Comment by malarzm** [comment]
I've changed the issue status to "Feature" since there's no bug, just missing information, might be indeed a good idea to investigate possibility of including collection changes in the changeset (given they will be no sick effects of course) - right now we can even emit `preUpdate` event with empty changeset just because only `ReferenceMany` field was changed (https://github.com/doctrine/mongodb-odm/blob/f3ea0fcb7fa916b85d286be07bf3794c0ab5665f/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L1171-L1174)

**Comment by malarzm** [comment]
#1339 was merged today and modified collections are now included in the changeset :)
