### ISSUE TITLE
Document caveats with ODM's unorthodox use of DBRef objects

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#1042]
For context: https://github.com/doctrine/mongodb-odm/issues/1041#issuecomment-77733134

> This is a long-standing problem with the MongoDB shell and, to a lesser degree, server. Doctrine's use of DBRef objects to store extra values goes back to some very early MongoDB versions, and this functionality is not documented (I'm not sure if it ever was, to be honest).
>
> [SERVER-10777](https://jira.mongodb.org/browse/SERVER-10777) is probably the most relevant issue regarding the shell not displaying DBRef fields (including `$db`!). I've also caught inadvertent BC breaks in the server, such as [SERVER-12263](https://jira.mongodb.org/browse/SERVER-12263).
>
> This personally bit me years ago during a data migration (documented [in this presentation](https://speakerdeck.com/jmikola/using-mongodb-responsibly?slide=31)). We would probably do well to talk about this in the ODM documentation, so I'll make a new issue to track that.

**Comment by malarzm** [comment]
@jmikola I've just found the reference in [this doc](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/reference-mapping.html#mixing-document-types) which seems to be correct place since its talking about mixed references?
