### ISSUE TITLE
Is the ODM production safe?

### ISSUE THREAD

**Issue by JCMais** [doctrine/mongodb-odm#1043]
This might be a silly question, but I need to use mongo for one of my projects and saw this, as I'm currently using the ORM provided by doctrine, I want to use this project too, but the question is, is anyone using this in a production environment?

**Comment by malarzm** [comment]
I'm using it on production for ~1.5 years and didn't have any issues :)

**Comment by gruberro** [comment]
I'm using it in production for about 4 years. Beyond a few bugs and the common database (Mongo related) learnings I've always been happy with the ODM!

**Comment by jmikola** [comment]
[OpenSky](https://www.opensky.com/) is going on 5 years with it.

The ODM isn't nearly as stable as ORM, but it's quite usable. You would do well to review the open issues to get a sense of outstanding bugs and missing features. There's still quite a backlog, but the primary goal was to triage issues into version milestones. @malarzm has been doing a great job helping out with that over the past year.

**Comment by smolinari** [comment]
Agreed. I am loving the activity.:)

Scott

**Comment by JCMais** [comment]
Good to see real use scenarios, thank you everyone!
