### ISSUE TITLE
Investigate Collection update and locking document

### ISSUE THREAD

**Issue by malarzm** [doctrine/mongodb-odm#1046]
As per [this](https://github.com/doctrine/mongodb-odm/pull/985#discussion_r26247231) comment:

> It strikes me as odd that subsequent Collection updates don't use the lock, though (see: [CollectionPersister::executeQuery()](https://github.com/doctrine/mongodb-odm/blob/30f42aa01ff4aa289c1090d6cc7fd79d1ac8afe1/lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php#L284)). It's like unrelated to this PR, but I think that warrants further investigation and we should open a ticket to revisit down the line.

**Comment by jmikola** [comment]
We haven't investigated this further, but #1096 introduced atomic collection strategies, which may aid with updating versioned documents.
