### ISSUE TITLE
ReferenceMany with repositoryMethod and eagerCursor causes fatal error

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1048]
When using referenceMany in combination with repositoryMethod, returning an eagerCursor instead of a regular cursor results in a fatal error in ```Doctrine\ODM\MongoDB\Persisters \DocumentPersister::createReferenceManyWithRepositoryMethodCursor```. This is because the eagerCursor does not support ```sort()```, ```limit()``` or ```skip()```. As such, repositoryMethods may not return eager cursors. There are two possibilities:

1. have the DocumentPersister unwrap the original cursor from the EagerCursor object and apply sort, limit and skip to that.
2. Have ```Doctrine\ODM\MongoDB\EagerCursor``` support sorting out of the box by wrapping the original methods from ```Doctrine\ODM\MongoDB\Cursor```. Note: this may depend on doctrine/mongodb#208.

I can provide a PR for both - just need to know what the better course of action is.

**Comment by malarzm** [comment]
Option number 1 seems to be good quickfix for the case.

As for 2nd option I'd additionally consider some common interface for these two to have something to rely on :)

**Comment by alcaeus** [comment]
Sounds good. I have a working draft prepared, I'll clean it up, add tests and push it in the coming days.

**Comment by malarzm** [comment]
:+1:

**Comment by malarzm** [comment]
#1049 has been merged
