### ISSUE TITLE
[RFC] "Nested" calls to DocumentManager::flush()

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1051]
Hello all,

currently it is possible to `flush()` the `DocumentManager` multiple times while it is already flushing. One example is a lifecycle event subscriber that calls some method that inserts another document and flushes the `DocumentManager`.
Currently, this case is not handled, the `DocumentManager` will happily run the nested `flush()` operation which can cause a bunch of issues. My suggestion is that the `DocumentManager` prevents such calls, unless such functionality breaks existing behavior. Comments?

**Comment by gruberro** [comment]
I'd like to see this change, as this would prevent me from a lot of trouble :+1:

**Comment by malarzm** [comment]
I remember using this to flush single document during bigger flush and nothing bad happened to me in the meantime

**Comment by alcaeus** [comment]
Let's say there is an event subscriber that listens to the ```onFlush``` event. That subscriber loops all changesets and does something if a specific field has changed. You've also got a second subscriber that listens to the ```postPersist``` event. That one creates a new document to be inserted and calls ```flush($document)```. This will cause the ```onFlush``` handler to be called a second time, and it will actually re-do whatever it has done for the first document since the document is still in the changesets (it will only be removed from there after the ```postFlush``` event has been triggered.

**Comment by malarzm** [comment]
I'm not saying it can't break, just throwing my 2 cents saying that I'm currently using flush within a flush :)

**Comment by alcaeus** [comment]
Ah, sorry :)
Yeah, I was thinking about how it could be made optional or whether the flushes could be correctly isolated. Technically, if the second flush tracked its own set of changes, it would be no problem.

**Comment by alcaeus** [comment]
Long time no see - just referencing the comments over in the ORM repository:

> Calling `flush()` inside a lifecycle listener is indeed not allowed.

([Source](https://github.com/doctrine/doctrine2/issues/6659#issuecomment-329980340)

Given that, I'd try to come up with a solution for 2.0 along with a deprecation notice for 1.2.

**Comment by malarzm** [comment]
#1722 prevents user from flushing more than once at a time
