### ISSUE TITLE
How to make nested where clauses with phpcr odm

### ISSUE THREAD

**Issue by lowki** [doctrine/mongodb-odm#1055]
The [phpcr odm documentation](http://doctrine-phpcr-odm.readthedocs.org/en/latest/reference/query-builder-reference.html) seems to be quite clear on that point, but I can't manage to make it.
Here the raw mysql equivalent expected:

    SELECT (foo, bar, baz) FROM table
    WHERE (foo = 'foo') AND bar = 'bar' OR (baz = 'baz' OR baz = 'bazinga')

I tried something like this.

    $qb->from()
    ->document('Detours\MainBundle\Document\Product', 'p');

    $qb->where()
    ->andX()
    ->eq()
    ->field('p.foo')
    ->literal('foo');

    $qb->andWhere()
        ->eq()
        ->field('p.bar')
        ->literal('bar')
        ->end();

    
    $qb->where()
       ->eq()
       ->field('p.baz')
       ->literal('baz');
    $qb->orWhere()
      ->eq()
      ->field('p.baz')
      ->literal('baz');

**Comment by malarzm** [comment]
@lowki I believe you wanted to ask this question in https://github.com/doctrine/phpcr-odm directly (or on stackoverflow) :)

**Comment by malarzm** [comment]
Feel free to reopen if the question is for mongodb odm indeed

**Comment by lowki** [comment]
Aww sorry, yes indeed, i'll post it on phpcr-odm.
