### ISSUE TITLE
Document is upserted and then updated during one flush operation

### ISSUE THREAD

**Issue by vkartaviy** [doctrine/mongodb-odm#1058]
* I have document with ```pre-generated id``` so it added to ```documentUpserts``` array after calling ```$dm->persist($document)```

* I have ```onFlush``` listener where I add some data to that document and then call ```$dm->getUnitOfWork()->recomputeSingleDocumentChangeSet($metadata, $document);```

* I call ```$dm->flush()``` and see the next picture:
```documentUpserts``` and ```documentUpdates``` has the same document to update.

It looks like the problem is [here](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L814),  in direct adding of the document to the ```documentUpdates``` array but should be through ```scheduleForUpdate``` method?

**Comment by alcaeus** [comment]
This sounds similar to this one here: https://github.com/doctrine/mongodb-odm/pull/999

Could you provide a gist? In that case I could just add your issue to that PR.

**Comment by vkartaviy** [comment]
Yep, it looks like the same issue but I would suggest to fix it with below patch, I tried it in my project and it goes well...

```diff
diff --git a/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php b/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php
index 6a34e25..562cbe0 100644
--- a/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php
+++ b/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php
@@ -811,7 +811,8 @@ class UnitOfWork implements PropertyChangedListener
                     : $changeSet;

                 $this->originalDocumentData[$oid] = $actualData;
-                $this->documentUpdates[$oid] = $document;
+                $this->scheduleForUpdate($document);
+                //$this->documentUpdates[$oid] = $document;
             }
         }

@@ -840,7 +841,8 @@ class UnitOfWork implements PropertyChangedListener
                         if (isset($this->documentChangeSets[$oid2])) {
                             $this->documentChangeSets[$oid][$mapping['fieldName']] = array($value, $value);
                             if ( ! $isNewDocument) {
-                                $this->documentUpdates[$oid] = $document;
+                                $this->scheduleForUpdate($document);
+                                //$this->documentUpdates[$oid] = $document;
                             }
                             break;
                         }
```

**Comment by alcaeus** [comment]
While this works for upserts it does not work for regular inserts. ```scheduleForUpdate()``` throws an exception if there's no ```documentIdentifier``` set. Regular inserts don't set this until they've been written to the database, so there would be an exception thrown. It could work with some exception handling, what do you think @malarzm

**Comment by vkartaviy** [comment]
As I see if a new document passed through ```persist``` then it should be in ```documentIdentifier``` according to [this line](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L1023)?

**Comment by malarzm** [comment]
@vkartaviy your fix causes a bunch of tests to fail with ``InvalidArgumentException: Document has no identity.`` I was on #999 yesterday but got distracted by deployment finally, do you guys need it over the weekend or can I get back to it on Monday? :)

**Comment by alcaeus** [comment]
That's the exception I was referring to, which is why I decided not to use ```scheduleForUpdate()``` and instead just check if it's there. I can change it, but probably won't get to it until Monday.

**Comment by vkartaviy** [comment]
The exception was due to embedded documents passed to ```scheduleForUpdate``` but as I see embedded documents are not processed during ```executeUpdates``` so we can skip it at all...

Also I see that we can optimize ```computeOrRecomputeChangeSet``` and ```executeUpdates``` regarding embedded documents but that is should be another issue :ok_hand:

**Comment by vkartaviy** [comment]
Btw - do we need change sets for embedded documents at all?

**Comment by malarzm** [comment]
#782 has been merged in https://github.com/doctrine/mongodb-odm/commit/b1089b723df8ae2230694a3899941e05d560c41f
