### ISSUE TITLE
DateTest::testOldDate() fails on 32-bit platforms

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#1060]
@jwage mentioned that https://github.com/doctrine/mongodb-odm/commit/c36c0606fb0a2f933e843cf68963f3cf4e8f207f failed for him on a 32-bit test environment:

```
1) Doctrine\ODM\MongoDB\Tests\Functional\DateTest::testOldDate
InvalidArgumentException: Could not convert "1900-01-01" to a date value
```

This is due to the the test date exceeding the bounds for a negative 32-bit int. From `strtotime()`'s documentation:

> The valid range of a timestamp is typically from Fri, 13 Dec 1901 20:45:54 UTC to Tue, 19 Jan 2038 03:14:07 UTC. (These are the dates that correspond to the minimum and maximum values for a 32-bit signed integer.) 

Interestingly, DateTime doesn't seem to have this problem:

```
vagrant@precise32:/vagrant/data/mongodb-odm$ php -r "echo (new \DateTime('1900-01-01'))->format('c');"
1900-01-01T00:00:00+00

vagrant@precise32:/vagrant/data/mongodb-odm$ php -r "var_dump((new \DateTime('1900-01-01'))->format('U'));"
string(11) "-2208988800"

vagrant@precise32:/vagrant/data/mongodb-odm$ php -r "var_export(strtotime('1900-01-01'));"
false
```

This is mainly because it prints a `long long` directly to a string buffer (see: [here](https://github.com/php/php-src/blob/a04ab4b54b36786e81d71b2398c227492df9058e/ext/date/php_date.c#L1208)), which it returns. Meanwhile, `strtotime()` returns a platform-dependent `long` (see: [here](https://github.com/php/php-src/blob/a04ab4b54b36786e81d71b2398c227492df9058e/ext/date/php_date.c#L1506)).

---

There is no clear solution for ODM, since [`MongoDate::__construct()`](https://github.com/mongodb/mongo-php-driver-legacy/blob/05db7766158f0d0d24c4bb903adbe8d52d078a46/types/date.c#L71) takes `long` values for its `sec` and `usec` parameters. Ultimately, MongoDate would need to accept a string as its first argument, and parse that directly into an `int64_t` (reported and tracked by [PHP-1424](https://jira.mongodb.org/browse/PHP-1424)).

**Comment by malarzm** [comment]
@jmikola related JIRA ticket was made for legacy driver, is this something new one is tackling/will tackle?

**Comment by jmikola** [comment]
> related JIRA ticket was made for legacy driver, is this something new one is tackling/will tackle?

[`MongoDB\BSON\UTCDateTime::__construct()`](http://php.net/manual/en/mongodb-bson-utcdatetime.construct.php) accepts a string argument since 1.0.0, which will be parsed as a 64-bit integer.

**Comment by alcaeus** [comment]
It's almost 2018 and I'm very willing to close this and ignore 32-bit platforms (sorry @jwage).

@jmikola I didn't quite get whether ext-mongodb still has the same problem - now that dev-master uses ext-mongodb this might no longer be an issue.

**Comment by jmikola** [comment]
> I didn't quite get whether ext-mongodb still has the same problem - now that dev-master uses ext-mongodb this might no longer be an issue.

Looking at [`DateType`](https://github.com/doctrine/mongodb-odm/blob/05b47038fbecb9142a1823eef7aceca45325c2cd/lib/Doctrine/ODM/MongoDB/Types/DateType.php#L74), I believe the issue still remains, as you cast a concatenated string of seconds and milliseconds to an integer.

An easy and portable fix would be to simply pass the DateTime object to `UTCDateTime::__construct()`, which has been supported since `ext-monogdb` 1.2.0. Is there any reason that wasn't done in the original implementation?

**Comment by malarzm** [comment]
> It's almost 2018 and I'm very willing to close this and ignore 32-bit platforms (sorry @jwage).

Yeah, gonna do that now it's 2023 👼
