### ISSUE TITLE
ReferenceMany with repositoryMethod vs. priming references

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1065]
We use a bunch of ```ReferenceMany``` mappings with ```repositoryMethod``` in our software, sometimes including ```sort``` and ```limit``` fields. To reduce the number of database queries, we tried adding reference priming in some of the queries. Since reference priming is implemented in ```Doctrine\ODM\MongoDB\Query\Query``` (https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Query/Query.php#L260..L268), there were two big problems with this:

1. Using ```limit``` or ```sort``` in the mapping causes exceptions. This is due to the fact that the query loops over the results of the queries to collect the objects to be primed. This opens the MongoDB cursor object which means that no limit or sort can be applied to the cursor anymore.
2. When using ```count()``` on the field, the query would be very slow since the execute() method of the query (to return the cursor) would always prime references, even when we're not even interested in the objects themselves.

To fix this, reference priming could be moved to ```Doctrine\ODM\MongoDB\Cursor``` and only prime references once the first object is to be hydrated. This would resolve both issues:
1. The cursor would definitely have to be opened when returning the first result of the query, so we're not breaking any future limit or sort operations since they were impossible anyways.
2. Using ```count()``` would not cause objects to be loaded and thus not trigger reference priming.

I started working on implementing this into the ```Cursor``` class (and into ```EagerCursor``` as well) but wanted to get some feedback on this before finishing up the job. What do you guys think?

**Comment by acrozes** [comment]
I have an error in link with this case, but without using limit() or sort():

Documents:
```
class Account
{
    /**
     * @MongoDB\ReferenceMany(
     *  targetDocument="State",
     *  mappedBy="account",
     *  cascade={"remove"}
     * )
     */
    protected $states = [];

    /**
     * @MongoDB\ReferenceMany(
     *  targetDocument="State",
     *  mappedBy="account",
     *  sort={"createdAt"="desc"},
     *  limit=480
     * )
     */
    protected $lastStates = [];

    /**
     * @MongoDB\ReferenceMany(
     *  targetDocument="State",
     *  mappedBy="account",
     *  repositoryMethod="getLastDailyStates"
     * )
     */
    protected $lastDailyStates = [];
}

class State
{
    /**
     * @MongoDB\ReferenceOne(targetDocument="Account", inversedBy="states")
     */
    protected $account;
}

```
And the repo:
```
class StateRepository extends DocumentRepository
{
    public function getLastDailyStates(Account $account = null)
    {
        $qb = $this->createQueryBuilder('State')
            ->field('createdAt')->gte(new \DateTime('now - 20 day'))
            ->group([], ['dailyStates' => new \stdClass()])
            ->reduce('function (obj, result) {
                var date = obj.createdAt.toISOString().substring(0, 10);

                if (!(result.dailyStates[date])) {
                    result.dailyStates[date] = obj;
                }
            }');
        if (!empty($account)) {
            $qb->field('account')->references($account);
        }

        $ds = $qb->getQuery()->execute();

        return $ds[0]['dailyStates'];
    }
```
When I call: $d->getLastDailyStates() I have the error:
PHP Fatal error:  Call to a member function sort() on array in C:\Mes documents\moua\soclead\vendor\doctrine\mongodb-odm\lib\Doctrine\ODM\MongoDB\Persisters\DocumentPersister.php on line 809

But in the repo::getLastDailyStates I don't use sort() 
I don't understand if it is an error or a bug ...

**Comment by malarzm** [comment]
@acrozes ``repositoryMethod`` is supposed to return ``Cursor`` or ``EagerCursor`` according to [docs](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/complex-references.html#repositorymethod-example). Example over there is a bit unfortunate as now it returns ``array`` but this has been amended lately in #1054 to clarify everything

**Comment by malarzm** [comment]
@alcaeus idea seems reasonable :+1:

**Comment by malarzm** [comment]
#1068 was merged
