### ISSUE TITLE
Which repo is the correct one?

### ISSUE THREAD

**Issue by kidbrax** [doctrine/mongodb-odm#1071]
There is this repo and the one at https://github.com/doctrine/mongodb.  They both seem to be Doctrine projects.  I'm confused as to which one is the official library or do they serve different purposes.  Are they both maintained?

**Comment by jwage** [comment]
@kidbrax doctrine/mongodb-odm is an object mapper and doctrine/mongodb is just a raw library for connecting and querying mongodb.
