### ISSUE TITLE
Link from embeded document to parent

### ISSUE THREAD

**Issue by ivan1986** [doctrine/mongodb-odm#1077]
Now can not be accessed from EmbededDocument to it's root document
it whill be good add annotations for parent EmbededDocument and root Document

**Comment by malarzm** [comment]
@ivan1986 you can use ``UnitOfWork::getParentAssociation`` for that purpose

**Comment by ivan1986** [comment]
yes, can, but what about annotation ;)

**Comment by malarzm** [comment]
I'm not sure how do you want to achieve this by annotation?

**Comment by ivan1986** [comment]
````
/** @Document */
class BigObject {
     /** @EmbedMany(targetDocument="SmallObject") */
     protected $child;
}
/** @EmbededDocument */
class SmallObject {
     /** @ParentDocument */
     protected $parent;   // <- BigObject link
     /** @EmbedMany(targetDocument="TinyObject") */
     protected $child;
}
/** @EmbededDocument */
class TinyObject {
     /** @ParentDocument */
     protected $parent;   // <- SmallObject link
     /** @RootDocument */
     protected $root;   // <- BigObject link
}
````

**Comment by alcaeus** [comment]
I like the idea - I've come across this several times, especially since you don't have UOW within the documents where you normally need to resolve the parent association. Thus, it would be quite nice if the hydrator could resolve this and hydrate the parentAssociation into the document.

**Comment by smolinari** [comment]
I am a bit confused by this and I'll also admit, I am not anywhere near as knowledgeable as I should be about ODM. Maybe you could help me understand. :-) 

Thinking from a data access pattern perspective, when would you want data from an embedded document and not want any data from the parent document? Isn't that the whole purpose of MongoDB's document storage? So you can save those pesky joins, when you need to? And if you need to access data often in an embedded document alone, wouldn't it be "more correct" despite the reference work (the pesky joins), to reference to a different and whole new collection?

I guess I'd just like to understand the use case/ reasoning, where the need for this idea will come up.

Scott

**Comment by alcaeus** [comment]
Let's say you have a ```Person``` document which can contain multiple ```PhoneNumber``` documents. In ORM, you will have them as references and include a inversed reference so the ```PhoneNumber``` knows what ```Person``` it belongs to.
You can do the same in ODM. But, and here comes MongoDB's document storage into play, you can also embed those ```PhoneNumber``` documents into ```Person```. In that case, when loading a ```Person``` you've automatically loaded all ```PhoneNumber``` documents and you can't load a ```PhoneNumber``` without loading the owning ```Person``` document.
However, there is no way to access the owning ```Person``` document from within the ```PhoneNumber```. From outside you can get the ```Person``` document by calling ```UnitOfWork::getParentAssociation($phoneNumber)```. The annotation would put that reference into a designated property within ```PhoneNumber``` so you can traverse up a document tree, not only down.

I hope that explains the use case a bit - maybe I've used it wrong the entire time as well, but I've had those use cases multiple times now.

**Comment by malarzm** [comment]
I am struggling with my opinion on this. On one hand I could use this myself and stop passing both parent and embedded object as it makes things a bit easier. On the other hand it ties my document to ODM as I can't use this link without having Hydrator doing its work first (not that I want to change ODM at some point, but I like to write tests on plain objects). Also I wouldn't be able to use this linking in following case:

```
$person = new Person();
$person->addPhoneNumber(new PhoneNumber('12345678'));
```

unless I add linking logic myself to ``addPhoneNumber``.

**Comment by malarzm** [comment]
Continuing my last post this is working as well:

```
<?php

namespace Doctrine\ODM\MongoDB\Tests\Functional\Ticket\GH1077;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

class GH1077Test extends \Doctrine\ODM\MongoDB\Tests\BaseTest
{   
    public function testIdea()
    {
        $person = new Person('Maciej Malarz');
        $person->addPhoneNumber(new PhoneNumber('12345678'));
        $this->assertSame($person, $person->numbers[0]->owner);
        $this->dm->persist($person);
        $this->dm->flush();
        $this->dm->clear();
        $fetched = $this->dm->getRepository(get_class($person))
                ->findOneByName('Maciej Malarz');
        $this->assertSame($fetched, $fetched->numbers[0]->owner);
    }
}

/**
 * @ODM\Document(collection="person")
 */
class Person
{
    /**
     * @ODM\Id
     */
    private $id;
    
    /**
     * @ODM\String
     */
    public $name;

    /**
     * @ODM\EmbedMany(targetDocument="PhoneNumber")
     */
    public $numbers;

    public function __construct($name)
    {
        $this->name = $name;
        $this->numbers = new ArrayCollection();
    }
    
    public function addPhoneNumber(PhoneNumber $number)
    {
        $number->owner = $this;
        $this->numbers[] = $number;
    }
}

/**
 * @ODM\EmbeddedDocument
 */
class PhoneNumber
{
    /**
     * @ODM\String
     */
    public $number;
    
    /**
     * @ODM\ReferenceOne(simple=true, targetDocument="Person")
     */
    public $owner;

    public function __construct($number)
    {
        $this->number = $number;
    }
}
```

It will store additional information in database but gives all power back to developer and is more transparent.

**Comment by smolinari** [comment]
@alcaeus - Thanks for the explanation. 

So, with ODM, if you query for a certain phone number in the `Person` collection and get a result, currently you don't have any direct way to address who the number belongs to?

Scott

**Comment by malarzm** [comment]
@smolinari: you can't query for a ``PhoneNumber`` itself, it must come with owning ``Person`` object

**Comment by smolinari** [comment]
@malarzm Thanks Maciej. 

Is the query limitation a limitation in the ODM? Because I thought with MongoDB, you could query for data held in the embedded document, but you get the parent document as the result. 

Scott

**Comment by malarzm** [comment]
@smolinari I think I misunderstood your previous question :) You can query for data held in embedded document with ODM and as you said you will get parent document as a result. The ``PhoneNumber`` itself (as PHP object) doesn't know where it belongs without a) ``UnitOfWork`` or b) reference held in it as in my example.

**Comment by smolinari** [comment]
Ahh...now we are getting there! :-) ..... think.

Couldn't the fact the embedded document is part of the `Person` document result in an implicitly mapped relation between the two objects automatically? I don't even think extra mapping metadata should be needed. It should be automatic because the schema of the document needs to be enforced anyway. 

And wouldn't your test need to query for the telephone number and assert the number's owner is related to the person object to prove the relationship method works "bottom up"? 

Would that `Person` reference also mean an unnecessary query to get the actual `Person` object data again, when it is needed? Or is ODM smart enough to "keep" the parent document data in the background until the object is hydrated/ created? 

Like I said, I am a bit confused and new to all this. I would have thought embedded documents (the objects) would automatically know what document they are embedded in (the parent object). 

Scott

**Comment by malarzm** [comment]
> Couldn't the fact the embedded document is part of the Person document result in an implicitly mapped relation between the two objects automatically? I don't even think extra mapping metadata should be needed. It should be automatic because the schema of the document needs to be enforced anyway. 

The schema is enforced from up to bottom: ``Person`` will (usually) know it will hold ``PhoneNumber`` but ``PhoneNumber`` doesn't know where it will be held, we are only marking it as embedded document for ODM. For instance I personally have ``File`` embedded document and I'm embedding it in several places

> And wouldn't your test need to query for the telephone number and assert the number's owner is related to the person object to prove the relationship method works "bottom up"?

Even if I query for ``PhoneNumber`` then I will get ``Person`` object since data needs to be hydrated and that ``Person`` instance will hold my ``PhoneNumber`` for which I was querying. Data needs to be hydrated from top to bottom so it doesn't matter how I query.

> Would that Person reference also mean an unnecessary query to get the actual Person object data again, when it is needed? Or is ODM smart enough to "keep" the parent document data in the background until the object is needed? 

Yes it will be smart enough. In such cases ODM firstly checks if object that is being referenced is already known to ``UnitOfWork`` - if it is then instance is instantly returned and if not ``Proxy`` object is created (and the query won't be issued until it's needed by accessing ``Proxy`` methods/properties).

**Comment by smolinari** [comment]
Ok. Thanks. I am now no longer so confused. ( I still have a lot to learn!):) Top to bottom enforcement. Got it.

Scott

**Comment by jmikola** [comment]
@alcaeus @malarzm: Reading the above thread, I don't think there'd be a problem with this. We already have synthetic fields when it comes to GridFS. Provided we can ensure UoW merely hydrates the `@ParentDocument` mapped field and ignores it thereafter (similar to `@NotSaved`), I don't see a problem.

We'll certainly want to document that the field is only usable immediately after hydration. If the user decides to sever the relationship between the parent and embedded document (e.g. removing it from a collection, stuffing it on another document), it may still store an incorrect reference.

**Comment by colinodell** [comment]
:+1:  I think this feature would be incredibly useful.

> Provided we can ensure UoW merely hydrates the @ParentDocument mapped field and ignores it thereafter (similar to @NotSaved), I don't see a problem.

That solution sounds perfect to me.

**Comment by jwage** [comment]
I am not sure if we need a feature for this. You should be able to accomplish what you want with something like this using lifecycle callbacks.

    <?php

    /**
     * ...
     * @Document
     * @HasLifecycleCallbacks
     */
    class Parent
    {
        /** @EmbedMany(targetDocument="Child") */
        private $children;   

        /** @PostLoad */
        public function postLoad()
        {
            foreach ($this->children as $child) {
                $child->setParent($this);
            }
        } 
    }

    /** @EmbeddedDocument */
    class Child
    {
        /** @var Parent */
        private $parent;

        public function setParent(Parent $parent)
        {
            $this->parent = $parent;
        }
    }

**Comment by colinodell** [comment]
> You should be able to accomplish what you want with something like this using lifecycle callbacks.

True, but it would be nice if this library offered a simple annotation to automate this, instead of requiring the same boilerplate code across all the embedded documents.  (I wouldn't mind taking a stab at this if somebody could point me in the right direction.)

**Comment by malarzm** [comment]
@colinodell this won't require boilerplate code across all embedded document, you could hook globally to `postLoad` and check for some `ChildrenAreParentAwareInterface` or something like this :)

Anyway if you are willing to work on this you will need to tweak few things (might not be all, from top of my head):

1. Add new annotation (and xml/yaml mapping options, so you will work with all 3 drivers) and probably allow it only on documents explicitly marked as embedded documents (on class metadata level)
2. Adjust `HydratorFactory` to be aware that it needs to hydrate parent into such field
3. Ensure `UnitOfWork` will skip these fields during computing change sets
4. Add tests
5. Amend the docs (annotation reference should be enough)

**Comment by jwage** [comment]
I still don't think we should add a feature for this. The lifecycle callbacks are there to handle these types of features without having to have an explicit feature in the core for every possible scenario someone could come up with.

**Comment by colinodell** [comment]
@malarzm Thanks for the suggestion, I really like that approach!

@jwage It could be argued that referencing the parent might be common enough to warrant the feature.  However, @malarzm's solution works great for my needs and it avoids some of the gotchas that @jmikola mentioned.  (And I totally understand not wanting to set a precedent for adding everyone's pet feature when existing functionality works just fine.)

I'll go the `postLoad` route for now (instead of implementing a new annotation).  Thanks everyone for the guidance!

**Comment by akomm** [comment]
Embed document does not know where it will be embedded. It can be used anywhere. But sometimes you have cases, where an embedded document is supposed to be used in only one document. In this case you might need access the parent document. 

What about @EmbeddedDocument(ownedBy="Document\Parent")? 
This would require an additional property with @ParentDocument annotation (or exception - invalid mapping) and you would add set the parent as @malarzm mentioned, so it also works when you test.

When you try to set use owned embed document by a document not set as owner you could get feedback, that it is not valid.

**Comment by malarzm** [comment]
> Embed document does not know where it will be embedded.

At this moment a specific embedded document (instance of an object) could be owned by exactly 0 or 1 document. If it is used twice and ODM encounters such situation during persistence-related traversal (persist/computing change set), it'll be fixed (i.e. in document that is not an original owner, the embedded document is cloned and set once again). So the embedded document itself does not know where it's embedded but ODM knows :)

**Comment by akomm** [comment]
I meant it rather ahead of time, not at runtime when things are resolved and you have instances.

**Comment by alcaeus** [comment]
After some thinking, I've decided that we won't implement this for the time being. While it makes sense to have a reference to the owning document, I believe this is best left to the user to implement, as ODM can only properly fill the field if it was loaded from the database. ODM will not know that you've called `$owner->setEmbedded($embedded)` and that it should imply `$embedded->setOwner($owner)`. That's something for the developer to implement, so it's better to leave the logic up to them.
