### ISSUE TITLE
Problem with serializing uninitialized PersistentCollection

### ISSUE THREAD

**Issue by ofetisov** [doctrine/mongodb-odm#1078]
Hi guys! I serialize my entire document which has some embedded array-fields (which are fetched as PersistentCollection) and if they are uninitialized (and they really are, right after fetch and hydration) I've got unrepresentative string which doesn't tells anything about it's content. It seems quite bad for me doing initialization of every "array" of my document before serialization, so i came up with idea: what do you think about adding  'mongoData' string into array that returns from "__sleep" method? I've tested and it seems not ruining any tests, and in general it looks like serialization is not used at all. So I think this is not big deal. Thanks in advance!

**Comment by malarzm** [comment]
Won't it break after unserialization under certain conditions? I mean that ``PersistentCollection`` needs ``UnitOfWork`` to [initialize itself](https://github.com/doctrine/mongodb-odm/blob/683728eb0b4723dd5551686addc724f8f1b13afe/lib/Doctrine/ODM/MongoDB/PersistentCollection.php#L185) which might not be available after ``unserialize($document);`` if you won't merge document first.

**Comment by ofetisov** [comment]
@malarzm and won't it break now? I think no, cause unserialized object will have no "mapping" and will fail on this [line](https://github.com/doctrine/mongodb-odm/blob/683728eb0b4723dd5551686addc724f8f1b13afe/lib/Doctrine/ODM/MongoDB/PersistentCollection.php#L173). And I can't see how my improvement will influence on this.

**Comment by malarzm** [comment]
Oh sorry for oversight I haven't looked at second condition there :) If no tests are failing and everything is working properly I'm personally ok with addition :+1:

**Comment by ofetisov** [comment]
Should i make some PR or we need some more thoughts about that?

**Comment by malarzm** [comment]
We can always have a discussion in a PR :)

**Comment by malarzm** [comment]
Closing along with PR, see https://github.com/doctrine/mongodb-odm/pull/1079#issuecomment-172271018
