### ISSUE TITLE
Cache issue with getting data with same collection but different query filter

### ISSUE THREAD

**Issue by mudiman** [doctrine/mongodb-odm#1089]
Two query back to back returned the same result inspite of separate output field list and filter query. I had to refresh the result for the actual result.

**Comment by malarzm** [comment]
@mudiman I'm sorry but I'm not sure what the issue is. Do you mean using ``refresh()`` from ``QueryBuilder``?

**Comment by mudiman** [comment]
I have a collection which i queried with query builder. First query i
selected few field and applied a filter on a reference field inside an
embeded document in that collection. Then i did the same with different
select fields and different column in reference field inside an embeded
document in same collection it returned me the same output of first one. I
figured out that it was returning proxy cache data. So i had to call
refresh at the end of query to get new data.

**Comment by malarzm** [comment]
ODM can't assume ``refresh()`` for you, some details on that can be found here: https://github.com/doctrine/mongodb-odm/pull/896 so I believe this is not a bug.

**Comment by mudiman** [comment]
ok thanks
