### ISSUE TITLE
getTypeClass not working on Collection

### ISSUE THREAD

**Issue by wodka** [doctrine/mongodb-odm#1106]
Notice: Undefined property: Doctrine\ODM\MongoDB\PersistentCollection::$typeClass

**Comment by malarzm** [comment]
@wodka how did you manage to get such an error?

**Comment by wodka** [comment]
For SonataAdmin Bundle there is a Pull Request that contained a reference to Doctrine 2.4 code:
https://github.com/sonata-project/SonataAdminBundle/pull/2985/files#diff-5ce9b658fbcaa128b4326ce1cc07bd14R123

While I was trying to fix that to work with odm I realised the same funktion exists there:

**Doctrine\ODM\MongoDB\PersistentCollection:** *typeClass is never set*
```php
    public function getTypeClass()
    {
        return $this->typeClass;
    }
```

**Doctrine\ORM\PersistentCollection:** *works*
```php

    /**
     * Creates a new persistent collection.
     *
     * @param EntityManagerInterface $em         The EntityManager the collection will be associated with.
     * @param ClassMetadata          $class      The class descriptor of the entity type of this collection.
     * @param Collection             $collection The collection elements.
     */
    public function __construct(EntityManagerInterface $em, $class, Collection $collection)
    {
        $this->collection  = $collection;
        $this->em          = $em;
        $this->typeClass   = $class;
        $this->initialized = true;
    }

    /**
     * @return Mapping\ClassMetadata
     */
    public function getTypeClass()
    {
        return $this->typeClass;
    }
```

**Comment by malarzm** [comment]
For the quickest solution: is it possible to add check for ODM's PersistentCollection in Sonata and use `getMapping()` method instead? Or it would be cool if you'd be able to send PR here fixing the issue :)

**Comment by wodka** [comment]
Hi, 

I'll try to fix it - I already have a solution based on the SonataAdmin Configuration (working)

can you point me in a direction where the persistent collection is usually created?
thx :)

**Comment by malarzm** [comment]
@wodka I'd check `UnitOfWork` and `HydratorFactory` for sure :)

**Comment by malarzm** [comment]
PR: #1109

**Comment by malarzm** [comment]
#1109 is merged manually in https://github.com/doctrine/mongodb-odm/commit/5b30e0f7a677c8a7494d82176bb8a747f4e82fb9
