### ISSUE TITLE
BETA13 increases query volume by 25%

### ISSUE THREAD

**Issue by blockjon** [doctrine/mongodb-odm#1108]
I love beta13.. though I just noticed that as soon as I deployed it, my query mix jumped up by approx 25%. I just reverted it and you can see as soon as I do that, the queries to my main collection drop back down by 25%.

In this release, the *only* thing I did was deploy beta13 so there is something that has been done which increases the # of queries.

Screenshot:
![graph](https://cloud.githubusercontent.com/assets/1198745/7849424/27293a6e-048a-11e5-8e51-c710e7a11fa5.png)

**Comment by smolinari** [comment]
Out of curiosity and sorry for the off-topic, but what program or tool are you using to do that measurement?

Scott

**Comment by malarzm** [comment]
@blockjon I guess you were upgrading from BETA12? Could you check if https://github.com/doctrine/mongodb-odm/pull/692 is your troublemaker?

**Comment by blockjon** [comment]
@smolinari we pump mongo metrics into graphite and display them with an extension called grafana

**Comment by blockjon** [comment]
@malarzm You are correct, I was on BETA12 and I upgraded to BETA13.

I'm not sure how to repro this in staging... I tried to figure out where in my app the extra query is coming from but I can't figure it out.

Would you suggest I create a fork and from BETA13, I just remove https://github.com/doctrine/mongodb-odm/pull/692 and then deploy that to my live env? Is that a rational idea?

**Comment by malarzm** [comment]
@blockjon it would be the best if for instance functional test suite would be producing extra queries as well, then you could bisect between BETA12 and BETA13 locally/in dev to find the exact commit. If not then what you've said might be good idea, theoretically everything should be working properly with such fork :)

**Comment by malarzm** [comment]
For the record @alcaeus pointed out it should not be #692 and he's investigating #1068

**Comment by alcaeus** [comment]
I took another look at #1068 and it doesn't look like it's to blame - that's just what I can see from my end though.
We were running our own version that included #1068 for a while now and it did not increase query numbers. The last update was two weeks ago, so we're not running BETA13 yet. Currently, we're missing #1096 and #1100 - not sure if they contribute to the issue.

**Comment by malarzm** [comment]
@alcaeus these two you have mentioned are opt in feature and only affecting write operations (and decreasing number of queries :) )

@blockjon I think that bisecting is the best way to find the culprit

**Comment by blockjon** [comment]
@malarzm For now I think we are going to live with the extra queries since we need the fix to the data corruption so badly. If I have the time to find where the extra queries are coming from I will update this issue. Thanks for your attention to this problem.

**Comment by alcaeus** [comment]
@blockjon Following up on your query issues - what's the current state? #1112 enforced eager cursors for reference priming, thus making sure that priming multiple fields would not run the original query multiple times. Did that solve your issues?
