### ISSUE TITLE
Update on an embbeded document

### ISSUE THREAD

**Issue by joshlopes** [doctrine/mongodb-odm#1110]
Hey , Sorry if this was already discussed or even fixed

i have a document Product that embeds ProductAttributes which has the follow string properties size and color. Attributes can be null so i have documents like this: {attr: null} 

As soon as you try to update it will do a update query something like this: {$set: {"attr.cl":"RED","attr.sz":"Small"}} which generates the follow error:

````
 cannot use the part (attr of attr.cl) to traverse the element ({attr: null})
````

If attr: was {} it would be okay -- what would be a elegant solution for this bug ?

FYI: I'm using on composer the doctrine mongo version 

````
"doctrine/mongodb-odm": "1.0.*@dev",
"doctrine/mongodb-odm-bundle": "3.0.*@dev",
````

And mongo 3 on the server

**Comment by malarzm** [comment]
@joshlopes why do you need `attr` to be null?

**Comment by joshlopes** [comment]
I guess from our legacy code or Import system -- true be told those are still be generated so i would rather be prepared for it :) and afterall we do have the option to some column be nullable = true so Doctrine should handle those cases.

**Comment by malarzm** [comment]
@joshlopes I can't recall ODM saving `null` to database for something that is supposed to be `EmbedMany` collection, it would rather `$unset` the field. Can you please provide failing test case that produces your error?

Alternatively you may use `atomicSet` collection strategy we introduced in BETA13 (or even older `set` strategy if you're not using latest ODM) which should fix your issue as they will write whole `attr` field at once (I suppose you are using default collection strategy which will create embedded field if it's not existing but can't traverse `null` as stated in exception).

**Comment by joshlopes** [comment]
@malarzm its EmbedOne collection i suppose the atomicSet are meant to be used for the Many ones only.

Will try to create a test where it fails

**Comment by malarzm** [comment]
Ah your `ProductAttributes` is `EmbedOne`, never mind my previous comment

**Comment by malarzm** [comment]
@joshlopes attaching mapping would make it more clearer :) anyway I will appreciate having failing test case

**Comment by malarzm** [comment]
@joshlopes any update on the test?

**Comment by joshlopes** [comment]
I didnt have time to do any test @malarzm and i am afraid i wont have it. I sorted the problem somehow or maybe i refactored that bit.

So closing this issue -- if it happens again i will make sure to proper comment it out , attaching the code and make you a test. 

Thanks !

**Comment by malarzm** [comment]
@joshlopes thanks for the update!
