### ISSUE TITLE
Still at risk of data loss & corruption with strategy="atomicSet"

### ISSUE THREAD

**Issue by blockjon** [doctrine/mongodb-odm#1114]
I'm getting 2 update queries instead of 1 update query even when I am using @malarzm 's new atomicSet. I'm not sure if that means there's more work to do to fix the problem, or if perhaps I'm doing something wrong. I'm probably doing something wrong.

Here's a functional test which exhibits this behavior:
https://github.com/doctrine/mongodb-odm/pull/1113

**Comment by malarzm** [comment]
I'm afraid that probably I'm the one who did something wrong :)

**Comment by jmikola** [comment]
Fixed by #1118.
