### ISSUE TITLE
Excessive cascade in reference inside embedded

### ISSUE THREAD

**Issue by zeliard91** [doctrine/mongodb-odm#1115]
I've added a test to show this issue : https://github.com/zeliard91/mongodb-odm/commit/b2f04fd3241b9510cad919f55c42cb8596e38a3f

I don't know if it is a wanted behaviour but any changes in a referenced document inside an embedded document is committed when the owner document is persisted.

Test case : 
```php
<?php

/** @ODM\Document */
class Offer
{
    /** @ODM\Id */
    protected $id;

    /** @ODM\String */
    public $name;

    /** @ODM\EmbedMany(targetDocument="Link") */
    public $links;
}

/** @ODM\EmbeddedDocument */
class Link
{
    /** @ODM\Id */
    protected $id;

    /** @ODM\String */
    public $url;

    /** @ODM\ReferenceMany(targetDocument="ReferencedDocument") */
    public $referencedDocuments;

}

/** @ODM\Document */
class ReferencedDocument
{
    /** @ODM\Id */
    protected $id;

    /** @ODM\String */
    public $name;

}

// ...

// Object order fetched from database
$offer->links[0]->referencedDocuments[0]->name = 'new name';

$dm->persist($order);
$dm->flush();
$dm->clear();
```

After this, the ReferencedDocument has been updated though there is no cascade option in the `@ODM\ReferenceMany` annotation

**Comment by jwage** [comment]
This is the expected behavior. The `ReferencedDocument` is already persisted and being managed by Doctrine so when you change `name`, the change is detected on flush and saved to the database. cascade={"persist"} only applies to finding and persisting newly created and referenced objects.

**Comment by zeliard91** [comment]
OK, thank you for the reply.
