### ISSUE TITLE
Adding an embedded item to an existing record results in data loss

### ISSUE THREAD

**Issue by blockjon** [doctrine/mongodb-odm#1117]
Given a book with a chapter, this sequence of events fails:
```
// imagine a book already exists with a chapter in it...
$book = $dm->findOneBy(array('_id' => $id));
// Add a second chapter to this book object which already has a chapter
$book->chapters->add(new Chapter('Chapter Two'));
$dm->flush();
$dm->clear();

$book = $dm->findOneBy(array('_id' => $id));
this->assertEquals(2, $book->chapters->count()); // <- Fails!!!!
```
Is it just me, or does this seem *really* bad?

Here's my take on fixing it:
https://github.com/doctrine/mongodb-odm/pull/1116

**Comment by malarzm** [comment]
Indeed this is happening but if I'm seeing correctly only when `set` or `atomicSet` is used since they're merging new objects using `set()` which may overwrite object using same index (which is very likely when using `add()` on uninitialized collection)

**Comment by blockjon** [comment]
@malarzm To answer your question, it seems that initialize() must be called manually if the strategy is "set" or "atomicSet". However, initialize() does not need to be called if you are using "pushAll", "setArray", or "atomicSetArray".

In order to simplify, it would be awesome if the ODM's API always worked the same way so that the developer does not need to manually call initialize() ever.

**Comment by malarzm** [comment]
@blockjon I'm hiding manual initialization and forcing ODM to think about this for developer in #1119

**Comment by blockjon** [comment]
i like https://github.com/doctrine/mongodb-odm/pull/1119
