### ISSUE TITLE
Mapping exception for combining simple references and discriminators

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#1124]
Per @jwage's comment in https://github.com/doctrine/mongodb-odm/pull/1038#issuecomment-87233315:

> I think we should throw an exception if you combine simple => true and a discriminator. That type of relationship is inherently not simple and storing the reference as an array is critical to be able to store the discriminator value so we can construct the proper class during hydration.

As explained in the [Simple References documentation](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/reference-mapping.html#simple-references) and discussed in the above ticket, we do not have a viable solution to handle discriminated, simple references. Additionally, @clslrns discussed a caveat in that PHP limits us to creating a proxy object of the top-level class, which may be abstract, and does not allow us to cast into the more specific class after proxy initialization (solving this within the language would require some way to redeem a proxy object for its resolved instance, which conflicts with the idea of lazy initialization).

----

For the uninitiated, "simple" references are fields storing a referenced document's `_id` value (or an array of them in the case of a reference-many relationship). This is the lighter form of ODM's standard references, which are [DBRef](http://docs.mongodb.org/manual/reference/database-references/#dbref-explanation) objects.

**Comment by malarzm** [comment]
#1162 was merged manually in https://github.com/doctrine/mongodb-odm/commit/ab600a72be81ab618c421212a1ddf5e9a2a06cbd
