### ISSUE TITLE
atomicSet is not compatible with Lifecycle callbacks

### ISSUE THREAD

**Issue by blockjon** [doctrine/mongodb-odm#1126]
I have created https://github.com/doctrine/mongodb-odm/pull/1125 to exhibit this problem.

**Comment by jmikola** [comment]
@blockjon: If you happen to open a PR with a failing test first, feel free to skip a separate issue. That will make it easier to consolidate discussion (even if the test simply ends up being cherry-picked in lieu of merging the original PR).

**Comment by blockjon** [comment]
ok.. I will close this issue out but leave the PR open in order for it to be triaged there
