### ISSUE TITLE
Where would be the most optimal place to cache Mongo records when using Doctrine ODM?

### ISSUE THREAD

**Issue by blockjon** [doctrine/mongodb-odm#1127]
I would like to store each record in a cache.

My app typically loads individual records by the mongo ID. Is there a project, module, plugin or similar that someone has already developed that already does record caching?

If not, where would be the best place in the ODM logic flow for me to hook into and add caching?

**Comment by malarzm** [comment]
@blockjon for sure [this](https://github.com/doctrine/mongodb-odm/blob/d305acad9307a9f7419ec8a6f904de2fae38f770/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php#L478) is one place of interest. I think it would be interesting to dispatch an event with criteria and allow listeners returning cached results. @jmikola @jwage @alcaeus thoughts?

**Comment by smolinari** [comment]
Out of curiosity, but isn't Mongo performing well enough? 

Scott

**Comment by blockjon** [comment]
Mongo has a "global lock" meaning during a write, everything stops. Under scale, the lock percentage increases to dangerous levels. No bueno. We are looking at alternatives.

**Comment by smolinari** [comment]
With Version 3 they lowered MMap to collection level locking and if you use WiredTiger, you get document level concurrency. Are you using Version 3?

Scott

**Comment by blockjon** [comment]
Not sure if we upgraded to version 3 yet...it wouldn't be a game changer since 98% of the queries go to the same two collections.

**Comment by smolinari** [comment]
Yes, please do test for sure, before you make any major version changes. :-) But, from what I've been reading, WT does make a considerable difference. 

Scott

**Comment by bicatu** [comment]
@blockjon even if you are sending queries to the same collection the lock is at document level.  So it gets pretty close as you would have in terms of, for example, MySQL in the row-level locking.

So unless you have really many concurrent writes to the same document caching should not be the major concern.  As @smolinari mentioned if the server is performing (enough memory, indexed) you should be fine.

**Comment by malarzm** [comment]
Closing in favour of #1490
