### ISSUE TITLE
Indexes not created when embedding a document using mixed document types 

### ISSUE THREAD

**Issue by bicatu** [doctrine/mongodb-odm#1135]
According to the user manual when I specify the indexes on a embedded document it will be created when persisting the main document.

It is not happening when the embedded document type varies.

To reproduce
Main Document Entity

```php
/**
 * @ODM\Document
 */
class Document
{
    /**
     * @var string Id
     * @ODM\Id
     */
    private $id;

    /**
     * @ODM\EmbedOne(discriminatorField="type")
     */
    private $embedded;

    // setters and getters
}
```

First embedded type
```php
/**
 * @ODM\EmbeddedDocument
 */
class Embedded1
{
    /**
     * @ODM\Date
     * @ODM\Index
     */
    private $timestamp;

    // setters and getters
}
```

test code
```php
$document = new Document();
$embedded = new Embedded1();
$embedded->setTimestamp(new \DateTime());
$document->setEmbedded($embedded);

$dm->persist($document);
$dm->flush();
$sm = $dm->getSchemaManager();
$sm->ensureIndexes();
```

When using find the document and the embedded data has been saved but the getIndexes does not show anything other than the _id.

If I update the annotation to mention targetDocument the index gets created normally.

**Comment by malarzm** [comment]
@bicatu if you want indexes for embedded documents to be created you have to provide `targetDocument` or `discriminatorMap` or otherwise ODM doesn't know what can be embedded and what indexes will not be created. Feel free to reopen if something is unclear :)

**Comment by bicatu** [comment]
Hi @malarzm it is clear even though I do not agree per se.  The field type tell it what class to use for the embedded document and in the class I do have the indexes.   Hence in my opinion there is a way of achieving the same functionality as when we have when we statically map the document.

May I suggest that if this is not a feature request at least the documentation on the index page is updated to make this limitation clear.

**Comment by malarzm** [comment]
> The field type tell it what class to use for the embedded document

@bicatu what field type are you referring to?

```
    /**
     * @ODM\EmbedOne(discriminatorField="type")
     */
    private $embedded;
```

**Comment by bicatu** [comment]
When I am persisting the document (with its embedded sub-document) I have the entity and the discriminatorField which contains the class name of that embedded document.

From that name I have the definition, hence the index annotation.  Is this clear?

**Comment by malarzm** [comment]
As far as I am concerned  ODM is not checking in database what embedded documents are used in main documents, only metadata is used for that.

> According to the user manual when I specify the indexes on a embedded document it will be created when persisting the main document.

Can you please paste a link to that part of docs?

**Comment by bicatu** [comment]
Hi http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/indexes.html is the one that mentions at the section "Embedded Indexes" about the creation of the indexes for embedded documents.

And http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/embedded-mapping.html#mixing-document-types for the embedded documents.

So there is no mention that "in order to create the indexes you have to specify the targetDocument or the discrimitatorMap on the Document"

**Comment by malarzm** [comment]
Indeed we should amend the documentation (or would you mind making a PR?). Thank you for the report!

**Comment by bicatu** [comment]
I can make the PR.  Is there any reference on the proper procedure to do so - update the documentation ?

**Comment by malarzm** [comment]
I don't think we have a procedure for that - you just open a PR with needed changes referencing this issue, we review that, maybe ask for amendments and merge afterwards :)

**Comment by bicatu** [comment]
I created a pull request.

**Comment by jmikola** [comment]
See #1143.

**Comment by jmikola** [comment]
#1143 has been merged.
