### ISSUE TITLE
@postUpdate events trigger at an unexpected moment when using EmbedMany

### ISSUE THREAD

**Issue by blockjon** [doctrine/mongodb-odm#1145]
My project uses strategy=set for nearly all of our EmbedMany elements and we also use @postUpdate hooks all over the place. 

Given a document (such as book) with many embedded documents (such as chapters), if you make changes to both the "surface" of the document (such as the book title) and then you also modify the chapters at the same time and then call flush(), the sequence of queries and postUpdate callbacks seems wrong.

When you flush() a change as I have described above, the sequence of events that takes place looks like this:

1) MongoDB update query to update the surface of the db record (the book title).
2) postUpdate hooks fired for *both* the surface and also for the embedded documents
3) MongoDB update query to update the embedded documents

Imagine an app where you update the title of a book and modify a chapter in one flush() such that after the chapter is edited, you email alert the publisher via a @postUpdate hook on the Chapter document.

Because of the sequence of the events, the email is sent *before* the chapter is actually saved to the database server. This means that if there's a fatal MongoDB error on step 3, the email was still sent and the user is disappointed because the application sent the email and the data was never saved.

The whole idea of a "postUpdate" hook is that the the event would fire *after* the database record was saved....not before it was saved.

**Comment by malarzm** [comment]
#1155 aims to fix this

**Comment by malarzm** [comment]
#1155 was merged manually in https://github.com/doctrine/mongodb-odm/commit/5b0ff1c5d4a19594b778352e9bb0fc6a54ed2152
