### ISSUE TITLE
distinct() doesn't use document mapped name

### ISSUE THREAD

**Issue by pablomoreno61** [doctrine/mongodb-odm#1148]
I'm trying to make a distinct query to my database using queryBuilder, but I cannot use my document property name in the distinct method, instead of this I have to use the real database field name. Otherwise I have no problems using the property name in my sort or field methods.

For example:

        $qb = $this->dm->createQueryBuilder('myapp\Domain\User\Document\User');

        # I cannot use something like "$qb->field('postalCode')" or "postalCode"
        $qb->distinct('postal_code');

        # Using postalCode (property name) instead of postal_code (database name)
        $qb->addAnd($qb->expr()->field('postalCode')->equals(new \MongoRegex("/$needle/")));
        $qb->sort('postalCode', 'asc');

        $results = $qb->getQuery()->execute();

**Comment by malarzm** [comment]
@pablomoreno61 indeed `distinct()` is called from doctrine/mongodb's Builder and it has no idea that the field should be translated and neither it happens in ODM's Builder `getQuery()` method (I think that logic should be put in the `getQuery()` method). Would you like to work on PR?

**Comment by pablomoreno61** [comment]
Yeah, sure @malarzm. What Can I do?

**Comment by malarzm** [comment]
@pablomoreno61 I usually write failing unit test first, try to fix that one, next run whole suite and finally submit a PR :)

**Comment by malarzm** [comment]
#1161 was merged manually in https://github.com/doctrine/mongodb-odm/commit/0ddaafd35c7120ea8328cd438fdee0a8003ea896

**Comment by pablomoreno61** [comment]
works like a charm, thanks @malarzm !!
