### ISSUE TITLE
Rollout question: how can I programatically change my EmbedMany strategy from set to atomicSet for 1/100th of records?

### ISSUE THREAD

**Issue by blockjon** [doctrine/mongodb-odm#1150]
I'm gaining confidence in @malarzm 's atomicSet strategy. I'm trying to figure out a "good" way to try using atomicSet on a specific model only for a consistent 1/100th of the documents.

What would be the best way for me to do something like this (pseudo code):
```
...
if ($book->getId() % 100 == 0) {
   $dm->changeStrategyMapping(Book->chapters, 'atomicSet');
}
$dm->flush();
```

**Comment by jmikola** [comment]
The collection mapping is specified through ClassMetadata and applies at the class level. The [PHPDriver](https://github.com/doctrine/common/blob/ff72726b0876638fa7db2f28b0f26e3f1f6656ca/lib/Doctrine/Common/Persistence/Mapping/Driver/PhpDriver.php) or [StaticPhpDriver](https://github.com/doctrine/common/blob/ff72726b0876638fa7db2f28b0f26e3f1f6656ca/lib/Doctrine/Common/Persistence/Mapping/Driver/StaticPHPDriver.php) would give you the most flexibility change a collection's strategy, but even that would have to be done per-request (or ODM bootstrap).

**Comment by blockjon** [comment]
Ok thanks
