### ISSUE TITLE
PostCommit event to allow a "second round" of database operations with clean UnitOfWork

### ISSUE THREAD

**Issue by vmattila** [doctrine/mongodb-odm#1158]
This issue might be a little bit controversial but doesn't hurt to suggest and talk about it anyway. ;) I've noticed that as an application grows, it's rather easy to hit errors and strange behavior caused by some unsupported call stacks: like calling `$dm::flush()` inside already ongoing flush operation.

Now the latest possibility to intercept database operations is `postFlush` event that still happens within the `UnitOfWork::commit()`. It would be useful if there were one more event triggered after the `UnitOfWork::commit()` that could be used to do something after all previous database operations are fully done.

The danger there is indeed infinite loops as mentioned by @jmikola in a related [StackOverflow question and discussion](http://stackoverflow.com/questions/23927996/creating-persisting-new-document-while-preupdate-event-in-doctrine-mongodb). This SO question describes also one possible use case for this feature.

**Comment by malarzm** [comment]
FWIW 1) #1155 changes flow of commit to remove collection stuff from there so THEORETICALLY UnitOfWork::commit() could be reorganized tu use FIFO queue and run as long as its needed BUT:

1. This kinda breaks inserts as we use `MongoWriteBatch` to insert multiple documents of same class
2. Infinite recursion of course

We could work around 1. by changing FIFO to something more sophisticated but I believe that 2. will be hellish to debug for developers.

---

FWIW 2) personally I dropped using Doctrine events in favour of my own ones and I'm a happy person as I'm free to do anything I want and just call `$dm->flush()` after all listeners are done with their work :) The only issue I faced was #977 but it's possible to work it around (either manually or with #1131 but I'm not yet sure if I covered everything there and had more important things to take care of so far)

**Comment by vmattila** [comment]
Actually I've also been thinking to build a new layer of persistence management on top of ODM but so far Doctrine events have been working relatively well.

As dependencies between documents increase things are getting complicated. For example `prePersist` + `onFlush` combination on a document triggers a new database query of some other related documents -> their `preLoad` modifies them on the fly and new `flush()` would be required. We're still actually inside the first `onFlush` and `$uow->commit()`, aren't we.

I do not know if subsequent `$uow->commit()` or `$dm->flush()` calls could be deferred until the previous flush/commit is done?

**Comment by alcaeus** [comment]
For the record, there is a discussion about how to deal with nested flushes in #1051, however that discussion hasn't led anywhere yet.

**Comment by alcaeus** [comment]
FWIW, nested flushes are forbidden starting with ODM 2.0. And no, you still won't be able to trigger a whole new flush cycle from `postFlush`, as we only clean up internal structures after raising `postFlush` event.

Best not open that can of worms and implement this in a custom document manager.
