### ISSUE TITLE
Using push() - with each() - and pushAll() in DocumentRepository doesn't prepare embedded documents 

### ISSUE THREAD

**Issue by net02** [doctrine/mongodb-odm#1165]
When updating an EmbedMany field in a DocumentRepository, explicitly using QueryBuilder pushAll or push (with Expr::each, i.e. to leverage Expr::slice), embedded documents are not prepared.

A MongoException _zero-length keys are not allowed, did you use $ with double quotes?_ ensues due to the string representation of the PHP Object being used.

Examples:

``` php
/**
 * @ODM\Document(repositoryClass="FooRepository")
 */
class Foo
{
    ...
    /** 
     * @ODM\EmbedMany(targetDocument="Bar") 
     */
    protected $bars = array();
    ...
}

class FooRepository extends DocumentRepository
{
    public function pushBar(Foo $foo, Bar $bar) {
        $qb = $this->createQueryBuilder();
        $innerExpr = $qb->expr();
        $innerExpr
            ->sort('barField', 1)
            ->slice(3)
            ->each([$bar])
        ;
        $qb
            ->update()
            ->field('bars')->push($innerExpr)
            ->field('id')->equals($foo->getId())
            ->getQuery()
            ->execute()
        ;
        // or
        $qb
            ->update()
            ->field('bars')->pushAll([$bar])
            ->field('id')->equals($foo->getId())
            ->getQuery()
            ->execute()
        ;
    }
}
```

The second example doesn't really make sense since using Foo::addBar($bar) with the default strategy works, but I stumbled upon the first then verified it affected explicitly calling pushAll too.

As a workaround, I tried manually preparing values and stumbled upon another bug with $each. Here's the hack:

``` php
class FooRepository extends DocumentRepository
{
    public function pushBar(Foo $foo, Bar $bar) {
        $pb = new \Doctrine\ODM\MongoDB\Persisters\PersistenceBuilder($this->getDocumentManager(), $this->getDocumentManager()->getUnitOfWork());
        $metadata  = $this->getClassMetadata();
        $value = $pb->prepareEmbeddedDocumentValue($metadata->fieldMappings['bars'], $bar);

        $qb = $this->createQueryBuilder();
        $innerExpr = $qb->expr();
        $innerExpr
            ->sort('barField', 1)
            ->slice(3)
            ->each([$value])
        ;
        ...
    }
}
```

This raises an error in [DocumentPersister::prepareQueryOrNewObj](https://github.com/doctrine/mongodb-odm/blob/6dce966fa450c4f7e57a6482f8f43c2aa2e32b74/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php#L928) (which I guess should be revised to fix $each and $pushAll embedded documents preparation in first place). It's quite convoluted but it breaks down to

``` php
in_array(0, array('$and', '$or', '$nor')
```

asserting true due to in_array not being strict, and it's easy fixed adding the strict flag.

I could set up a pull request with this small fix, and maybe a shortcut to PersistenceBuilder || prepareValue in DocumentRepository (it's not accessible from the DocumentPersister right now).
Tried my hand at fixing _the grand schema of things_ in [DocumentPersister::prepareQueryOrNewObj](https://github.com/doctrine/mongodb-odm/blob/6dce966fa450c4f7e57a6482f8f43c2aa2e32b74/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php#L922-L948) but I think it's too much for me at the moment :)

**Comment by malarzm** [comment]
@net02 thanks for the report! I think so far everybody (including me) was using plain values with `QueryBuilder` but indeed it makes sense to consider such usage. As for the feature itself I don't think `PersistenceBuilder` should be exposed anywhere for preparing embedded documents' value and all action should be done behind the scenes, maybe somewhere nearby [these lines](https://github.com/doctrine/mongodb-odm/blob/6dce966fa450c4f7e57a6482f8f43c2aa2e32b74/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php#L977-L981)? Just a quick idea :)

I have added this to 1.x milestone but if somebody would hack an implementation by the time we want to release 1.0 then most probably it will be included ;)

**Comment by malarzm** [comment]
However there's one thing that need to be tackled: nested embedded documents. Given that we may not know exact mapping all the way up we may insert wrong discriminator value to newly created embedded document.

**Comment by dev-ish** [comment]
Found this thread after a google search and unfortunately it doesn't looks like this feature is implemented in doctrine/mongodb-odm so far. It would be really nice if this behaviour was implemented.

For those that need this, i found a not so nice way to do this. As a quick solution

```
$pb = new \Doctrine\ODM\MongoDB\Persisters\PersistenceBuilder($this->getDocumentManager(), $this->getDocumentManager()->getUnitOfWork());
$metadata  = $this->getClassMetadata();

$value = $pb->prepareEmbeddedDocumentValue($metadata->fieldMappings['bar'], $history);

$this->getCollection()->findAndUpdate(
    [$metadata->fieldMappings['id']['name'] => new \MongoId($product->getId())],
    ['$push' => [
        $metadata->fieldMappings['bar']['name'] => [
            '$each' => [$value],
            '$slice' => 3,
            '$sort' => [
                'barField' => -1
            ]
        ]
    ]]
);
```

**Comment by borisceranic** [comment]
Since MongoDB v3.6, the deprecated `$pushAll` operator has been removed, and `$push` + `$each` should be used instead.

Not sure if this is the right place to mention it, I'm not aware that there is another issue regarding this.

Relevant links:

* https://docs.mongodb.com/manual/release-notes/3.6/#removed-operators
* https://docs.mongodb.com/manual/release-notes/3.6-compatibility/#pushall-compatibility
