### ISSUE TITLE
Mongoid strategy issue

### ISSUE THREAD

**Issue by navneetccna** [doctrine/mongodb-odm#1167]
when i use following mongoid strategy

```
/** @ODM\Id(strategy="NONE") */

$id = '50e6c53cf8ae035c1b000001';
$User->setId($id);
```

id inserted successfully in collection but getting following error

> Warning: Illegal offset type in vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php on line 1565

**Comment by malarzm** [comment]
@navneetccna which ODM version are you using? Both [current dev-master](https://github.com/doctrine/mongodb-odm/blob/b1089b723df8ae2230694a3899941e05d560c41f/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L1565) and [BETA13](https://github.com/doctrine/mongodb-odm/blob/1.0.0-BETA13/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L1565) have comments in that line.

Also using "NONE" strategy means that you must generate ID on your own, I'd say that best would be to do that before `persist()`

**Comment by malarzm** [comment]
Closing because of no response
