### ISSUE TITLE
Deprecate annotations that conflict with reserved words in PHP7 

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#1168]
See:

 * https://github.com/doctrine/phpcr-odm/issues/641
 * https://github.com/doctrine/phpcr-odm/pull/643

This is not terribly urgent, since the existing [mongo](http://pecl.php.net/package/mongo) extension will not be updated for PHP7 compatibility ([mongodb](http://pecl.php.net/package/mongodb) will); however, we should probably get this change in before 1.0.0 stable.

----

Per [PHP7 reserved words](http://php.net/manual/en/reserved.other-reserved-words.php), we need to not include `Int.php`, `Bool.php`, `String.php`, and `Float.php` from `DoctrineAnnotations.php` on PHP7+.

**Comment by Soullivaneuh** [comment]
@jmikola What is your suggestion about how to solve it?

**Comment by Soullivaneuh** [comment]
BTW I have a question: What is the difference between `Bool` and `Boolean` annotations?

**Comment by malarzm** [comment]
@Soullivaneuh they're the same thing, we had inconsistency with `Boolean` being full name and `Int` being short so we introduced full and short versions of both

**Comment by stanlemon** [comment]
@Soullivaneuh just use the ```@Field(type="bool")``` annotation instead of ```@Bool```

**Comment by Soullivaneuh** [comment]
> @Soullivaneuh they're the same thing, we had inconsistency with Boolean being full name and Int being short so we introduced full and short versions of both

@malarzm In this case, why not just deprecate `Bool` and use `Boolean` instead?

> @Soullivaneuh just use the @Field(type="bool") annotation instead of @Bool

@stanlemon I just get this error directly on app/console:

```bash
$ php app/console 
PHP Fatal error:  Cannot use 'Bool' as class name as it is reserved in vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Bool.php on line 23

Fatal error: Cannot use 'Bool' as class name as it is reserved in vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Bool.php on line 23
```

I don't use `Bool` annotation on my documents.
