### ISSUE TITLE
Reduce queries when priming references for single collection inherited documents

### ISSUE THREAD

**Issue by gruberro** [doctrine/mongodb-odm#1170]
I think priming references could save some queries on inherited documents by not grouping the references by their reference class name but the parent class name if the inheritance type is of ```SINGLE_COLLECTION```.

See [ReferencePrimer.php#L152](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php#L152) and [ReferencePrimer.php#274](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php#L274) for the related code parts.

In my particular case we have a single inherited collection with 4 different types of document instances also causing 4 priming queries. By consolidating those class references to it's parent collection this could save 3 queries.

**Comment by malarzm** [comment]
@gruberro do you maybe have a benchmark for both small and big data sets? I'm curious what is quicker, 4 queries with `=` or 1 query with `$in`, possibly worth checking with index on discriminator as well?

**Comment by gruberro** [comment]
I'll try to put together some performance data within the next few days!!

**Comment by gruberro** [comment]
I finally did some research on this. In fact there is no practical difference. Most queries are that fast, that consolidating the queries would safe only some few millis under some circumstances. It might also safe some query time with very huge result sets, but in all of this cases I'd no longer prime references as this would cost too much memory (eager) etc. So no real improvement possible here - my first thoughts were wrong, I'm going to close the idea.
