### ISSUE TITLE
Undefined index 'strategy' since the introduction of the CollectionHelper

### ISSUE THREAD

**Issue by redthor** [doctrine/mongodb-odm#1174]
Hi there, thanks for Doctrine!

We've been following dev-master and started getting this error in our tests:

```
exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Notice: Undefined index: strategy' in /var/www/site/web/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php:1047 Stack trace: 
#0 /var/www/site/web/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php(1047): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/...', 1047, Array) 
#1 /var/www/site/web/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php(936): Doctrine\ODM\MongoDB\Persisters\DocumentPersister->prepareQueryElement('nodes.id', '763cf7d5-0f88-4...', NULL, true) 
#2 /var/www/site/web/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php(926): Doctrine\ODM\MongoDB\Persisters\DocumentPersister->prepareQueryOrNewObj(Array) 
#3 /var/www/site/web/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php(470): Doctrine\ODM\MongoDB\Persisters\DocumentPersister->prepareQueryOrNewObj(Array) 
#4 /var/www/site/web/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentRepository.php(184): Doctrine\ODM\MongoDB\Persisters\DocumentPersister->load(Array) 
```

I did a `git bisect` and tracked it down to https://github.com/doctrine/mongodb-odm/commit/dfd7d64fe71f6963e90cc49960fca32116910dbb

The fields `nodes` is `type: collection` in our mapping file. `nodes.id` is an `id` key in the array of nodes.

For the moment I've pinned mongo-odm in our composer.json:
`"doctrine/mongodb-odm": "dev-master#1522f509a511f26238dafce2798ccd91a6c627f7"`

**Comment by malarzm** [comment]
@redthor thanks for the report, I will try to take care of this today or tomorrow!

**Comment by malarzm** [comment]
@redthor you said that 

> started getting this error in our tests

is there any chance you could create a failing test case? I'd include it to prevent regressions

**Comment by malarzm** [comment]
Actually one more question: how come `nodes` are Collection (which is a numerically indexed array) and yet you have `nodes.id`? Shouldn't you use Hash field?

**Comment by redthor** [comment]
> failing test case

Sure thing. I'll look at creating one tomorrow. Is there a particular test file that would be best to start with?

> Shouldn't you use Hash field?

Yes, I think you're right. The implementation was a bit rushed. We'd need to convert over to `hash`, run tests to create them, then add a database migration and re-test with the old data.... It's a good idea thank you. I'll ticket it :) (Actually, a better implementation may require converting to a `Node` class and use `ArrayCollection`, hmmm...)

**Comment by malarzm** [comment]
> Sure thing. I'll look at creating one tomorrow. Is there a particular test file that would be best to start with?

You can take a look at tests/.../Functional/Ticket folder, it's a good start :)

**Comment by redthor** [comment]
Unfortunately this is passing:
https://github.com/redthor/mongodb-odm/commit/920c9f93ec1a31877065aa84a8d7fca5a7b93676

I'll try some more digging to find out what combination is making it happen...

**Comment by redthor** [comment]
I believe I've found the issue now:
https://github.com/redthor/mongodb-odm/commit/5d40e6e02243fb2671de6c421223bb9093d7db2c

field mappings are different between drivers. There isn't a 'strategy' key on by default for the YAML driver which we use.

**Comment by malarzm** [comment]
@redthor thanks, I'll try to investigate it today/tomorrow
