### ISSUE TITLE
Batch insert continueOnError issue

### ISSUE THREAD

**Issue by metanav** [doctrine/mongodb-odm#1176]
Suppose I have a BlogPost document which has  comments (ReferenceMany to Comment document). If I do batch insert of BlogPost documents (say 10 items) with flush option 'continueOnError' and due to some constraints one of BlogPost (say 7th one) is rejected by MongoDB, all other BlogPost documents are persisted in MongoDB but Comment documents are not saved. I believe Doctrine ODM  executes two queries one for saving BlogPost and another one for saving Comments and just after saving BlogPost it throws exception which blocks the next query execution. Is this a bug? Is there any better way to handle this situation?

**Comment by malarzm** [comment]
@metanav you should be able to `flush` again. I'm not sure if ignoring exceptions at all would be good idea, what do you think @jmikola ?

**Comment by metanav** [comment]
@malarzm 
You mean I should call flush() again in catch block?
Should I call it with or without "continueOnError = true" ? Will it again throw exception if there is another constraint violation?

Example:
```
$blogpost->addComments($comments);
try {
    $dm->persist($blogpost);
    $dm->flush(null, array('continueOnError' => true))
} catch (\Exception $ex) {
    $dm->flush();
}
```

**Comment by malarzm** [comment]
Frankly it'll be the best to test, I'm not sure how much bulletproof is doing another `flush` after an errored one, there are many things that could or could not go wrong with it. But to answer your questions:

> You mean I should call flush() again in catch block?

Yes, I believe that's what I meant :)

> Should I call it with or without "continueOnError = true" ?

Up to you

> Will it again throw exception if there is another constraint violation?

Yes
