### ISSUE TITLE
Unable to use custom object id

### ISSUE THREAD

**Issue by marcospassos** [doctrine/mongodb-odm#1178]
Hi folks!

I'm trying to use a custom object id without success. I've defined a custom mapping type, but seems like id fields just ignore the attribute `type`, thus the conversion is not performed.

Mapping:
```xml
<document name="Acme\User"  customId="true">
    <field fieldName="id" id="true" type="user_id" strategy="NONE" />
</document>
```

Custom type mapping:
```php
class UserIdType extends Type
{
    public function convertToDatabaseValue($value)
    {
        return $value !== null ? (string) $value : null;
    }

    public function closureToMongo()
    {
        return '$return = (string) $value;';
    }

    public function convertToPHPValue($value)
    {
        return $value !== null ? UserId::fromString($value) : null;
    }

    public function closureToPHP()
    {
        return '$return = Acme\UserId::fromString((string) $value);';
    }
}
```

Model:
```php
namespace Acme\User;

class User
{
    private $id;

    public function __construct(UserId $id)
    {
         $this->id = $id;
    }
}
```

Error:

```
zero-length keys are not allowed, did you use $ with double quotes?
```

For DDD adopters, is very common to have an id represented by an object.

If you guys agree, I would be glad to provide a PR to fix it.

**Comment by malarzm** [comment]
@marcospassos indeed looks like a good thing to have, PR will be much appreciated!

**Comment by malarzm** [comment]
I've scheduled this to be in 1.x but if feature will be done by the time we release 1.0 I'll happily include it :)

**Comment by marcospassos** [comment]
@malarzm Nice! I'll work on this over the next days. Could you please take a look at #1179 as well?

**Comment by marcospassos** [comment]
PR added including unit tests.

**Comment by malarzm** [comment]
I'm in countryside so I'll take a look at all the things tomorrow ;)
