### ISSUE TITLE
Bool is a reserved class name on PHP 7

### ISSUE THREAD

**Issue by Soullivaneuh** [doctrine/mongodb-odm#1187]
Produced error:

```
Fatal error: Cannot use 'Bool' as class name as it is reserved in vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Bool.php on line 23
```

This class have to be deprecated and renamed.

**Comment by malarzm** [comment]
We are going to deprecate all reserved annotations (https://github.com/doctrine/mongodb-odm/issues/1168) and drop them once PHP7 and mongo driver for it will be ready

**Comment by Soullivaneuh** [comment]
Didn't see that issue. Was looking with `bool` search keyword.

Thanks.
