### ISSUE TITLE
EmbedMany persistence doesn't create empty array

### ISSUE THREAD

**Issue by ofetisov** [doctrine/mongodb-odm#1195]
Hi there! I've encountered a tricky problem and couldn't find a appropriate solution. I have document with EmbedMany field like

```
    // It is configured to use discriminator map I think it doesn't has 
    // any influence on my question so i omitted the details.

    /**
     * @ODM\EmbedMany(
     *     discriminatorField="t",
     *     discriminatorMap={"a"="ClassA"}
     * )
     */
    protected $comments = array();
```

So the problem is: when i'm trying to save (persist & flush) new document with empty comments field - ODM doesn't creates comment field at all. And i need to have empty array there to be able to run [$size](http://docs.mongodb.org/manual/reference/operator/aggregation/size/) queries on this field.

I've debugged a little bit and found the root of the problem. [PersistenceBuilder (line 77-80)](https://github.com/doctrine/mongodb-odm/blob/1.0.0-BETA13/lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php#L77-L80)

```
    // @ReferenceMany and @EmbedMany are inserted later
    if ($mapping['type'] === ClassMetadata::MANY) {
        continue;
    }
```

It skips this field here, and never "inserts it later" due to the fact that no EmbedDocument is scheduled to persist/insert.

So could somebody give me an advice how to deal with this?

**Comment by malarzm** [comment]
@ofetisov you can use [$ifNull](http://docs.mongodb.org/manual/reference/operator/aggregation/ifNull/#exp._S_ifNull):

```
db.col.aggregate([ 
    { 
        "$project": { 
            someValue: 1, 
            nb: { "$size": { "$ifNull": [ "$array", [  ] ] } } } 
    } 
]);
```

**Comment by ofetisov** [comment]
@malarzm Thank you for quick response! Yes, I know about $ifNull but i would prefer to have empty array in my DB. Maybe there is some way to configure embedMany?

**Comment by malarzm** [comment]
> Maybe there is some way to configure embedMany?

Sorry, there is not or at least I can't recall it :)

**Comment by ofetisov** [comment]
@malarzm bad news =( But in any case thank you for your time.

**Comment by josefsabl** [comment]
@malarzm Very bad news indeed. We ran into serious problems due to this too. Why I think this is a bug and not a feature?

1) Mongo itself supports empty array with embedded documents so no reason to say that it is a bad practice.
2) It is inconsistent with other field types that respect default php value including empty arrays.

Of course that you can always work around in isolated example but imagine you have some heavily object oriented solution where every piece of final logic (think query) is separated in various parts of the code. Then you can run into big troubles.

Thanks for considering fixing that.

**Comment by malarzm** [comment]
@josefsabl I never said it is a bad practice nor that it shouldn't be fixed :P We'll certainly appreciate a PR. Quick solution would be indeed to have a configuration option for `EmbedMany` and `ReferenceMany` that would tweak `PersistenceBuilder` behaviour and change `$unset` when collection is removed to `$set` with empty array.

Looking at [this if](https://github.com/doctrine/mongodb-odm/blob/1.0.2/lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php#L78) it might be also worth working on #1039 at the same time (that one is in my plans)

**Comment by ajax13** [comment]
Hello, I have the same problem.  Any hook to unlock the situation until it is gonna be fixed?

**Comment by ajax13** [comment]
I've made a PR, I hope you will acceptd!
https://github.com/doctrine/mongodb-odm/pull/1624
