### ISSUE TITLE
hydration/caching gives me unexpected results

### ISSUE THREAD

**Issue by pablomoreno61** [doctrine/mongodb-odm#1196]
Hydration is not giving me the expected information in the given scenario.

I'm executing a filtered query, which will return some fields for given user _ids.

<code>
    $qb = $this->dm->createQueryBuilder('CSP\Domain\User\Document\User')->select($fields)->field('_id')->in($oids);

    $users = $qb->getQuery()->execute();
</code>

After that, If I execute a findOneBy to a previous used _id (previous query), it will return the previous cached/hydrated document (filtered) instead of the new one (full document)

<code>
    $userDocument = $this->userDocumentRepository->findOneBy($criteria);
</code>

My guess is that hydration should only affect to exact queries, as it is not the same: "db.users.find({id:1}, fields)" != "db.users.find({id:1})"

**Comment by malarzm** [comment]
I believe there's not much we can do automatically, your first query has registered documents in the `UnitOfWork` and later queries for these documents will return that very instances (their data could be updated by calling `->refresh()` while building query but unfortunately there's no way to pass that hint via `DocumentRepository`).

The situation can be fixed manually by calling `$dm->refresh($userDocument)` after fetching it if you know that previously you were querying for part of objects.

**Comment by pablomoreno61** [comment]
If mongo information changes between both queries, because an update query, is this situation still happening?

Refresh could be a solution, I'm actually doing queries with hydrate(false) to avoid this problem.

**Comment by malarzm** [comment]
> If mongo information changes between both queries, because an update query, is this situation still happening?

If you run an update with `Query` then yes, we have scheduled a documentation improvement for this (#880 with all discussion). There's a lot of place to improve here but it's also hard to make a good change.

**Comment by jmikola** [comment]
Documentation has been added to #1203.
