### ISSUE TITLE
Entities passed to the choice field must be managed

### ISSUE THREAD

**Issue by OndrejPiza** [doctrine/mongodb-odm#1198]
Hi,

I have a problem. For some reason documents with many to many relation( so far only this one I have tested ) are not correctly loaded to the choice field. 

I have articles and categories. Until the article was not in a category, everything was OK and choice list was correctly rendered. When I assigned an article to the category, this error appeared.

My article form:
```
        $builder->add('categories', 'document', [
            'class' => 'Acme\ArticlesBundle\Document\ArticleCategory',
            'property' => 'title',
            'required'=> false,
            'multiple' => true,
            'expanded' => false,
        ]);
```
Article document:
```
    /**
     * @var ArrayCollection
     *
     * @ODM\ReferenceMany(targetDocument="ArticleCategory", inversedBy="articles", cascade={"persist"})
     */
    protected $categories;
```
Category document:
```
    /**
     * @var ArrayCollection
     *
     * @ODM\ReferenceMany(targetDocument="Article", mappedBy="categories")
     */
    protected $articles;
```

In the DB everything is saved, so the relation is working. 

Did I forget something? I checked the EntityChoiceList class for the type of em option and it is the correct Mongo DB Document Manager.

**Comment by OndrejPiza** [comment]
Hi,

I kind of figure it out, only don't know the reason. I was using my own document manager, which name differs from the "default". When I switched back to the "defalut" it worked. So the question is, if I'm using my own, do I have to register him somewhere as default one globally even for symfony?

**Comment by malarzm** [comment]
@OndrejPiza thanks for the report! If you need to use your own `DocumentManager` you would need to register it in `ManagerRegistry` but unfortunately that is immutable (https://github.com/doctrine/DoctrineMongoDBBundle/issues/268). There's my PR in the bundle (where the issue should be reported so I'll close this one) https://github.com/doctrine/DoctrineMongoDBBundle/pull/269 which sole purpose is dealing with situation like yours as I've run into similar one. You can use my fork for the time being or I will get back to it once we're done with stabilizing ODM.
