### ISSUE TITLE
DBRef field orders

### ISSUE THREAD

**Issue by bensquire** [doctrine/mongodb-odm#1200]
We had a 2.4 system thats recently been upgraded to 2.6 and then 3.0.1. Everything appeared to be working, until we saw this message:

    Found $db field without a $id before it, which is invalid.

A quick google found this code, https://github.com/mongodb/mongo/blob/master/src/mongo/db/exec/update.cpp#L98

and a quick look in our DB reveals the ordering is incorrect in some of our collections DBRef's. We've never inserted this data manually, so we're trying to work out if this is a symptom of the DB upgrade, or a bug thats was removed in an old version of Doctrine or something else.

Can anyone offer any insight?
Thanks

Ben

**Comment by malarzm** [comment]
At a glance ODM seem to [specify correct order of the fields](https://github.com/doctrine/mongodb-odm/blob/441966f77ff4ae2cdc7eeee4d261d3931e5a699e/lib/Doctrine/ODM/MongoDB/DocumentManager.php#L691-L695) at least in current `dev-master`.

**Comment by bensquire** [comment]
Thanks @malarzm I've checked back as far as version 7 (thanks to your link), it doesn't seem to be  symptom of Doctrine. If nothing else I can tick this off the list of possible causes.

Cheers

**Comment by alcaeus** [comment]
We've had the same problem when doing the upgrade and couldn't trace it back to anything either. We ended up rewriting all of our documents with broken references.

**Comment by bensquire** [comment]
@alcaeus Thanks its nice to know we're not the only ones who've experienced this issue. How did you go abouts rewriting all your documents? I'm assuming it wasn't by hand?

P.S. Did you use compose.io, by chance?

**Comment by bensquire** [comment]
@websirnik I literally went through and manually corrected the issue. At some point in the past we'd manually modified some documents which Mongo 2 had accepted, v3 not so much. Sorry I can't offer any better advice...

**Comment by alcaeus** [comment]
@websirnik same as @bensquire, we also went through the database and manually updated all references.
