### ISSUE TITLE
Create a similar project targeting Google Cloud Datastore

### ISSUE THREAD

**Issue by atrauzzi** [doctrine/mongodb-odm#1209]
There's [currently a library](https://github.com/tomwalder/php-gds) targeting google cloud datastore for php, although it would be nice to see one done according to Doctrine conventions.

Especially given that google cloud datastore is quite similar to mongodb.

**Comment by malarzm** [comment]
Idea is interesting (especially if projects are alike and we could for instance abstract things in doctrine/mongodb like doctrine/dbal does) but I'm not sure we have enough workforce to do that (or in my case knowledge as I haven't used Google's product).

**Comment by atrauzzi** [comment]
Understandable.  I guess there are a lot of document-like database solutions out there that would benefit from having a generic ODM available.  Even if they are designed for different purposes, the general concepts of being document-centric and schemaless would make them worth targeting from one library.  Similar to how we do MSSQL, postgres, and MySQL all from Doctrine ORM.

**Comment by jmikola** [comment]
This would definitely need to be implemented in a separate repository, like the other ODM projects (see: [here](https://github.com/doctrine?utf8=%E2%9C%93&query=odm)) under the Doctrine project.

**Comment by malarzm** [comment]
Closing as we have not enough people on board to do such thing
