### ISSUE TITLE
How to perform double flush

### ISSUE THREAD

**Issue by OndrejPiza** [doctrine/mongodb-odm#1215]
Hi,

is it possible to perform double flush on DocumentManager< 

I have my own class with little modified behavior on flush method

```
/**
     * Flushes all changes to objects that have been queued up to now to the database.
     * This effectively synchronizes the in-memory state of managed objects with the
     * database.
     *
     * @param object $document
     * @param array $options Array of options to be used with batchInsert(), update() and remove()
     * @throws \InvalidArgumentException
     */
    public function flush($document = null, array $options = array())
    {
        if (null !== $document && !is_object($document) && !is_array($document)) {
            throw new \InvalidArgumentException(gettype($document));
        }
        $this->errorIfClosed();

        $this->unitOfWork->commit($document, $options);

        foreach($this->afterFlushDocuments as $documentTemp){
            $this->merge($documentTemp);
            $this->refresh($documentTemp);
            $this->persist($documentTemp);
        }
        
        $this->unitOfWork->commit($document, $options);

        $this->afterFlushDocuments = [];
    }
```

But instead of updating in the second flush, the objects are inserted.  Should  I call resfresh on the UnitOfWork? 

The scenario is to automatically update some documents, but to perform this action I need the ID keys and I don't want to use listeners.

**Comment by malarzm** [comment]
> The scenario is to automatically update some documents, but to perform this action I need the ID keys 

Document's IDs are generated during initial `persist()` and are available just after it, I think there's no need to hack flush method for this :)

**Comment by OndrejPiza** [comment]
Thank you, I wasn't aware of the fact, that ID is generated by doctrine. My initial thought was that MongoDB is handeling this stuff, just like the MySQL generate ID after insert if strategy is set to AUTO.

Tahnk you for this information. I find it really usefull. :-)

**Comment by malarzm** [comment]
@OndrejPiza if you're using AUTO strategy you'll be getting `new \MongoId()`casted to string as an identifier and you would have to be a [terribly unlucky man to get a collision](http://stackoverflow.com/questions/4677237/possibility-of-duplicate-mongo-objectids-being-generated-in-two-different-colle)
