### ISSUE TITLE
ReferenceMany ( PersistenCollection ) causses exception when flush

### ISSUE THREAD

**Issue by OndrejPiza** [doctrine/mongodb-odm#1216]
Hi,

I have an Article document wit assigned categories

```
    /**
     * @var ArrayCollection
     *
     * @ODM\ReferenceMany(targetDocument="ArticleCategory")
     */
    protected $categories;
```
and ArticleCategories with articles:

```
    /**
     * @var ArrayCollection
     *
     * @ODM\ReferenceMany(targetDocument="Article")
     */
    protected $articles;
```
but when I try to save it, it causes a problem:

```
ContextErrorException in PrettyDataCollector.php line 226: Catchable Fatal Error: Object of class Doctrine\ODM\MongoDB\PersistentCollection could not be converted to string
```
It tries to convert PersistetCollection type to basic MongoDB types in function bsonEncode and this point it it fallback to the last (string) $value which conversion does not PersistenCollection support.

Do I have any mistakes in the configuration or document setting?

**Comment by malarzm** [comment]
[PrettyDataCollector](https://github.com/doctrine/DoctrineMongoDBBundle/blob/9e98fd9def517c68c8b8db43333545faef9a94b6/DataCollector/PrettyDataCollector.php#L43) should collect raw queries sent to database so `PersistentCollection` being there is strange as it should be converted to array already. Can you paste full code snippet that is causing the error?

**Comment by OndrejPiza** [comment]
I was trying to achive a functionality, that will take the object state, convert it to associated array and than pass it as a pervioues version and this version it than added to the article versions collection.

This collection is embedded and mapped by me in the Listener ( the parameter of the version class is correct ):
```
        $versions['fieldName'] = 'versions';
        $versions['type'] = 'many';
        $versions['embedded'] = true;
        $versions['targetDocument'] = $this->versionDocumentClass;
        $versions['strategy'] = 'pushAll';
        $versions['name'] = 'versions';
        $versions['nullable'] = true;
        $versions['options'] = [];
        $versions['isCascadeRemove'] = true;
        $versions['isCascadePersist'] = true;
        $versions['isCascadeRefresh'] = true;
        $versions['isCascadeMerge'] = true;
        $versions['isCascadeDetach'] = true;
        $versions['association'] = 4;
        $versions['isOwningSide'] = true;
        $versions['isInverseSide'] = false;
```
Same config works ok for translations, which basically are the same, only embedded collection of documents.

This is the part from the versions trait:
```
    /**
     * @var ArrayCollection
     */
    protected $versions = [];

    /**
     * @return ArrayCollection
     */
    public function getVersions()
    {
        return $this->versions;
    }

    /**
     * @param $versions
     * @return IVersionable
     */
    public function setVersions($versions)
    {
        $this->versions = $versions;

        return $this;
    }

    /**
     * @param IVersion $version
     * @return IVersionable
     */
    public function addVersions(IVersion $version)
    {
        $this->versions[] = $version;

        return $this;
    }
```

and here is the Version document
```
/**
 * Class SingleVersion
 *
 * @ODM\EmbeddedDocument()
 * @ODM\Indexes({ @ODM\Index(keys = {"actionType"="asc"}) })
 */
class Version extends AbstractDocument implements IVersion
{
    /**
     * @var string
     *
     * @ODM\String(name="actionType")
     */
    protected $actionType;

    /**
     * @var string
     *
     * @ODM\Date(name="dateOfAction")
     */
    protected $dateOfAction;

    /**
     * @var array
     *
     * @ODM\Hash(name="data")
     */
    protected $data = [];

    /**
     * @return string
     */
    public function getActionType()
    {
        return $this->actionType;
    }

    /**
     * @param string $actionType
     */
    public function setActionType($actionType)
    {
        $this->actionType = $actionType;
    }

    /**
     * @return string
     */
    public function getDateOfAction()
    {
        return $this->dateOfAction;
    }

    /**
     * @param string $dateOfAction
     */
    public function setDateOfAction($dateOfAction)
    {
        $this->dateOfAction = $dateOfAction;
    }

    /**
     * @return array
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * @param array $data
     */
    public function setData($data)
    {
        $this->data = $data;
    }

    /**
     * Return string representation of entity
     *
     * @return string
     */
    public function __toString()
    {
        return "Version";
    }
}
```
I checked, that article after serialization to the data property containes his parent category, but everything is converted to associated array. o there shouldn' be a problem for @Hash to store it.

**Comment by OndrejPiza** [comment]
I've done some digging and it looks like the settings for mapping are wrong. Because when I move the translations or basically any embedded documents collection to the trait class and tries to mapped it dynamically, it all went wrong. Am I missing any settings? Because if I move the property back to the Article document, it works.

LoadClassMetadataListener:
```
    /**
     * @param LoadClassMetadataEventArgs $eventArgs
     */
    public function loadClassMetadata(LoadClassMetadataEventArgs $eventArgs)
    {
        $reflexionClass = $eventArgs->getClassMetadata()->getReflectionClass();
        $interfaces = $reflexionClass->getInterfaceNames();
        if (in_array($this->translatableInterface, $interfaces)) {
            $this->mapTranslatable($eventArgs, $reflexionClass);
        }
    }

.................

    /**
     * @param LoadClassMetadataEventArgs $eventArgs
     * @param \ReflectionClass $reflectionClass
     */
    protected function mapTranslatable(LoadClassMetadataEventArgs $eventArgs, \ReflectionClass $reflectionClass)
    {
        $metaData = $eventArgs->getClassMetadata();

        if (!$metaData->hasAssociation('translations')) {
            $metaData->mapField($this->createTranslatedMappingArray($reflectionClass->getName() . 'Translation'));
        }
    }

...............

    /**
     * @param $translationClass
     * @return array
     */
    protected function createTranslatedMappingArray($translationClass)
    {
        $translations = [];

        $translations['fieldName'] = 'translations';
        $translations['type'] = 'many';
        $translations['embedded'] = true;
        $translations['targetDocument'] = $translationClass;
        $translations['strategy'] = 'pushAll';
        $translations['name'] = 'translations';
        $translations['nullable'] = false;
        $translations['options'] = [];
        $translations['isCascadeRemove'] = true;
        $translations['isCascadePersist'] = true;
        $translations['isCascadeRefresh'] = true;
        $translations['isCascadeMerge'] = true;
        $translations['isCascadeDetach'] = true;
        $translations['association'] = 4;
        $translations['isOwningSide'] = true;
        $translations['isInverseSide'] = false;

        return $translations;
    }
```
This was retaken from what I know from ORM and what I see in the passed metadata when the EmbeddedDocuments were originaly in the document Article.

**Comment by OndrejPiza** [comment]
I've done some digging but couldn't find any solution. I find out, that my dynamically mapped properties after calling mapField were missing in the reflFields, so I've added them manually, but it still doesn't get me to the working state of app. I can do some research, but could you please told me, if there is an working example of dynamic mapping?

Or perhaps where could I try to start looking for problem? I couldn't find any more deeply focused documentation on how doctrine ODM works ( hydrators, creating proxies .... ).

Thank you

**Comment by OndrejPiza** [comment]
Here is my exception:
```
 in PrettyDataCollector.php line 226
at ErrorHandler->handleError('4096', 'Object of class Doctrine\ODM\MongoDB\PersistentCollection could not be converted to string', '...../vendor/doctrine/mongodb-odm-bundle/DataCollector/PrettyDataCollector.php', '226', array('query' => array('createdOn' => object(DateTime), 'translations' => object(PersistentCollection)), 'array' => false, 'parts' => array('"createdOn"' => 'new ISODate("2015-08-24T07:19:00+02:00")'), 'key' => 'translations', 'value' => object(PersistentCollection), 'formatted' => 'new ISODate("2015-08-24T07:19:00+02:00")')) in PrettyDataCollector.php line 226
at PrettyDataCollector->bsonEncode(array('createdOn' => object(DateTime), 'translations' => object(PersistentCollection))) in PrettyDataCollector.php line 224
at PrettyDataCollector->bsonEncode(array('_id' => object(MongoId), 'action' => 'update', 'loggedAt' => object(MongoDate), 'objectId' => '55c8652bd593e010228b4567', 'objectClass' => 'ACME\ArticlesBundle\Document\Article', 'version' => '2', 'data' => object(stdClass), 'username' => 'admin')) in PrettyDataCollector.php line 206
at PrettyDataCollector->bsonEncode(array('000000007424557400007fd71573b92f' => array('_id' => object(MongoId), 'action' => 'update', 'loggedAt' => object(MongoDate), 'objectId' => '55c8652bd593e010228b4567', 'objectClass' => 'ACME\ArticlesBundle\Document\Article', 'version' => '2', 'data' => object(stdClass), 'username' => 'admin'))) in PrettyDataCollector.php line 92
```

By the code, it looks like some logger thats creating information about my actions. Could that be a source of problem? That I'm passing the property translations even to this object as well?

**Comment by malarzm** [comment]
@OndrejPiza I haven't been playing myself with dynamic mapping much so I'm not sure how much help I'll be, but let's take a stab at it. First I'd write a test for ODM only (as PrettyDataCollector comes from Bundle) and see if dynamic mapping is saved correctly (comparing to similar document mapped normally). If this works, I'd check persist flow if it can save and read back document with dynamic mapping correctly. If that works as well then probably bug will be in the bundle.

**Comment by OndrejPiza** [comment]
It looks like it's related to the Symfony profiler. It occurs when PrettyDataCollector collects logged data query from symfony logger. 

Somehow it contains my dynamically added translations in raw state (PersistentCollection), which is unable to work with.

**Comment by malarzm** [comment]
> When I block it in the symfony profiler, the only thing that is staing is the "zero-length keys exception"

That sound like something is wrong with your dynamic mapping then as `PersistentCollection` wasn't converted to plain array on its way to the database (which causes profiler to fail down the line as well). I'd definitely follow steps I've provided to find culprit.

**Comment by OndrejPiza** [comment]
@malarzm I've followed your guide and found the problem. It was the GedmoDoctrineExtensions Bundle. It somehow messed the dynamicaly builded properties. When I disabled it, it all start working. 

So I can approve that dynamic mapping works OK with a little slight problem, that when you call mapField, the field is added to the mapping and association array, but the reflFields are not updated, so you have to add it to this array too and also you have to set accessibility to this reflection property. But with these correctly set, it works flawessly.

Thank you very much for your help :+1:
