### ISSUE TITLE
Cannot add/edit/update referenced or embedded documents after commit.

### ISSUE THREAD

**Issue by peshi** [doctrine/mongodb-odm#1218]
When using ODM with Symfony I can't add/edit or update referenced / embedded documents from this commit:
```
https://github.com/doctrine/mongodb-odm/commit/e2f23bc3eea11393995f0a799a02f34380201606
```
Error: 
```
Attempted to call an undefined method named "getUseIdentifierKeys" of class "Doctrine\MongoDB\LoggableCursor".
```

This commit is working fine:
```
https://github.com/doctrine/mongodb-odm/commit/17979498aaa575fadcdd9162d6e3133a0e7d234b
```

My scenario is pretty simple,
```
$document = $dm->getRepository('Document')->find($id);
$document->setUsername('blabla');
$dm->persist($document);
$dm->flush();
```

**Comment by alcaeus** [comment]
Could you add the versions of doctrine/mongodb-odm and doctrine/mongodb you are using? ```getUseIdentifierKeys()``` was introduced in doctrine/mongodb 1.2 which is enforced as a minimum dependency in composer.json.

**Comment by peshi** [comment]
Honestly I haven't used "doctrine/mongodb": "~1.2" as I expected this to update automatically, this didn't seem to be the case, after adding this line it now works.

Thank you.

**Comment by alcaeus** [comment]
You shouldn't have to define it in your composer.json - did it not update when you updated doctrine/mongodb-odm?

**Comment by peshi** [comment]
It actually didn't update when using 'composer update'
