### ISSUE TITLE
Recursive function calls using set strategy and a repositoryMethod

### ISSUE THREAD

**Issue by rubenrua** [doctrine/mongodb-odm#1220]
See https://github.com/rubenrua/mongodb-odm/commit/ba8d02412e063e0ad5362e2d404f5df5b1e4d1bb

**Comment by rubenrua** [comment]
Added a test and a possible fix in the pull request #1221.

**Comment by malarzm** [comment]
Let's keep discussion (if there'll be one in #1221)
