### ISSUE TITLE
Does the ODM support MongoDB's v2.6 comment feature?

### ISSUE THREAD

**Issue by blockjon** [doctrine/mongodb-odm#1224]
http://docs.mongodb.org/v2.6/reference/operator/meta/comment/

**Comment by malarzm** [comment]
You should be able to use it using [Cursor::addOption](https://github.com/doctrine/mongodb-odm/blob/c3933ad5eb0c23e7262f60efa1ad12605484bf48/lib/Doctrine/ODM/MongoDB/Cursor.php#L200)

**Comment by blockjon** [comment]
I believe i have figured out how to use setOption() when doing a find query. However, when I'm inserting or updating data, its not clear to me how to do a $comment.

http://docs.mongodb.org/manual/reference/operator/meta/comment/ says "To attach comments to query expressions in other contexts, such as db.collection.update(), use the $comment query operator instead of the meta-operator."

Can you give me an example of how I could attach a MongoDB $comment to a database update?

**Comment by blockjon** [comment]
I think i have it figured out. I need to add a $comment key to the $newObj attribute during a write.

**Comment by malarzm** [comment]
Glad it's working :)
