### ISSUE TITLE
Unit of work -> annotation events should also get eventargs

### ISSUE THREAD

**Issue by ThePatzen** [doctrine/mongodb-odm#1228]
Since doctrine 2.4 also annotation events should get eventargs. It seems this is not yet implemented for mongodb-odm right?

**Comment by alcaeus** [comment]
What exactly do you mean with annotation events? Do you mean lifecycle callbacks (those annotated using ```@ODM\prePersist```)?

#1222 changes event arguments for the preLoad callback (which at this time is the only callback receiving args at all). All other lifecycle callbacks do not receive event args at this time.

**Comment by ThePatzen** [comment]
Hi! I've talked about those Lifecycle callbacks.
For example see http://doctrine-orm.readthedocs.org/en/latest/reference/events.html#lifecycle-callbacks-event-argument this says "Since 2.4 the triggered event is given to the lifecycle-callback." 
Am i unterstanding something wrong?

**Comment by alcaeus** [comment]
@ThePatzen you understood everything correctly, I was just ensuring we're talking about the same thing.

While the ORM (for which you linked to the docs) added an event object to the lifecycle callbacks, the ODM does not have that functionality yet: https://doctrine-mongodb-odm.readthedocs.org/en/latest/reference/events.html#lifecycle-callbacks
I've scheduled this feature for inclusion in the next milestone. Of course, you can always create a pull request to get us started on this feature.

**Comment by malarzm** [comment]
FWIW #1222 is ready I just never got to start merging 1.x PRs yet :)

**Comment by malarzm** [comment]
#1222 has been merged
