### ISSUE TITLE
clone not working on embeded document

### ISSUE THREAD

**Issue by navneetccna** [doctrine/mongodb-odm#1231]
Every thing else get cloned but EmbedMany not working
/** @ODM\EmbedMany(targetDocument="BaselineBudget\Document\BaselineBudgetItems") */
    private $BaselineBudgetItems = array();

/**
     * @return the $BaselineBudgetItems
     */
    public function getBaselineBudgetItems() {
        return $this->BaselineBudgetItems;
    }

    /**
     * @param string $BaselineBudgetItems
     */
    public function setBaselineBudgetItems($BaselineBudgetItems) {
        $this->BaselineBudgetItems = $BaselineBudgetItems;
    }

**Comment by malarzm** [comment]
As stated multiple times in various issues (#1229 being most recent) each and every embedded document MUST be cloned separately as each of them is tracked by `UnitOfWork`.

**Comment by navneetccna** [comment]
tired this

$clone = clone ($data);

            $clone->setStatus("Published");
            foreach ($data->getBaselineBudgetItems() as $key => $BaselineBudgetItems) {
                echo "<pre>";
                print_r($BaselineBudgetItems);
            }


            $getBaselineBudgetItems = clone ($data->getBaselineBudgetItems());

            $clone->setBaselineBudgetItems($getBaselineBudgetItems);

Warning: spl_object_hash() expects parameter 1 to be object, null given in /vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php on line 316

**Comment by malarzm** [comment]
If you believe this is a bug please provide a failing test case

**Comment by malarzm** [comment]
For the record please see #1252
