### ISSUE TITLE
DBRef persist error when using @referenceMany(repositoryMethod) and cascade remove

### ISSUE THREAD

**Issue by decebaldecebal** [doctrine/mongodb-odm#1232]
Hello,
I have encountered a strange bug when using this with the Doctrine MongoODM Bundle for Symfony.

I have the following User document: (methods skipped)

```php

/**
 * @MongoDB\Document(collection="users")
 */
class User
{
    /**
     * @MongoDB\Id
     */
    protected $id;

    /**
     * @MongoDB\String
     * @MongoDB\Index(unique=true, order="asc")
     */
    protected $username;

    /**
     * @MongoDB\String
     */
    protected $password;

    /**
     * @MongoDB\ReferenceMany(targetDocument="Article", mappedBy="user", cascade={"remove"})
     */
    protected $articles;

    /**
     * @MongoDB\ReferenceMany(targetDocument="Comment", mappedBy="user", cascade={"remove"})
     */
    protected $comments;

    /**
     * @MongoDB\ReferenceMany 
     */
    private $data;

    /**
     * @MongoDB\ReferenceMany(
     *      targetDocument="Article",
     *      mappedBy="user",
     *      sort={"title"="desc"},
     *      limit=2
     * ) 
     */
    protected $orderedArticles;

    /**
     * @MongoDB\ReferenceMany(
     *      targetDocument="Comment",
     *      mappedBy="user",
     *      repositoryMethod="getLongComments",
     *      sort={"content"="asc"}
     * ) 
     */
    protected $longComments;
}
```

The problem I was having is that when I deleted a user, because I have cascade remove on $comments variable and also have the referenceMany(repositoryMethod) annotation on $longComments variable, since both reference the same Comment document and are mapped by the same variable, the method `getLongComments` from the Comment repository gets called after I remove a user so I get an 
`Cannot create a DBRef for class AppBundle\Document\User without an identifier. Have you forgotten to persist/merge the document first?`

This is how my Comment repository looks like and how I fixed the error:

```php
class CommentRepository extends DocumentRepository
{
    public function getLongComments(User $user)
    {
        $qb = $this->createQueryBuilder();
        $expr = new \MongoRegex("/.{20,}/");

        if ($this->getDocumentManager()->getUnitOfWork()->getDocumentState($user) == UnitOfWork::STATE_MANAGED) { //the error is fixed if I check that the current user is persisted, if not that error appears
            $qb->field('user')->references($user);
        }
        $qb->addAnd($qb->expr()->field('content')->equals($expr));

        return $qb->getQuery()->execute();
    }
}
```

I am not sure if this is a bug or it is supposed to happen, but it seems really weird.I have followed the exact documentation of the Doctrine MongoDB ODM when making this so I am not sure this is related to the Symfony Bundle or to the Doctrine MongoDB ODM Bundle itself.

Thank you in advance for your help.

**Comment by alcaeus** [comment]
Just a question to understand this properly: did you call ```getLongComments()``` on the deleted document yourself or was it called automatically by ODM?

**Comment by decebaldecebal** [comment]
It was called automatically when I deleted the user.
