### ISSUE TITLE
PHP7 status

### ISSUE THREAD

**Issue by xleliberty** [doctrine/mongodb-odm#1234]
Hi all, 

We are planning php7 migration of our projects, but for now mongodb-odm is a stopper.
Is there a planned ETA for odm compat with php7 ? 

thanks

Xavier

**Comment by malarzm** [comment]
@jmikola I think you have the best insight? :)

**Comment by jmikola** [comment]
PHP 7 support will not be coming to the [legacy driver](http://pecl.php.net/package/mongo), which ODM and the underlying Doctrine MongoDB library depend on. Our current developments (in the MongoDB PHP team) are towards the [new extension](http://pecl.php.net/package/mongodb), which will support PHP 7 and HHVM alike. We are still making headway towards a stable release, and work to port over the Doctrine projects would only start after that point.

In the meantime, you may have some luck utilizing [mongofill](https://github.com/mongofill/mongofill), which is a pure PHP implementation of the legacy driver's API; however, I've not tested that myself.

**Comment by xleliberty** [comment]
Thank you for your answer.
I'me aware that dev is now turned to new extension. 
Ok  let's wait for a first stable release of mongodb ext :) 

Regards
Xavier

**Comment by lugaidster** [comment]
Are there any news regarding this given that the new driver has just recently gotten a stable release with php 7.0 support?

**Comment by yonisolo** [comment]
With the release of PHP7 and mongodb 3.2, doctrine is not usable for futur project, any news? I don't want to return to mongoDB PHPLIB...

**Comment by malarzm** [comment]
Please stick with older versions for now, no ETA available yet. 

Also I'm locking this issue, #1292 remains open for questions and +1s.

**Comment by alcaeus** [comment]
I would like to add that you can use ODM with MongoDB 3.2 without any problems. There are a few pull requests open to add 3.2 features to doctrine/mongodb and ODM itself and we're waiting on a possible driver update for documentValidation features. Existing features, however, work just fine with 3.2.
