### ISSUE TITLE
Case insensitive sort by string fields

### ISSUE THREAD

**Issue by OndrejPiza** [doctrine/mongodb-odm#1237]
Hi,

is it possible to perform case insensitive sort action on DB collection without using map&reduce function or aggregation functions?

And if not, are there any docs for implement such a functionality?

I'm trying to be able to sort items by field of embedded document and I'm struggling with it. How should I do this ? 

For example:
```
{
  id: "some_id",
.....
 translations: [
    0:
      {
         title: "Some title"
      }
 ],
.......
}
```

Thanks for any advice

**Comment by malarzm** [comment]
Unfortunately MongoDB still doesn't support case insensitive sorting (https://jira.mongodb.org/browse/SERVER-90). I personally am sorting such objects on PHP side (of course it's not perfect but fits my use case). Also you could create another field which will have lowercased title and sort by it.
