### ISSUE TITLE
EmbedOne do not work on documents

### ISSUE THREAD

**Issue by YSimple** [doctrine/mongodb-odm#1245]
Hey Guys,

i have `User` document  that embed one `Location` which also a document in `Locations` collection which fails to update, no exception  / error is thrown but its just not saved on user document,  am i missing something ?    

Mappings : 

    /**
     * Class User
     * @Document(collection="users")
     */
    class User 
    {
        /**
         * @var string
         * @Id(strategy="none")
         */
        private $id;

        /**
         * @var string
         * @Field(type="string")
         */
        private $first_name;

        /**
         * @var string
         * @Field(type="string")
         */
        private $last_name;

        /**
         * @var Location
         * @EmbedOne(targetDocument="Location")
         */
        private $location;
    }

    /**
     * Class Location
     * @Document(collection="locations")
     */
    class Location 
    {
       /**
         * @var string
         * @Id(strategy="none")
         */
        private $id;

        /**
         * @var string
         * @Field(type="string")
         */
        private $city;

        /**
         * @var GeoPoint
         * @EmbedOne(targetDocument="GeoPoint")
         */
        private $geo_point;
    }

    /**
     * Class GeoPoint
     * @EmbeddedDocument()
     */
    class GeoPoint 
    {
      /**
         * @var float
         * @Field(type="float")
         */
        private $latitude;

        /**
         * @var float
         * @Field(type="float")
         */
        private $longitude;
    }

Note : when i use `EmbedMany, ReferenceOne`  the location is saved on user document

**Comment by malarzm** [comment]
You cannot use the same document as both `Document` and `EmbeddedDocument`. If you need it in two places create a `MappedSuperclass` and extend it with two classes: one annotated by `@Document` and one annotated as `@EmbeddedDocument`.

**Comment by YSimple** [comment]
@malarzm can this be done by another way ? im going `DDD` so im trying to keep my models independent i dont wana create a MappedSuperclass just to embed

**Comment by malarzm** [comment]
I'm afraid not, this is what ODM requires you to do (at current state at least). Maybe one day it will be possible :)

**Comment by YSimple** [comment]
@malarzm ok bro, i will go with the `MappedSuperclass` but i have another question lets say that now i will have tow classes `LocationDocument` , `LocationEmbeddedDocument` both extend `MappedSuperclass` how can i define the annotations to make it possible to query for a `LocationDocument` by its `id` and embed it in the `User` like `LocationEmbeddedDocument` ? also its amazing what you guys did so far i hope i can contribute one day

**Comment by malarzm** [comment]
Ah yeah, this is where fun begins. Cleanest IMO would be having named constructors (given `AbstractLocation` is MappedSuperclass and `Location` concrete document):

```
class EmbeddedLocation extends AbstractLocation
{
    public static function fromLocation(Location $loc)
    {
        return new EmbeddedLocation(/*....*/);
    }
}
```

The other way is going dirty and employ reflections ;)

> i hope i can contribute one day 

We'll surely appreciate it!

**Comment by YSimple** [comment]
Thank you @malarzm for help
