### ISSUE TITLE
Sort by indexes on emebeded documents

### ISSUE THREAD

**Issue by OndrejPiza** [doctrine/mongodb-odm#1246]
Hi,

is it possible to create index on some field in the embedded document and than use that index as hint for sorting? Can it be combined with other indexes or conditions?

What I need is to sort by some value of nested document contains nesting values. But the problem is, that nested documents are saved as array and therefore MongoDB needs index to access correct item, or at least from GUI it looks that way.

Let's say I have a Embeded documents called Translations which has Embeded documents SortItems and this SortItems contains values of properties for each translation. 

Now I would like to run a query, that would sort the collection according to the value of sortItem embedded document and correct locale of translation. Since MongoDB does not support associated arrays, is it possible to achieve some way? Or is there a better way how to achieve sorting mechanism?

Thanks

**Comment by alcaeus** [comment]
Yes, that is possible, see the [docs section on indexes](https://doctrine-mongodb-odm.readthedocs.org/en/latest/reference/indexes.html#embedded-indexes). Basically, in your embedded documents you can add any index to your mapping, it will be created in all collections with the necessary property path.
If you want to add an index hint to the query, you should be able to use the name you specified when creating the index.

**Comment by OndrejPiza** [comment]
OK, now I understand. Thank you.
