### ISSUE TITLE
When clearing cache hydrators and proxies, if don't exist, casing fatal error

### ISSUE THREAD

**Issue by OndrejPiza** [doctrine/mongodb-odm#1250]
Hi,

I have a problem. When I'm trying to clear cache in prod env, if there is no hydrator or proxie that used to be, because I switched from auto_generation from true to false, as I thought that for prod env this is better settings not to auto regenerate hydrators and proxies, only if there are some missing. 

But problem was, that after this settings change, it looked like it remembers, that there should be some of them and during cache clear it is trying to require them.

So my question is, if this is correct behavior or that I should look in my settings for a problem? 

I have to switched to this settings:
```
doctrine_mongodb:
    auto_generate_hydrator_classes: true
    auto_generate_proxy_classes: true
```

**Comment by malarzm** [comment]
I'm sorry for long response time, you may want to test [AUTOGENERATE_FILE_NOT_EXISTS](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Configuration.php#L72) setting. Please feel free to reopen in case there's something still wrong
