### ISSUE TITLE
how use range with ISOdate???

### ISSUE THREAD

**Issue by timy-life** [doctrine/mongodb-odm#1254]
my mongodb like this
>{ 
  "_id" : ObjectId("5626257418498e185061a34c"),
  "id" : NumberLong(4),
  "file_id" : NumberLong(11),
  "record_id" : 4,
  "log_time" : ISODate("2015-10-20T19:10:56Z"),
  "player_id" : NumberLong("6179421825328548839"),
  "opt" : 1,
  "item_id" : 7111,
  "item_num" : 1,
  "reason" : 0,
  "now_num" : 0,
  "db_from" : "sjsy_log_9377s9045"
}

php code like this
>$startTime = new \MongoDate(strtotime('2015-10-20 00:00:01'));
		$endTime = new \MongoDate(strtotime('2015-10-20 23:59:59'));
>>$res = $this->get('doctrine_mongodb')->getManager()->getRepository('AnalysisBundle:LogItem')
->field('file_id')->range($startTime, $endTime)->getQuery()->execute();
>>dump($res->toArray());

but return reulst is null.
>NewUserController.php on line 81:
 []

Now this problem has been resolved. My php time zone is PRC.but mongodb is GMT. 
>//设置跟Mongo一样的时区
   date_default_timezone_set(" Etc/GMT");
   $startTime = new \MongoDate(strtotime('2015-10-20 00:00:01'));
   $endTime = new \MongoDate(strtotime('2015-10-20 23:59:59'));
   $res = $this->get('doctrine_mongodb')
                      ->getManager()
                      ->createQueryBuilder('AnalysisBundle:LogItem')
                      ->field('log_time')
                      ->range($startTime, $endTime)
                      ->getQuery()->execute();
   dump($res->count());

result :
> 681378

**Comment by alcaeus** [comment]
> field('file_id')->range(

Have you tried checking the ```log_time``` instead of the ```file_id```?

**Comment by timy-life** [comment]
i'm sorry. now ,php code like this .
>$startTime = new \MongoDate(strtotime('2015-10-20 00:00:01'));
		$endTime = new \MongoDate(strtotime('2015-10-20 23:59:59'));
		$res = $this->get('doctrine_mongodb')
->getManager()
->createQueryBuilder('AnalysisBundle:LogItem')
->field('log_time')
->range($startTime, $endTime)
->getQuery()->execute();
		dump($res->toArray());

resulst is  []

query conditon like this
> #query: array:1 [▼
      "log_time" => array:2 [▼
        "$gte" => MongoDate { ▼
          +sec: 1445270401
          +usec: 0
        }
        "$lt" => MongoDate { ▼
          +sec: 1445356799
          +usec: 0
        }
      ]

Document 
>	/**
	 * @MongoDB\Date
	 */
	protected $log_time;

what's wrong ???

**Comment by zacharyzh** [comment]
Jingle Bells, Jingle Bells, Jingle all the way ...

**Comment by alcaeus** [comment]
Closing for lack of input.
