### ISSUE TITLE
backupExisting can't be set

### ISSUE THREAD

**Issue by kevinmlong** [doctrine/mongodb-odm#1260]
Seems there is no way on the command line to set the flag to tell the DocumentGenerator not to backup files (resulting in a `<filename>.php~` file being created). I have tested and will submit a PR, but this can be done by adding an option to `GenerateDocumentsCommand.php` and setting this value on the DocumentGenerator object in the `execute()` call.

**Comment by malarzm** [comment]
Indeed the option seems to be missing, will surely appreciate a PR!

**Comment by kevinmlong** [comment]
@malarzm - just created the PR. When do you think you'll be able to incorporate it into a release?

**Comment by malarzm** [comment]
It can be included in 1.0.3 which should be available in forthcoming days

**Comment by kevinmlong** [comment]
Thanks! Just pushed updates to the PR

**Comment by malarzm** [comment]
#1261 was merged
