### ISSUE TITLE
Does setOnInsert work via Doctrine ODM or the query builder?

### ISSUE THREAD

**Issue by blockjon** [doctrine/mongodb-odm#1262]
Looking for how to use setOnInsert (https://docs.mongodb.org/manual/reference/operator/update/setOnInsert/) with Doctrine. Are there any examples of this?

**Comment by malarzm** [comment]
I haven't used that myself but as usual in such situations I'd try to sneak this into query builder somehow ;) Making this a proper feature would require explicit upsert in DocumentManager I believe?

**Comment by blockjon** [comment]
I think i figured it out. Something like this works:
```        
        // Configure a $setOnInsert
        $newObj = $qb->getNewObj();
        $newObj['$setOnInsert'] = array(
            '_id' => 123123,
        );
        $qb->setNewObj($newObj);
```

**Comment by alcaeus** [comment]
@blockjon you're right, there is no support for ```$setOnInsert``` at all yet. I've created doctrine/mongodb#235 to add this feature to the underlying query builder so that people can use it in queries. I'm not yet sure how we could handle this for documents managed by ODM.

**Comment by sakalys** [comment]
Any news on this?

**Comment by malarzm** [comment]
@sakalys it's available through the [query builder](https://github.com/doctrine/mongodb-odm/blob/5d9b452c067a7d9eeb4d2555cfa168df76e6a99e/lib/Doctrine/ODM/MongoDB/Query/Builder.php#L1431)

**Comment by sakalys** [comment]
> I'm not yet sure how we could handle this for documents managed by ODM.
what about that part?

**Comment by malarzm** [comment]
Nothing new, there's https://github.com/doctrine/mongodb-odm/issues/1425 to track that
