### ISSUE TITLE
getSingleResult() and remove() deletes multiple documents

### ISSUE THREAD

**Issue by bensquire** [doctrine/mongodb-odm#1267]
It could be me, but I have the following query:

````
$invite = $this->documentManager
->createQueryBuilder('\SomeLibrary\Document\PublisherMemberInvite')
->field('publisher.id')->equals('123456789012345678901234')
->getQuery()->getSingleResult();
````

which I'm using and then passing into

    $this->documentManager->remove($invite);

What I'm seeing is multiple PublisherMemberInvites being deleted, even though I've only requested a single result. My document doesn't have any cascades and if I adjust the query to:

````
$invite = $this->documentManager
->createQueryBuilder('\SomeLibrary\Document\PublisherMemberInvite')
->field('publisher.id')->equals('123456789012345678901234')
->field('email')->equals('foo@bar.com')
->getQuery()->getSingleResult();
````
It only removes single document (although I would expect this to match only 1, the previous query would in theory match multiple ).

Is this a bug, is it by design? I had a quick look at the DocumentManager.php and in turn UnitOfWork.php and I don't pretend to understand it all, but it doesn't look like it should do what I'm seeing.

Maybe i've done something stupid...

**Comment by malarzm** [comment]
It does look strange indeed, any chance you could transform this to a failing test case? It would help fixing a lot!

**Comment by alcaeus** [comment]
I've tried to reproduce this with the following test case but couldn't:

```
<?php

namespace Doctrine\ODM\MongoDB\Tests\Functional\Ticket;

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

class GH1267Test extends \Doctrine\ODM\MongoDB\Tests\BaseTest
{
    public function testRemoveWithGetSingleResult()
    {
        $document1 = new GH1267Document();
        $document1->name = 'foo';

        $document2 = new GH1267Document();
        $document2->name = 'bar';

        $this->dm->persist($document1);
        $this->dm->persist($document2);
        $this->dm->flush();
        $this->dm->clear();

        $this->assertCount(2, $this->dm->getRepository(GH1267Document::class)->findAll());

        $qb = $this->dm->createQueryBuilder(GH1267Document::class);
        $result = $qb->getQuery()->getSingleResult();

        $this->dm->remove($result);
        $this->dm->flush();

        $this->assertCount(1, $this->dm->getRepository(GH1267Document::class)->findAll());
    }
}

/** @ODM\Document */
class GH1267Document
{
    /** @ODM\Id */
    public $id;

    /** @ODM\Field(type="string") */
    public $name = false;
}
```

@bensquire if the issue persists, please re-open this issue with a failing test case so we can look at fixing this.
