### ISSUE TITLE
Mixing form types for embedmany field type

### ISSUE THREAD

**Issue by OndrejPiza** [doctrine/mongodb-odm#1270]
Hi,

have you ever need to add different types of forms based on provided document type? I'm trying to achieve something like collection behavior with all allow add , allow delete functionality, but with my own form types, so I can't settle with generated ones.

Thank for any advice

**Comment by malarzm** [comment]
> but with my own form types, so I can't settle with generated ones.

what do you mean by this?

**Comment by OndrejPiza** [comment]
I'm using KNP Labs ORM Behavior modified for ODM with a2Lix translations bundle. I also have some special types, based on document, which I use for better selecting images. So I need to be able to specifiy form type and pass it to the form builder. Which I can't if collection is made dynamically, like you can add or delete new ones, but symfony won't recognize my own types and use default ones,. So I need to be able to loop through the embedded documents and add dynamically these new forms from them. Which is OK, each document know which form it needs.

But I don't know if this is correct aproach. It just sound natural to being able to mix document types in single collection of embedded documents, so I thought there is some way how to mix form types as well.

**Comment by malarzm** [comment]
>  I thought there is some way how to mix form types as well.

That is good question for Symfony :baby: Anyway we have done something like this (unfortunately can't share the exact solution), we ended up extending `collection` type and having subscribers on PRE_SUBMIT and PRE_SET_DATE that are aggressively changing built form based on underlying data (basing on discriminators)
