### ISSUE TITLE
Error zend_mm_heap corrupted in CLI when updating schema

### ISSUE THREAD

**Issue by OndrejPiza** [doctrine/mongodb-odm#1272]
Hi,

have you ever encountered error "zend_mm_heap corrupted" ? It happens only when I'm trying to update schema to create new Indexes. 

I've tried some possible fixes, but non of them worked. Everything works OK, but only this command failing.

I turned off the output_buffering. So far nothing helps.

**Comment by malarzm** [comment]
@OndrejPiza check if you're using latest driver as this reminds me of https://github.com/doctrine/mongodb-odm/pull/1045 . If that is not fixing your issue please paste whole stack trace and ping @jmikola as he's the master of drivers :)

**Comment by malarzm** [comment]
ping @OndrejPiza

**Comment by malarzm** [comment]
Closing because of lack of response

**Comment by OndrejPiza** [comment]
Sorry for taking my time to answer. Updating Mongo driver really worked for me.

**Comment by malarzm** [comment]
Glad to hear that!
