### ISSUE TITLE
Trait statement is missing on generation

### ISSUE THREAD

**Issue by kevinmlong** [doctrine/mongodb-odm#1273]
When document classes are generated - trait statements are missing.

**Comment by malarzm** [comment]
I recall I was once working on making the generator inline with ORM's trait-wise: https://github.com/doctrine/mongodb-odm/pull/988 if that helps :)

**Comment by malarzm** [comment]
Triaging as a bug but not scheduling on purpose

**Comment by malarzm** [comment]
Code generators were removed in #1708
