### ISSUE TITLE
load referenced document

### ISSUE THREAD

**Issue by wajaja** [doctrine/mongodb-odm#1274]
i have a  two-way relationship between two documents;  post and user.
in user I can do this to get the posts from a user list by $ user-> getPosts () However, it is difficult for me to obtain a username for each post.
i do this:

$user = $this->createQueryBuilder()
                ->find()
                ->field('author')
                ->equals(new \MongoId('author.$id'));
 $username = $user->getUsername();

but nothing happens
 what can I do to get a username  for each post?

**Comment by solocommand** [comment]
@wajaja It would depend [how you have it modelled](https://gist.github.com/solocommand/20340d02ad7d5df2f235). If your `Post` document owns a reference to a `User` document, you would be able to query to retrieve the username.

In your example though, you seem to already have the author's `id` field. If you do, why aren't you just querying the `User` collection for that author?

Alternatively, you could just use inverse relationships to retrieve the username from the post. `$post->getUser()->getUsername()` will do what you want if you have the relationships modelled correctly.

**Comment by malarzm** [comment]
Also I'd add that `new \MongoId('author.$id')` is not valid MongoId.

**Comment by wajaja** [comment]
@malarzm what is the correct way to use to instantiate the MongoId object?

**Comment by malarzm** [comment]
Just pass the correct id if you wish the object to represent id of your choice. Also the query will depend on your mapping, as @solocommand mentioned, if you used simple references then `MongoId` will be your friend, if you're storing full reference then database field holds `DBRef`. The easiest will be using inverse side (again, like @solocommand shown in the example :) )

**Comment by solocommand** [comment]
Assuming a valid MongoId, `new \MongoId('56424537f52c6beb018b4567')` or `new \MongoId("$id")` if you're passing it in. I assumed your find was pseudocode -- if not then your `$user` object is going to be a mongo `Cursor`. You would want to append `->getSingleResult()` or call `findOne` instead of `find`.

**Comment by wajaja** [comment]
I assume that by submitting a post with a reference of the user's id is stored in user. $ id, how can I recover my username template. knowing that I'm doing this {{ post.author }} in my twig template.  it does not work

**Comment by solocommand** [comment]
If your relationships are set up correctly, you would want `{{ post.author.username }}`. `post.author` is just going to be the `User` document itself, which should throw an error if you don't have a `__toString()` method defined on that class.

You should be sure that the relationships are set up correctly for your documents, and that you are creating them with the referenced models. Is the data stored correctly in MongoDB itself?

```
// Your `User` document should already be available as `$user`.
$post = new Post();
$post->setAuthor($user);

$documentManager->persist($post);
$documentManager->flush();
```

The above code would create a `Post` document, assign the `User` document to the `author` field, manage the document and ultimately save it to MongoDB. Is this similar to how you are creating new `Post`s?

**Comment by wajaja** [comment]
thank you a lot solocommand ; Now I found out where errors;
1. in my template
2. in how to submit post

how can I define the _toString () method?

**Comment by solocommand** [comment]
PHP [magic methods](http://php.net/manual/en/language.oop5.magic.php#object.tostring) documentation for `__toString()`. Generally speaking, you aren't going to want to implement it. It's use-case is for implicit type conversion -- in your case you should access the property of the class you actually want to display: `{{ post.user.username }}`

**Comment by wajaja** [comment]
solocommand  I got this error : Impossible to access an attribute ("username") on a null variable in OPPostBundle:Home:news.html.twig at line 11

**Comment by wajaja** [comment]
@solocommand I followed all your instructions; but I'm doing this:  {{ post.user }} in my template I get null;  seems that the reference does not work

**Comment by solocommand** [comment]
@wajaja Glad we could help :smile:

**Comment by malarzm** [comment]
:+1: :)
