### ISSUE TITLE
Persist and Flush Only the embedded Document

### ISSUE THREAD

**Issue by wajaja** [doctrine/mongodb-odm#1285]
Hello; 
Is it possible to  persist and Flush the embedded ducument without the parent document?
if yes; how can I do this?

**Comment by malarzm** [comment]
No, embedded documents can not be persisted on its own. However you can utilize query builder and update them manually (but that will happen without DocumentManager knowing about it)

**Comment by wajaja** [comment]
thanks you @malarzm for your answers

**Comment by malarzm** [comment]
Cheers
