### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by wajaja** [doctrine/mongodb-odm#1287]
Hi; 
I've an error; 

Catchable Fatal Error: Argument 1 passed to OP\MediaBundle\Document\Image::setFile() must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile...  After trying to upload file in my image document.

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * 
 * 
 * @ODM\Document(
 *      db="media",
 *      collection="images",
 *     repositoryClass="Md\MediaBundle\Repository\ImageRepository"
 * )
 */
class Image
{
    /**
     * @var MongoId $id
     *
     * @ODM\Id(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string $path
     *
     * @ODM\Field(name="path", type="string")
     */
    protected $path;

    /**
     * @var integer $size
     *
     * @ODM\Field(name="size", type="integer")
     */
    protected $size;
    
    private $file;
    ...
    
    /**
     * sets file
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file)
    {
        $this->file = $file;
    }
    
    public function getFile()
    {
        return $this->file;
    }

what is missing in this code?

**Comment by malarzm** [comment]
You haven't pasted setter but I'd guess that you have typehint for `UploadedFile` and you're passing something else.

Anyway this is not ODM issue at all, please use StackOverflow for such problems.
