### ISSUE TITLE
New MongoDB driver compatibility

### ISSUE THREAD

**Issue by castarco** [doctrine/mongodb-odm#1292]
Hello,

there is a new PHP driver for MongoDB ( http://docs.php.net/manual/en/set.mongodb.php ) , compatible with HHVM and with PHP7. As far as I know, the current implementation of the Doctrine MongoDB-ODM library relies on the "old/legacy" mongo driver ( http://docs.php.net/manual/en/book.mongo.php ).

Are there any plan to "migrate" this library to the new driver?

**Comment by hydrapolic** [comment]
+1

**Comment by alcaeus** [comment]
Please see [this comment](https://github.com/doctrine/mongodb-odm/issues/1234#issuecomment-143586903) for more information about support for the new MongoDB driver (which in turn will bring PHP 7 compatibility).

**Comment by christoph-hautzinger** [comment]
+1

**Comment by castarco** [comment]
That's being discussed here: https://github.com/doctrine/mongodb/issues/239

**Comment by luispabon** [comment]
:+1:

**Comment by acrozes** [comment]
+1

**Comment by xtuc** [comment]
+1

**Comment by yonisolo** [comment]
So I can just say +1, hope you will handle the new mongodb driver soon!

**Comment by mariotux** [comment]
+1

**Comment by alcaeus** [comment]
Keep in mind that while the driver is stable, the recommended [userland library](https://github.com/mongodb/mongo-php-library) is not. It currently is in beta status and some features like GridFS are still being implemented, though @jmikola can say more about that.

Keep in mind that this is not simply replacing all occurences of `Mongo*` with a corresponding `MongoDB\*` class, we're talking significant API changes between the versions that will require large changes to many ODM features.

In the meantime, if you absolutely want to use PHP 7 and want to risk a few things you can check out [mongofill](https://github.com/mongofill/mongofill) or [mongo-php-adapter](https://github.com/alcaeus/mongo-php-adapter) to provide the `ext-mongo` API on top of the c driver and `ext-mongodb`, respectively. Note however that mongofill seems to provide the 1.3.0 API (according to its version constant), lacking many features of newer MongoDB versions while mongo-php-adapter is still a work in progress, not feature-complete and not recommended for production use.

Full disclosure: mono-php-adapter is a library I'm writing and not associated with the Doctrine project.

**Comment by yonisolo** [comment]
I'm not challenging you about the work which is done, I know this is quite new and complex, just want to be reassured about the futur capacity of odm to manage this new driver on PHP7 as lots of people and project are trusting doctrine.

**Comment by sebfek** [comment]
+1

**Comment by peterrehm** [comment]
@alcaeus Will it be much work to adapt the new userland library? Is your approach with the adapter the simplest solution?

**Comment by alcaeus** [comment]
It is going to be a considerate amount of work. We're going to push out 1.1 soon*ish* and then we'll probably start tackling stuff for the 2.0 milestone. Migration to `ext-mongodb` is of course on the very top of the list.

The adapter is a non-official way of running ODM on HHVM or PHP 7, just like mongofill has been for quite some time. If you are running PHP < 7, there is (at the time of this writing) no downside to using `ext-mongo` directly. More directly, I'd encourage people **NOT** to use the adapter if you can run `ext-mongo` on the system, simply because there is [a list of known issues](https://github.com/alcaeus/mongo-php-adapter/blob/master/README.md#known-issues) of which quite a few will be present in the upcoming 1.0 release.

**Comment by nsoftproject** [comment]
+1

**Comment by peterrehm** [comment]
@alcaeus Thank you for the detailed answer, looks like for simple odm applications the adapter is looking good if there is the need to update to PHP 7. Do you have a rough timeline on 1.0 of the adapter?

**Comment by alcaeus** [comment]
We're wrapping up exception handling and will publish a first alpha then. 1.0 won't hit before https://github.com/mongodb/mongo-php-library hits 1.0.0 as I don't want to rely on beta packages for this.

**Comment by peterrehm** [comment]
Sounds awesome, thanks for your hard work! I will give it a try then.

**Comment by kwuerl** [comment]
+1

**Comment by mike22** [comment]
+1

**Comment by jmikola** [comment]
Locking the thread for "+1" defenses. @alcaeus and @malarzm will follow up here as progress is made.

**Comment by malarzm** [comment]
There's an update in yesterday's [1.0.5 release blog post](http://www.doctrine-project.org/2016/02/16/doctrine-mongodb-odm-release-1.0.5.html)

**Comment by malarzm** [comment]
Current `master` branch is using new driver so I'm closing this issue. Please note it's not battle tested yet so while we believe in our test suite, please avoid running bleeding edge ODM in production. On the other hand, if temporary lack of GridFS or sharding is not bothering you, we'd appreciate some test flights and feedback even though we're before an alpha release :)
