### ISSUE TITLE
MongoDB 3.2 compatibility?

### ISSUE THREAD

**Issue by metanav** [doctrine/mongodb-odm#1301]
ODM is still using legacy mongo php driver. Will it work with MongoDB 3.2? Is there any timeline to upgrade to new mongodb php driver?

**Comment by alcaeus** [comment]
Most if not all features are/will be supported by the legacy driver, I'll let @jmikola go into more detail on that one.
As for the new mongodb driver, this [has been said before](https://github.com/doctrine/mongodb-odm/issues/1234#issuecomment-143586903).

Most features aren't limited by the driver but rather the implementation in doctrine/mongodb and ODM.
So far we have:
- New aggregation operators in doctrine/mongodb#240
- Partial index support in #1303

Still missing:
- readConcern for queries (might need driver changes)
- Document validation (will need driver changes for bypassDocumentValidation, see [this ticket at mongodb](https://jira.mongodb.org/browse/PHP-1492))
- Text Search Enhancements (most likely doctrine/mongodb only)
- Bit Test Query operators (most likely doctrine/mongodb only)

I'll be working on these features in the next week with the goal of having them in doctrine/mongodb 1.3 and doctrine/mongodb-odm 1.1. No timeline has been set on either yet. Of course, you can always help things along by creating a pull request to get us started.

**Comment by metanav** [comment]
Thanks @alcaeus for detailed explanation. Just wanted to make sure, if I replace the existing MongoDB 3.0.7 with 3.2 and I am not going to use any new features of 3.2 for now, will it work without breaking anything with legacy driver?

**Comment by alcaeus** [comment]
It's been running smooth on my dev machine, haven't upgraded anything else yet.

**Comment by davidchchang** [comment]
Hi @alcaeus, can we confirm with someone on the Mongo team (perhaps @jmikola as you suggested earlier) that the legacy mongo driver supports and is compatible with MongoDB 3.2? According to the PHP driver page, the latest version of the legacy mongo driver is **_not_** compatible with MongoDB 3.2: https://docs.mongodb.org/ecosystem/drivers/php/#compatibility

Is this a case of outdated documentation, or is the legacy driver actually not fully compatible with 3.2? We just want to be aware of any issues we may run into going forward once we adopt mongodb-odm on our project.

Thanks!

**Comment by alcaeus** [comment]
I can comment on some features as I've been using MongoDB 3.2 with `ext-mongo` 1.6.* and ODM 1.0.* in production for a while now: they work quite well, especially the new aggregation operators.

As for 3.2 features, I can update the list above as follows:

* Aggregation operators have made it to doctrine/mongodb 1.3.0
* Text search enhancements have made it to doctrine/mongodb 1.3.0
* Bit Test query operators have made it to doctrine/mongodb 1.3.0
* Partial index support will be in ODM 1.1.0

You can take advantage of the new operators by updating doctrine/mongodb to the latest version. We still have a couple of open pull requests for ODM 1.1 but you can always give dev-master a spin if you want to try partial index support.

As for document validation, we could add it to ODM 1.1 but it would lack support for the bypassDocumentValidation flag (I believe that will need driver changes). I'm not sure I'd want to add validation without that option.
That leaves readConcern which I believe would also require driver changes. I'll leave it to @jmikola to update the status on those features or correct me if I'm wrong 😉

**Comment by davidchchang** [comment]
Thanks for your prompt reply, @alcaeus! We are using MongoDB 3.2 with the MongoDB PHP library (which builds on the lower-level mongodb extension). We have made good progress developing against ODM 1.0.* this week, and even though we now have both drivers (legacy + new) installed at the same time, everything seems to be working fine.

If I have some time in the next week, I will release a mongodb-odm wrapper package for Laravel.

Thanks for your update!
