### ISSUE TITLE
PHP 5.4 compatibility  of mongodb-odm

### ISSUE THREAD

**Issue by DevMaster112** [doctrine/mongodb-odm#1305]
Hello community,

I using the dev-master of mongodb-odm. With the latest commits the compatibility with php 5.4 was removed. 

```
  * - doctrine/mongodb-odm dev-master requires php ^5.5 -> your PHP version (5.4.33) or "config.platform.php" value does not satisfy that requirement.
  * - doctrine/mongodb-odm dev-master requires php ^5.5 -> your PHP version (5.4.33) or "config.platform.php" value does not satisfy that requirement.
  * - Installation request for doctrine/mongodb-odm dev-master -> satisfiable by doctrine/mongodb-odm[dev-master].
``` 

So i can't do any deploy with capistrano / capifony for my projects. 

Is the support for PHP 5.4 stopped so that i have to upgrade to PHP >5.5 for using mongodb-odm?

**Comment by alcaeus** [comment]
Thou shalt not use dev-master. Please use a stable version - the upcoming 1.1 version (which dev-master is) will drop PHP 5.4 support.

```
require: {
    "doctrine/mongodb-odm": "^1.0",
    [...]
}
```
