### ISSUE TITLE
Why isn't the changeset recomputed after cascadePreUpdate() is called?

### ISSUE THREAD

**Issue by MidnightDesign** [doctrine/mongodb-odm#1310]
I've got a `preUpdate` listener that modifies some data on a document before it is persisted, but that does't work since the changeset reflects the document's state before the listener [was called](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L1226).

Is there a specific reason why the changeset isn't recomputed after that? It seem strance since [there is a call to `recomputeSingleDocumentChangeSet()` after `invokeLifecycleCallbacks()`](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L1218) but not after this.

My code works when I put another call to `recomputeSingleDocumentChangeSet()` after `cascadePreUpdate()`.

**Comment by malarzm** [comment]
I believe this is happening because

1. lifecycle callbacks were not receiving event as an argument and couldn't call `recomputeSingleDocumentChangeSet()` on their own
2. recomputing can be expensive and since listeners often have more complicated logic it might be not necessary to recalculate change set after each call

**Comment by MidnightDesign** [comment]
So is the solution to call recompute from my event listener?

**Comment by MidnightDesign** [comment]
I'm so sorry. I just wanted to propose adding this to the documentation and then I saw that [it's already in there](http://doctrine-orm.readthedocs.org/projects/doctrine-mongodb-odm/en/latest/reference/events.html#preupdate). RTFM, I guess. : (

Thanks for your help anyway.

**Comment by malarzm** [comment]
@MidnightDesign no problem! :)
