### ISSUE TITLE
[RFC] Changesets: array vs. object

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1330]
Right now, the changeset for a document is an array containing tuples for each field that was changed: `[ 'field' => ['oldValue', 'newValue'] ]`

Of course, this works well but as evidenced by #1329 it can be difficult to accomodate different objects, in this case collections. We could solve this by introducing changeset classes:
```
interface DocumentChangeset extends ArrayAccess
{
    protected $document; // The document this changeset is for
    protected $metadata; // ClassMetadata object for the document
    protected $fieldChangesets;  // Array of FieldChangeset objects

    public function getDocument();
    public function getMetadata();
    public function getChangedFields();
    public function getFieldChangesets();
    public function isFieldChanged($fieldName);
    public function getFieldChangeset($fieldName);
}

interface FieldChangeset
{
    protected $document;
    protected $metadata;
    protected $mapping;
    protected $oldValue;
    protected $newValue;

    public function getOldValue();
    public function getNewValue();
}
```

By implementing `ArrayAccess` in `DocumentChangeset` we could provide a BC layer to the old tuple format. There is another advantage to this change. Currently embedded documents are listed in the changeset if they have changed, but the old and new values are (in most instances) the same object, so one has to check the DocumentManager for the changeset of the embedded document. With object changesets we could provide a special changeset that provides the embedded document changeset:

```
interface EmbeddedDocumentChangeset extends FieldChangeset
{
    protected $changeset; // DocumentChangeset object for the embedded document in question

    public function getChangeset();
}
```

Last but not least, we could solve the issue mentioned in #1329 by having a `CollectionChangeset` class that provides the known old and new values (which in most cases is the same collection object). This class could provide various helpers to return all changesets for documents in this collection and methods to get all elements that were added or removed from the collection.

```
interface CollectionChangeset extends FieldChangeset
{
    protected $changesets; // DocumentChangeset objects for all elements in this collection

    public function getChangesets();
    public function getAddedElements();
    public function getRemovedElements();
}
```

I'm interested in opinions or ideas - the goal is to make changesets more accessible to developers and this structured way of providing them should help.

**Comment by malarzm** [comment]
Huge :+1: from me as I also wanted to make changesets as objects for some time and seeing that possible in a BC way is simply amazing!

**Comment by jwage** [comment]
This is how I built it in the skeleton-mapper https://github.com/doctrine/skeleton-mapper/tree/master/lib/Doctrine/SkeletonMapper/UnitOfWork

**Comment by gruberro** [comment]
I like the idea! This would help a lot when working with changesets - for example I see a lot of code cleanup and increased readability in event subscribers :smile:!

**Comment by alcaeus** [comment]
> seeing that possible in a BC way is simply amazing!

It may not be completely BC. For example, an instance of a class that implements ArrayAccess would still not pass the `is_array()` check, so anybody using that to see if it's a valid changeset would suddenly find their code no longer working :disappointed:

**Comment by alcaeus** [comment]
Closing RFC ticket since PR for 2.0 is already open.
