### ISSUE TITLE
Console commands are not accessible through IDE

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1334]
Tracking a report by @webdevilopers on [Twitter](https://twitter.com/webdevilopers/status/684828904134176769):
> Using Doctrine2 console commands for ORM works fine in PhpStorm. Any way to get it working with ODM?

**Comment by webdevilopers** [comment]
You didn't give me enough time for research! ;)

Here is the script loading the  HelperSet`
https://github.com/doctrine/mongodb-odm/blob/master/tools/sandbox/mongodb.php
equivalent to
https://github.com/doctrine/doctrine2/blob/master/bin/doctrine.php#L54-L67

Not sure if the commands were (ever) available yet by the PHPStorm Symfony plugin.

**Comment by alcaeus** [comment]
Take all the time you need, just wanted to have this tracked so I don't forget about it. ;)

**Comment by webdevilopers** [comment]
Typing `php app/console doctrine` suggests the available commands e.g. `doctrine:mongodb:generate:repositories`. So I guess everything is fine with the `mongodb-odm` AND the `DoctrineMongoDBBundle`.

I think it is the @PHPstorm plugin that does yet not recognize it.

**Comment by webdevilopers** [comment]
This issue can be closed. Restarting PHPStorm was not enough. But reloading the commands under `Settings` will indeed import all the commands without adding any custom script.

**Comment by malarzm** [comment]
Thanks for update @webdevilopers I admit that I forgot to check this out because of other stuff going on - sorry for that :(
