### ISSUE TITLE
Annotations that are indented by tab are not processed.

### ISSUE THREAD

**Issue by josefsabl** [doctrine/mongodb-odm#1337]
Annotations that are indented by tab are not processed.

```
/**
 *     @ODM\Boolean
 * previous line is indented by tab
 */
public $thisWillNotBePersisted;
```

**Comment by malarzm** [comment]
@josefsabl thank you for the report! Would you mind opening the issue in https://github.com/doctrine/annotations since the bug will in that component?

**Comment by josefsabl** [comment]
sure! thanks for directing me.
