### ISSUE TITLE
referenceMany query not working

### ISSUE THREAD

**Issue by faizalpribadi** [doctrine/mongodb-odm#1338]
Hello doctrine developers, i have small litle project depend on this libraries, but i have a problem with my query , and this is not working to populate child document ( reference ) from parent document, my issue, i want to update & delete from parent document to execution child document reference

![mongo-odm](https://cloud.githubusercontent.com/assets/1262414/12352674/aaf6a466-bbba-11e5-83f5-c61e6e6ad082.png)

```php
$user = $dm->getRepository('task')
    ->createQueryBuilder()
    ->field('posts.$id')->equals('56960e2229770fd45a8b456f')
    ->getQuery()
    ->execute();

print_r($user); // is null
```

i hope someone help me for this, i'm new with this libraries, and then documentation of doctrine odm its not explain detailing information in query binder, so far, thanks for great working doctrine developer :+1:

**Comment by malarzm** [comment]
@faizalpribadi 

1. For support please use StackOverflow or IRC #doctrine channel
2. Documentation does include quite few informations on [QueryBuilder](http://doctrine-orm.readthedocs.org/projects/doctrine-mongodb-odm/en/latest/reference/query-builder-api.html) and the method you're looking for is `references`
