### ISSUE TITLE
Cascade option not work

### ISSUE THREAD

**Issue by wajaja** [doctrine/mongodb-odm#1340]
hi, I have a problem with the cascade option in my documents;
I have two documents; picture and comment, I'd like to reference a picture to a comment; when the comment is created using the prepersist  event; but this does not work properly.
the comment is created and the picture is also created but there is no reference in the two documents.

here is the code:
In the Comment.php

    class Comment
    {
        /**
         * @MongoDB\Id
         */
        protected $id;
     /**
         * @MongoDB\ReferenceOne(targetDocument="OP\MediaBundle\Document\Picture", mappedBy="commentId", cascade={"persist", "remove"})
         */
        protected $picture;
      ...

In the Picture.php

    class Picture
    {
    /**
     * @var MongoId $id
     *
     * @ODM\Id(strategy="AUTO")
     */
    protected $id;
    /** 
     *
     * @ODM\ReferenceOne(targetDocument="OP\PostBundle\Document\Comment", inversedBy="pictures")
     */
    protected $commentId;

in the controller 

       class CommentController extends Controller
       {
       ...
          public function createAction($id, Request $request)
         {
             //Get the Current User
             $user = $this->getUser();  
             $comment = new Comment();
             $commentForm     = $this->createForm(CommentType::class, $comment);

            $commentForm->handleRequest($request);       
        
            if ($commentForm->isValid()) {
            
            $dm->persist($comment);
            
            $dm->flush();

             return new JsonResponse(array());
        }

**Comment by malarzm** [comment]
@wajaja in `Comment` the `picture` is mapped as inverse side of reference which is not checked for changes so there is nothing to be cascaded, you need to either change mapping or persist your Picture explicitly.

**Comment by wajaja** [comment]
What is the best way can i do for this issue

**Comment by malarzm** [comment]
Depends on why you wanted the picture to be on inverse side of the reference

**Comment by wajaja** [comment]
thanks you!

**Comment by wajaja** [comment]
HI @malarzm , 
I apologize for this issue already closed;
I do what you'd advise me to do on this issue; it works. now the problem is how to display the array of referenced pictures in twig?; 

Here is a comment document stored in my database
{ "_id" : ObjectId("56a7c48faa95aa8c0a00002c"), "content" : "test", "createdAt"
 : ISODate("2016-01-26T19:10:05Z"), "visible" : true, "author" : DBRef("users",
ObjectId("56a76a44aa95aa780a00002a"), "opinion"), "pictures" : [ DBRef("pictures
", ObjectId("56a7c48faa95aa8c0a00002d"), "opinion"), DBRef("pictures", ObjectId(
"56a7c490aa95aa8c0a00002e"), "opinion") ], "postId" : DBRef("posts", ObjectId("5
6a76cf8aa95aad40d00002a"), "opinion"), "nbLikers" : 0 }

**Comment by malarzm** [comment]
Just treat them as they'd be that objects (pictures) - when you fetch Document via Doctrine it converts `DBRef` to `Proxy` objects (specialized proxies that are extending your domain model, done for the sake of lazy loading)

**Comment by wajaja** [comment]
in this case how do I proceed to recover the array of image; I do not have advanced knowledge with doctrine

**Comment by malarzm** [comment]
I'm not sure what array of image are you referring to... given (part of) document:

```
class Something
{
    /** @ReferenceMany(targetDocument="Image") */
    private $images;
}
```

you can safely assume that `$document->getImages()` will return you a `Collection` of `Image`

**Comment by wajaja** [comment]
it's what I do but it returned nothing; in my template I have 
     comment.pictures | length 
which return 0 
throughout the documents and yet I have referenced pictures  in those documents

**Comment by malarzm** [comment]
No idea what's going wrong then, in normal cases this just works :) the best would be reproducing issue in a failing test case if you believe this is ODM's fault
