### ISSUE TITLE
Dynamic database based on document property

### ISSUE THREAD

**Issue by PalliDotCom** [doctrine/mongodb-odm#1345]
Is it possible to choose the database based on a property of the document?

Folllowing structure:

database:
  collection
database:
  collection

Document
  database: database1 / database2

I´ve looked into the code but i seems it isn´t possible right now because all of the necessary objects will instantiated based on class name.

Any ideas?

**Comment by malarzm** [comment]
Yes, right now document can belong to one collection only and that's defined on `ClassMetadata` level. There's similar issue #1243 - could you please post your use case there to consolidate discussion? IMO making collection dependant on property could be an option if it's immutable (or properly considered) is ok-ish save-wise however querying API will still be cluttered. Anyway that's my personal point of view, let's see what others will say :)

**Comment by malarzm** [comment]
Oh actually, by `table` you mean `database`?

**Comment by PalliDotCom** [comment]
We have a legacy mongodb structure and we want to use doctrine mongodb to connect with the old mongodb cluster. There was a database lock in mongodb 2.0 on insertion of an object and we separated the collection into several databases to keep the databases and the effect of the locking small. I know it was just a dirty workaround ;)

A refactoring of the mongodb structure is not an option right now. 

I think it is not trivial to implement this in the document manager and i will use the php mongodb client instead of doctrine for this part.
