### ISSUE TITLE
Undefined property $distance

### ISSUE THREAD

**Issue by zajca** [doctrine/mongodb-odm#1346]
Hi, I run to this error and I'm bit confused.

```
Notice: Undefined property: MongoDBODMProxies\__CG__\MyBundle\Document\Place::$distance
```

My use case is this:

I have place document which have coordinates and 2d index (following documentation)

```
/**
 * @ODM\Document
 * @ODM\Index(keys={"coordinates"="2d"})
 */
class Place extends AbstractDocument
{

    /**
     * @ODM\Distance
     */
    public $distance;

    /**
     * @Type("Coordinates")
     * @Assert\Valid
     * @ODM\EmbedOne(targetDocument="Coordinates")
     */
    protected $coordinates;
...
```

and user document which can have multiple favourites places:

```
/**
 * @ODM\Document 
 */
class User extends AbstractUser
{
    /**
     * @var ArrayCollection<Place> $favourites
     * @ODM\ReferenceMany(targetDocument="Place")
     */
    protected $favourites;

    public function addFavourite($place)
    {
        $this->favourites->add($place);

        return $this;
    }

    public function hasFavourite($place)
    {
        return $this->favourites->contains($place);
    }
...
}
```

weird thing happens when I try to add more favourites (this newer happen when adding first)

```
       if ($user->hasFavourite($place)) {
              return ...;
        }
        $user->addFavourite($place);
        $dm->persist($user);
        $dm->flush();
...
```

In ```MongoDBODMProxies\__CG__\MyBundle\Document\Place``` class I notice in constructor:
```
unset($this->distance)
```
which is cause of error. If I set property to protected error disappear.

I'm not sure if this is a bug or I don't understand what doctrine is doing.

//I'm using symfony3 and mongodb-odm master

**Comment by alcaeus** [comment]
As you've properly noticed, you need to make the property `protected` or `private` for this to work, as is noted [in our documentation](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/architecture.html).

**Comment by malarzm** [comment]
@zajca as @alcaeus noted it is way better to use `protected` or `private` visibility and it's your quickest way to fix the problem. I'd discourage using public persistent properties but this should work in fact and warrants an investigation.

As for Proxies doing `unset($this->public)`: it needs to be done as Proxies also ships custom `__get` method which needs to be called for the field to be lazy loaded: this is [part of ProxyGenerator doing so](https://github.com/doctrine/common/blob/773c56e51fc26ae07a47146fae31b320dd6cada3/lib/Doctrine/Common/Proxy/ProxyGenerator.php#L412)

**Comment by malarzm** [comment]
So @zajca if you could get as started with a failing test case it'd be neat :)

**Comment by zajca** [comment]
@malarzm I try to take a look at it at evening. 
for complete report here is full generated Proxy http://pastebin.com/hZCMhrLb

**Comment by zajca** [comment]
Well I'm bit disappointed, I try to create same nonsense situation and test didn't fail :(
https://github.com/zajca/mongodb-odm/commit/ed5a59a2577cf4abde4e1bf76dfd883724790561

**Comment by malarzm** [comment]
@zajca you need to call `$this->dm->clear()` somewhere and query again document, only then the referenced objects will be proxies

**Comment by zajca** [comment]
@malarzm thanks, test is now failing :)
https://github.com/doctrine/mongodb-odm/pull/1347

**Comment by malarzm** [comment]
Cool! I'll close this one then to consolidate any discussion on it
