### ISSUE TITLE
Serialization of 'closure' is not allowed

### ISSUE THREAD

**Issue by ivan1986** [doctrine/mongodb-odm#1356]
this commit https://github.com/doctrine/mongodb-odm/commit/56aed17a3bb749e25a7aaa06b24f2e7bea660316 (find by git bisect)
produce error serialize LifecycleEventArgs
LifecycleEventArgs object go to \Doctrine\ODM\MongoDB\UnitOfWork::getIdForIdentityMap and try serialize

**Comment by ivan1986** [comment]
ping @malarzm

**Comment by malarzm** [comment]
@ivan1986 did you close this by accident or it's not an issue after all?

**Comment by ivan1986** [comment]
ups, sorry

**Comment by malarzm** [comment]
No worries :) How did you run into this? Any chance for a failing test case?

**Comment by ivan1986** [comment]
hmm, i find this bug after composer update, but maybe it's project issue

**Comment by malarzm** [comment]
Ok, triaging with "needs test" until we have more info

**Comment by ivan1986** [comment]
in my case it was
```
    /**
     * @ODM\PrePersist()
     */
    public function setUuid($uuid = null)
```

it is not a doctrine bug, sorry

**Comment by malarzm** [comment]
Glad you figured that out!
