### ISSUE TITLE
PHP 7.0 Not Supported - mongodb vs ext-mongo version requirement

### ISSUE THREAD

**Issue by TomHAnderson** [doctrine/mongodb-odm#1364]
https://github.com/doctrine/mongodb-odm/blob/master/composer.json#L16

The composer.json file requires ext-mongo and that's for < PHP 7.0.  The composer.json must be modified to check for mongodb in a BC Break release.

**Comment by alcaeus** [comment]
Please have a look at #1292 which covers this topic at length. The upcoming releases of doctrine/mongodb and doctrine/mongodb-odm will allow people to run on PHP 7 using a polyfill library such as [mongo-php-adapter](https://github.com/alcaeus/mongo-php-adapter) or [mongofill](https://github.com/mongofill/mongofill). Full support for the new driver is planned for the 2.0 release.
