### ISSUE TITLE
Make Hydrators more usable outside of UoW scope

### ISSUE THREAD

**Issue by malarzm** [doctrine/mongodb-odm#1377]
I was lately playing with hydrating data into documents and, unfortunately, hydrator assumes the data that goes through should be registered in `UnitOfWork` (this is perfectly valid assumption when hydrating data from database, but not desirable when hydrating manually). Because of call to [`UnitOfWork::registerManaged`](https://github.com/doctrine/mongodb-odm/blob/8f1c34f0ec338dc95393ea44e8bdceb56df0b413/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L2800) nested embedded documents are marked as managed and their snapshot is saved which later makes up wrong change sets when preparing update query.

Since [`hydrate`](https://github.com/doctrine/mongodb-odm/blob/8f1c34f0ec338dc95393ea44e8bdceb56df0b413/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorInterface.php#L37) will gladly accept any `$hints` passed to it I'd propose adding one, that would omit any calls registering objects in associated `UnitOfWork` effectively only populating objects with data, as it could be expected. Alternatively we could decouple registering objects and do that in `UoW` instead, but that'd warrant iterating over reflection once again which is not that good performance-wise (but is praiseworthy ;) ).

Thoughts?

**Comment by beberlei** [comment]
There are hints in the ORM for this, "READ_ONLY" i think, where it makes the objects "detached" automatically.

**Comment by alcaeus** [comment]
Using hints would make sense and keep this on par with ORM. It seems though that this isn't enabled in UnitOfWork.

**Comment by jwage** [comment]
:+1: Makes sense to me. I had started to port the read only objects feature from the ORM a few years back but it never made it fully in to the code base. I think you might see some references to read only in the code base.

**Comment by malarzm** [comment]
Reminder for future me: look into tackling https://github.com/doctrine/mongodb-odm/issues/715#issuecomment-130780072 at the same time
