### ISSUE TITLE
Default collection strategy is error-prone due to silent type switching

### ISSUE THREAD

**Issue by Bilge** [doctrine/mongodb-odm#1388]
The default collection strategy, `pushAll`, may write a JSON array or an object depending on whether the PHP array has contiguous keys starting at index 0 or not. This is not made very clear from the documentation; although [there is a note about this behaviour for the set strategy](http://doctrine-orm.readthedocs.org/projects/doctrine-mongodb-odm/en/latest/reference/storage-strategies.html#set) there is no mention of it for the default `pushAll` strategy. Moreover, although there is a `setArray` alternative for `set` there exists no such analogue for `pushAll` (i.e. `pushAllArray`).

The behavior of the default strategy is chronically error-prone because of the way collections are handled when elements are removed. Both [remove](https://github.com/doctrine/collections/blob/866e100a425b8b73d15393fd081c6bf067f05bf9/lib/Doctrine/Common/Collections/ArrayCollection.php#L116) and [removeElement](https://github.com/doctrine/collections/blob/866e100a425b8b73d15393fd081c6bf067f05bf9/lib/Doctrine/Common/Collections/ArrayCollection.php#L132) call `unset` which will create a hole in the collection if the collection length is greater than one and any element other than the last is removed. As soon as the hole is created Mongo silently swaps the array type to an object. This causes update errors to seemingly appear out of nowhere whenever elements have been removed from a collection because of the type mismatch.

The collections library is shared between all Doctrine backends but this issue will never affect ORM because it doesn't rely on PHP array keys to infer types. Since ODM does, it's probably ill-advised that the default strategy will automatically switch between one type to another. Therefore I'd like to propose changing the default collection strategy to always store JSON arrays by default whether that means creating a new `pushAllArray` strategy or just changing it to `setArray` by default.

**Comment by malarzm** [comment]
I want to change default strategy to `atomicSetArray` but we can't do that before 2.0 as it will be a BC break (see https://github.com/doctrine/mongodb-odm/issues/1239).

Also to address your concern:

> The default collection strategy, pushAll, may write a JSON array or an object depending on whether the PHP array has contiguous keys starting at index 0 or not.

This is not true, If you take a look at [CollectionPersister::insertElements](https://github.com/doctrine/mongodb-odm/blob/0573f48b25e16633ad4fd2c1490a0bb65d3c7354/lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php#L194) you'll see that we're calling `array_values` to ensure the array is in fact list. Also when it comes to removing elements [CollectionPersister::removeElements](https://github.com/doctrine/mongodb-odm/blob/0573f48b25e16633ad4fd2c1490a0bb65d3c7354/lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php#L158) is first unsetting array elements (and Mongo is [putting null](https://docs.mongodb.org/manual/reference/operator/update/unset/#behavior) in their places) and later `$pull`s nulls out of the array. All operations are done on arrays and they shall remain as arrays in the database still.

You're right saying that `unset` leaves holes in the array but this is fixed as soon as collection is saved during [taking snapshot of collection](https://github.com/doctrine/mongodb-odm/blob/0573f48b25e16633ad4fd2c1490a0bb65d3c7354/lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php#L231) so the PHP collection is in sync with what is stored in the database. While we're in there, you'll notice [`CollectionHelper::isList`](https://github.com/doctrine/mongodb-odm/blob/0573f48b25e16633ad4fd2c1490a0bb65d3c7354/lib/Doctrine/ODM/MongoDB/Utility/CollectionHelper.php#L61) which yields true for both `pushAll` and `addToSet` effectively making ODM call `array_values` in various places to ensure the collection will be stored as a BSON array.

**Comment by Bilge** [comment]
So if we were seeing issues where ODM was failing to update a collection because its type had suddenly changed to an object instead of an array, are you saying that the cause must lie elsewhere?

**Comment by malarzm** [comment]
It should. Also as usual, practice may differ from theory :baby: I don't think we have any tests checking if underlying BSON value is still array, isolating issue would help a lot with undestanding what's going wrong and when

**Comment by alcaeus** [comment]
Closing in favour of #1940: we will drop the non-atomic collection strategies which cause this problem.
