### ISSUE TITLE
Allow falsey values to be identifier

### ISSUE THREAD

**Issue by Gerassim** [doctrine/mongodb-odm#1394]
If i have document identifier 0 in my collection, when i want to flush i have an error Cannot create a DBRef for class without an identifier.

In https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/DocumentManager.php#L676 doctrine odm uses !$id, but $this->unitOfWork->getDocumentIdentifier returns identifier or null. Should replace !$id to $id === null?

**Comment by malarzm** [comment]
I think this won't be the only place requiring such fix, I'd be open to such change tho (given tests are written). Also as `0` isn't a top choice for an identifier I'm inclined to ask - why `0`? :)

**Comment by Gerassim** [comment]
Compatibility with older versions of our project :)

**Comment by alcaeus** [comment]
PR has been merged, thanks for the report!
