### ISSUE TITLE
Question: How to deal with inconsistent document structures with EmbedMany/EmbedOne 

### ISSUE THREAD

**Issue by araines** [doctrine/mongodb-odm#1396]
I appreciate this is probably a little bit of an odd use-case, but its something I'm struggling with and would love it if someone had an idea which might help.

The issue I have is that I'm trying to integrate ODM on top of a legacy system which has documents stored where the embedded document can be either an object (in the case where there was only one) or an array (in the case where there was many).  For reasons I won't go in to, migrating or altering the legacy system which creates these documents is not an option.

I've got a document set up as so:

```
class Competition
{
    /**
     * @MongoDB\EmbedMany(targetDocument="TeamStanding", name="TeamStandings")
     */
    private $teamStandings = [];

    /**
     * @MongoDB\EmbedOne(targetDocument="TeamStanding", name="TeamStandings")
     */
    private $teamStanding;
```

Because these are both linked to the same json node `TeamStandings`, only one takes effect.  For reference the document structure looks something like:

```
{
  "TeamStandings": {
      // team standing
  }
}
```

or 

```
{
  "TeamStandings": [
    {
      // team standing 1
    },
    {
      // team standing 2
    }
}
```

It seems like I need something like an "EmbedManyOrOne" annotation!  All and any suggestions are appreciated.

**Comment by malarzm** [comment]
If it's possible for you to lazily migrate you could try altering what's coming from database with `preLoad` event/lifecycle callback:

```
/**
 * @MongoDB\Document
 * @MongoDB\HasLifecycleCallbacks
 */
class Competition
{
    /**
     * @MongoDB\EmbedMany(targetDocument="TeamStanding", name="TeamStandings")
     */
    private $teamStandings = [];

    /** @PreLoad */
    public function fixTeamStandings(\Doctrine\ODM\MongoDB\Event\PreLoadEventArgs $eventArgs)
    {
        $data =& $eventArgs->getData();
        if (isset($data['TeamStandings'][0]) {
            return; // looks like a list, do nothing
        }
        $data['TeamStandings'] = [ $data['TeamStandings'] ];
    }
}
```

Please note however that `preLoad`'s signature is different in 1.0.x and `dev-master` (see #1222 for reasoning) so for this I'd advise you to use `dev-master` and switch to 1.1 as soon as we tag it.

**Comment by araines** [comment]
@malarzm - that was exactly what I was looking for.  Thanks so much for the insight and speedy response.
