### ISSUE TITLE
Multiple connections example

### ISSUE THREAD

**Issue by jarnstedt** [doctrine/mongodb-odm#1399]
Does Doctrine ODM support multiple connections? We have a system where each tenant has it's own database. Any examples about how to configure multiple databases/connections?

**Comment by malarzm** [comment]
Yes it does, there's even a chapter [in the docs](http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/config.html#multiple-connections).

**Comment by jarnstedt** [comment]
We don't currently use Symfony. Not sure if DoctrineMongoDBBundle can be used without it.

**Comment by Steveb-p** [comment]
Symfony configuration is just a helper around construction of Doctrine connection and document manager classes. You can create as many instances of both as you want with different parameters.

See `DocumentManager::create`.

**Comment by Steveb-p** [comment]
See http://doctrine-orm.readthedocs.org/projects/doctrine-mongodb-odm/en/latest/tutorials/getting-started.html#persistent-models (second part)

**Comment by malarzm** [comment]
Sorry @jarnstedt for some reasons I was sure I've seen bundle in the notification email hence linked to it. Going down the route @Steveb-p is suggesting is a way to go, I'm even doing something similar in my work project.

**Comment by jarnstedt** [comment]
Exactly what I was trying to figure out, thank you!
