### ISSUE TITLE
Improve documentation for more advanced features

### ISSUE THREAD

**Issue by malarzm** [doctrine/mongodb-odm#1402]
This includes, but is not limited to:
- [ ] GridFS
- [ ] Geospatial queries

As per suggestion in http://stackoverflow.com/questions/36968156/advice-on-mongodb-odm-libraries-supporting-gridfs-and-geospatial-extension?noredirect=1#comment61676206_36968156

**Comment by Steveb-p** [comment]
@malarzm @alcaeus I have stumbled upon the docs for aggregation framework - which is really nice btw - but they suggest that it is present in version 1.1.3, which is not the case. Should I open a new issue, or can I hijack this one a little? :)

![image](https://cloud.githubusercontent.com/assets/3183926/22736518/c7477268-edfe-11e6-994c-6a70ac1fbd49.png)

**Comment by malarzm** [comment]
@Steveb-p good catch, instead of creating new issue would you mind creating a PR with a note like one in [Custom Collections](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/custom-collections.html) chapter instead? :) That must have been overlooked originally as PR was quite huge ;)

**Comment by Steveb-p** [comment]
Sure, will do in the evening :)
