### ISSUE TITLE
Getting a full list of all related documents / document classes + associations

### ISSUE THREAD

**Issue by vmattila** [doctrine/mongodb-odm#1404]
This idea/suggestion became to my mind while trying to find out all managed document that have a `@ReferenceOne` or `@ReferenceMany` association to another class: would it be possible to receive from the metadata driver a full list of document classes that refer to a given class? Or a bit further: all documents that refer to the given document?

Our use case is to merge two similar documents that may (or may not) be referred in other documents. Let's say there are two `Customer` documents `CustomerA` and `CustomerB`. They are referred in `Order` documents `Order1` and `Order2` similarly. During the regular housekeeping procedure we find that `CustomerA` and `CustomerB` are actually same person, so we'd like to leave `CustomerA` as the only document and remove `CustomerB`. Now it's a little bit hard to find in ODM world the documents that refer to `CustomerB` (=`Order2`) so we could replace `CustomerB` with `CustomerA`.

This kind of feature in ODM level could also allow interesting relational world features like restricting removals of referred documents, with a performance impact though.

**Comment by malarzm** [comment]
> would it be possible to receive from the metadata driver a full list of document classes that refer to a given class?

Yes, it would be possible but the list may or may not be complete. Reason is that you can map a reference without specifying `targetDocument` or `discriminatorMap` (and if you specify a `discriminatorMap` but forget to add discriminator value, ODM will still accept such reference, IIRC there was a plan to forbid such behaviour in 2.0). Also you could hold inverse references (and they can be added anytime as they're not stored in db) and utilize them.

Also there is a Doctrine extension https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/reference_integrity.md that may come in handy (at least it was suggested in https://github.com/doctrine/mongodb-odm/issues/709#issuecomment-169982658 that was pondering over similar concept).
