### ISSUE TITLE
$cursor->current() or $cursor->next() return null

### ISSUE THREAD

**Issue by Identity-labs** [doctrine/mongodb-odm#1407]
Hi, 

I use mongodb-odm with this configuration

    php5.6
    zf2, 
    mongodb 3.0.11, 
    ext-mongodb 1.1.6

composer :
        "mongodb/mongodb": "1.0.x",
        "alcaeus/mongo-php-adapter": "1.0.x",
        "doctrine/doctrine-mongo-odm-module": "dev-master",

Code : 
        $qb = $dm->createQueryBuilder('Foo');
        $qb->field('_id')->equals($id);
        $query = $qb->getQuery();
        $cursor = $query->execute();

$cursor->current() or $cursor->next() return null

but iterator_to_array($cursor); return my document in array

Thx for your help

**Comment by alcaeus** [comment]
Unlike the original `MongoCursor::next()`, ODM cursors don't return an element when calling next. The correct order of operation is calling `next()` followed by `current()` to open the cursor and return the first element, respectively. Alternatively you can also call the `getNext()` method which combines these two calls.
