### ISSUE TITLE
$dm->flush() continueOnError not found

### ISSUE THREAD

**Issue by Identity-labs** [doctrine/mongodb-odm#1408]
Hi,

I use mongodb-odm with this configuration
        php5.6
        zf2, 
        mongodb 3.0.11, 
        ext-mongodb 1.1.6

composer :
        "mongodb/mongodb": "1.0.x",
        "alcaeus/mongo-php-adapter": "1.0.x",
        "doctrine/doctrine-mongo-odm-module": "dev-master",

When I use and I have a duplicate entry, my other document are not persisted with this method :
        $db->flush(null, array('continueOnError' => true, 'ordered' => false));
And throw MongoDuplicateKeyException 

Do you have a solution to this problem ?
How to force Upsert ? (http://php.net/manual/fr/class.mongodb-driver-bulkwrite.php)
I think doctrine only insert document if _id exists or auto-generated by custom id generator,
But with persist method we can't specify insert update or upsert

Thx for your help

**Comment by alcaeus** [comment]
> I think doctrine only insert document if _id exists or auto-generated by custom id generator

You are correct. If your document already has an identifier, the document is written to the database using an upsert query. If there is no ID, one is generated and the document is written to the database using an insert.

As for `continueOnError` not working, could you provide a failing test case?

**Comment by Identity-labs** [comment]
Hello

I have created an repo ready to go clone and execute
https://github.com/Identity-labs/mongodb-odm-flush-issue

This exemple show continueOnError fail with the third doc,
And an _id with IdGenerator don't upsert

**Comment by Identity-labs** [comment]
No one have the same issue ?

**Comment by alcaeus** [comment]
Sorry, I took a quick peek and then forgot about this, my bad. I'll take a look at it this afternoon and convert it into a functional test.

**Comment by alcaeus** [comment]
Alright, took a look. From what it looks like, this would be an issue with the driver or none at all, one of the driver guys (ping @jmikola) would have to answer it. It boils down to this code:

```
$client = new MongoClient();
$coll = $client->selectCollection('test', 'duplicate');
$coll->drop();
$coll->insert(['_id' => 1]);
$coll->batchInsert([['_id' => 1], ['_id' => 2]], ['continueOnError' => true]);
var_dump(iterator_to_array($coll->find()));
```

The result of this is:
```
Warning: Uncaught exception 'MongoDuplicateKeyException' with message 'localhost:27017: E11000 duplicate key error collection: test.duplicate index: _id_ dup key: { : 1 }' in php shell code:1
Stack trace:
#0 php shell code(1): MongoCollection->batchInsert(Array, Array)
#1 {main}
  thrown in php shell code on line 1

array(2) {
  [1] =>
  array(1) {
    '_id' =>
    int(1)
  }
  [2] =>
  array(1) {
    '_id' =>
    int(2)
  }
}
```

So, while the driver throws an exception, the documents get inserted nonetheless. This seems to be intented behavior, quoting from [the batchInsert documentation](https://secure.php.net/manual/en/mongocollection.batchinsert.php) (emphasis mine):
> Boolean, defaults to FALSE. If set, the database **will not stop processing a bulk insert** if one fails (eg due to duplicate IDs). This makes bulk insert behave similarly to a series of single inserts, except that calling MongoDB::lastError() will have an error set if any insert fails, not just the last one. If multiple errors occur, only the most recent will be reported by MongoDB::lastError().

The way I see it, it doesn't say the code won't throw an exception, it only says it will not stop processing documents at the first exception.

**Comment by alcaeus** [comment]
Closing here: `continueOnError` doesn't do what OP thought it would do: it doesn't silence exceptions, it just ensures operations are not cancelled on the first error but continues to execute bulk operations.
