### ISSUE TITLE
LifecycleEventArgs is not passed to lifecycle callback method

### ISSUE THREAD

**Issue by metanav** [doctrine/mongodb-odm#1421]
I am getting following exception: 
Argument 1 passed to MetaLib\Document\Embedded\Annotation\Media::prePersist
() must be an instance of Doctrine\ODM\MongoDB\Event\LifecycleEventArgs, none given.

Document class:
```

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Doctrine\ODM\MongoDB\Event\LifecycleEventArgs;

/** 
 * @ODM\EmbeddedDocument 
 * @ODM\HasLifecycleCallbacks
 */
class Media extends AbstractMedia
{
    /** @ODM\ReferenceOne(targetDocument="Document\MainMedia", inversedBy="annotations") @ODM\Index */
    protected $media;
    
    /** @ODM\String */
    protected $mediaId;
    
    /** @ODM\PrePersist */
    public function prePersist(LifecycleEventArgs $eventArgs)
    {
        $this->mediaId = $this->media->getId();
    }
}
```

**Comment by malarzm** [comment]
Thanks for the report! I'll try to look into this somewhen this week :)

**Comment by alcaeus** [comment]
@metanav which version of ODM are you using? 1.0 or dev-master?

**Comment by metanav** [comment]
@alcaeus I am using packages below:

doctrine/mongodb:    1.3.0           
doctrine/mongodb-odm:  1.0.5 
doctrine/doctrine-mongo-odm-module:  0.10.0

**Comment by alcaeus** [comment]
As I expected. Unfortunately, our docs are a bit messed up and show dev-master docs for 1.0 at the moment. We'll get all this sorted out right after doing the 1.1 release.

ODM 1.0 does not pass lifecycleEventArgs to lifecycle callbacks, only lifecycle events get those. ODM 1.1 also passes them to callbacks, which is what you saw in the documentation.

For now, remove the argument to prePersist or wait a couple of days, 1.1.0 is just around the corner.
