### ISSUE TITLE
Can we use aggregation framework?

### ISSUE THREAD

**Issue by pablomoreno61** [doctrine/mongodb-odm#1426]
Hi,

Is aggregation framework available at doctrine2? I need to execute a query like this:

db.products.aggregate({$match:{created_at:{$exists:true}}}, {$project: {name: 1, month: {$month: '$created_at'}, day: {$dayOfMonth: '$created_at'}}},{$match: {month: 6, day: 3}})

I cannot find any example talking about that.

**Comment by malarzm** [comment]
Yes you can, underlying `doctrine/mongodb` is exposing a builder since https://github.com/doctrine/mongodb/pull/213 and while you can not hydrate results into objects yet (#1263) you're free to use the feature and will just get back plain arrays with data.

**Comment by pablomoreno61** [comment]
hum, that works with ODM? I will try. Do you have any complete example?

**Comment by pablomoreno61** [comment]
I got it :), here is the example:

        $pipeline = array(
            array('$match' =>
                array(
                    'created_at' => array('$exists' => true)
                )
            ),
            array('$project' =>
                array(
                    'name' => true,
                    'month' => array(
                        '$month' => '$created_at'
                    ),
                    'day' => array(
                        '$dayOfMonth' => '$created_at'
                    ),
                )
            ),
            array('$match' =>
                array(
                    'month' => $month,
                    'day' => $day,
                )
            ),
        );

        return $this->getDocumentManager()->getDocumentCollection('Product')->aggregate($pipeline);

and it returns an Doctrine\MongoDB\ArrayIterator

**Comment by malarzm** [comment]
Glad it works :)
