### ISSUE TITLE
Warning: Undefined index: strategy in Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php:248

### ISSUE THREAD

**Issue by kufd** [doctrine/mongodb-odm#1435]
When i updated mongo-odm to 1.1.0 i have got warning "Notice Undefined index: strategy" in Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php:248

It happens when i try to update mapped object:
$this->dm->persist($object);
$this->dm->flush($object);

**Comment by alcaeus** [comment]
Are you using a metadata cache? Metadata changed in 1.1, so you need to make sure that was cleared.
If the problem still persists, can you try to reproduce this in a test case or share some of the mapping that is causing this?

**Comment by kufd** [comment]
Here you can find testcase to reproduse the issue https://github.com/kufd/doctrine-odm-issue-1435

**Comment by alcaeus** [comment]
Thanks, I see the problem now. I'll get a fix ready soon.
