### ISSUE TITLE
Claify difference between name and fieldName

### ISSUE THREAD

**Issue by arendjantetteroo** [doctrine/mongodb-odm#1442]
I've git bisected it to this commit. 

git bisect bad
339a910a6314ff633ced79e96301fd650d68f18e is the first bad commit
commit 339a910a6314ff633ced79e96301fd650d68f18e
Author: Maciej Malarz <malarzm@gmail.com>
Date:   Sun Dec 20 23:45:39 2015 +0100

    Let ReflectionException bubble

:040000 040000 ef8770485fc75a13bee684e4c010de7fd3fcf1cb 8af82efd24a5b5e445e5c60dcdd1e6615007ba5e M      lib
:040000 040000 72d8c87f84327d1a0401456eaf710ac8862fb2db 78cb287b70fa9a12b979234b628a47c4b8bb8c1a M      tests

It results in the symfony cache:clear not correctly running, so breaking the app. 

I'm running with the samlSpBundle, which uses a doctrine mongodb mapping in a seperate file, which works fine in 1.0.4 but breaks in 1.0.5 and up due to this reflectionException bubble. 

SSOState mapping: 
https://github.com/aerialship/SamlSPBundle/blob/master/src/AerialShip/SamlSPBundle/Resources/config/doctrine-mapping/SSOState.mongodb.xml

I'm not sure if the issue is with the mapping or the way this changed in the bundle. 

Let me know what I can do to help resolve this. i want to upgrade to 1.1 for the php7 support, but this is blocking it.

**Comment by malarzm** [comment]
It seems that the mapping in bundle you're linking is not correct, field's `fieldName` is supposed to point to class' property name while `name` can be used to change field's name in the database (and linked mapping does opposite).

Disclaimer: we have mistakenly used `field`/`fieldName` wrongly ourselves (or at least I did few times) so please do take above statement with grain of salt and if I'm wrong please tell :)

**Comment by arendjantetteroo** [comment]
@malarzm That does indeed seem to solve the cache clear issue. 
I guess the mapping was wrong all the time, but it was working as i mapped it myself in my child object. When fixing this in the bundle, that is no longer necessary. 

So the exception is showing that something was wrong all along. 

I'll create a pull request against the Saml bundle, thanks for the fast feedback. 

I'm not sure if the mapping is correctly described in the documenntation, but a note about this might be a good idea if it's not :)

**Comment by malarzm** [comment]
Glad it works, I'm marking this as documentation issue then ;)

**Comment by alcaeus** [comment]
Fixed in #1447.

**Comment by arendjantetteroo** [comment]
Thanks :)
