### ISSUE TITLE
Revisit Custom Mapping Types docs

### ISSUE THREAD

**Issue by malarzm** [doctrine/mongodb-odm#1444]
As pointed out on IRC, http://doctrine-orm.readthedocs.io/projects/doctrine-mongodb-odm/en/latest/reference/basic-mapping.html#custom-mapping-types is quite outdated and it should be updated

**Comment by malarzm** [comment]
I should have written that down 👶 From the top of my head, there's https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Types/ClosureToPHP.php to help with custom types, I think one of the method was also no longer needed... @alcaeus do you remember something more by any chance? Maybe it'd also be ok to drop `closureToPHP` and by default do what the trait does?

**Comment by juliusstoerrle** [comment]
I think the closure is actually used, at least I got some error a few days ago when I forgot to add the namespace to a class inside the string. But can't verify that right now.

Which trait are you referencing?

**Comment by malarzm** [comment]
> Which trait are you referencing?

The one I linked in previous post: https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Types/ClosureToPHP.php

**Comment by alcaeus** [comment]
There's #1607 to handle the `closureToPHP`. No idea what else could be meant with that.

**Comment by malarzm** [comment]
Commenting here so it won't get lost on Slack:

> Maciej Malarz [8:17 PM]
> 
> `Type::closureToMongo` is not used currently
> 
> alcaeus [8:18 PM]
> 
> Oh?
> 
> Maciej Malarz [8:18 PM]
> 
> I think it was meant for generated persisters
> so we could drop that for 2.0
> also I was thinking about making what `ClosureToPHP` does a default in `Type`
> if we'd want a more performant code we can always override that method
> and by default folks won't need to care
> thoughts?
> 
> alcaeus [8:25 PM]
> 
> I’d have to take a deeper look, I thought it was used in hydrators
> 
> Maciej Malarz [8:26 PM]
> 
> `closureToPHP` is used in Hydrators
> I've mixed two things in one conversation :)
