### ISSUE TITLE
 Class 'dbName.collectionName' does not exist 

### ISSUE THREAD

**Issue by metanav** [doctrine/mongodb-odm#1450]
Why  am I getting this exception all of a sudden. This is happening for one of the queries I am building using aggregation builder.
 I checked the dbName and collectionName which is correct.

Trace is given below: 
```
{"trace":[{"file":"vendor/doctrine/common/lib/Doctrine/Common
/Persistence/Mapping/RuntimeReflectionService.php","line":41,"function":"nonExistingClass","class":"Doctrine
\\Common\\Persistence\\Mapping\\MappingException","type":"::","args":["dbName.collectionName"]},{"file"
:"vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping
/AbstractClassMetadataFactory.php","line":281,"function":"getParentClasses","class":"Doctrine\\Common
\\Persistence\\Mapping\\RuntimeReflectionService","type":"->","args":["dbName.collectionName"]},{"file"
:"vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping
/AbstractClassMetadataFactory.php","line":311,"function":"getParentClasses","class":"Doctrine\\Common
\\Persistence\\Mapping\\AbstractClassMetadataFactory","type":"->","args":["dbName.collectionName"]
}
```

The Doctrine ODM version I am using:
doctrine/doctrine-mongo-odm-module : 0.10.0
doctrine/mongodb-odm : 1.0.6

**Comment by alcaeus** [comment]
Could you please show some code that is leading to this error?

**Comment by metanav** [comment]
@alcaeus  below is the snippet. I think calling createQueryBuilder() after createAggregationBuilder() is causing the issue. But I had the same code before and it was working. I don't know which update broke this.
       ```
        $collection = $this->dm->getDocumentCollection(Document::class);
        $ab = $collection->createAggregationBuilder();
        $qb = $this->dm->createQueryBuilder($collection);
        $metadata = $this->dm->getMetadataFactory()->getAllMetadata();
         /* @var $filterManager  \ZF\Doctrine\QueryBuilder\Filter\Service\ODMFilterManager */
        $filterManager->filter($qb, $metadata[0], $params['filter']);
        $ab->match()->equals($qb->getQuery()->getQuery()['query']);
 ```

**Comment by metanav** [comment]
hmm...

Changing 
$qb = $this->dm->createQueryBuilder($collection); 
to 
$qb = $this->dm->createQueryBuilder(Document::class) 
works. I don't remember why I was passing $collection before instead of Document::class and how did it work?

**Comment by metanav** [comment]
Ok my bad! It must be document name.

**Comment by alcaeus** [comment]
> Ok my bad! It must be document name.

FWIW, it has always been that way. On the other hand, thanks for reminding me about filters. I had almost forgotten them for the ODM aggregation builder....again ;)
