### ISSUE TITLE
PHP7 - Int annotation class is a reserved class name

### ISSUE THREAD

**Issue by lsv** [doctrine/mongodb-odm#1459]
FatalErrorException in
`vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Int.php:26`

Compile Error: Cannot use 'Int' as class name as it is reserved

**Comment by alcaeus** [comment]
Using ODM in PHP 7 you cannot use the `Int`, `String`, `Float` and `Bool` annotations for mapping. In fact, [they aren't included for PHP 7](https://github.com/doctrine/mongodb-odm/blob/0236d92cd74a4cf5c52019215fd24426fd0469b4/lib/Doctrine/ODM/MongoDB/Mapping/Annotations/DoctrineAnnotations.php#L41..L47). Instead, you have to use the `Field` mapping with the `type` property set:
```php
/** @ODM\Field(type="int") */
var $intField
```

**Comment by lsv** [comment]
And its also in the docs - I was just to fast, sorry

**Comment by alcaeus** [comment]
No worries. Glad it's solved.

**Comment by j0k3r** [comment]
Maybe, instead of `@deprecated This class will be removed in ODM 2.0` you should put something like 

```
@deprecated This class will be removed in ODM 2.0. Use `@ODM\Field(type="int")` instead
```

**Comment by malarzm** [comment]
@j0k3r good idea, mind adding the note? If not I can do it later in the evening
