### ISSUE TITLE
getTypeOfField not working

### ISSUE THREAD

**Issue by caiquecastro** [doctrine/mongodb-odm#1460]
I have my code like this:
`$documentMetaData = new ClassMetadata('MyNamespace\To\MyDocument');`

and then I do 

`$typeOfField = $documentMetaData->getTypeOfField('name');`

But it is not returning what I expected.

Am I doing it wrong? I've also tried to pass a document instance to the constructor of ClassMetaData but it didn't work neither.

**Comment by alcaeus** [comment]
You have to fetch a valid `ClassMetadata` instance from the document manager:
```php
$documentMetaData = $dm->getClassMetadata('MyNamespace\To\MyDocument');
$typeOfField = $documentMetaData->getTypeOfField('name');
```

**Comment by caiquecastro** [comment]
Thanks!
