### ISSUE TITLE
php extension problem

### ISSUE THREAD

**Issue by faghihian71** [doctrine/mongodb-odm#1487]
pecl install mongo db require 

> MongoDB\BSON\ObjectID

but the doctrine-odm use mongoId

php site said:

> This extension that defines this class is deprecated. Instead, the MongoDB extension should be used. Alternatives to this class include:
> MongoDB\BSON\ObjectID

**Comment by malarzm** [comment]
Please follow https://github.com/doctrine/mongodb-odm/blob/master/CHANGELOG-1.1.md#php-7-compatibility for usage with PHP 7 and/or new driver
