### ISSUE TITLE
EmbeddedDocument in associative (hash) value

### ISSUE THREAD

**Issue by pilou** [doctrine/mongodb-odm#1489]
Hi!

I would like to have the same kind of embedded document as values of associative array keys.
In the database it should look like this:
```
{
   ...,
   foo: {
      'en': {
           'bar' => 'barValue for en',
           'baz' => 666,
           ...
      },
      'fr': {
           'bar' => 'barValue for fr',
           'baz' => 555,
           ...
      },
      ...
   }
}
```

The values of the keys of `foo` should be hydrated to an EmbeddedDocument, and stored in db as expected.

Could sbdy put me on track how to do this? I'm little confused and lost in the jungle of the documentation.

Is this should be a custom mapping type, or this is to do possible with the current components?

**Comment by malarzm** [comment]
You need to use normal `EmbedMany` and change `strategy` to either `set` or `atomicSet` ([docs](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/storage-strategies.html#set)).

Also for support/usage questions please use StackOverflow next time.

**Comment by pilou** [comment]
Thanks, works like expected.

There is a bit of caveat :(

We use document generator from yaml, and its keeps creating the `addPARAM_NAME` function.

The embeddedDocument should not have the language parameter (or the key in the array) because its used in a non-I18n context too (in another document) and it would be inconvinient, also it should not know its language.

With this in mind I think the implementation of this use case in the document should look like this:
The generated functions look like this:
```
public function addFoo(Doc $foo)
public function removeFoo(Doc $foo)
public function getFoo()
```
It should be like this:
```
public function setFoo($key, Doc $foo)
public function removeFoo($key)
public function getFoo()
```
I did overwrite the generated functions and create a `set` function and owerwritten `add` to be the alias of the `set` function.

The thing that bugs me is having the `add` function at all. If I delete it, it will keep generated back. I can't see any options telling the Generator not to do that.
It keeps creating it if `$fieldMapping['type'] === ClassMetadataInfo::MANY`

I'd be more than happy to contribute and create this associative(Embed|Reference)Many generator.

**Comment by alcaeus** [comment]
You should not use Generators more than once, they are intended to be used after initial mapping. When you later change the mapping, you should add the information to the class manually, as the generators would remove all custom logic you might have added to your documents.

**Comment by malarzm** [comment]
I think we could however add some check for `strategy` for `many` fields and if its allowing associative array, generate appropiate methods. Any thoughts on this @alcaeus?

**Comment by pilou** [comment]
@alcaeus  As I experienced the Generators newer owerwrites the Document, Entityt, Repo files unless you tell it with a cli argument. So adding things to a schema and reGenerate is usually flawless.
However the `__constructor` isnt appended with new ArrayCollection if you add another (Embed|Reference)Many if the `__constuctor` already exists. But thats not a trivial thing to implement, like checking if a method exsits.
So Generators wont overwrite custom logic unless you tell it to do so.

Also the addXXX, removeXXX functions are generated non-chainable, they dont `return $this;` Is it designed like that, or just missed that? If just missed I'll make a PR for that.
