### ISSUE TITLE
queryBuilder group only accepts MongoDate

### ISSUE THREAD

**Issue by caiquecastro** [doctrine/mongodb-odm#1493]
Did any recent change to the code, made the date range not accept the \DateTime and only \MongoDate?

The parameters are: `(\DateTime $from, \DateTime $to)`

The query used to be:

```
 $query = $this->createQueryBuilder()->group(
            [],
            ['sum' => 0],
            "function(doc, ret){ ret.sum += doc.price; }",
            [
                'condition' => [
                    'createdAt' => [
                        '$gte' => $from,
                        '$lte' => $to,
                    ]
                ]
            ]
        )->getQuery();
```

It was not matching any result, and then I changed to:

```
'createdAt' => [
    '$gte' => new \MongoDate($from->getTimestamp()),
    '$lte' => new \MongoDate($to->getTimestamp()),
]
```

And it now works!

**Comment by malarzm** [comment]
@caiquecastro do you recall in which version of ODM (and possibly underlying doctrine/mongodb) it was working? Are you using ODM on PHP 5.x or running PHP 7 with some adapter?

**Comment by caiquecastro** [comment]
I am running on PHP 5.6

**Comment by malarzm** [comment]
And the rest of versions (ODM and doctrine/mongodb)?

**Comment by caiquecastro** [comment]
Sorry for the delay.

I'm running ODM 1.1.

**Comment by alcaeus** [comment]
After doing some testing, I found that everything works as expected. The problem is with passing the `condition` option directly, as shown in your example. In this case, you're responsible to ensure only BSON types are passed to the driver.

If you want the query builder to handle type conversion for you, change your code:
```
$query = $this->createQueryBuilder()
    ->group(
        [],
        ['sum' => 0],
        "function(doc, ret){ ret.sum += doc.price; }"
    )
    ->field('createdAt')
    ->gte($from)
    ->lte($to)
    ->getQuery();
```

This way, types are properly converted according to the mapping in your document.

**Comment by alcaeus** [comment]
Closing for lack of feedback. @caiquecastro feel free to reopen this if the issue persists or you feel there's a bug after all. Thanks!
