### ISSUE TITLE
Need conversion to search for UUID indexed fields

### ISSUE THREAD

**Issue by curry684** [doctrine/mongodb-odm#1494]
Using current stable, consider the following document:
```php
/*
 * @MongoDB\Document
 * @MongoDB\Index(keys={"recipient"="asc"})
 */
class Notification
{
    /**
     * @MongoDB\Id
     */
    protected $id;

    /**
     * @MongoDB\Field(type="bin_uuid")
     */
    protected $recipient;
}
```
Now the following returns results properly:
```php
return self::findBy(['recipient' => new \MongoBinData($user->getId(), \MongoBinData::UUID)]);
```
While this returns an empty array:
```php
return self::findBy(['recipient' => $user->getId()]);
```
I would expect this transformation to be performed natively based on the mapping data.

(as for the use case and not having an actual relationship - the User is in ORM, not ODM, I'm only using Mongo for 'lossy big data' in this project)

**Comment by malarzm** [comment]
@curry684 agree this would be great thing to have, I even started working on it some time ago however it's not as easy as it seems to be... For now, in addition to `\DateTime` and `\MongoId`, only references are being prepared (#1363) (and possibly embedded documents are handled too), rest is yet to be implemented. Also I'll allow myself to close this ticket as we already have #1179 to track the feature request :)
