### ISSUE TITLE
Method convertToPHPValue does not get called for Custom Types.

### ISSUE THREAD

**Issue by mgonzalezbaile** [doctrine/mongodb-odm#1509]
I think this is a recurrent issue (I've seen similar already opened) so I wanted to propose an approach to make the `convertToPHPValue` method work without modifying anything else in the rest of the code.

I have created the PR #1510 modifying the test class `CustomTypeTest` to show how it works.

To avoid using reflection to instantiate `Type` I have pushed PR #1513.

This allows to test the custom hydrators (custom types) properly, both hydrate (convertToPHPValue) and extract (convertToDatabaseValue) methods.

**Comment by malarzm** [comment]
Closing as #1513 was merged
