### ISSUE TITLE
Memory leak: $dm->clear() does not completely free objects obtained with "select" method

### ISSUE THREAD

**Issue by arturmelanchyk** [doctrine/mongodb-odm#1515]
I have PortalUser collection with over 170k documents. PortalUser document has a field portal_account which is a reference to PortalAccount collection. Since i do not need any fields to be hydrated besides portal_account i use following code:

```
    `$usersIterator = $this->getDocumentManager()
        ->getRepository('ClientPortalGenericBundle:PortalUser')
        ->createQueryBuilder()
        ->select('portal_account')
        ->field('portal_account')
        ->notEqual(null)
        ->getQuery()
        ->getIterator();

    $itemsProcessed = 0;
    foreach ($usersIterator as $user) {
        // ... some logic here
        if ($itemsProcessed % 2000 === 0) {
            $beforeMem = memory_get_usage() / 1024 / 1024;
            $this->getDocumentManager()
                ->flush();
            $this->getDocumentManager()
                ->clear();
            $afterMem = memory_get_usage() / 1024 / 1024;
        }

        $itemsProcessed++;
    }`
```

Using Xdebug i found out that memory usage raises on every iteration, $afterMem is always higher then $beforeMem by 5-10mb in my case, which is causing "memory limit exhausted" PHP error

Eventually I found that if PortalUser is completely hydrated (commenting out "select" statement in query) everything works as expected and there would not be any memory leaks. In this case  $afterMem is always lower $beforeMem.

I was able to reproduce this with ODM versions 1.0.0 and 1.0.8. 
I consider this as a memory leak bug, please verify

**Comment by malarzm** [comment]
@arturmelanchyk would you be able to provide a test (or standalone code that we could execute on our own)? That would speed things up a bit :)

**Comment by malarzm** [comment]
@arturmelanchyk I tried to reproduce the issue by fetching partial document and inspecting `UnitOfWork` variables after `->clear()` is called but everything looks OK to me. Maybe it's the volume that is required maybe it's something else in your code - I'm afraid I won't get any further without a test case from you @arturmelanchyk

**Comment by arturmelanchyk** [comment]
Sorry, it was Monolog memory leak, ticket can be closed
http://stackoverflow.com/questions/35977213/memory-leak-symfony-and-monolog-and-console

**Comment by malarzm** [comment]
Thanks for getting back to us @arturmelanchyk it's really appreciated!
