### ISSUE TITLE
preLoad() expected to be a reference, value given

### ISSUE THREAD

**Issue by crashbtz** [doctrine/mongodb-odm#1528]
Hello,

I've updated the mongodb-odm bundle and now, I have an error:

> Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: Parameter 1 to MongoDBODMProxies\__CG__\Ftven\Bundle\EducationCoreBundle\Document\Video\Video::preLoad() expected to be a reference, value given" at /var/www/html/api/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php line 582

In my entity (like http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/annotations-reference.html#preload):

    /**
     * @param array $data
     *
     * @ODM\PreLoad()
     */
    public function preLoad(array &$data)
    {
        my code
    }

The issue seems to come from the HydratorFactory.php in the method hydrate()

Before the update:

    if ( ! empty($metadata->lifecycleCallbacks[Events::preLoad])) {
            $args = array(&$data);
            $metadata->invokeLifecycleCallbacks(Events::preLoad, $document, $args);
        }

Now:

    if ( ! empty($metadata->lifecycleCallbacks[Events::preLoad])) {
            $args = array(new PreLoadEventArgs($document, $this->dm, $data));
            $metadata->invokeLifecycleCallbacks(Events::preLoad, $document, $args);
        }

Did I do something wrong? Maybe something I have to do before the upgrade?

Thanks

**Comment by Steveb-p** [comment]
`preLoad` now - like other events - passes event object instead of just array of data, hence the warning. You should probably update your code to expect object of class `PreLoadEventArgs`.

You have spotted an error/missing info in documentation though ;)

**Comment by crashbtz** [comment]
indeed, everything works fine with a PreLoadEventArgs argument

Thanks a lot

**Comment by crashbtz** [comment]
No worries.
Indeed, I haven't seen that documentation, I was looking on this one (http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/annotations-reference.html#preload) which is now updated.
Whatever, thanks for your reactivity
