### ISSUE TITLE
Can't see database querie in symfony dev toolbar with aggregate

### ISSUE THREAD

**Issue by AizeLeOuf** [doctrine/mongodb-odm#1534]
If I use this query in my DocumentRepository :
```
use Doctrine\MongoDB\Aggregation\Builder;
...

$qBuilder = new Builder($this->getDocumentManager()->getDocumentCollection($this->getClassName()));

        return $qBuilder->execute();
```

I see no querie executed in Symfony dev toolbar panel Doctrine MongoDB :'( any idea ?

FYI with createQueryBuilder(), it's works perfectly : 

```
        $qBuilder = $this->createQueryBuilder();
        return $qBuilder->getQuery()->execute();
```

**Comment by alcaeus** [comment]
Thanks for the report! As the Symfony dev toolbar is provided by the DoctrineMongoDBBundle, I've created an issue there: https://github.com/doctrine/DoctrineMongoDBBundle/issues/392.
