### ISSUE TITLE
Project with aggregate queries

### ISSUE THREAD

**Issue by AizeLeOuf** [doctrine/mongodb-odm#1535]
```
$qBuilder = new Builder($this->getDocumentManager()->getDocumentCollection($this->getClassName()));
$reduceQuery = $qBuilder->expr()->field('minute')->minute('$startTime');
            $sortArray = array(
                    '_id.minute' => 'asc',
                );
$qBuilder->group()
                ->field('_id')->expression($reduceQuery)
                ->field('value')->avg('$value')
                ->sort($sortArray);
$qBuilder->project()->includeFields(array('value'));

return $qBuilder->execute();
```
return data like array(2) { ["_id"]=> array(1) { ["minute"]=> int(0) } ["value"]=> float(4932453.1377246) }
But if I replace : 
`$qBuilder->project()->includeFields(array('value'));`
to 
`$qBuilder->project()->includeFields(array('value', 'startTime'));`

I see no change in my dump result : 
array(2) { ["_id"]=> array(1) { ["minute"]=> int(0) } ["value"]=> float(4932453.1377246) }

Any idea ? project doesn't support ISODate ?

**Comment by alcaeus** [comment]
After the group stage, the documents only contain the `_id` and `value` fields, so including the `startTime` field won't work.

**Comment by AizeLeOuf** [comment]
Problem solved thanks for your feedback :)

**Comment by alcaeus** [comment]
For the record, if you're brave and want to try dev-master of ODM you can create an aggregation builder from a repository:
```php
$builder = $this->createAggregationBuilder();
$builder
    ->group()
        ->field('id')->expression($reduceQuery)
        ->field('value')->avg('$value')
    ->sort($sortArray)
;
```

That way, you don't have to take care of type conversion (e.g. to convert date values to `MongoDate` and back) and can optionally hydrate the results into objects.
