### ISSUE TITLE
Force @ReferenceMany to contain only one reference to each document

### ISSUE THREAD

**Issue by vmattila** [doctrine/mongodb-odm#1537]
I've been working with bulk operations in our app, where I should be able to add/remove one or more documents to `@ReferenceMany` association of a collection of other documents. Use case is simple adding a group for thousands of users.

As some of the users already may be in the group, I should explicitly check whether the user has the group before I will call `$user->getGroups()->add($group);` to avoid duplicate references.

It would be useful if I could simply define something like `once=true` to the association definition, like `

```php
/**
  * @ReferenceMany(targetDocument="Group", once=true)
  */
protected $groups;
```

ODM would then ensure that the reference is added only once.

**Comment by malarzm** [comment]
You could utilize [`addToSet` strategy](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/storage-strategies.html#addtoset), the document would have duplicated documents but that wouldn't be possible in the database. Would this be enough for your use case?

**Comment by alcaeus** [comment]
If `addToSet` is not enough, you could implement a custom collection class that ensures items added to the collection are unique.

**Comment by malarzm** [comment]
True, if you don't feel like implementing your own collection there's [ObjectSet in malarzm/collections](https://github.com/malarzm/collections#objectset) available :)

**Comment by malarzm** [comment]
@vmattila any thoughts?

**Comment by vmattila** [comment]
Well yes, I think `addToSet` is exactly what I look for here. :) So closing this issue.
