### ISSUE TITLE
Document not stored when property of Document uses underscore

### ISSUE THREAD

**Issue by webdevilopers** [doctrine/mongodb-odm#1539]
I'm updating an older project which seemed to work fine so far with this document:

```php
/** @MongoDB\Document(collection="histories") */
class History
{
    /** @MongoDB\Id */
    private $id;

    /** @MongoDB\Field(type="string") */
    private $notes;

    /** @MongoDB\Field(type="string") */
    private $date;

    /** @MongoDB\Field(type="string") */
    private $type;

    /** @MongoDB\Field(name="contact_id", type="int") */
    private $contact_id;

    /** @MongoDB\Field(type="string") */
    private $contact_name;
```

Using underscore here seems to be legit. As it worked before and other people successfully used it e.g. here:
* http://stackoverflow.com/questions/32274827/symfony-2-doctrine-odm-returning-errors-on-existing-fields

But suddenly the Document stopped persisting the `$contact_id` class property. While `$contact_name` indeed was added!

I renamed the properties using `camelCase`:

```php
    /** @MongoDB\Field(name="contact_id", type="int") */
    #private $contact_id;
    private $contactId;

    /** @MongoDB\Field(type="string") */
    private $contact_name;
```

Now BOTH fields are persisted correctly.

Looks like this issue is only related to the `int` type. I cleared the metatdata cache several times.
I'm gonna use `camelCase` from now. But maybe this is important to you. Maybe it is related to an update to PHP7 some months ago.

I'm using `dev-master`.

Possibly related:
* https://github.com/doctrine/mongodb-odm/issues/1459
* https://github.com/doctrine/mongodb-odm/issues/842

**Comment by alcaeus** [comment]
Could you please provide a failing test case? This looks like one of "those" bugs ;)

**Comment by webdevilopers** [comment]
It looks like this is NOT a bug. I recognized some problems with several naming strategies.
Instead of using the `doctrine:mongodb:cache:clear-metadata` command I completely removed the `app/cache/dev` folder. Only then everything started to work fine.

Looks like it is a problem with the command then?

**Comment by malarzm** [comment]
@webdevilopers most probably the Hydrators needed to be regenreted as well and that happens when you clear the cache :)

**Comment by webdevilopers** [comment]
You are right! I added the `doctrine:mongodb:generate:hydrators` command and the issue is solved!
Thanks!
