### ISSUE TITLE
php7, mongodb, windows server 2008, composer do not work =)

### ISSUE THREAD

**Issue by pinouf** [doctrine/mongodb-odm#1545]
hello,
I Try to install mongodb with php 7.0.9 on windows serveur 2008.

- i installed php 7.0.9 with MAMP
- i install mongodb php driver on https://pecl.php.net/package/mongodb ( 1.2.2 )
- php -m  ( i have mongodb)
- i try to install my application with composer

        "doctrine/mongodb": "1.3.*@dev",
        "doctrine/mongodb-odm": "1.1.*@dev",

- I have an error 

the requested php extension mongo is missing from your system windows..

Strange no?? ... 

Thanks, =)

**Comment by malarzm** [comment]
Please read [PHP 7 compatibility](https://github.com/doctrine/mongodb-odm/blob/master/CHANGELOG-1.1.md#php-7-compatibility) part of change log.

Offhand I think we should copy that to README
