### ISSUE TITLE
w for WriteConcern must be a string or integer PHP7

### ISSUE THREAD

**Issue by araines** [doctrine/mongodb-odm#1549]
Following the notes in the changelog, I'm attempting to upgrade our system to PHP7.  I've installed alcaeus/mongo-php-adapter as described, but I seem to be getting the following user warnings:

```
User Warning: w for WriteConcern must be a string or integer in vendor/alcaeus/mongo-php-adapter/lib/Alcaeus/MongoDbAdapter/Helper/WriteConcernConverter.php line 28
```

After a little debugging it seems that `$wstring` is coming in as a boolean, which then causes this error.  Honestly, I don't know a huge amount about Mongo - but hopefully someone has had a similar issue?

**Comment by alcaeus** [comment]
Could you please open an [issue against the adapter](https://github.com/alcaeus/mongo-php-adapter/issues)? Please include some sample code that helps reproducing the issue, I haven't hit that error using ODM at all. Thanks!

**Comment by araines** [comment]
Just in case anyone else finds this when doing a similar upgrade, I did manage to trace it back to an error in one part of our code.  It seems that the old `mongo` PHP extension used to allow WriteConcern to be set to `true` and it would work fine, whereas the adapter expects it to be an integer or string.  It was actually nothing to do with the ODM in the end, it was where a bit of legacy code was directly manipulating the collection (apologies to @alcaeus for raising this in the wrong place).

**Comment by alcaeus** [comment]
@araines thanks for the update. I've created https://github.com/alcaeus/mongo-php-adapter/issues/146 to track this and investigate once I've got my mind set on the adapter again.

**Comment by alcaeus** [comment]
Just a quick update: while never documented, the legacy driver indeed accepts passing boolean values as `w` option to insert and update commands. To avoid breaking working code for people migrating to the adapter, I've fixed this in https://github.com/alcaeus/mongo-php-adapter/pull/151. Again, thanks for bringing this up!
