### ISSUE TITLE
Update DBRefs when referenced document is updated

### ISSUE THREAD

**Issue by mikhalchuk** [doctrine/mongodb-odm#1555]
I have 2 documents A and B. Both are stored already.
A has a dbrefs containing B.
When I add B to A., flush all the changes and access A from B gives empty result. If I refresh B manually I see referenced objects.
Here is a small peace of code:
```
mapping A
<reference-one field="b" target-document="B" inversed-by="a" />

mapping B
<reference-many field="a" target-document="A" mapped-by="b">

$b = $repositoryB->find(...);
$a = $repositoryA->find(...);
$a->setB($b);
// flush document manager

$b = $repositoryB->find(...);
// $b doesn't have ref to $a

$dm->refresh($b);
// $b has ref to $a
```

Could you please help me? What I'm doing wrong?

Thanks

**Comment by Steveb-p** [comment]
`find` method does not update the object. It recoveres it from cache if it's already present. In this case, it returns **exactly** the same object instance as before.

What you probably want to do is either explicitly `$b->setA($a)` as well, or include it as part of `$a->setB()` method.

**Comment by malarzm** [comment]
@Steveb-p beat me with answer time so I'll just add that "cache" he's referencing is in-memory cache ("identity map") of ODM :)

Offhand @mikhalchuk next time please post support question on StackOverflow using `doctrine-odm` tag (or ask on IRC), issues on GitHub are for bug reports/feature requests.
