### ISSUE TITLE
Why not use $ref to resolve the class name instead of the discriminator field _doctrine_class_name?

### ISSUE THREAD

**Issue by Nilz11** [doctrine/mongodb-odm#1558]
Hello,

I don't know if someone already had the idea, but I couldn't find anything inside the issues.

The discriminator field inside the DbRef object causes some problems which are also mentioned on the doc page. 

So instead of saving the doctrine class name inside the dbref field, why not use the information that is already there? With the table name which is inside the $ref we could look up the needed class name to hydrate the reference or not?

If I do not see a problem, please point that out for me. Otherwise it would be cool to have this option.

Thanks,
nilz

**Comment by malarzm** [comment]
Without keeping discriminator in the `DBRef` object we wouldn't know which `Proxy` should be created (think single collection inheritance) and we'd need to query real document upfront which would defeat whole concept of proxies and lazy loading.

**Comment by Nilz11** [comment]
Ok for single collection inheritance I see that otherwise we would need to query the real document.

**Comment by malarzm** [comment]
Closing since the question was answered, feel free to continue though if you have more questions
