### ISSUE TITLE
Suggestion: New type of reference to deprecate usage of dbref

### ISSUE THREAD

**Issue by Nilz11** [doctrine/mongodb-odm#1560]
Hi,

I have another question.

First of all some explanation:
DbRefs are more or less on the way to being deprecated by mongodb, on the page about database references in most cases it recommends to use simple references and let the reference be resolved by the application.
Also new features in mongodb do not work with DbRefs, e.g. some map-reduce functionality and $lookup. 

See here for example here: https://jira.mongodb.org/browse/SERVER-14466
"[...] we've never formally deprecated use of DBRef. The DBRef convention is **still** widely used in ODM libraries."

Also the way it is now with a discriminator field inside the dbref for references specified, it is hard to query and a lot of tools do not support modifying such documents (e.g. robomongo). To query for an array of references which point to different tables, you need to either use $elemMatch which is slow compared to an $eq match or you need to know if there is a discriminator field inside the document and build the query accordingly (equal with $id, $ref or with $id, $ref and _doctrine_class_name).

Suggestion / question:
Can't we implement a new type of reference, next to id, dbRef and dbRef with $db, which handles relations in a simple and consistent way. E.g. there could be the class name (or some short form of it) and the object id stored inside a reference object and doctrine could resolve the relations.

Then also features like $lookup and using references inside map-reduce would work, querying would be simpler and in some cases even faster (depending on implementation).

Thanks for your comments :) 
Nilz

**Comment by alcaeus** [comment]
I've thought about that before, especially with the limitation about using DBRef objects in `$lookup` stages. It would most likely still be quite similar to the current DBRef object, besides the `$` prefix:
```
{
    ref: 'collection',
    id: ObjectId(...),
    discriminatorField: 'value'
}
```

I've added this to the 2.0 milestone, we can always push it forward if we want to.

**Comment by Nilz11** [comment]
Would be cool to have it earlier. I can also help to make changes, but probably need deeper understanding of the Doctrine internals first.

About the structure to have it like the original DBRef makes sense for me, in order to have the real collection name for lookup stages. The problem with discriminator field inside ref mentioned above would disappear then but there could be still some more improvement inside the query building:

Method includesReferenceTo at the moment uses $elemMatch which is less effective than using an $eq search instead. $elemMatch uses a collection scan while $eq can use an index scan. Building the query using $eq just is a little bit more complicated because we need to check whether there is a discriminator field on the reference or not and do the query appropriately.

**Comment by alcaeus** [comment]
As for the different way of storing a reference, you can look at #1349, which introduced a DBRef witthout the `$db` field. That would allow users to store references as a kind of embedded document that is usable in aggregation pipeline stages as well.

As for the `$elemMatch` vs. `$eq` check, there is a minor performance improvement we can add. `$elemMatch` is only required when we have more than just the `$id` field to check for, which isn't the case for most references (in fact, it's only necessary when there is no `targetDocument` set on the association). In all cases where the query looks like `{ foo: { $elemMatch: { '$id': ObjectId(...) } } }` we could change this to `{ 'foo.$id': ObjectId(...) }`. If you feel up for it, you can create a pull request for it (since it's a performance optimization, I'd suggest creating it against the master branch), otherwise I'll see if I can get to it in the coming weeks.

**Comment by Nilz11** [comment]
I did start making changes here:
https://github.com/Nilz11/mongodb-odm/tree/feature/ref-without-dbref

Still need to add testing for the new ref types. Existing tests are green. You can have a look at the approach if it's ok like that in general, also if the naming of the type is ok or you might have a better idea.

**Comment by alcaeus** [comment]
Can you create a pull request and mark it as "work in progress"? That would allow us to comment on the implementation directly. Thanks!

**Comment by amcsi** [comment]
So the PR is here apparently: #1566
I would like to express that I'm really interested in this new feature 👍

**Comment by malarzm** [comment]
Gonna close this issue as PR is already in a 1.2 bucket.
