### ISSUE TITLE
Bi-direction reference with inheritance does not work or is not supported?

### ISSUE THREAD

**Issue by josefsabl** [doctrine/mongodb-odm#1562]
Hello, I have a problem to make bi-directional reference work with inheritance. There is suggestion in the docs that I can omit targetDocument but it does not seem to work for bi-directional reference.

http://stackoverflow.com/questions/42164640/doctrine-odm-bi-direction-reference-with-inheritance

Is this a bug? Missing feature? Am I overlooking something? I understand that this probably does not belong here, but I am a bit desperate, thank you for feedback :-)

**Comment by malarzm** [comment]
I'll try to get back to your SO question later today, closing issue as it indeed doesn't belong here :)

**Comment by josefsabl** [comment]
Thank you so very much :-)
