### ISSUE TITLE
Interfaces are invalid as mapped superclasses

### ISSUE THREAD

**Issue by Bilge** [doctrine/mongodb-odm#1565]
It is inconsistent that abstract classes are permitted but interfaces are denied as targets for mapped superclasses: neither can be instantiated and both may define concrete implementations via a discriminator map. 

The problem with this limitation is Doctrine forces an application designer to use an abstract class where an interface may be preferred, which violates the idea that Doctrine should be able to merely decorate an existing system with persistence features.

**Comment by alcaeus** [comment]
Closing here: I don't see us implementing this in the near future. A working PR is always appreciated.
