### ISSUE TITLE
Aggregation builder rename _id field

### ISSUE THREAD

**Issue by billiam13s** [doctrine/mongodb-odm#1569]
I am using createAggregationBuilder() to project a new field name id (replace mongodb _id field). The aggregation builder would replace `id` to `_id`.

Code: `$ab->project()->field('id')->expression('$_id')`

Builded query:
```
"$project": {
    "_id": "$_id"
}
```

Would like to build:
```
"$project": {
    "id": "$_id"
}
```

Is there a way to override the current behaviour any field named `id` and `_id` to `_id`?

Thanks

**Comment by alcaeus** [comment]
No. Any field name found in the mapping information will be converted from its PHP name to its MongoDB name. This can't be disabled in ODM aggregation builder. You can go one step deeper and use `Doctrine\MongoDB\Aggregation\Builder`, but be aware that you will not have type conversion (e.g. from `DateTime` to `MongoDate`), mapping awareness or methods like `references`.

**Comment by billiam13s** [comment]
@alcaeus Thanks for the quick reply. We decided to update all our id fields to _id, keep all our queries result consistent.
