### ISSUE TITLE
Inheritance document custom id strategy

### ISSUE THREAD

**Issue by billiam13s** [doctrine/mongodb-odm#1570]
We have inheritance documents, want to setup custom id generation strategy on each level. Currently, it seen like all level of child of the documents resolve to the root parent's document id gererator even when they have it own generator set. Should there be a way to use child's own id generator beside setting `strategy: NONE` then set id manually?

**Comment by malarzm** [comment]
@billiam13s if I understand your issue properly, it's about setting `@ODM\Id` once again for each child document, right? What would you expect more or see convenient to fit the use case?

**Comment by billiam13s** [comment]
Yes, we are setting the id strategy again for each sub children classes and would like to use their own id generator instead of the parent class id generator. 

Example:
```
/** 
 * @Id(strategy="CUSTOM", type="string", options={"class"="MediaIdGenerator"})
 *
 * ID: M-<numnbers>
 */
class Media
{
    $_id
}

/** 
 * @Id(strategy="CUSTOM", type="string", options={"class"="BookIdGenerator"})
 *
 * ID: B-<author>-<numnbers>
 */
class Book extends Media
{
    $author
}

/** 
 * @Id(strategy="CUSTOM", type="string", options={"class"="DiskIdGenerator"})
 *
 * ID: D-<numnbers>
 */
class Disk extends Media
{

}

/** 
 * @Id(strategy="CUSTOM", type="string", options={"class"="CDIdGenerator"})
 *
 * ID: CD-<numnbers>-<$number_tracks>
 */
class CD extends Disk
{
    $number_tracks
}

/** 
 * @Id(strategy="CUSTOM", type="string", options={"class"="DVDIdGenerator")}
 *
 * ID: DVD-<numnbers>-<movie_length>
 */
class DVD extends Disk
{
}
```

At the moment, we solve the problom by setting id `strategy: NONE`  then manually calling the sub-class id generator manully. It would be nice if children classes can resolve to their own id generator.

**Comment by malarzm** [comment]
I would expect this to work:

```
/** 
 * ID: M-<numnbers>
 */
class Media
{
    /* @Id(strategy="CUSTOM", type="string", options={"class"="MediaIdGenerator"}) */
    protected $_id;
}

/** 
 * ID: B-<author>-<numnbers>
 */
class Book extends Media
{
    /* @Id(strategy="CUSTOM", type="string", options={"class"="BookIdGenerator"}) */
    protected $_id;

    $author
}
```

Personally I don't like putting `@Id` annotation to the class level as it's a field mapping by design

**Comment by alcaeus** [comment]
> Personally I don't like putting `@Id` annotation to the class level as it's a field mapping by design.

I'm surprised that even works - `@Id` is most definitely a field annotation and not class annotation. I know the annotation library supports restricting where annotations can be used (e.g. `@Field` can only be used on properties, not on a class or method). We should do so, but only for 2.0 since it would be a BC break.

**Comment by malarzm** [comment]
> I'm surprised that even works

Is it? I thought it's an example how @billiam13s would like to see it

**Comment by alcaeus** [comment]
Oh, maybe I misunderstood then. I don't see where that would improve anything compared to the current implementation?

**Comment by billiam13s** [comment]
I am sorry guys. I should have put the pseudo code correct. The @id are at the field level as @malarzm shown. We use ymal instead of annotation, I was careless to make that example. 

Base on what you guys are saying. If @id are set again on each sub-classes in annotation format, sub-classes would like it own id generator. Right? Is there an issue with ymal format then?

Thanks

**Comment by malarzm** [comment]
> Base on what you guys are saying. If `@id` are set again on each sub-classes in annotation format, sub-classes would like it own id generator. Right?

Right, I won't bet my head on it, but I'd expect it to happen :)

> Is there an issue with ymal format then?

This is a possibility, YAML is sometimes off compared to annotations or XML. Best would be if you could write a failing test case and submit it as a PR, it'd speed up investigating.

**Comment by billiam13s** [comment]
Thanks for understanding. 

Would you able to give me a few hits as of how to start? Where should test case locate? I will try my best to make the test case soon.

**Comment by malarzm** [comment]
Sure! The easiest way to start is taking a look at our "functional" tests located here: https://github.com/doctrine/mongodb-odm/tree/master/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket and I even see something YAML related here: https://github.com/doctrine/mongodb-odm/tree/master/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1435 for you to see how things needs to be configured. If you'd need more help try pinging me here or on IRC

**Comment by alcaeus** [comment]
1) YAML is dropped in 2.0, fixing that problem
2) Re-mapping the identifier in child classes is the way to go in this scenario.

Closing here.
