### ISSUE TITLE
Nested query builder not working

### ISSUE THREAD

**Issue by nicholasnet** [doctrine/mongodb-odm#1573]
I am trying to build this mongo query using query builder but it seems like there is problem with query builder in situation where conditions are nested.

**Mongo query**
```
db.getCollection('queues').find({
    $and:[
        {queue: 'testo'},
        {
            $or:[
                
                {$and: [{reserved_at: null}, {available_at:{'$lte':1490323024}}]},
                {reserved_at:{'$lte':1490323024}}
               
            ]
        }
    ]
});

// SQL equivalent
// SELECT *
// FROM  q
// WHERE q.queue = :queue
// AND ((q.reservedAt IS NULL AND q.availableAt <= :now) OR (q.reservedAt <= :expiration))
// ORDER BY q.id ASC
// LIMIT 1

```

This is what is tried 
        
    $builder = $this->get('doctrine_mongodb')->getManager()->createQueryBuilder('AppBundle:Queue');
    $builder->findAndUpdate()->addAnd([
        $builder->field('queue')->equals($queue),
        $builder->addOr([
            $builder->addAnd([
                $builder->field('reservedAt')->equals(null),
                $builder->field('availableAt')->lte($currentTime)
            ]),
            $builder->field('reservedAt')->lte($expiration)
        ])
    ])
    ->sort('id', 'ASC')
    ->limit(1)
    ->field('reservedAt')->set($currentTime->getTimestamp());

    $result = $builder->getQuery()->execute()->toArray();`

But I am getting this error.

`exception: nextSafe(): { $err: "Can't canonicalize query: BadValue $or/$and/$nor entries need to be full objects", code: 17287 }`

**Comment by alcaeus** [comment]
When adding nested expressions, you need to create a new expression object. FWIW, I simplified away the second `addAnd`, since adding multiple conditions on a single expression object is always equates a logical and.

```
$builder
    ->findAndUpdate()
    ->addAnd([
        $builder->expr()
            ->field('queue')
            ->equals($queue),
        $builder->expr()->addOr([
            $builder->expr()
                ->field('reservedAt')->equals(null),
                ->field('availableAt')->lte($currentTime),
            $builder->expr()
                ->field('reservedAt')->lte($expiration)
        ])
    ])
    ->sort('id', 'ASC')
    ->limit(1)
    ->field('reservedAt')
    ->set($currentTime->getTimestamp())
;
```

**Comment by nicholasnet** [comment]
As per you comment I tried this.

```
$builder
->findAndUpdate()->addAnd([
    $builder->expr()->field('queue')->equals($queue),
    $builder->expr()->addOr([
        $builder->expr()->field('reservedAt')->equals(null)->field('availableAt')->lte($currentTime),
        $builder->expr()->field('reservedAt')->lte($expiration)
    ])
])
->sort('id', 'ASC')
->limit(1)
->field('reservedAt')->set($currentTime->getTimestamp());
```
I am getting this error.

`exception: nextSafe(): { $err: "Can't canonicalize query: BadValue $or/$and/$nor entries need to be full objects", code: 17287 }`

**Comment by alcaeus** [comment]
Yeah, sorry about that - I missed that you were passing an array to `addOr`. It only takes one argument and needs to be called multiple times. Then again, the first call to `addAnd` isn't necessary either, that's what happened:

```
$builder
    ->findAndUpdate()
    ->field('queue')->equals('queue')
    ->addOr(
        $builder->expr()
            ->field('reservedAt')->equals(null)
            ->field('availableAt')->lte($currentTime)
    )
    ->addOr(
        $builder->expr()->field('reservedAt')->lte($expiration)
    )
    ->sort('id', 'ASC')
    ->limit(1)
    ->field('reservedAt')->set($currentTime);
```

No, alternatively, if you are using at least version 1.4.0 of the underlying `doctrine/mongodb` library, you can pass both expressions to `addOr` at the same time, but not as an array:
```
$builder
// ...
    ->addOr(
        $builder->expr()
            ->field('reservedAt')->equals(null)
            ->field('availableAt')->lte($currentTime),
        $builder->expr()->field('reservedAt')->lte($expiration)
    )
```

**Comment by nicholasnet** [comment]
No worries. We are making progress but seems like it is still not producing right result. No error this time but no result either.

Given this as input and using the query you gave. I _tried second version as well._
```
$retryAfter = 1000;
$queue = 'test';
$currentTime = new \DateTimeImmutable;
$expiration = $currentTime->modify((int) ($retryAfter * -1) . ' seconds');

$job = $builder->findAndUpdate()
               ->returnNew()
               ->field('queue')->equals($queue)
               ->addOr($builder->expr()->field('reservedAt')->equals(null)->field('availableAt')->lte($currentTime))
               ->addOr($builder->expr()->field('reservedAt')->lte($expiration->getTimestamp()))
               ->sort('id', 'ASC')
               ->limit(1)
               ->field('reservedAt')->set($currentTime->getTimestamp())
               ->getQuery()
               ->execute();
```
I am getting this as command result.
`db.queues.runCommand({ "findandmodify": "queues", "query": { "queue": "test", "$or": [ { "reserved_at": null, "available_at": { "$lte": new ISODate("2017-03-27T22:08:28-04:00") } }, { "reserved_at": { "$lte": 1490665908 } } ] }, "update": { "$set": { "reserved_at": 1490666908 } }, "new": true, "sort": { "_id": 1 } });`

But the actual result that I should be getting is this one.
`db.queues.runCommand({ "findandmodify": "queues", "query": { "$and": [ { "queue": "test" }, { "$or": [ { "$and": [ { "reserved_at": null }, { "available_at": { "$lte": 1490667436 } } ] }, { "reserved_at": { "$lte": 1490666436 } } ] } ] }, "update": { "$set": { "reserved_at": 1490667436 } }, "new": true, "sort": { "_id": 1 } });`

which gives me result.

**Comment by nicholasnet** [comment]
Thank you that worked.
