### ISSUE TITLE
QueryBuilder: can not update with $each expression

### ISSUE THREAD

**Issue by hq9000** [doctrine/mongodb-odm#1575]
we want to update many documents and set an array value [1, 2, 3] for a field.

finally we've come up with this solution:

$qb->updateMany()->field('targetGeo')->addToSet($qb->expr()->each([1,2,3]));
however, the generated query makes mongo fail:

[MongoWriteConcernException] localhost:27017: The argument to $each in $addToSet must be an array but it was of type NumberLong64

debugging query gives us:

Array (
    [type] => 5
    [multiple] => 1
    [query] => Array
        (
        )

    [newObj] => Array
        (
            [$addToSet] => Array
                (
                    [targetGeo] => Array
                        (
                            [$each] => 1
                        )

                )

        )

)
apparently, it's this [$each] => 1 which makes it fail.

We can't figure out what is going wrong here. Is it a bug in query builder or we are not using it the right way?

we are using doctrine-mongodb 1.4 and doctrine-odm 1.1.3
==============================

exhaustive description can be found here along with the patch we found:
http://stackoverflow.com/questions/43073362/doctrine-mongodb-how-to-can-not-set-array-value-to-a-field

**Comment by malarzm** [comment]
@hq9000 thanks for the report! It indeed looks like a bug in ODM, I'll need to double check whether solution you've posted in the SO will not break something else.

**Comment by malarzm** [comment]
@hq9000 what type of the field were you trying to update? I'm asking because I've tried to write a failing test case on current `1.1.x` branch and it's passing (on field with type `collection`)?

**Comment by malarzm** [comment]
Closing because of no update from OP. I couldn't make the test fail while using `collection` as a type of field but the described effect is possible with `int` ([yay PHP casting](https://3v4l.org/pjtsm)). @hq9000 please feel free to reopen with more details or better yet, a failing test case.
