### ISSUE TITLE
chmod(): No such file or directory

### ISSUE THREAD

**Issue by mikaelmattsson** [doctrine/mongodb-odm#1581]
I some times get this error and when I do, it clears out all properties on the user document in the database. This is kind of annoying as you can imagine. This might be because I am using docker on OSX and have the *doctrine hydrators dir* mounted with the ”cached consistency flag”

```[2017-04-26 06:53:44] app.ERROR: ErrorException: chmod(): No such file or directory in /var/www/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php:423 Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'chmod(): No suc...', '/var/www/vendor...', 423, Array)
#1 /var/www/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php(423): chmod('/var/www/storag...', 436)
#2 /var/www/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php(146): Doctrine\ODM\MongoDB\Hydrator\HydratorFactory->generateHydratorClass(Object(Doctrine\ODM\MongoDB\Mapping\ClassMetadata), 'AppUserEntities...', '/var/www/storag...')
#3 /var/www/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php(460): Doctrine\ODM\MongoDB\Hydrator\HydratorFactory->getHydratorFor('App\\User\\Entiti...')
#4 /var/www/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php(2692): Doctrine\ODM\MongoDB\Hydrator\HydratorFactory->hydrate(Object(App\User\Entities\User), Array, Array)
#5 /var/www/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php(649): Doctrine\ODM\MongoDB\UnitOfWork->getOrCreateDocument('App\\User\\Entiti...', Array, Array, Object(App\User\Entities\User))
#6 /var/www/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php(514): Doctrine\ODM\MongoDB\Persisters\DocumentPersister->createDocument(Array, NULL, Array)
#7 /var/www/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentRepository.php(186): Doctrine\ODM\MongoDB\Persisters\DocumentPersister->load(Array)
#8 /var/www/app/User/Providers/Auth/UserAuthProvider.php(36): Doctrine\ODM\MongoDB\DocumentRepository->findOneBy(Array)
```

Code referred to in the error:

```php
$tmpFileName = $fileName . '.' . uniqid('', true);
file_put_contents($tmpFileName, $code);
rename($tmpFileName, $fileName);
chmod($fileName, 0664);
```

**Comment by alcaeus** [comment]
We've had something similar before (#1495) but haven't quite managed to get to the bottom of this. If my memory serves me right, this happens when you first rename a file or folder that was copied to the container, as that translates to a cross-device rename (Docker transparently writes changes to its file system to a separate file system to avoid modifying the original). I've created a gist that tries to show the problem: https://gist.github.com/alcaeus/a367e895e6c55f7fb93870dcba46efa9

If you could share your Dockerfile, I'd be happy to try and see what's going on and if there's anything we can/should fix on our end.

**Comment by mikaelmattsson** [comment]
The dockerfile looks like this:
```Dockerfile
FROM php:7.1-fpm

# Install modules
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        libssl-dev \
    && pecl install mongodb \
    && echo "extension=mongodb.so" > /usr/local/etc/php/conf.d/ext-mongodb.ini \
    && echo "upload_max_filesize = 5M" > /usr/local/etc/php/conf.d/upload.ini \
    && docker-php-ext-install iconv mcrypt mbstring exif zip \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer
```

And this is a part of our docker-compose.yml

```yml
  backend-php:
    build: ./docker/backend/php-fpm
    working_dir: /var/www
    links:
      - mongodb
      - mongodb-test
    volumes:
      - ./backend:/var/www:cached
      - ./data/logs/backend-php:/logs:cached
```

Note that you will need the latest edge version of docker for the consistency flag to work.

I cant really share more about our set up.

Btw, the problem only seem to occur when two requests are run close to each other.

I will try at a later time to set the doctrine hibernation cache dir to be a directory outside the mounted scope.

**Comment by alcaeus** [comment]
Thanks for the update. If I interpret your code correctly, you mount the code (and thus the cache folder) into the docker container as a shared folder, correct? I'm not sure how that plays out, we copy our code into the docker image, leaving the creation of the cache folders to the software when it's run. That way, it's only created inside each container and not shared between containers.

> I will try at a later time to set the doctrine hibernation cache dir to be a directory outside the mounted scope.

I suspect (and hope) this would fix your issues - please let me know if it works.

**Comment by alcaeus** [comment]
Closed due to lack of feedback - this is also not an issue with Doctrine but rather your environment.

**Comment by zaerl** [comment]
I know that this issue has been closed 2 years ago but I leave a comment for all the visitors with the same problem. I can confirm that this error only happens when the cache folder is inside a docker shared volume.
