### ISSUE TITLE
Versioning and locking documentation

### ISSUE THREAD

**Issue by bmichalski** [doctrine/mongodb-odm#1585]
I was looking for the YAML equivalent of the `@Version` annotation, but could not find it in the documentation (http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/yml-mapping.html).

It looks like it's already supported by both the YAML and XML drivers (see https://github.com/doctrine/mongodb-odm/blob/master/tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php which is extended by both the YAML and the XML test suites).

It does not appear in the documentation.

I'm trying to write the missing documentation and have a few questions about it:

* __About versioning__:
The current `@Version` annotation documentation (http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/annotations-reference.html#version) states:
  > The annotated instance variable will be used to store version information, which is used for pessimistic and optimistic locking

  How is the `version` field used for pessimistic locking?

  My understanding is that the `version` field is used for optimistic locking to store the version of the document, but I could not find where it is in use, or required, for pessimistic locking.
 
  Do we need to enable versioning to be able to use pessimistic locking?

* __About locking__:
  The `@Version` annotation documentation states that it cannot be used on the id property.
  
  Can the `@Lock` annotation be used with the id property?

* __Combining both__:
  Can both annotations be used on the same document?

  Can both annotations can be used on the same field? (I'm pretty sure we should not do this.)

* __Regarding Pessimistic Locking__:
   Should we add a warning regarding potential deadlocks?

**Comment by alcaeus** [comment]
Thanks for taking care of the documentation. Here are some answer to your questions, mostly from looking at the code since I haven't dealt with locking at all so far.

> My understanding is that the version field is used for optimistic locking to store the version of the document, but I could not find where it is in use, or required, for pessimistic locking.

You are correct. The `version` field is used for optimistic locking, the `lock` field for pessimistic locking.

> Do we need to enable versioning to be able to use pessimistic locking?

From what the code tells me, no.

> The `@Version` annotation documentation states that it cannot be used on the id property.

The only checks I could find are whether the property is an `int` or `date` - the mapping class throws an exception if this isn't the case. While this may imply that you could use it on an ID field, it really makes no sense as the ID field is supposed to be immutable, while the lock and version fields are designed to be changed continuously. I've made a note to investigate this. This also answers your next question:

> Can the `@Lock` annotation be used with the id property?

No.

> Can both annotations be used on the same document?

A quick look says "yes", e.g. in the `update` method in `DocumentPersister`. I'm not sure why you would want to use both at the same time, but there are no checks to forbid one when the other is enabled.

> Can both annotations can be used on the same field? (I'm pretty sure we should not do this.)

There is no check for this, but (as you mentioned) this shouldn't be possible. I've made a note to check this out as well.

> Should we add a warning regarding potential deadlocks?

Warnings about deadlocks are always good when dealing with locks 😉 

Again, thanks for taking the time to improve the documentation! I'll check the points mentioned above and get back to you once I know more.

**Comment by malarzm** [comment]
I can only add that http://doctrine-orm.readthedocs.io/en/latest/reference/transactions-and-concurrency.html#locking-support should be good source of knowledge (and maybe even good starting point for our chapter on locking?) :)

**Comment by bmichalski** [comment]
@alcaeus I have updated the versioning doc (in PR #1586) according to your answer.

As for the deadlocks I mentioned, I was thinking about the case when your script dies before releasing its lock, causing other scripts to either wait indefinitely for the lock or throw an exception.

So not a deadlock in the sense of a process P1 waiting for a resource R1 possessed by a process P2 waiting for a resource R2 possessed by process P1.

In this case I think a correct expression would be "stale lock", which have happened to me quite a few times.

But I guess I can also add a word about deadlocks.
Come to think of it, I can figure cases where PHP requests would wait for each other to release locks, effectively creating a deadlock situation.

I'm working on an update for #1587.

**Comment by alcaeus** [comment]
> As for the deadlocks I mentioned, I was thinking about the case when your script dies before releasing its lock, causing other scripts to either wait indefinitely for the lock or throw an exception.

Oh, yes. Please include that as well - I didn't even think of that possibility. "Stale lock" is an excellent wording for this case 👍

**Comment by bmichalski** [comment]
I have updated #1587 with a small warning about stale locks and deadlocks.
Can you think of things that should be added to #1586 and #1587 before its merged?

**Comment by alcaeus** [comment]
Sorry for the long time without updates. To summarize, I'd let another person proofread your pull requests one more time.
I would like to take this opportunity to thank you for writing the documentation - especially as your first contribution to the project. Cheers! 🍻

**Comment by bmichalski** [comment]
My pleasure :)
I'd like to continue improving this great project, is there a prioritized list of things to do, or should I just look at the issues and pick some?

**Comment by malarzm** [comment]
@bmichalski if you're willing to continue on improving documentation we have quite few issues labelled with [documentation](https://github.com/doctrine/mongodb-odm/labels/documentation) (and the list is far from being complete). If you'd like to do some coding then I believe we don't have any prioritized list prepared, best will be just taking something from the issues backlog or getting hold of me or @alcaeus in the #doctrine channel on freenode (IRC) ;)

**Comment by malarzm** [comment]
Closing since related PRs were merged
