### ISSUE TITLE
Increment doesnt incremet

### ISSUE THREAD

**Issue by santaatnas** [doctrine/mongodb-odm#1591]
Hello, i'm, trying to increment the field, and get no results;

Here is my code:

```
class Query
{
    /**
     * @ODM\Id
     */
    protected $id;

    /**
     * @ODM\Field(type="int", strategy="increment")
     *
     */
    protected $my_id = 0;

    public function incrementMyId()
    {
        $this->my_id++;
    }
}
```

When in action i try:

` $query = new Query();
 $query->incrementMyId();
$this->documentManager->persist($query);
$this->documentManager->flush();`

The field my_id is always equals to int(1);`
Can u help me with this issue? Thanks.

**Comment by malarzm** [comment]
Asking [question](http://stackoverflow.com/questions/43979320/odm-mongodb-autoincrement-doesnt-work) on StackOverflow is sufficient as this is usage issue, closing this one
