### ISSUE TITLE
simple=true and storeAs="id" are not equivalent in the hydrator!

### ISSUE THREAD

**Issue by Bilge** [doctrine/mongodb-odm#1595]
This structure involves four documents: a GridFS document with a collection of embedded documents each referencing one other GridFS document. Both GridFS documents inherit from an abstract base as shown below. 

```php
/** @MappedSuperclass */
class Base {
        /** @Id */
        private $id;

        /** @File */
        private $file;
}

/** @Document */
class A extends Base {
        /** @EmbedMany(targetDocument="B") */
        private $bs = [];
}

/** @EmbeddedDocument */
class B {
        /**
         * Stored as ObjectId!
         * @a\ReferenceOne(targetDocument="C", storeAs="dbref", cascade="all")
         */
        private $c;
}

/** @Document */
class C extends Base {
        /**
         * Also stored as ObjectId!
         * @ReferenceOne(targetDocument="A", simple=true)
         */
        private $a;
}
```

In this structure there are two `ReferenceOne` associations, each pointing to a GridFS document and both are persisted as `ObjectIds` instead of `DBRef`. Curiously, if one changes `simple=true` and `storeAs="dbRef"` to `storeAs="id"` the code works completely fine, and has done for years, by using an ObjectId to look up a foreign identifier. This bug was only discovered since upgrading a very old version of ODM. It seems as if ODM has always referenced foreign GridFS documents by `ObjectId` instead of `DBRef` but nobody ever noticed.

The bug reveals itself when trying to load existing documents and the hydrator tries to dereference a property of `DBRef` that does not exist on an `ObjectId` as shown below.

>Fatal error: Cannot use object of type MongoId as array in BHydrator.php on line 52

That part of the hydrator code looks like the following.

```php
        /** @ReferenceOne */
        if (isset($data['c'])) {
            $reference = $data['c'];
            if (isset($this->class->fieldMappings['c']['storeAs']) && $this->class->fieldMappings['c']['storeAs'] === ClassMetadataInfo::REFERENCE_STORE_AS_ID) {
                $className = $this->class->fieldMappings['c']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['c'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['c']->setValue($document, $return);
            $hydratedData['c'] = $return;
        }
```

Line 52 is `$mongoId = $reference['$id'];`.

It seems references to GridFS documents are always stored as `ObjectId` instead of `DBRef`, which breaks the hydrator unless `storeAs=id` is set.

**Comment by malarzm** [comment]
Thanks for detailed report @Bilge! Will try to have a closer look tomorrow

**Comment by Bilge** [comment]
❤️

**Comment by malarzm** [comment]
I started putting a test case for this but then I realized it's not really possible (if I understand the issue correctly)... so instead @Bilge few question if I may:

> This bug was only discovered since upgrading a very old version of ODM.

Do you recall how old the version was? As a starter I took a look at BETA1 and I must say it looks very different internally :D So if we could pinpoint the version I should dig through, that'd be great.

> `@ReferenceOne(targetDocument="C", storeAs="dbref", cascade="all")` (from class `B`)

`storeAs` is relatively new so just to make sure, previously there was no `simple=true` in the mapping so the reference was supposed to be full blown `DBRef`, right?

**Comment by Bilge** [comment]
I don't see what relevance the original version is, I'm using the current version now. I changed `simple=true` to `storeAs="dbref"` just to show that the problem still occurs using that new attribute, but it's exactly the same issue specifying `simple=true`, they're completely analogous.

**Comment by malarzm** [comment]
> I don't see what relevance the original version is, I'm using the current version now.

Ah, I thought it could be some archaic version of ODM that ignored what type of reference was specified in the mapping. Given it's not it'll be way easier.

So previously you had `@ReferenceOne(targetDocument="C", simple=true, cascade="all")` or without `simple=true` part?

**Comment by Bilge** [comment]
With.

**Comment by malarzm** [comment]
You know that `storeAs="id"` is the new `simple=true`?

**Comment by Bilge** [comment]
So I'm told. Previously I was under the impression it was equivalent to `storeAs="dbRef"`, but right or wrong, it doesn't change the fact that it's storing the reference as an `ObjectId`, which is completely wrong.

**Comment by malarzm** [comment]
> it doesn't change the fact that it's storing the reference as an ObjectId, which is completely wrong.

If it's about storing then you're absolutelly right but I can't see how that could happen (taking a look [here](https://github.com/doctrine/mongodb-odm/blob/b5d0c89cd63b3e05f58071c1025f7b776fcaa157/lib/Doctrine/ODM/MongoDB/DocumentManager.php#L678)). If it's about reading old data (saved with the `simple=true` that you had in place before) it has all rights to fail now with different type of reference specified.

**Comment by Bilge** [comment]
Not only does it continue to read old data by replacing `simple=true` with `storeAs=id` but it also continues to write new documents in the same way.

**Comment by malarzm** [comment]
That's good, those two mean exactly the same, [as per documentation](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/reference-mapping.html#storing-references):

> The storeAs=id option used to be called a “simple reference”. The old syntax is still recognized (so using simple=true will imply storeAs=id).

If you change it to anything else you also need to adjust data you have stored already.

**Comment by Bilge** [comment]
Evidently they don't mean exactly the same thing to the hydrator because the change was necessary to avoid the fatal error described in the original post. We need the hydrator to follow this code path:

```php
if (isset($this->class->fieldMappings['c']['storeAs']) && $this->class->fieldMappings['c']['storeAs'] === ClassMetadataInfo::REFERENCE_STORE_AS_ID) {
```

This does not happen if `simple=true` is specified instead.

**Comment by malarzm** [comment]
In original post you have `@a\ReferenceOne(targetDocument="C", storeAs="dbref", cascade="all")` - the `storeAs` is set to `"dbref"`, not `"id"`

**Comment by Bilge** [comment]
Yes, and that will reproduce the hydrator fatal error. If you want to see it "work" with `ObjectIds` you would need to change it to `storeAs="id"`, as I have had to do for the time being.

**Comment by malarzm** [comment]
What I mean is now there are few contradictions. Originally you wrote:

> It seems as if ODM has always referenced foreign GridFS documents by ObjectId instead of DBRef but nobody ever noticed.

But then it turned that you had `simple=true` specified in the mapping before which sole purpose was to save references as plain identifier's value (so `ObjectID`). To recap, deprecated way:

`simple=true` -> `c: ObjectID("...")`
other reference (default) -> `c: { $ref: "coll", $id: ObjectId("..."), $db: "db" }`

current way

`storeAs="id"` ->  `c: ObjectID("...")`
`storeAs="dbRef"` -> `c: { $ref: "coll", $id: ObjectId("...") }`
`storeAs="dbRefWithDb"` (default) -> `c: { $ref: "coll", $id: ObjectId("..."), $db: "db" }`

I'm still

**Comment by Bilge** [comment]
Wait... you're saying `simple=true` and `storeAs="id"` are *supposed* to store `ObjectId`? 🤔 

For some reason, I thought that they were supposed to just store a plain string ID, e.g. 

`storeAs="id"` -> `c: 'foo'`

**Comment by Bilge** [comment]
Nevertheless, even with my tragic misunderstanding, the fact remains that in this scenario `simple=true` and `storeAs="id"` are **not equivalent in the hydrator**, because one causes a fatal error whilst the other does not.

**Comment by malarzm** [comment]
One issue down, yay! As to the other one I can't find a test wrote specifically for transorming `simple=true` to `storeAs="id"` (which happens [here](https://github.com/doctrine/mongodb-odm/blob/b5d0c89cd63b3e05f58071c1025f7b776fcaa157/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php#L1309-L1316)) but I see we still have some `simple=true` scattered in tests so hopefully this is a glitch somewhere... Let me get back to you tomorrow as I need to get some sleep :)

**Comment by Bilge** [comment]
❤️

**Comment by alcaeus** [comment]
> Wait... you're saying `simple=true` and `storeAs="id"` are supposed to store ObjectId? 

To be precise, the difference between `dbRef` and `id` is that one stores a `DBRef` object in the database with the `$id` field set to the identifier of the referenced object. The other stores the identifier directly in the field. In both cases the identifier is stored with exactly the same type as it was declared (mostly `ObjectId`). If you use an int as an identifier, the reference stores an int.

**Comment by amcsi** [comment]
Not sure if it helps, but simple=true is deprecated

https://github.com/Nilz11/mongodb-odm/blob/master/docs/en/reference/annotations-reference.rst#referencemany

> simple - deprecated (use `storeAs: id`)

**Comment by malarzm** [comment]
@amcsi that's true, however it should still work :)

**Comment by malarzm** [comment]
@Bilge if I'm not mistaken, the glitch is not on our side, this test is passing:

```
<?php

namespace Doctrine\ODM\MongoDB\Tests\Functional\Ticket;

use Doctrine\ODM\MongoDB\Tests\BaseTest;
use Documents\Account;
use Documents\User;

class GH1595Test extends BaseTest
{
    public function testGo()
    {
        $user = new User();
        $account = new Account();
        $account->setName('Works');
        $user->setAccountSimple($account);
        $this->dm->persist($user);
        $this->dm->persist($account);
        $this->dm->flush();
        $this->dm->clear();

        $user = $this->dm->find(User::class, $user->getId());
        $this->assertInstanceOf(User::class, $user);
        $this->assertInstanceOf(Account::class, $user->getAccountSimple());
        $this->assertSame('Works', $user->getAccountSimple()->getName());
    }
}
```

the field's mapping is:

```
    /** @ODM\ReferenceOne(targetDocument="Account", simple=true, cascade={"all"}) */
    protected $accountSimple;
```

and in `Hydrator` I'm correctly seeing that the mapping has following properties specified:

```
  'simple' =>bool(true)
  'storeAs' =>string(2) "id"
```

Can you check if there's something odd happening on your side? Or make the test I've pasted fail?

**Comment by malarzm** [comment]
@Bilge any update on this?

**Comment by Bilge** [comment]
Not yet, sorry. I'd have to spend some time looking into it to compare my version to yours 😞

**Comment by alcaeus** [comment]
Closing since we can't reproduce it and for lack of feedback. @Bilge if you could provide a failing test case, feel free to reopen this.
