### ISSUE TITLE
ReferenceMany rendering NULL

### ISSUE THREAD

**Issue by mnguye08** [doctrine/mongodb-odm#1596]
Hi,

I'm using Symfony 3 with Doctrine MongoDB.
My issue is that when I create an object with ReferenceMany property, this object renders a NULL value in query result but it's ok in database.

**Property definition in entity**

```
/**
 * @MongoDB\ReferenceMany(targetDocument="Customer")
 */
private $customers = array();
```

**Query result**

`object(PlannerBundle\Document\Account)#782 (7) { ["id":protected]=> string(32) "3289c874c3793c81b50975488cedaec5" ["username":"PlannerBundle\Document\Account":private]=> string(4) "test" ["password":"PlannerBundle\Document\Account":private]=> NULL ["email":"PlannerBundle\Document\Account":private]=> string(4) "test" ["roles":"PlannerBundle\Document\Account":private]=> array(1) { [0]=> string(10) "ROLE_ADMIN" } ["customers":"PlannerBundle\Document\Account":private]=> NULL ["isActive":"PlannerBundle\Document\Account":private]=> bool(true) }`

**Directly with MongoDB command line**

```
> db.account.find()
{ "_id" : "3289c874c3793c81b50975488cedaec5", "username" : "test", "email" : "test", "roles" : [ "ROLE_ADMIN" ], "isActive" : true, "customers" : [ "583996a09dba3e62bfd96a73ab053549" ] }
```

Do you know why?
Thanks by advance for your help

**Comment by malarzm** [comment]
The issue most probably was with cache, for future reference please see this [SO answer](http://stackoverflow.com/a/43869685/5982920) for how to mitigate such problems.
