### ISSUE TITLE
ReferenceMany mapped by nested property of EmbedMany collection fails to be merged with ObjectManager

### ISSUE THREAD

**Issue by Bilge** [doctrine/mongodb-odm#1597]
How about this for an edge case.

I'm not sure the inheritance is relevant but I want to paint an honest picture of my structure for the avoidance of doubt.

```php
/** @MappedSuperclass */
abstract class Base {
        /** @ReferenceMany(targetDocument="B", mappedBy="cs.d" cascade="all") */
        private $bs = [];
}

/** @Document */
class A extends Base {
        /** @Id */
        private $id;
}

/** @Document */
class B {
        /** @Id */
        private $id;

        /** @EmbedMany(targetDocument="C") */
        private $cs = [];
}

/** @EmbeddedDocument */
class C {
        /** @ReferenceOne(
            inversedBy="bs",
            discriminatorMap={"f":"Foo", "b":"Bar"},
            discriminatorField="t"
        ) */
        private $d;
}
```

This structure works fine except in the following scenario:
1. An instance of `A` is fetched fetched from the `ObjectManager`.
2. `ObjectManager` is cleared.
3. `A` is merged back into the `ObjectManager`.

In this scenario the following error occurs:

>Undefined index: cs.d

>mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:1955
mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:2140
mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:1963
mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:1775
mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentManager.php:467

---

Note the discriminator classes are defined elsewhere and probably entirely irrelevant.

**Comment by alcaeus** [comment]
That's....interesting to say the least. I'll take a look later this week, but this looks like it needs some debugging to figure out. Thanks for the report!

**Comment by amcsi** [comment]
Not sure if it helps, but simple=true is deprecated

https://github.com/Nilz11/mongodb-odm/blob/master/docs/en/reference/annotations-reference.rst#referencemany

> simple - deprecated (use `storeAs: id`)

**Comment by alcaeus** [comment]
For the record, I haven't forgotten this issue, just had a few days off and unfortunately caught a nasty bug. I will debug this before the end of the week.

**Comment by Bilge** [comment]
Cool, thanks for the update @alcaeus and get well soon 👍

**Comment by alcaeus** [comment]
@Bilge Either I'm missing something, or there is something else involved. I tried reproducing your bug with the following test case: https://github.com/alcaeus/mongodb-odm/blob/gh-1597/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1597Test.php. Did I reproduce your scenario properly? Because it isn't failing over here...

**Comment by chefemaster** [comment]
I have the same problem.
My solution was to implement a field in the ReferenceMany class,  $notSaved, and assign the value 'true'.

English is not my mother tongue; please excuse any errors on my part.

**Comment by Bilge** [comment]
@alcaeus That doesn't look the same as the code I posted at all. The discriminator belongs to the field of `C`, not the base class. Furthermore, the field of `C` does not point to a target document. Maybe you think these are still equivalent, and maybe they are, I don't know.

Also I technically never call `clear()`; the clear happens implicitly between two dependent test cases. That is, one test depends on another, and PHPUnit clears down between the two tests. I believe calling `clear()` effectively emulates the same scenario in a single test case, though.

**Comment by alcaeus** [comment]
@bilge I changed the test to account for the missing `clear` and the discriminator, and it still passes. Since you apparently have a failing test, please post it here (or send it to me privately if you don't want to share it in an open setting). Thanks.

**Comment by alcaeus** [comment]
Closing since I can't reproduce it and for lack of feedback. @Bilge if you could produce a failing test case, feel free to reopen this issue. @chefemaster if you manage to reproduce this error in a minimal script, it would be much appreciated as well.
