### ISSUE TITLE
Add read-only option for document mappings

### ISSUE THREAD

**Issue by tux-rampage** [doctrine/mongodb-odm#1602]
Doctrine ORM allows to map a class as read-only. This ODM implementation does not support something like this.
It would be a great feature to mark document classes read-only to make sure their data is immutable.

**Comment by alcaeus** [comment]
There is a `NotSaved` annotation that you can use to ensure changes to fields are not written to the database. Is that what you're looking for, only at the document level instead of field level?

**Comment by malarzm** [comment]
@alcaeus IIRC ORM had `ReadOnly` as a class-level setting. Effectively this was allowing you to insert but never update (i.e. was omitting such documents when calculating change sets)

**Comment by malarzm** [comment]
@tux-rampage throwing this into `1.x` bucket so it won't be lost. PR from you will greatly speed things up!
