### ISSUE TITLE
Allow readPreference and readConcern on document-level

### ISSUE THREAD

**Issue by malarzm** [doctrine/mongodb-odm#1611]
This is a follow-up to #1610, as per @alcaeus' suggestion it might be feasible to add it to references as well.

**Comment by malarzm** [comment]
@alcaeus: Heads up as I've started working on this: turns out `readConcern` won't be supported in 1.2 as old driver doesn't have `MongoCollection::setReadConcern`

**Comment by jmikola** [comment]
Indeed, `ext-mongo` has no notion of a `readConcern` at all, nor the [`find`](https://docs.mongodb.com/manual/reference/command/find/) command that supports it.

**Comment by malarzm** [comment]
@alcaeus @jmikola I also assume we should allow a way to specify `readPreferenceTags` on a class level (and references later)?

**Comment by jmikola** [comment]
I assumed that any `readPreference` option would include both the read preference mode and tags, but I'll defer to @alcaeus.

**Comment by alcaeus** [comment]
I agree with @jmikola here - `readPreference` should always include `readPreferenceTags` as that's important tool for server selection when using secondary read preferences.

**Comment by malarzm** [comment]
You guys ok with separate fields for preference and tags? Also not sure how to allow specifying tags in a sane way in XML mappings :/

**Comment by jmikola** [comment]
> Also not sure how to allow specifying tags in a sane way in XML mappings :/

I believe it's already been done in DoctrinMongoDBBundle. See [`<xsd:element name="readPreferenceTags">`](https://github.com/doctrine/DoctrineMongoDBBundle/blob/74c3e1cc6d14a44707f8d162437a6454c0cbeff7/Resources/config/schema/mongodb-1.0.xsd#L59) and related entities.

I think a sensible structure in XML would be something like:

```xml
<readPreference mode="primary" />

<readPreference mode="secondaryPreferred">
    <tagSet>
        <tag name="use" value="reporting"> 
        <tag name="dc" value="east"> 
    </tagSet>
    <tagSet /> <!-- equivalent to: <tagSet></tagSet> -->
</readPreference>
```

**Comment by malarzm** [comment]
Good point indeed, I fixated too much on having read preference as an attribute :)
