### ISSUE TITLE
Aggregate function is not available

### ISSUE THREAD

**Issue by ketavc** [doctrine/mongodb-odm#1614]
Hi,
I want to find the SUM of column value using aggregate function.
I tried to use SUM function but it is not available.There are only three aggregate functions are available i.e. min, max and count. But SUM and AVG are missing.

Can you please help me how can i use SUM and AVG using createQueryBuilder function of Doctrine - MongoDB?

**Comment by malarzm** [comment]
Hi @ketavc! We keep "Issues" on GitHub for bug reports and other development activities around ODM. To get answers on how to use the ODM please post on [StackOverflow](https://stackoverflow.com/questions/tagged/doctrine-odm) and tag the question with "doctrine-odm".
