### ISSUE TITLE
prepareQueryOrNewObj adds an array index to criteria

### ISSUE THREAD

**Issue by CarlesKapy** [doctrine/mongodb-odm#1615]
I'm using a BsonFilter to add a criteria which queries DBRef to be in an array of id.

The queried document looks like this:

```
{
    "_id" : ObjectId("5959546a6811f5c438000033"),
    "name" : "Device Test Sub2",
    "mac" : "6B:50:51:86:34:8F",
    "state" : "active",
    "client" : {
        "$ref" : "Client",
        "$id" : ObjectId("5959546a6811f5c43800002b"),
        "$db" : "test_database"
    },
    "createdAt" : ISODate("2017-07-02T20:15:38.952Z"),
    "updatedAt" : ISODate("2017-07-02T20:15:38.952Z")
}
```

My BsonFilter returns a criteria that looks like this:
`['client'  => $_clientHierarchy]`

Where `$_clientHierarchy` is an array of MongoIds.

When the query is executed,  the generated criteria after being processed by `prepareQueryOrNewObj` method looks like this (`$preparedQuery`):

```
Array
(
    [0] => Array
        (
            [client] => Array
                (
                    [0] => MongoId Object
                        (
                            [$id] => 5959546a6811f5c438000029
                        )

                    [1] => MongoId Object
                        (
                            [$id] => 5959546a6811f5c43800002a
                        )

                    [2] => MongoId Object
                        (
                            [$id] => 5959fd966811f57018000029
                        )

                    [3] => MongoId Object
                        (
                            [$id] => 595a05426811f5701800002a
                        )
                )
        )
)
```

This query does not return the correct result. I guess the problem is the [0] index beacuse if I query a criteria without it, the returned value is correct.

I've also tested with different criterias like:
```
['client' => ['$id' => ['$in' => $_clientHierarchy]]]
['client.$id' => ['$in' => $_clientHierarchy]]]
```

What Am I doing wrong?

Thanks!

**Comment by alcaeus** [comment]
From the code i'd expect `['client.$id' => ['$in' => $_clientHierarchy]]`` to work. I know it works outside a BsonFilter. Could you share some code or maybe even create a [functional testcase](https://github.com/doctrine/mongodb-odm/tree/master/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket)?

**Comment by CarlesKapy** [comment]
Sorry guys, I was nesting the criteria inside an extra array in another place.

As @alcaeus said, it workds with criteria `['client.$id' => ['$in' => $_clientHierarchy]]]`.

Thanks
