### ISSUE TITLE
Mongodb driver native support

### ISSUE THREAD

**Issue by manuelbcd** [doctrine/mongodb-odm#1616]
Hi.  Sorry for repost.  Do we have any new on mongodb driver native support?

I'm doing well with alcaeus mongo-php-adapter but it's up to 10x times slower than direct connection (tested with legacy mongoc driver vs mongodb driver + alcaeus adapter).

I think we have a huge room for improvement if we could evolve this feature. I have been reading comments from 2015 but changelogs still do not announce anything about this functionality.

Thanks in advance.

WBR

**Comment by alcaeus** [comment]
We're working on it and are hoping to release ODM 2.0 this year.

**Comment by aftabnaveed** [comment]
@alcaeus is the master branch using the native driver? We are about to start working on the application just wondering if we should start with the master branch or not?

**Comment by alcaeus** [comment]
> is the master branch using the native driver

Yes.

> just wondering if we should start with the master branch or not

I don't recommend it: there's lots of breakage coming your way. While it uses the new driver, we're going to break a lot of BC and some things are still broken. Until the first beta, you really shouldn't trust it to actually store your data.

**Comment by aftabnaveed** [comment]
Do you know the estimated time when would the final version be released?

**Comment by alcaeus** [comment]
Unfortunately, no. We're working on it, but there are a few changes that still need work, mainly GridFS.
