### ISSUE TITLE
Aggregation builder: Add support for aggregation pipeline stages added in MongoDB 3.4

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1618]
See doctrine/mongodb#288, doctrine/mongodb#292 and doctrine/mongodb#293.

Main work required affects supporting `$graphLookup` in combination with simple references.

Also, merging #1566 would also allows us to use non-DBRef-references in `$lookup` and `$graphLookup` as well.

**Comment by allucardster** [comment]
Maybe it's not the place but I think is so cool this feature would be added to the project in the 1.2 release. Thanks a lot for all your efforts :+1:

**Comment by alcaeus** [comment]
It will. dev-master already supports most of the stages, the new ones added in 3.4 will definitely be part of the 1.2 release.

**Comment by alcaeus** [comment]
#1654 has been created - closing this issue.
