### ISSUE TITLE
How to load the date from mogndob with php timezone ? 

### ISSUE THREAD

**Issue by thibaultfalque** [doctrine/mongodb-odm#1625]
Hi, 
My php application use the "Europe/Paris" timezone so when I save an entity to mongodb the date is converted to UTC date. It's not problem. But if I load an entity with date the datetime loaded not use the timezone of PHP but the UTC and the date it's not correct because there is a time lag. 

So how to load the date from mongodb with the correct timezone ? 

I use Doctrine with Symfony 3 and the field="date" annotation.

**Comment by jmikola** [comment]
> date it's not correct because there is a time lag.

I assume "time lag" is referring to the natural difference between time zones, which causes [`DateTime::format()`](http://php.net/manual/en/datetime.format.php) to return an unexpected calendar day? In that case, you should be able to produce the expected calendar day by first calling [`DateTime::setTimeZone()`](http://php.net/manual/en/datetime.settimezone.php) to convert the DateTime back to your local time zone.

ODM's [DateType](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Types/DateType.php) does not support time zones, but I believe you could create a [custom mapping type](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/basic-mapping.html#custom-mapping-types) based on the date type that  calls [`date_default_timezone_get()`](http://php.net/manual/en/function.date-default-timezone-get.php) and applies the local time zone when converting the database value (`MongoDate`) to a PHP value (`DateTime`).

I'd have to defer to @malarzm and @alcaeus, but I don't believe we have any functionality to allow custom field types to take additional mapping parameters. Ideally, you would be able to annotate the field with a preferred time zone (or possibly the name of another field in the document that stores a string indicating the desired time zone) and have that be applied by the type wrapper. This idea likely constitutes a feature request.

**Comment by thibaultfalque** [comment]
So the idea is to create a new type where there is in the method closureToPhp similar to: 
$mongoDate->toDateTime()->setTimezone(new \DateTimeZone(date_default_timezone_get()))

(https://stackoverflow.com/a/42015911/6461660) 

The second idea is to create an annotation with the timezone and modify DateType for use this timezone ?

**Comment by jmikola** [comment]
> So the idea is to create a new type where there is in the method closureToPhp similar to

AFAIK, both `closureToPhp()` and `convertToPHPValue()` would need to be implemented.

> The second idea is to create an annotation with the timezone and modify DateType for use this timezone?

Correct. The second idea describes a potential new feature for ODM. The first idea (custom type) is possible to implement in your application with ODM's current functionality.

**Comment by thibaultfalque** [comment]
Ok at first time I implemented the first idea. 

I submit a pull request for this new feature of ODM if you do not mind. Do you any rules for contribute ? 

So for create the feature it's better to create a new [FieldType](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Mapping/Annotations/AbstractField.php) no ?  Else how add an attribute to a [Type](https://github.com/doctrine/mongodb-odm/blob/d728cc1e309475ed52f4cd9aa35208e699941f9e/lib/Doctrine/ODM/MongoDB/Types/Type.php). 

I open the discussions on this feature.

**Comment by malarzm** [comment]
I won't bet my head on this, but with default timezone set you should get `DateTime` objects with your time zone with ODM (or actually the underlying driver) converting it to/from UTC as data flies. At least I recall I faced issues after changing the default time zone :)

> I don't believe we have any functionality to allow custom field types to take additional mapping parameters. Ideally, you would be able to annotate the field with a preferred time zone (or possibly the name of another field in the document that stores a string indicating the desired time zone) and have that be applied by the type wrapper. This idea likely constitutes a feature request.

Unfortunately there is no way currently for type to consider any additional parameters as it doesn't know about field's mapping at all. Also this is not the first time such thing is needed (support for `DateTimeImmutable` as a parameter was one, custom collections for `collection` another) but I fail to recall what was the conclusion. Probably to defer it until 2.0 :)

> AFAIK, both closureToPhp() and convertToPHPValue() would need to be implemented.

1.2 will provide user with [`ClosureToPHP`](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Types/ClosureToPHP.php) trait so only `convertToPHPValue()` is really needed.

**Comment by jmikola** [comment]
> I submit a pull request for this new feature of ODM if you do not mind. Do you any rules for contribute ?

@thibaultfalque: I would suggest implementing the custom field type in your application and simply creating an issue for ODM to extend the existing `date` type to support additional options in ODM 2.0. I don't think it's worth submitting a PR for a new date type with timezones against the 1.x branch, since this is something already being considered for 2.0 (previously discussed in https://github.com/doctrine/mongodb-odm/issues/1453). If you do create a new issue requesting the feature, it would be helpful to link to #1453 in the description to keep them associated.

> I won't bet my head on this, but with default timezone set you should get DateTime objects with your time zone with ODM

@malarzm: That appears to be correct, based on the [`DateTime::__construct()`](http://php.net/manual/en/datetime.construct.php) documentation and how DateType constructs DateTime instances. To quote the PHP.net docs:

> If $timezone is omitted, the current timezone will be used.
>
> Note: The $timezone parameter and the current timezone are ignored when the $time parameter either is a UNIX timestamp (e.g. @946684800) or specifies a timezone (e.g. 2010-01-28T15:00:00+02:00).

**Comment by thibaultfalque** [comment]
I have add call of setTimezone in setter and constructor of my entity and it's works. So maybe it's possible to modify the date.timezone property of php.ini and in this case the timezone use by the DateTime constructor is correct.

**Comment by jmikola** [comment]
> I have add call of setTimezone in setter and constructor of my entity and it's works.

That may work for creating new entities or assigning a new DateTime on an existing entity, but I don't expect it handles the case of applying a local time zone from a DateTime value read from the database, which requires `convertToPHPValue()` in the ODM type class.

**Comment by malarzm** [comment]
Closing as there's no new activity and questions seems to be answered: set the default timezone in `php.ini` file.

**Comment by Warped-zaiden** [comment]
> Ok at first time I implemented the first idea.
> 
> I submit a pull request for this new feature of ODM if you do not mind. Do you any rules for contribute ?
> 
> So for create the feature it's better to create a new [FieldType](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Mapping/Annotations/AbstractField.php) no ? Else how add an attribute to a [Type](https://github.com/doctrine/mongodb-odm/blob/d728cc1e309475ed52f4cd9aa35208e699941f9e/lib/Doctrine/ODM/MongoDB/Types/Type.php).
> 
> I open the discussions on this feature.





https://phps.space/questions/updating-the-date-field-format-in-mongodb-using-php
