### ISSUE TITLE
Return results as array or JSON

### ISSUE THREAD

**Issue by psa-gbellencontre** [doctrine/mongodb-odm#1632]
Hello
I'm having trouble with the creation of a jSON API. 
I use the MongoDB ODM with Symfony, everything works fine, but I don't understand how to get results as an array (or directly in jSON) after a findAll query.

I get a cursor (I also tried with eagerCursor, but it doesn't solve my problem). 
And the only way I have to output an array, this is the cursor and a foreach.
But I have a large amount of data, and I'm not comfortable with this.
Doctrine MySQL ODM have some helpers methods (ex: getArrayResults), and I'm surprised MongoDB ODM not having any similar method.

Is there any other solution ?
Thanks for your answers.

**Comment by malarzm** [comment]
Cursor has a [`toArray()`](https://github.com/doctrine/mongodb-odm/blob/9b6b42d14ae72db8e3ce696cc81f6608844acd50/lib/Doctrine/ODM/MongoDB/Cursor.php#L639) method with which you will get an array.

Also next time please post usage questions on [StackOverflow with doctrine-odm tag](http://stackoverflow.com/questions/tagged/doctrine-odm).

**Comment by malarzm** [comment]
I think I have misread your question, if you want to omit the hydration and just get plain data from MongoDB you need to [disable hydration](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/query-builder-api.html#disabling-hydration).
