### ISSUE TITLE
Php notice for query builder / dbref query preparation: Undefined index: $db

### ISSUE THREAD

**Issue by Nilz11** [doctrine/mongodb-odm#1635]
If no target document is set and storeAs is set to "dbRef" the query builder will throw a PHP notice:

`Undefined index: $db`

when doing an equals with something like this, where $user is a document

`->field('user')->equals($user)`

Issue is that there is a bug in document persister `prepareDbRefElement` method:

`if ($mapping['storeAs'] === ClassMetadataInfo::REFERENCE_STORE_AS_ID) {`

should be

`if ($mapping['storeAs'] !== ClassMetadataInfo::REFERENCE_STORE_AS_DB_REF_WITH_DB) {`

**Comment by malarzm** [comment]
@Nilz11 thanks for submitting the issue! One question though, what is the value of `$mapping['storeAs']`? I believe that at this point it can be either `ClassMetadataInfo::REFERENCE_STORE_AS_ID` or `ClassMetadataInfo::REFERENCE_STORE_AS_DB_REF_WITH_DB` so both conditions should mean the same.

**Comment by Nilz11** [comment]
What about ClassMetadataInfo::REFERENCE_STORE_AS_DB_REF?

**Comment by malarzm** [comment]
Sorry, not sure what about that?

**Comment by Nilz11** [comment]
storeAs can be one of this three values. `ID` case works fine, `db-ref-with-db` works fine but `db-ref` not.

Why do you say that the `store-as` value can not be `db-ref`

**Comment by malarzm** [comment]
I'm sorry, you are correct, for some reason I thought about generating DBRef object, not preparing it.

**Comment by Nilz11** [comment]
Can add a test when I have time later

**Comment by alcaeus** [comment]
Closing since #1636 was merged.
