### ISSUE TITLE
Missing value with mapping type "hash" if key is empty

### ISSUE THREAD

**Issue by jarkt** [doctrine/mongodb-odm#1641]
The mapping type "hash" should store an associative array direct and without manipulation. But values with empty keys are not stored!

**Comment by malarzm** [comment]
@jarkt What does the insert/update query look like? Is it missing that key too? Could you please provide a failing test case? Offhand, empty key sounds a bit exotic :)

**Comment by jarkt** [comment]
I only modify a document and persist and flush it. How can I see the native query? I assume the key is missing there too, because mongodb itself has not a problem with empty keys.

In my case it's an array with error messages. The default message has no key. I don't think it's an exotic case.

**Comment by malarzm** [comment]
> How can I see the native query?

If you're using Symfony then it'll be available in the profiler, otherwise you'll need to set a logger (see [this](https://github.com/doctrine/mongodb-odm/blob/f7379e4eeaffcd33d83fb4b0fcc4ccce1acb8a4e/tests/Doctrine/ODM/MongoDB/Tests/Functional/AtomicSetTest.php#L34) test for an example)

**Comment by jarkt** [comment]
Oh, the empty key seems to be part of the query. This is the logger output:

    Array
    (
        [update] => 1
        [query] => Array
            (
                [_id] => MongoId Object
                    (
                        [objectID:MongoId:private] => MongoDB\BSON\ObjectID Object
                            (
                                [oid] => 59a98197d0a7e8013f2afac3
                            )
    
                    )
    
            )
    
        [newObj] => Array
            (
                [$set] => Array
                    (
                        [validatorErrors] => stdClass Object
                            (
                                [] => Value missing!
                                [min] => Value too short!
                                [max] => Value too long!
                            )
    
                    )
    
            )
    
        [options] => Array
            (
                [w] => majority
            )
    
        [db] => devdb
        [collection] => CategoryParameter
    )

**Comment by jarkt** [comment]
But it's not written to the database...?!

**Comment by malarzm** [comment]
It's not ODM's fault then as array is passed as-is (thus I'm removing `bug` label). What driver are you using?

**Comment by jarkt** [comment]
Doctrine\ORM\Mapping\Driver\AnnotationDriver

**Comment by malarzm** [comment]
No no, I mean PHP's driver for MongoDB - is it legacy `ext-mongo` or new `ext-mongodb` used together with Alcaeus' adapter?

**Comment by jarkt** [comment]
I've already wondered :)
"ext-mongodb" in combination with alcaeus/mongo-php-adapter (^1.0).

**Comment by malarzm** [comment]
In that case the best would be checking first if adapter is not losing the empty key while translating query. If it's not, then maybe it's the new driver that has a bug? cc @jmikola

**Comment by jarkt** [comment]
Seems to be a problem with the adapter. I've created a new pull request: https://github.com/alcaeus/mongo-php-adapter/pull/196
