### ISSUE TITLE
Compile Error: ... getProxyDefinition() Failed opening required ... __CG__AppBundleDocumentACCPermission.php

### ISSUE THREAD

**Issue by manuelbcd** [doctrine/mongodb-odm#1644]
Hi. I have a document that is not creating the proxy cache file. The whole "Proxy" folder is populated within "cache" with all proxies but only this file is not created.

`Error Message: Compile Error: Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition(): Failed opening required '/var/www/html/app/cache/dev/doctrine/odm/mongodb/Proxies/__CG__AppBundleDocumentACCPermission.php'
`

Do anybody have a clue about how to find out the problem?

Thanks in advance

**Comment by malarzm** [comment]
Try setting a breakpoint to see what's going wrong in the factory.

**Comment by manuelbcd** [comment]
Thanks @malarzm . Yes I did that and I discovered that the problem was mine. Database values was not consistent. But I have dealed with this problem several times and I'm wondering if we could improve the error output in order to point to the problem.  The actual "Failed to open..." is very generic.

Thank you for your help

**Comment by malarzm** [comment]
@manuelbcd I'm sure we can improve the error message, but I don't understand what the problem was :)

**Comment by manuelbcd** [comment]
The problem was DB inconsistency. Documents fields were not matching with the mapped exclussion groups.  With a backup of db it is working well. 
However doctrine error was pointing to a proxy file that never exists so in short doctrine is making you follow an incorrect clue when you want to fix the problem.

**Comment by malarzm** [comment]
> The problem was DB inconsistency. Documents fields were not matching with the mapped exclussion groups.

Sorry, but I don't see what goes wrong here, is it that you were trying to create a `Proxy` for an unmapped class? If so, then I think an exception from `ClassMetadataFactory` should be thrown already. Also, exclusion policy is not a concept from Doctrine but from some serializer I reckon?

**Comment by manuelbcd** [comment]
Sorry I meant DiscriminatorMap instead of exclussion, i mistaken the word. 
Thank you. If you think that it's correct then everything is ok.

Regards

**Comment by malarzm** [comment]
Ah unsupported discriminator values. Yes, they can be tricky, but due to BC we can't do much in 1.x as people can rely on the behaviour (e.g. incomplete discriminator map). We aim to improve the situation by being very strict on what is in the discriminator map and what comes from DB but we can only do that in 2.0 - https://github.com/doctrine/mongodb-odm/issues/563 is used to track the request. I think we can close this for now, if there's anything more please post/reopen :)
