### ISSUE TITLE
Missing Aggregation completely

### ISSUE THREAD

**Issue by mywebstuff** [doctrine/mongodb-odm#1651]
Hi!

For some reason my version of mongodb-odm is missing the complete Aggregation part. I mean I don't have the complete `Aggregation` directory, nor do I have the `createAggregationBuilder` function in the DocumentManager.php and DocumentRepository.php file.
Mongodb-odm was installed via composer, and composer tells me that I'm using the latest (1.1.6) version of the package.

Other details:
PHP version: 7.0.23
Framework: Symfony, with additional packages (doctrine/mongodb-odm-bundle v3.3)

**Comment by alcaeus** [comment]
Aggregation builder will be part of ODM 1.2 which will be released later this month. You'll have to use `dev-master` at your own risk if you want to use aggregation already.

**Comment by mjanos10** [comment]
Thank you @alcaeus! I was looking for the problem for like 2 days non-stop.

So what I should be doing is just change my composer.json file to this:
```
"require":{
  "doctrine/mongodb-odm": "dev-master",
}
```
And then run a `composer update` right?
Thanks for your help :)

**Comment by alcaeus** [comment]
That's correct - switch to `dev-master`, update and please let us know in the issue tracker of any issues you find. And don't forget switching back to `^1.2` once it's released because we'll break stuff afterwards ;)

**Comment by mywebstuff** [comment]
Thank you @alcaeus, you're the best! :)

**Comment by mywebstuff** [comment]
Tested and it works fine :) Thanks again for the help!
