### ISSUE TITLE
Aggregation query and Expr addor and addand

### ISSUE THREAD

**Issue by AizeLeOuf** [doctrine/mongodb-odm#1653]
Hi,

Can't find a way to do this working query in Mongo shell using this bundle :

db.Job.aggregate([{ $match: {$or: [{ username: "test" }, { username: "root" }]} }]);

```
use Doctrine\MongoDB\Aggregation\Builder;
$qBuilder = new Builder($this->getDocumentManager()->getDocumentCollection($this->getClassName()));

$qBuilder->match()->addOr($qBuilder->expr()->field('username')->equals('test'));
$qBuilder->match()->addOr($qBuilder->expr()->field('username')->equals('root'));
$qBuilder->execute();
```

This code create a query
db.Job.aggregate([{ $match: {$or: [{ username: "test" }]} },{ $match: {$or: [{ username: "root" }]} }]);

I want to support logical operator in an aggregation builder (mandatory for group and project features) with standard query builder it's works using $qBuilder->addAnd($qBuilder->expr()->field('username')->equals('test'));

Try this other possibility without success :'(
```
        $code = $qBuilder->matchExpr();
        $code->field('username')->equals('test');
        $codeB = $qBuilder->matchExpr();
        $codeB->field('username')->equals('root');

        $qBuilder->match()->addOr(array($code,$codeB));
```

Any help please ? Can't find example to solve my issue :s

**Comment by alcaeus** [comment]
```
$builder = new Builder(...);
$builder
    ->match()
        ->addOr($builder->expr()->field('username')->equals('test'))
        ->addOr($builder->expr()->field('username')->equals('root'))
;
```

Or even simpler:
```
$builder
   ->match()
        ->field('username')
        ->in(['test', 'root'])
;
```

As for your last example, would've worked if you had not passed an array, but individual arguments: `$qBuilder->match()->addOr($code, $codeB)`

Of all those possible solutions, I'd always use the variant using `$in`.

**Comment by alcaeus** [comment]
Noticed a major mistake only while re-reading my reply now: when creating an expression for a `match` stage, you have to use `$builder->matchExpr()` instead of `$builder->expr()` - the latter one creates an expression object for aggregation operators which have a different syntax. The first example should thus read:
```
$builder = new Builder(...);
$builder
    ->match()
        ->addOr($builder->matchExpr()->field('username')->equals('test'))
        ->addOr($builder->matchExpr()->field('username')->equals('root'))
;
```

**Comment by AizeLeOuf** [comment]
Nice one !!!! thanks it's works :)

Now if you need to mix addOr and AddAnd with precedence priority on MongoDB (3.2 aka without facet) can you support this feature with matchExpr()/addOr and addAnd ? any idea to address this issue without doing a subquery for each operand: 

> A and B and C or D

 means (A and B) then ("A and B result" and C) and so on...

**Comment by alcaeus** [comment]
> A and B and C or D

IIRC, this should be `(A and B and C) or D` - which can be done easily by doing:
```$builder->match()
    ->addOr(
        $builder->matchExpr()->addAnd($a)->addAnd($b)->addAnd($c),
        $d
    )
;
```

with each variable being its own sub expression. Other combinations can be done accordingly, but I haven't used these very often.

Also note that the following two are identical:
```
$builder->match()
    ->field('foo')
    ->equals('bar')
    ->field('bar')
    ->equals('baz')
;
$builder->match()
    ->addAnd(
        $builder->matchExpr()->field('foo')->equals('bar'),
        $builder->matchExpr()->field('bar')->equals('baz')
    )
;
```
