### ISSUE TITLE
UnitOfWork and spl_object_hash uniqueness

### ISSUE THREAD

**Issue by mmucklo** [doctrine/mongodb-odm#1655]
UnitOfWork relies on spl_object_hash being unique.  However if an object gets destroyed (garbage collected), a new object can receive the same spl_object_hash.

http://php.net/manual/en/function.spl-object-hash.php

I'm seeing a case where an object has been recycled, but the $documentStates map inside of lib/Doctrine/ODM/MongoDB/UnitOfWork.php still contains a reference to that object.

So when a new object is created and attempted to be saved, UnitOfWork thinks it's not new, causing quite the problem...

**Comment by malarzm** [comment]
@mmucklo any chance you could provide a failing test case? Theory is, that `UnitOfWork` keeps reference to each managed document (embedded documents included) which effectively will prevent that object to be picked by a garbage collector. If there is a scenario that doesn't clean everything it should, we should fix that.

**Comment by mmucklo** [comment]
I was seeing the issue break some of my phpunit test cases.  I've since worked around it bit calling ->clear() on the DocumentManager...
