### ISSUE TITLE
Support Symfony 4

### ISSUE THREAD

**Issue by MatTheCat** [doctrine/mongodb-odm#1662]
Currently this package requires `"symfony/console": "~2.3|~3.0"` which prevent using `doctrine/mongodb-odm-bundle` with Symfony 4.

**Comment by alcaeus** [comment]
#1663 changes this and will be included in the upcoming 1.1.7 and 1.2.0 releases. Note that the bundle is a different story, that will take a few days/weeks depending on how much time I can spend on it.

**Comment by MatTheCat** [comment]
Nice! Seems the bundle added Symfony 4 with its 3.4 version though?

**Comment by alcaeus** [comment]
You are correct. Such is the state of my time for the bundle :(
