### ISSUE TITLE
How to execute cursor.forEach() method

### ISSUE THREAD

**Issue by josefsabl** [doctrine/mongodb-odm#1683]
I need to execute [this](https://docs.mongodb.com/manual/reference/method/cursor.forEach/) method on some find() query but didn't find how to do it.

Is there a way to do something like that?

[This](https://stackoverflow.com/questions/47639191/move-an-embedded-object-from-one-array-field-to-another-in-doctrine-odm) is my use case.

**Comment by alcaeus** [comment]
What you linked is the documentation for the `mongo` shell. Running `cursor.forEach` there is the same as iterating over the results of a `findBy` call in a repository.

**Comment by josefsabl** [comment]
Oh, I see now. Thanks.
