### ISSUE TITLE
References not loaded for new/merged documents

### ISSUE THREAD

**Issue by araines** [doctrine/mongodb-odm#1689]
I'm experiencing a little trouble with references at the moment, and I'm not sure exactly what the issue is.

I'm trying to deserialize some data in to a `Schedule` object which already has an associated `Race` document stored which is accessible by a repository method.  Unfortunately, unless I `flush` and `refresh` the `Schedule`, the `referenceOne` to the `Race` never resolves.

Here is a simplified version of the problem I'm having:

```
class Schedule
{
    /**
     * @MongoDB\ReferenceOne(targetDocument="Race", mappedBy="schedule", repositoryMethod="findResults")
     */
    private $race;

    public function getRace()
    {
        return $this->race;
    }
}
```

```
// Persisting a new document
$schedule = $serializer->deserialize($data);
$this->dm->persist($schedule);
$schedule->getRace(); // null

// Merge with an existing document
$schedule = $serializer->deserialize($data);
$schedule = $this->dm->merge($schedule);
$schedule->getRace(); // null

// Must flush and refresh in order to actually make the reference work
$schedule = $serializer->deserialize($data);
$this->dm->persist($schedule);
$this->dm->flush();
$this->dm->refresh($schedule);
$schedule->getRace(); // Race
```

I would expect that each time I attempt to `getRace` it would give me the `Race` document from Mongo as it is now operating on a managed document?

This is pretty problematic as I need to be able to follow those inverse relationships prior to flushing the changes to the database.  Am I doing something wrong?  Is there a way to force those relationships to be restored on an unflushed document?

**Comment by alcaeus** [comment]
The interesting part is `$serializer->deserialize($data)`: what does it set for whatever property is returned in `$schedule->getRace()`? If it's `null`, it will override whatever else was loaded from the database, as it assumes you want to unset it: https://github.com/doctrine/mongodb-odm/blob/858d656f0f5b768c4cb295b8c22fe30f40308199/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L1889..L1890.

**Comment by araines** [comment]
Thanks for the input.  I'm fairly certain it isn't setting that property at all, but I'll set about proving that to be sure.

However, that would only explain the `merge` operation not working - but would not explain the `persist` issue?  Also is something is not set then it will be `null` anyway - so I'm not sure how the UnitOfWork can tell the difference between a property which is `null` because it was never set to anything and a property which is `null` because it was set to `null`.

Perhaps I have misunderstood?

**Comment by araines** [comment]
I suppose another way of doing this would be to do:
```
$schedule = new Schedule();
$dm->persist($schedule);
$schedule->getRace(); // returns null - would like it to return the related Race document
```

Whilst I can appreciate the relationship hydration process may only occur when loading from the database, rather than also on persisting, is there a way to force that hydration process to reoccur?

**Comment by alcaeus** [comment]
It can't know whether it was never set or purposefully set to `null` - which is why it doesn't override the original value. The other option would be to use `null` from the document given to `merge`, which might be **really** undesirable.

As for your follow-up, there's no way for ORM to know your schedule object matches something in the database already. `persist` tells the UoW "I've got a new document for you to manage", not "look, this might or might not be in the database, so do what I want in this specific case, mkay?". There will always be use-cases where the logic we implement will not always work, you'll just have to solve this. One example would be fetching the document in question and serializing the data into the managed instance, instead of deserializing into a new object and trying to get it to merge up with the data already in the database.

**Comment by araines** [comment]
I completely understand, I was hoping there might be a simple way to retrigger the hydration process rather than serializing data directly in to the managed instance as whilst that works nicely for the simple example above, it is unfortunately not a great fit for our particular use-case.

Thanks for the help anyway.
