### ISSUE TITLE
[2.0] Document BC breaks and add deprecations in 1.3

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1696]
For every BC break we made in 2.0, there needs to be a deprecation warning and (if possible/sensible) a forward layer for people to prepare switching to ODM 2.0. This affects, but is not limited to BC breaks in #1553.

**Comment by malarzm** [comment]
FWIW I was using labels for PRs breaking BC: https://github.com/doctrine/mongodb-odm/issues?utf8=%E2%9C%93&q=label%3A%22BC+break%22+milestone%3A2.0.0

**Comment by alcaeus** [comment]
BC breaks have been documented in the `UPGRADE` document. Now we need to add BC layers (deprecations, possibly backports of new classes, etc.) in 1.3. All PRs that need this have been tagged with the [needs-1.3-compat-layer](https://github.com/doctrine/mongodb-odm/issues?utf8=✓&q=label%3Aneeds-1.3-compat-layer+) tag.

**Comment by alcaeus** [comment]
Closing as current BC breaks have been documented in 1.3.
