### ISSUE TITLE
[2.0] Clean up query options for inverse references

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1699]
In ODM 1.x, it's possible to specify both `repositoryMethod` and any of the `skip`, `limit` and `sort` options on an inverse reference. While the repository method is required to return a cursor, the legacy driver allowed applying custom options on the cursor before iteration started. With `ext-mongodb`, this is no longer possible.

The current proposal is to throw a `MappingException` if a `repositoryMethod` is combined with `sort`, `skip` or `limit`, but it may be more appropriate to pass these mapping options to the repository method and let the method decide how to handle them.

**Comment by malarzm** [comment]
As a started I think we should go with `MappingException` (and deprecation notice for 1.3). Later on given some time we may get back to passing additional parameters as a new feature.

**Comment by malarzm** [comment]
Closing as related PRs were submitted.
