### ISSUE TITLE
[2.0] Add PHPStan

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1701]
From the documentation: 
> [PHPStan](https://github.com/phpstan/phpstan) focuses on finding errors in your code without actually running it. It catches whole classes of bugs even before you write tests for the code.

**Comment by malarzm** [comment]
I was lately playing with PHPStan and running it against ODM was also on my list :+1:

**Comment by carusogabriel** [comment]
@alcaeus Can I PR it? :innocent:

**Comment by malarzm** [comment]
@carusogabriel feel free, I'm in the middle of setting up new computer (and seeing if I can run MongoDB on that funky linux in Windows 10 :P )

**Comment by carusogabriel** [comment]
As I'm new to PHPStan, just a question: by `[2.0] Add PHPStan` means require it in dev-dependencies and work on `phpstan.neon`?

**Comment by malarzm** [comment]
My roadmap was:

1. Add it to require-dev and configure if needed (can take a look at ORM)
2. Get to a decent (5?) level without errors (at least 1 commit per level to ease review)
3. Take a page from ORM's playbook and add PHPStan to travis

**Comment by alcaeus** [comment]
Level 1 and parts of level 2 added in #1714.

**Comment by carusogabriel** [comment]
@alcaeus @malarzm May we add https://github.com/phpstan/phpstan-strict-rules or better to increase PHPStan level first?

**Comment by malarzm** [comment]
Problem with increasing levels is typehinting Common's metadata (as per interface) and expecting our own implementation. I'm :-1: for adding `if`s but maybe `assert` would be the way to go?

**Comment by carusogabriel** [comment]
Gonna try tonight to increase one more level :smile:

**Comment by malarzm** [comment]
Closing, we're on level 7 for now :)
