### ISSUE TITLE
Aggregation : Directly define the query in a Match stage or by MatchExpr 

### ISSUE THREAD

**Issue by Alsatian67** [doctrine/mongodb-odm#1741]
Seen by https://github.com/doctrine/mongodb-odm/issues/1653 , we can inject a matchExpr query to $builder->match()->addAnd(...) or $builder->match()->addOr(...).

This is also possible when we write the query manualy (array('$or'=>array(...)).

But how can we directly use a manualy written query or a matchExpr after $builder->match() or $builder->matchExpr() ?

Something like : 

`$builder->match()->query(array('$or'=>array(...))`

It it is not possible this is a feature request :)

**Comment by alcaeus** [comment]
If for whatever reason you want to do that, using `addAnd` and `addOr` allow you to inject arbitrary expressions. So, what you're looking for is `$builder->match()->addAnd(['$or' => ...]);`

Apart from that, I don't see a use-case for this: IMO there's no point combining query builder and native queries. Note that using arrays for queries disables features like type and name conversion that you may be relying on.

**Comment by Alsatian67** [comment]
Ok, thank you for the solution, I will put it directly in addAdd or addOr.

My use-case :

```
getResults(array $searchTerms)
{
    $builder = $this->dm->createAggregationBuilder(...);

    switch(count($searchTerms)){
        case 0; // No match stage
        break;
        case 1;
        // single match expression HERE
        break;
        default:
        $builder->match();
        
        foreach($searchTerms as $searchTerm){
            $builder->addAnd(...);
        }
    }

    // Then I need a builder because of the reste of the query :

    $builder->sort(...);

    // etc
}
```

**Comment by alcaeus** [comment]
Your `foreach` is incorrect: you need to tore the result of the `$builder->match()` stage as `$builder` is still an aggregation builder, not a match stage. Also, empty `$match` stages are removed during optimization by the server, as is a single epression in an `$and` stage if memory serves me right. Thus, you could simplify the `switch` to:

```
$match = $builder->match();
foreach ($searchTerms as $searchTerm) {
    $match->addAnd(...);
}

// Continue building the aggregation pipeline
$builder->sort();
```

Your example is lacking the reason why you need to add an array expression to a match stage.

**Comment by Alsatian67** [comment]
My` $searchTerm` is an `array('$or'=>array())` expression.

Thank you i solved my problem with your advices. Consider this issue closed.
