### ISSUE TITLE
EmbedMany fails when read from database

### ISSUE THREAD

**Issue by MrSpoocy** [doctrine/mongodb-odm#1765]
Version:
doctrine/mongodb-odm: current git version
mongodb/mongodb: 1.3
PHP: 7.1
OS: Mac OS

Simple construct: User, Link, Account.

After insert user, add Account and add Link (with Account) to the user, the db looks like:

```
{
    "_id" : ObjectId("5ab8fd7c30d2e54818402422"),
    "username" : "Manuel",
    "links" : [ 
        {
            "description" : "Link zum Account",
            "elements" : ObjectId("5ab9013630d2e5484817eec3"),
            "_doctrine_class_name" : "MongoTest\\Link"
        }
    ]
}
```

when i try to read the user, i got follow error `PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Doctrine\ODM\MongoDB\PersistentCollection::setMongoData() must be of the type array, object given, called in /MongoDBTest/Proxy/MongoTestUserHydrator.php on line 64 and defined in /MongoDBTest/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php:102`

[User.txt](https://github.com/doctrine/mongodb-odm/files/1850980/User.txt)
[Account.txt](https://github.com/doctrine/mongodb-odm/files/1850978/Account.txt)
[Link.txt](https://github.com/doctrine/mongodb-odm/files/1850979/Link.txt)
[MongoTestUserHydrator.txt](https://github.com/doctrine/mongodb-odm/files/1850987/MongoTestUserHydrator.txt)

**Comment by malarzm** [comment]
@MrSpoocy am I correct assuming that by "current git version" you mean `dev-master` branch? Can you please make a PR with failing test case?

**Comment by alcaeus** [comment]
@MrSpoocy can you please try to reproduce this issue? This might have happened in previous versions of dev-master but should no longer be the case with the current master (or 1.x for that matter).

**Comment by malarzm** [comment]
Closing as nothing happened here in 5 years 👼
