### ISSUE TITLE
 setRetryConnect is missing after update from 1.2.1 to 1.2.2 

### ISSUE THREAD

**Issue by pich** [doctrine/mongodb-odm#1768]
PHP 7.2.4
Symfony 4.0.6

In getDoctrineMongodb_Odm_DefaultConfigurationService.php line 39:

  [Symfony\Component\Debug\Exception\UndefinedMethodException]
  Attempted to call an undefined method named "setRetryConnect" of class "Doctrine\ODM\MongoDB\Configuration".

Exception trace:
 require() at /Users/user/Projects/someProject/var/cache/dev/ContainerH6nAxnZ/srcDevDebugProjectContainer.php:537
 ContainerH6nAxnZ\srcDevDebugProjectContainer->load() at /Users/user/Projects/someProject/var/cache/dev/ContainerH6nAxnZ/getDoctrineMongodb_Odm_DefaultConnectionService.php:12
 require() at /Users/user/Projects/someProject/var/cache/dev/ContainerH6nAxnZ/srcDevDebugProjectContainer.php:537
 ContainerH6nAxnZ\srcDevDebugProjectContainer->load() at /Users/user/Projects/someProject/var/cache/dev/ContainerH6nAxnZ/getDoctrineMongodb_Odm_DefaultDocumentManagerService.php:14
 require() at /Users/user/Projects/someProject/var/cache/dev/ContainerH6nAxnZ/srcDevDebugProjectContainer.php:537
 ContainerH6nAxnZ\srcDevDebugProjectContainer->load() at /Users/user/Projects/someProject/vendor/symfony/dependency-injection/Container.php:239
 Symfony\Component\DependencyInjection\Container->get() at /Users/user/Projects/someProject/vendor/symfony/doctrine-bridge/ManagerRegistry.php:35
 Symfony\Bridge\Doctrine\ManagerRegistry->getService() at /Users/user/Projects/someProject/vendor/doctrine/common/lib/Doctrine/Common/Persistence/AbstractManagerRegistry.php:231
 Doctrine\Common\Persistence\AbstractManagerRegistry->getManagers() at /Users/user/Projects/someProject/vendor/doctrine/mongodb-odm-bundle/CacheWarmer/PersistentCollectionCacheWarmer.php:63
 Doctrine\Bundle\MongoDBBundle\CacheWarmer\PersistentCollectionCacheWarmer->warmUp() at /Users/user/Projects/someProject/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:48
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /Users/user/Projects/someProject/vendor/symfony/http-kernel/Kernel.php:554
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /Users/user/Projects/someProject/vendor/symfony/http-kernel/Kernel.php:125
 Symfony\Component\HttpKernel\Kernel->boot() at /Users/user/Projects/someProject/vendor/symfony/http-kernel/Kernel.php:142
 Symfony\Component\HttpKernel\Kernel->reboot() at /Users/user/Projects/someProject/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:152
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /Users/user/Projects/someProject/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:113
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /Users/user/Projects/someProject/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /Users/user/Projects/someProject/vendor/symfony/console/Application.php:883
 Symfony\Component\Console\Application->doRunCommand() at /Users/user/Projects/someProject/vendor/symfony/framework-bundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /Users/user/Projects/someProject/vendor/symfony/console/Application.php:241
 Symfony\Component\Console\Application->doRun() at /Users/user/Projects/someProject/vendor/symfony/framework-bundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/user/Projects/someProject/vendor/symfony/console/Application.php:143
 Symfony\Component\Console\Application->run() at /Users/user/Projects/someProject/bin/console:39

PS. (donwngrade to 1.2.1 solve the problem)

**Comment by omarsoufiane** [comment]
same issue

**Comment by alcaeus** [comment]
I inadvertently tagged 1.2.2 from master yesterday. I have re-tagged it as 1.2.3 from the correct branch and am now working to remove the old tag. Apologies for the inconvenience.

**Comment by pich** [comment]
Andres, 1.2.3 works flawless.  :)
Thanks for fast response and fix. 
Great job!
