### ISSUE TITLE
ReferenceMany: get mthod returns PersistentCollection (PHP7.2)

### ISSUE THREAD

**Issue by etshy** [doctrine/mongodb-odm#1774]
HI
Like the title says, the get method of a ReferenceMany returns a PersistentCollection instead of an ArrayCollection, so it crash with PHP7.2 typehint.

Here is my code

```
    /**
     * @var ArrayCollection
     * @ODM\ReferenceMany(
     *     targetDocument="App\Model\Document\Chapter",
     *     mappedBy="series",
     *     strategy="addToSet"
     * )
     */
    protected $chapters;

    /**
     * @return ArrayCollection
     */
    public function getChapters(): ArrayCollection
    {
        return $this->chapters;
    }
```

`$chapters = $series->getChapters();`

and the error message I got : "Type error: Return value of App\Model\Document\Series::getChapters() must be an instance of Doctrine\Common\Collections\ArrayCollection, instance of Doctrine\ODM\MongoDB\PersistentCollection returned"

I don't know if it's a bug, if I missed something on the docs or if I just need to change the `@var ArrayCollection` to  `@var Collection` ? (and change the get typehint)

**Comment by alcaeus** [comment]
You need to typehint the Collection interface, not ArrayCollection for exactly the reason above.

**Comment by etshy** [comment]
Okay, thanks a lot.
Maybe add something on the doc for that ?
On docs, it only talk about ArrayCollection, it could be a bit confusing.

**Comment by jmikola** [comment]
I'm not sure where it would be best to advise using Collection this in the documentation, but if you find a particular place a PR would be appreciated (even if you're unsure) so we can continue the conversation and try to improve this for other users down the line.

**Comment by alcaeus** [comment]
I've created #1783 to track this: we should definitely update our code samples to use strict typing and parameter/return type hints, along with some explanation of internals (e.g. why ReferenceMany/EmbedMany are collections instead of arrays).
