### ISSUE TITLE
[2.0] Fix skipped tests

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1791]
As evidenced in the master build, there are a bunch of skipped tests: https://travis-ci.org/doctrine/mongodb-odm/jobs/376653436#L1607. Some of these relate to sharding support, others (e.g. SchemaManagerTest) needs to be refactored.

**Comment by caciobanu** [comment]
Wanted to give **$this->markTestSkipped('mongodb-driver: query logging does not exist');**  a try but not sure how to fix it. We should delete the tests or the feature has to be implemented ?

**Comment by alcaeus** [comment]
Update, there are now 3 tests that need fixing:
*  [`Doctrine\ODM\MongoDB\Tests\Functional\DocumentPersisterTest::testVersionIncrementOnUpdateSuccess`](https://github.com/doctrine/mongodb-odm/blob/4b59521bb4a16031b8b024008d88e118fc5cc5ec/tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php#L543)
* [`Doctrine\ODM\MongoDB\Tests\Functional\DocumentPersisterTest::testNoVersionIncrementOnUpdateFailure`](https://github.com/doctrine/mongodb-odm/blob/4b59521bb4a16031b8b024008d88e118fc5cc5ec/tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php#L569)
* [`Doctrine\ODM\MongoDB\Tests\Functional\ReferencePrimerTest::testPrimeReferencesInReferenceManyWithRepositoryMethodThrowsException`](https://github.com/doctrine/mongodb-odm/blob/4b59521bb4a16031b8b024008d88e118fc5cc5ec/tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php#L585)
