### ISSUE TITLE
[2.0] Drop namespace property from ClassMetadata

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1795]
https://github.com/doctrine/mongodb-odm/blob/8a98856ba14f5740054f49a83aedd6754a649d26/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php#L253

This involves all same-namespace name resolution magic, as used for `repositoryClassName` (and possibly other instances): https://github.com/doctrine/mongodb-odm/blob/8a98856ba14f5740054f49a83aedd6754a649d26/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php#L628

**Comment by malarzm** [comment]
Closing as #1812 was merged
