### ISSUE TITLE
Allow passing additional driver options

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1808]
Previously reported as https://github.com/alcaeus/mongo-php-adapter/issues/227. It looks like it's not currently possible to pass the `noCursorTimeout` to the driver when running a find query. This should be supported, along with any other options that were added to the new driver.

**Comment by malarzm** [comment]
If it's a matter of adding `noCursorTimeout` method to query builder I'd add it to 1.3

**Comment by alcaeus** [comment]
I'm not sure the legacy driver supports it - I'd have to check the source code or ask @jmikola.

**Comment by jmikola** [comment]
In the legacy driver, this can be expressed via the [`MongoCursor::immortal()`](http://php.net/manual/en/mongocursor.immortal.php) option.

This is not to be confused with [`MongoCursor::$timeout`](http://php.net/manual/en/class.mongocursor.php) and [`MongoCursor::timeout()`](http://php.net/manual/en/mongocursor.timeout.php), both of which are used for setting client-side socket timeouts, which could leave the operation running on the server.

Note that the `mongodb` extension doesn't implement cursor-level socket timeouts. It's `noCursorTimeout` option corresponds to the [`find` command option of the same name](https://docs.mongodb.com/manual/reference/command/find/) and can be used to control the lifetime of a cursor on the server.

**Comment by jmikola** [comment]
Note to self: the goal here is to support additional operation options (e.g. [`MongoDB\Collection::find()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-find/)) in the ODM query builder; however, we should refrain from dumping _all_ options into the already complex builder API.

**Comment by jmikola** [comment]
I think we can get away with adding `array_merge()` logic to https://github.com/doctrine/mongodb-odm/blob/485d84dc05401aea58db9d41335924475b50f7f1/lib/Doctrine/ODM/MongoDB/Query/Query.php#L415 as we do for other operation types. This would allow users to specify additional `find` options in the call to `getQuery()` instead of introducing new builder methods for each option.
