### ISSUE TITLE
Replace Doctrine\Common\Proxy with ocramius/proxy-manager

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1813]
As `Doctrine\Common\Proxy` is being deprecated for doctrine/common 2.9, we should use ocramius/proxy-manager for proxies in 2.0.

See https://github.com/doctrine/doctrine2/pull/6719 for the change in ORM.

**Comment by jmikola** [comment]
![](https://vignette.wikia.nocookie.net/mario-fanon/images/4/40/Mario_cape_running.gif/revision/latest?cb=20160305155015&path-prefix=es)
