### ISSUE TITLE
Combining Field and ReferenceOne annotations

### ISSUE THREAD

**Issue by romangetman** [doctrine/mongodb-odm#1816]
|    Q        |   A
|------------ | -----
| Version     | 1.2.4

I have the following class setup
```
class User
{
    /**
     * @MongoDB\Id
     */
    protected $id;

    /**
     * @MongoDB\ReferenceMany(
     *     sort={"created": "desc"},
     *     targetDocument="Account",
     *     mappedBy="user",
     *     strategy="set",
     *     storeAs="id"
     * )
     */
    protected $accounts = [];
}

class Account
{
    /**
     * @MongoDB\Id
     */
    protected $id;

    /**
     * @MongoDB\ReferenceOne(targetDocument="User", inversedBy="id", storeAs="id")
     */
    public $user;
}
```

The problem is that the field used to store the user id in the `Account` collection is called `uid`. If this was a regular field I'd just annotate it with `@MongoDB\Field(name="uid", type="id")`. 

But it seems it's not a valid option to combine the Field and ReferenceOne annotations. 

I thought changing `mappedBy="user"` to `mappedBy="uid"` would work. 

However it generates a bad query: 

`db.accounts.find({ "uid.$id": ObjectId() })` 
when I think it should be 
`db.accounts.find({ "uid": ObjectId() })`

since `storeAs="id"`.

What am I missing here?

**Comment by malarzm** [comment]
`ReferenceOne` is extending `AbstractField` which allows you to set `name` to set the field's name in the database. Also `inversedBy` parameter of the reference should point to the inverse collection, not id. To conclude your mapping should look like this:

```
    /**
     * @MongoDB\ReferenceOne(name="uid", targetDocument="User", inversedBy="accounts", storeAs="id")
     */
    public $user;
```

Next, given `accounts` are `ReferenceMany` with `mappedBy` means that this is inverse side of a reference thus it won't be stored in the document, you can get rid of `strategy` and `storeAs` settings there as they will have no effect.

**Comment by romangetman** [comment]
@malarzm this resolves all my issues, thanks.
