### ISSUE TITLE
UniqueIndex does not work in symfony 4

### ISSUE THREAD

**Issue by libressence** [doctrine/mongodb-odm#1818]
Some of annotations does not work in my documents 

`
/**

     * @var string
     * @ODM\Field(type="string")
     * @ODM\UniqueIndex
     * @Assert\NotBlank()
     */
    private $email;
`
`

     * @ODM\UniqueIndex
     * @Assert\NotBlank()
`
I can insert many  same email than i want and i have no mongodb error.
Field not blank does not work (Assert\NotBlank) with doctrine mongodb.

If you have any solution that will be great.
Thank

**Comment by malarzm** [comment]
For `UniqueIndex` to work you need to create indexes, please consult [this StackOverflow answer](https://stackoverflow.com/questions/41172585/index-not-created/41173619#41173619). The `Assert\NotBlank` is Symfony's annotation and its presence does not affect how ODM is working.

**Comment by libressence** [comment]
Ok @malarzm Thank !

**Comment by libressence** [comment]
So the only one solution for validate field empty is 
`    
     * @ODM\PrePersist
     * @ODM\PreUpdate
`

?

**Comment by malarzm** [comment]
That, or using Symfony's forms or requiring email to be present in `__construct` - there's plenty of ways :)

**Comment by libressence** [comment]
Ok thank @malarzm !
