### ISSUE TITLE
@UniqueIndex does not work

### ISSUE THREAD

**Issue by Espinasse** [doctrine/mongodb-odm#1833]
Try to create index on mongodb colleciton but annotation seem not working.

```
/**
 * @ODM\Document(collection="user", repositoryClass="App\Repository\UserRepository")
 * @ODM\HasLifecycleCallbacks
 */
class UserDocument implements UserInterface, \Serializable, DocumentInterface
{
    /**
     * @var string
     * @ODM\Field(type="string")
     * @ODM\UniqueIndex
     */
    private $username;
```

Symfony version : 4.1
composer.json :

```
        "alcaeus/mongo-php-adapter": "^1.1",
        "doctrine/mongodb-odm-bundle": "^3.0",
```

**Comment by Steveb-p** [comment]
How exactly do you attempt to create indexes? You're using a command to update the collection schema?

**Comment by Espinasse** [comment]
I, 
thank for you reply :)

May be a image can be more expressive.

![code](https://user-images.githubusercontent.com/37537389/43096006-ebda842a-8eb7-11e8-8fe2-44f63aabdc30.gif)

I just use annotation from Doctrine\ODM\MongoDB\Mapping\Annotations and try to make index by Document (above class definition) or above property class like $username for example.

**Comment by Espinasse** [comment]
Ha yes @Steveb-p thanks à lot :)
