### ISSUE TITLE
Support Decimal128 type

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1835]
See #1815: we want to support the Decimal128 type, converting values to strings for use with `bcmath`. This requires updating some operators and logic (e.g. when using `increment` strategy) to handle large decimal values.

**Comment by malarzm** [comment]
I've started working on this but I need to have https://github.com/doctrine/mongodb-odm/pull/2118 merged first as I'm sure I'll have conflicts.

**Comment by alcaeus** [comment]
Fixed in #2128.
