### ISSUE TITLE
[2.0] Update dependencies to supported versions

### ISSUE THREAD

**Issue by caciobanu** [doctrine/mongodb-odm#1843]
In composer.json some allowed versions of dependencies are not supported anymore; ex: symfony/console < 2.8. Maybe it is a good time to update the dependencies versions in composer.json ?

**Comment by malarzm** [comment]
Given support for 2.8 ends [in November](https://symfony.com/roadmap/2.8) I'm fine with bumping stuff to 3.4.

**Comment by caciobanu** [comment]
Should we up the rest of dependencies to their latest version also ?

**Comment by malarzm** [comment]
Yeah, I think why not. We can always lower them if needed

**Comment by malarzm** [comment]
Closing as #1845 was merged
