### ISSUE TITLE
Add pipeline to $lookup stage

### ISSUE THREAD

**Issue by Strick3r** [doctrine/mongodb-odm#1863]
|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

Mongo 3.6 add a pipeline lookup functionality that helps a lot in the futures developments, do you think that this feature can be added in a future veresion?

Thanks

**Comment by malarzm** [comment]
[`$lookup`](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2/reference/aggregation-builder.html#lookup) stage is already available in 1.2, what seems to be missing?

**Comment by Strick3r** [comment]
This is a new nice feature

New in version 3.6.

To perform uncorrelated subqueries between two collections as well as allow other join conditions besides a single equality match, the $lookup stage has the following syntax:

copycopied
{
   $lookup:
     {
       from: <collection to join>,
       let: { <var_1>: <expression>, …, <var_n>: <expression> },
       pipeline: [ <pipeline to execute on the collection to join> ],
       as: <output array field>
     }
}

**Comment by malarzm** [comment]
All right, thanks for clarification. I've put this into 2.x milestone. If you have some time it'd be great to see a PR!

**Comment by bluedogmilan** [comment]
Strongly needed!

**Comment by malarzm** [comment]
@bluedogmilan sending us a PR with implemented feature will greatly speed things up

**Comment by alcaeus** [comment]
@bluedogmilan furthermore, we’re holding all further features back to 2.1 to avoid introducing more complexity in 2.0. 2.1 will mainly focus on adding aggregation pipeline features from previous mongodb releases.

**Comment by bluedogmilan** [comment]
> @bluedogmilan sending us a PR with implemented feature will greatly speed things up

@malarzm Sorry for the newb question but I really do not know what PR stands for...

**Comment by Steveb-p** [comment]
I've taken a little time on it, since I'll probably need to use this functionality myself. Those two ways of handling `$lookup` are however really different and do not really mix & match.

Using one practically should disable another.

Is it acceptable to treat them as two separate classes with common ancestor? Or simply use some kind of flag to indicate which type of lookup is being used?

Should `pipeline` accept an instance of `Stage` / `Builder` like `Facet` does, or should it also allow to pass an array?

I've started by adding:
```php
public function let(array $let) : self
{
    $this->let = $let;
    return $this;
}

public function pipeline($pipeline) : self
{
    if (! is_array($pipeline) && ! $pipeline instanceof Expr) {
        throw new \InvalidArgumentException(__METHOD__ . ' expects either an aggregation builder or an aggregation stage.');
    }

    $this->pipeline = $pipeline;
    return $this;
}
```
methods and considering
```php
public function getExpression() : array
{
    if (isset($this->pipeline)) {
        $pipeline = $this->pipeline instanceof Expr ? $this->pipeline->getExpression() : $this->pipeline;
        return [
            '$lookup' => [
                'from' => $this->from,
                'let' => $this->let,
                'pipeline' => $pipeline,
                'as' => $this->as,
            ],
        ];
    } else {
        return [
            '$lookup' => [
                'from' => $this->from,
                'localField' => $this->localField,
                'foreignField' => $this->foreignField,
                'as' => $this->as,
            ],
        ];
    }
}
```

**Comment by emulienfou** [comment]
First of all, I made some changes on my fork here: https://github.com/emulienfou/mongodb-odm
It's a work in progress to add some tests.

**Comment by emulienfou** [comment]
However, I was able to make it work using an array in the `pipeline` key, such has:
```php
$builder->lookup('OnlineFestival')
    ->let(['festival' => '$fk_online_festivals'])
    ->pipeline(
        [
            [
                '$match' => [
                    '$expr' => [
                        '$and' => [
                            ['$in' => ['$_id', ['$ifNull' => ['$$festival', []]]]],
                            ['$eq' => ['$status', 'published']],
                            ['$gte' => ['$endAt', new UTCDateTime()]]
                        ]
                    ]
                ]
            ]
        ]
    )
    ->alias('online_festivals')
```

But using the query builder directly, seems to not working. I tested this kind of code:
```php
$builder->lookup('OnlineFestival')
    ->let(['festival' => '$fk_online_festivals'])
    ->pipeline([
        $builder->match()->addAnd(
            $builder->matchExpr()->in(['$_id', $builder->expr()->ifNull('$$festival', [])]),
            $builder->matchExpr()->equals(['$status', 'published']),
            $builder->matchExpr()->gte(['$endAt', new UTCDateTime()])
        )->getExpression()
    ])
    ->alias('online_festivals')
```
> This code seems to put the `$match` inside the lookup `pipeline`, but duplicate it in the root just after the lookup code

**Comment by buffcode** [comment]
@emulienfou 
> This code seems to put the `$match` inside the lookup `pipeline`, but duplicate it in the root just after the lookup code

This usually happens if you use the wrong expression variable.
First it seems to work, as you get the correct result as return, but the root builder will also append the same code.

Try using `$builder->expr()->addAnd(...)`

**Comment by emulienfou** [comment]
@buffcode seems not not working, I have the next error message: **Unrecognized pipeline stage name: '$and'**
If someone wants to work on this feature, feel free to open a PR my master branch is updated with this new feature.

**Comment by markitosgv** [comment]
How about this? It would be great to use pipeline on lookup stages

**Comment by nkanzari** [comment]
Hello everyone, is there any news about this one? I'm having trouble with lookup ignoring filters like soft delete.

**Comment by khaperets** [comment]
Hi everyone, is there any progress on this issue?

**Comment by khaperets** [comment]
Simple working example:
```php
class PipelineLookup extends \Doctrine\ODM\MongoDB\Aggregation\Stage\Lookup
{
    private array $pipeline = [];

    public function pipeline(array $pipeline): self
    {
        $this->pipeline = $pipeline;

        return $this;
    }

    public function getExpression(): array
    {
        $expression = parent::getExpression();

        if (false === empty($this->pipeline)) {
            $expression['$lookup']['pipeline'] = $this->pipeline;
        }

        return $expression;
    }
}
```
and in your code:
```php
$builder = $this->createAggregationBuilder();

$lookup = new PipelineLookup($builder, 'events', $this->dm, $this->class);
$lookup->pipeline([
    [
        '$match' => [
            '$expr' => [
                '$and' => [
                    ['$in' => ['$_id', ['$ifNull' => ['$$festival', []]]]],
                    ['$eq' => ['$status', 'published']],
                    ['$gte' => ['$endAt', new UTCDateTime()]]
                ]
            ]
        ]
    ]
]);

$builder->addStage($lookup);
```

**Comment by malarzm** [comment]
Please, do send PRs not questions or comments :)

**Comment by malarzm** [comment]
#2459 was merged manually, we can close this one 🎉
