### ISSUE TITLE
PersistentCollection instance lost raw data during serialization/deserialization process.

### ISSUE THREAD

**Issue by watari** [doctrine/mongodb-odm#1864]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 1.2.5

#### Summary

By default instance keep raw data from the database. So if you not accesses items from this collection before serialization, they will be not created from this raw data. This will cause lost of all data about items in collection during serialization/deserialization process. 
I solved this problem for itself by redefining PersistentCollection class - I added call of 'initialize' method in '_sleep'.

#### How to reproduce

1. Create instance of PersistentCollection with raw data.
2. Serialize instance.
3. Unserialize instance.
4. At this point data will be lost.

**Comment by malarzm** [comment]
Sorry this fell through the cracks, I'll close this issue to keep the conversation in one place since you've opened a PR :)
