### ISSUE TITLE
Support for fields in DocumentPersister

### ISSUE THREAD

**Issue by josefsabl** [doctrine/mongodb-odm#1865]
### Feature Request

As things stand it is impossible to select additional fields via a `DocumentRepository::findAll` method as DocumentPersister just does not pass `$fields` parameter in [collection->find](https://github.com/josefsabl/mongodb-odm/blob/1.2.5/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php#L539) call.

Implementing this should be fairly easy, would not break BC and would allow using text search relevance sort in the `DocumentRepository::findAll` method.

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | ???
| BC Break    | no

#### Summary

- Add  optional $field parameter to `DocumentPersister::loadAll` method.

**Comment by malarzm** [comment]
I'm not sure this is a correct flow, `findAll` returns array/iterator of hydrated documents and they can't really have additional fields, no?

**Comment by alcaeus** [comment]
Correct. If you want to use special options, like text search relevance, use the query builder. The find and findAll methods should not cover every possible use case, that’s what the query builder is for. Closing here.

**Comment by josefsabl** [comment]
Thank you for the direction. I dislike the query builders interface, but setQueryArray is what I need.

**Comment by alcaeus** [comment]
> I dislike the query builders interface, but setQueryArray is what I need.

The query builder is a more legible API to create query objects. You can also create them directly without utilizing the builder.
