### ISSUE TITLE
[2.0] must be of the type array, object given

### ISSUE THREAD

**Issue by olvlvl** [doctrine/mongodb-odm#1869]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | dk
| Version     | 2.0.0-alpha1

Hi,

I'm trying out `2.0.0-alpha1` and I get a lot of these: `must be of the type array, object given`. Please consider the following excerpt from `Doctrine\ODM\MongoDB\Persisters\DocumentPersister`:

```php
    /**
     * Creates or fills a single document object from an query result.
     *
     * @param object $result   The query result.
     * @param object $document The document object to fill, if any.
     * @param array  $hints    Hints for document creation.
     *
     * @return object The filled and managed document object or NULL, if the query result is empty.
     */
    private function createDocument($result, ?object $document = null, array $hints = []) : ?object
    {
        if ($result === null) {
            return null;
        }

        if ($document !== null) {
            $hints[Query::HINT_REFRESH] = true;
            $id                         = $this->class->getPHPIdentifierValue($result['_id']);
            $this->uow->registerManaged($document, $id, $result);
        }

        return $this->uow->getOrCreateDocument($this->class->name, $result, $hints, $document);
    }
```

`$result` is said to be an object (the `|null` is missing). In the test suite it's always an array, but in my application it's often a `MongoDB\Model\BSONDocument`, which can be used as an array because it extends `ArrayObject`. The problem is that both `registerManaged()` and `getOrCreateDocument()` expect `$result` to be an `array`.

From what I gathered from my tests, this happens when I'm searching for a document, using `findOneBy()` for instance.

```
        $family = $this->repository->findOneBy([

            Family::PROPERTY_COUNTRY => (string) $country,
            Family::PROPERTY_HANDLE => $handle,

        ]);
```

Raises the following exception:

```
1) HelloFresh\MenuService\Application\Command\Menu\IntegrationTest::shouldFailToActivateAnInvalidMenu
Failed asserting that exception of type "TypeError" matches expected exception "\HelloFresh\MenuService\Application\Exception\ValidationException". Message was: "Argument 2 passed to Doctrine\ODM\MongoDB\UnitOfWork::getOrCreateDocument() must be of the type array, object given, called in /app/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php on line 601" at
/app/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:2467
/app/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php:601
/app/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php:473
/app/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Repository/DocumentRepository.php:166
/app/src/Infrastructure/Persistence/Finder/FamilyFinder.php:32
```

I tried to converting `$result` into a array when a `BSONDocument`, but then it's another method failing for the same reason. What I don't understand is that I'm using the exact same driver both Docker images, one I created for [mongodb-odm](https://github.com/doctrine/mongodb-odm/pull/1868) and the one for my service. I don't get it :(

**Comment by olvlvl** [comment]
Found the solution in the tests:

```
$client = new Client(
    getenv('DOCTRINE_MONGODB_SERVER') ?: DOCTRINE_MONGODB_SERVER,
    [],
    ['typeMap' => ['root' => 'array', 'document' => 'array']]
);
```

I was missing that `['typeMap' => ['root' => 'array', 'document' => 'array']]` part. We really need an updated documentation, it still talk about `Doctrine\MongoDB\Connection` when we need a `Mongo\Client`.

https://github.com/doctrine/mongodb-odm/blob/f3ed76beb4dea085f06a407c9e12681e8aa59375/docs/en/reference/introduction.rst#setup

I'll see what I can do to help.

**Comment by alcaeus** [comment]
Interesting, did you create the client yourself? The type map should be applied automatically. We may however need to override it if a client is provided.

I’ll work on updating the documentation soon, completely missed the old classes there 😒

**Comment by olvlvl** [comment]
Looks like the default typeMap is wrong: https://github.com/mongodb/mongo-php-library/blob/bd148eab0493e38354e45e2cd7db59b90fdcad79/src/Client.php#L36

```
    private static $defaultTypeMap = [
        'array' => 'MongoDB\Model\BSONArray',
        'document' => 'MongoDB\Model\BSONDocument',
        'root' => 'MongoDB\Model\BSONDocument',
    ];
```

**Comment by alcaeus** [comment]
We set a type map when creating a document manager, but not when a client is provided, hence my question whether you create the client yourself.
