### ISSUE TITLE
[2.0] ocramius/proxy-manager does not create missing directories like doctrine/proxy was

### ISSUE THREAD

**Issue by olvlvl** [doctrine/mongodb-odm#1890]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | dev-master

#### Summary

`ocramius/proxy-manager` is not creating missing directories like doctrine/proxy used to do. Is this the new expected behavior?

#### Current behavior

Missing directories are not created which result in an error:

```
1) olvlvl\DoctrineGenerators\Document\HydratorGeneratorTest::testGenerator
ProxyManager\Exception\InvalidProxyDirectoryException: Provided directory "/app/tests/sandbox/Proxies" does not exist

/app/vendor/ocramius/proxy-manager/src/ProxyManager/Exception/InvalidProxyDirectoryException.php:19
/app/vendor/ocramius/proxy-manager/src/ProxyManager/FileLocator/FileLocator.php:32
/app/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Configuration.php:216
/app/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Configuration.php:182
/app/tests/Document/TestCase.php:51
/app/tests/Document/HydratorGeneratorTest.php:20
```

#### How to reproduce

Remove the proxies/hydrators destination folder.

#### Expected behavior

Missing directories are created.

**Comment by malarzm** [comment]
Ah @Ocramius and his strictness :D I think we should still create the directory if it doesn't exist, @alcaeus thoughts?

**Comment by alcaeus** [comment]
Well, if the library doesn't created, we probably should. I'll look into it.

**Comment by malarzm** [comment]
@olvlvl issue should be fixed now after updating ODM
