### ISSUE TITLE
Query documents by reference 

### ISSUE THREAD

**Issue by SinisterGlitch** [doctrine/mongodb-odm#1898]
Hi Support,

I made a stack post already and I would only post here since I'm desperate and have a time constraint.  Our databases have become very big and we are struggling with sort memory issues. I am currently rewriting the mongo services to get rid of the memory issues.

https://stackoverflow.com/questions/53372060/query-by-reference-in-doctrine-odm-mongo

**History**
Recreating mongo structure to combat memory issues in the former approach where a product is stored per locale and all values are an array hash (took to long to update).

**Current problem**
I can't seem to fetch products containing a referenced attribute with key "x" and value "y".

**Document classes**
Product (referenced to Value[])
Attribute (no references)
Value (referenced to Attribute)
My current approach is that the attributes and values are Referenced documents (the reason is that they change very often and I want to update them specifically without updating the whole product

    `/**
     * @param Builder $builder
     * @param ExportFilters $exportFilters
     */
    private function getProductsByFilters(Builder &$builder, ExportFilters $exportFilters)
    {
        $fields = MongoProduct::getFieldNames();
        $fields = array_diff($fields, ['values']);

        $attributes = $exportFilters->getSearch()['attributes'];

        $exp = $builder->expr()->eq('$$attribute.code', $attributes);

        return $builder
            ->project()
            ->includeFields($fields)
            ->field('values')
            ->filter('$values', 'value', $builder->expr()->filter('$$value.attribute', 'attribute', $exp));
    }`

**Comment by malarzm** [comment]
Being desperate IMO does not justify posting issue here 10 minutes creating post on SO. I'll look into it there as soon as I have a moment

**Comment by SinisterGlitch** [comment]
Apologies for this, I did not expect a quick reply.

I was too late with asking help, I have spent a few hours sleeping in the weekend, the rest trying to resolve this issue and already read all of the stackoverflow, doctrine pages and examples.

Given that i knew nothing about mongo since friday :(

**AggratetBuilder**

This aproach gives me only localized values (a product can contain 5000 values for 30 locales), it works and it is faster then a repositoryMethod on the getValues() in the Value document.

I wanted to use the same approach to continue filter the values by checking their value and referenced attribute, for example;

I want all products with values that are in en_GB  that matches with the statement below

**referenced attribute for a value should be (screen_size) and must have value "16 inch"**

it will return all products that matches the attribute filtering with the localized values

    `/**
     * @param Builder $builder
     * @param ExportFilters $exportFilters
     */
    private function applyLocaleFilter(Builder &$builder, ExportFilters $exportFilters)
    {
        if (!$exportFilters->hasLocales()) {
            return;
        }

        $fields = MongoProduct::getFieldNames();
        $fields = array_diff($fields, ['values']);

        $exp = $builder->expr()->eq('$$value.locale', $exportFilters->getLocale());

        $builder
            ->project()
            ->includeFields($fields)
            ->field('values')
            ->filter('$values', 'value', $exp);
    }`

(this helps me with localized values).

**Comment by SinisterGlitch** [comment]
Mongo attribute

`
    /**
     * Class MongoAttribute
     * @package Utomo\MongoBundle\Document
     *
     * @MongoDB\Document(
     *     repositoryClass="Utomo\MongoBundle\Document\Repository\MongoAttributeRepository",
     *     indexes={@Index(keys={"code"="desc", "name"="desc"}, options={"unique"=true})}
     * )
     */
    class MongoAttribute
    {
        /**
         * @var int
         * @MongoDB\Id(strategy="NONE")
         */
        private $id;
    
        /**
         * @var string
         * @MongoDB\Field(type="string")
         */
        private $code;
    
        /**
         * @var string
         * @MongoDB\Field(type="string")
         */
        private $name;
    
        /**
         * @var string
         * @MongoDB\Field(type="string")
         */
        private $type;
    
        /**
         * @var string
         * @MongoDB\Field(type="string")
         */
        private $pre_fix;
    
        /**
         * @var string
         * @MongoDB\Field(type="string")
         */
        private $post_fix;
`

Mongo product

    `
    /**
     * Class MongoProduct
     * @package MongoBundle\Document
     *
     * @MongoDB\Document(repositoryClass="MongoBundle\Document\Repository\MongoProductRepository",
     *     indexes={@Index(keys={"id"="desc", "name"="desc"}, options={"unique"=true})}
     * )
     */
    class MongoProduct
    {
        /**
         * @var integer
         * @MongoDB\Id(strategy="NONE")
         */
        protected $id;
    
        /**
         * @var string
         * @MongoDB\Field(type="string")
         */
        protected $name;
    
        /**
         * @var \DateTime
         * @MongoDB\Field(type="date")
         */
        protected $created;
    
        /**
         * @var \DateTime
         * @MongoDB\Field(type="date")
         */
        protected $updated;
    
        /**
         * @var boolean
         * @MongoDB\Field(type="bool")
         */
        protected $archived;
    
        /**
         * @var integer
         * @MongoDB\Field(type="bool")
         */
        protected $is_parent;
    
        /**
         * @var integer
         * @MongoDB\Field(type="bool")
         */
        protected $is_child;
    
        /**
         * @var boolean
         * @MongoDB\Field(type="bool")
         */
        protected $is_single;
    
        /**
         * @var string
         * @MongoDB\Field(type="string")
         */
        protected $attribute_set_id;
    
        /**
         * @var string
         * @MongoDB\Field(type="string")
         */
        protected $attribute_set_name;
    
        /**
         * @var MongoProduct
         * @MongoDB\ReferenceOne(targetDocument="MongoProduct")
         */
        protected $parent;
    
        /**
         * @var MongoProduct[]
         * @MongoDB\ReferenceMany(targetDocument="MongoProduct", cascade={"persist"}, orphanRemoval=true)
         */
        protected $children;
    
        /**
         * @var MongoValue[]
         * @MongoDB\ReferenceMany(targetDocument="MongoValue", cascade={"persist"}, orphanRemoval=true)
         */
        protected $values;
    `

Mongo value

    `/**
     * Class MongoValue
     * @package \MongoBundle\Document
     *
     * @MongoDB\Document(repositoryClass="MongoValueRepository",
     *     indexes={@Index(keys={"locale"="desc", "attribute"="desc", "id"="desc"}, options= . {"unique"=true})}
     * )
     */
    class MongoValue
    {
        /**
         * @var int
         * @MongoDB\Id(strategy="NONE")
         */
        private $id;
    
        /**
         * @var string
         * @MongoDB\Field(type="string")
         */
        private $locale;
    
        /**
         * @var string
         * @MongoDB\Field(type="string")
         */
        private $value;
    
        /**
         * @var MongoAttribute
         * @MongoDB\ReferenceOne(targetDocument="MongoAttribute", cascade={"persist"})
         */
        private $attribute;
    
        /**
         * @var MongoProduct
         * @MongoDB\ReferenceOne(targetDocument="MongoProduct", cascade={"persist"})
         */
        private $product;
`

**Comment by SinisterGlitch** [comment]
My current attempt is to retrieve a list of product IDs by filtering the values and returning products. 

Still in progress, trying to figure out what to do or coming up with total new approaches

    `
        /**
         * @param ExportFilters $exportFilters
         * @return mixed
         * @throws MongoDBException
         * @throws \MongoException
         */
        public function getProductsByValues(ExportFilters $exportFilters)
        {
            $builder = $this->getDocumentManager()
                ->createQueryBuilder(MongoValue::class);
    
            foreach ($exportFilters->getFilters() as $code => $values) {

                if (!is_array($values)) {
                    $values = [$values];
                }
    
    //            $attribute = $this
    //                ->getDocumentManager()
    //                ->createQueryBuilder(MongoAttribute::class)
    //                ->field('code')->equals((string) $code)
    //                ->getQuery()
    //                ->getSingleResult();
    
                foreach ($values as $value) {
                    $regex = new \MongoRegex(sprintf("/%s/i", $value));
    
                    $attribute = $this
                        ->getDocumentManager()
                        ->getRepository(MongoAttribute::class)->findOneBy(['code' => (string) $code]);
    
                    $builder->references($attribute);
                }
            }
    
            $products = [];
            foreach ($builder->getQuery()->execute() as $mongoValue) {
                $products[] = $mongoValue->getProduct();
            }
            $x =1;
    
            return $products;
        }
`
