### ISSUE TITLE
Unexpected behavior when insert fails

### ISSUE THREAD

**Issue by MatTheCat** [doctrine/mongodb-odm#1912]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.2.5

#### Current behavior

If `flush` fails to insert a new document (because of a `MongoDuplicateKeyException` eg.) it is left in a state where doctrine thought it has been persisted. Subsequent `flush` will then produce an `update` query which will do nothing.

The only way to persist the document is then to trigger an `upsert` by detaching and persisting it again.

#### How to reproduce

```php
$dm->persist($document);

while (true) {
    $document->computeUniqueValue();

    try {
        $dm->flush();

        break;
    } catch (MongoDuplicateKeyException $ex) {}
}
```

In case of `MongoDuplicateKeyException` in the first iteration the next `flush` will trigger an update so the second iteration always is the last without the document being persisted.

The only workaround I found is to write

```php
while (true) {
    $document->computeUniqueValue();
    $dm->persist($document);

    try {
        $dm->flush();

        break;
    } catch (MongoDuplicateKeyException $ex) {
        $dm->detach($document);
    }
}
```

#### Expected behavior

In case a document fails to be persisted I would expect subsequent queries to be inserts.

**Comment by alcaeus** [comment]
That definitely looks bad. I'll take a look at what we can do in 2.x, but the smartest choice would be to close the DocumentManager for future operations, just like is done in ORM. I'm not sure whether we can recover gracefully from this, but I'll see.

**Comment by alcaeus** [comment]
After reproducing this in a test case, I don't believe there's a good fix for 1.2. The problem is that we're using the batch API to insert documents (grouped by document class). With the legacy MongoDB driver, there's no way of knowing which document failed and which was inserted. We will know in 2.x, but I still need to figure out how to best recover from an error like that.

**Comment by MatTheCat** [comment]
Don't know anything about internals but I simply would have expected the document state to stay NEW.

**Comment by MatTheCat** [comment]
I guess when #1888 is fixed this issue will no longer be relevant, so I’m closing here.
