### ISSUE TITLE
Schema commands error out with 'The "maxTimeMs" option does not exist.'

### ISSUE THREAD

**Issue by Rybbow** [doctrine/mongodb-odm#1916]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.0.0-beta1

#### Summary

When trying to execute `doctrine:mongodb:schema:create`, `doctrine:mongodb:schema:update` or `doctrine:mongodb:schema:drop` from DoctrineMongoDBBundle an error 'The "maxTimeMs" option does not exist.' is printed out and the command fails.

#### Current behavior

Changes introduced in [this commit](https://github.com/doctrine/mongodb-odm/commit/0204d4079f1ace40a54a7b6c5755ae69db4c3809#diff-3c235a7aedeb6ba2bf96208a6e295210) introduced common options for schema related commands in `\Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\AbstractCommand::configure()`. However, since `parent::configure()` call is missing from the `configure()` method in all of `\Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\UpdateCommand`, `\Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\CreateCommand` and `\Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\DropCommand`, the options are not present and trying to use them causes an error.

#### How to reproduce

Install and configure `doctrine/mongodb-odm-bundle` in `dev-master` version in any Symfony project and execute any execute one of the mentioned commands.

#### Expected behavior

The command should not fail.

I guess adding the `parent::configure()` call to `AbstractCommand` will fix the problem. I can prepare a PR if that's the only required fix here. Also, I don't think `\Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\ValidateCommand` or `\Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\ShardCommand` use the new common schema command options anywhere and they don't really make much sense for them, so they should not be changed.

**Comment by alcaeus** [comment]
Thanks for the report. I'll prepare a fix shortly 👍

**Comment by Rybbow** [comment]
I can prepare a fix, it's not a problem. Just let me know if the solution I suggested is ok.

**Comment by alcaeus** [comment]
The solution is good. `ValidateCommand` doesn't need any of the options, that is correct. For the `ShardCommand`, we can pass a write concern to the respective schema manager methods and [`runShardCollectionCommand`](https://github.com/doctrine/mongodb-odm/blob/7ad215b38951bf1ecf140e4adf13520834fb2f69/lib/Doctrine/ODM/MongoDB/SchemaManager.php#L588) as `shardCollection` takes a write concern (see https://docs.mongodb.com/manual/reference/command/shardCollection/#dbcmd.shardCollection). I forgot about that when adding the options. We can also add that in a separate PR if you want to leave it out.

Either way, a PR with fixes is highly appreciated 👍

**Comment by Rybbow** [comment]
@alcaeus Ok, a PR is ready - https://github.com/doctrine/mongodb-odm/pull/1918 .
