### ISSUE TITLE
Does the ODM support MongoDB's v3.4 feature Views?

### ISSUE THREAD

**Issue by metanav** [doctrine/mongodb-odm#1923]
|    Q        |   A
|------------ | -----
| Version     | 2.0.0 or 1.2.5

### Support Question

If I create a View, will it work with ODM Document as a  drop-in replacement?
I know there are some limitations in  querying Views but I need only basic one e.g., findOne and findAll.

**Comment by alcaeus** [comment]
Nope, the ODM does not understand views. This is on our extended roadmap but won't be done in 2.0.

**Comment by alcaeus** [comment]
I've created #1925 and added it to the roadmap for 2.x (which is sometime after 2.1). Closing here.
