### ISSUE TITLE
Mark internal classes as @internal in PHPDocs

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1931]
Mark classes that are internal and not covered by the BC promise as `@internal` via PHPDoc to let users know that they shouldn't rely on their API.

Method signatures may be changed in minor releases.

**Comment by malarzm** [comment]
I think we could also add `final` to some classes like `CollectionPersister` or such

**Comment by alcaeus** [comment]
Absolutely. We can prepare that and mark them as `@final` in 1.3 along with deprecation notices if they're extended.

**Comment by malarzm** [comment]
Closing as I've just opened #1984 to mark classes as final which was last thing to do in this issue (PR has a needs compat label)
