### ISSUE TITLE
DiscriminatorMap annotation undocumented upgrade change

### ISSUE THREAD

**Issue by Steveb-p** [doctrine/mongodb-odm#1933]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.0.0-beta1

#### Summary

Documentation for upgrade does not indicate that `DiscrimatorMap` now always requires passing full class name along with whole namespace.

#### Current behavior

In 1.2 version of Doctrine ODM you can pass class names in current namespace. 2.0 always requires FQCN - I'm pretty sure now it's intended behavior.

#### Expected behavior

2.0 Upgrade docs should contain this information. Probably under changes related to annotations?

**Comment by malarzm** [comment]
We should also check if deprecation is in place

**Comment by alcaeus** [comment]
Deprecation was part of https://github.com/doctrine/mongodb-odm/pull/1927
