### ISSUE TITLE
Suggestion/RFC: use labels to help newcomers

### ISSUE THREAD

**Issue by juliusstoerrle** [doctrine/mongodb-odm#1941]
While I do have some experience with PHP I have not much experience with contributing to OSS (or for that matter other peoples code) yet, but would like to get involved with that more.

I find it hard to figure out where to start helping and would propose using `help wanted` and `good first issue` labels as explained by GitHub:
https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/

(Feel free to close this, as soon as you made a decision)

**Comment by malarzm** [comment]
Thanks for the suggestion! We're already using labels such as [Easy pick](https://github.com/doctrine/mongodb-odm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Easy+Pick%22) or [Needs test](https://github.com/doctrine/mongodb-odm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+Test%22) so unless `help wanted` and `good first issue` trigger some special GitHub behaviour, I think we're good here 👍

**Comment by malarzm** [comment]
Also we've tagged a bunch of stuff with [Hacktoberfest](https://github.com/doctrine/mongodb-odm/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3AHacktoberfest+) label. While it's not Hacktoberfest anymore, the issues should still be good for newcomers.
