### ISSUE TITLE
GenerateProxiesCommand/GenerateHydratorsCommand: assert is_string on an array

### ISSUE THREAD

**Issue by thiver** [doctrine/mongodb-odm#1943]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | dev-master

#### Summary

`$filter = $input->getOption('filter');`
`assert(is_string($filter));`

$filter returns an array because of InputOption::VALUE_IS_ARRAY, so the assertion fails always.

Class Methods:

Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateProxiesCommand::execute
Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateHydratorsCommand::execute

#### Current behavior

The commands cannot be executed because of the assertion fail.

#### How to reproduce

Run the GenerateProxiesCommand or GenerateHydratorsCommand command.

#### Expected behavior

The $filter should be asserted as an array.

**Comment by malarzm** [comment]
Sounds about right, @thiver do you mind making a PR to fix the bug?

**Comment by alcaeus** [comment]
🤦‍♂️ great find @thiver!

**Comment by thiver** [comment]
No problem, I will create a PR for it.

**Comment by malarzm** [comment]
Closing as #1944 was just merged
