### ISSUE TITLE
An element is duplicated in a collection

### ISSUE THREAD

**Issue by dossorio** [doctrine/mongodb-odm#1955]
### Bug Report

An new element of a collection is duplicated when the collection is updated

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.1.2

#### Summary

When you update a field of the root document, a field of the embedded document and try to add an element to a collection present in the embedded document, this element is duplicated

#### Current behavior

A new element in the mentioned collection ends up duplicated.

#### How to reproduce

Using the following collection structure:
```
{ 
  updatedAt: ISODate("Whatever_1"),
  embeddedDoc: { 
    field: 1, 
    collection: [
      { elemField: 1, anotherField: 1 },
      { elemField: 2, anotherField: 2 },
      ...
    ]
  } 
}
```
1. Insert a document with values in those fields and one element in the collection as follows:
`{ updatedAt: ISODate("Whatever"), embeddedDoc: { field: 1,  collection: [{ elemField: 1 }]}}`
2. Update the document as follows:
  - Update the `updatedAt` field
  - Update `embeddedDoc.field` with `2`
  - Add a new element to the collection `collection` as follows: `{ elemField: 2 }`
3. When you flush that document, the following queries are performed:
```
"$set" : {
  "updatedAt" : ISODate("Whatever_2"),
  "embeddedDoc.collection.1.elemField" : 2,
  "embeddedDoc.field" : 2
},
"$unset" : {
  "embeddedDoc.collection.1.anotherField" : true,
}
```
and
```
"$pushAll" : {
  "embeddedDoc.collection" : [
    {
	"elemField" : 2
    }
  ]
}
```

So the second element is added twice to the db

#### Expected behavior

With `pushAll` as the default storage strategy for this collection, the first query should have not include the new element of the collection, so it could be pushed in the second one without being duplicated.

The same happens with the rest of the collection storage strategies, with the difference that with  `setArray` the second query persists the whole array, so the changes performed by the first query are overwritten, and the collection ends up containing only two elements instead of three. Although with `setArray` the element is not duplicated, two updates were performed to do the same thing, which doesn't look right either.

**Comment by malarzm** [comment]
@dossorio is this happening with `1.2.x` version of ODM as well? Asking since `1.1` branch is not maintained. Also reading your extensive description it seems like you have a code to reproduce the issue. Any chance you could submit us a failing test case?

**Comment by dossorio** [comment]
Many thanks @malarzm for your message and your suggestion.

I have just tested with `1.2.6` and its still happening. 
The only difference I have noticed is that the second query uses `$push` and `$each` now:
```
"$push" : {
  "embeddedDoc.collection" : {
    "$each" : [
      {
	"elemField" : 2
      }
    ]
  }
}
```

I'll try to get a failing test case asap

**Comment by malarzm** [comment]
@dossorio when you get to it please open a PR against `1.2.x` branch, we'll first fix it there. If needed I'll take care of moving fixes to `master` branch after.

**Comment by alcaeus** [comment]
> The only difference I have noticed is that the second query uses `$push` and `$each` now

This is because the `$pushAll` operator was deprecated, so we work around this by using `$push` and `$each`. The end result is the same 👍

**Comment by dossorio** [comment]
I'll close this, as I figured out that the place where I was calling `persist` and `flush` affected the shape of the first query. 

By having changed that, the element of the array is not specified in the first query anymore, only in the second, so its not added twice

**Comment by alcaeus** [comment]
Glad you got it fixed. Thanks for letting us know!
