### ISSUE TITLE
Configuration::setLoggerCallable removed without mentioning in UPGRADE notes.

### ISSUE THREAD

**Issue by josefsabl** [doctrine/mongodb-odm#1959]
I consulted these materials before posting this:

https://github.com/doctrine/mongodb-odm/blob/master/UPGRADE-2.0.md
https://github.com/doctrine/mongodb-odm/blob/master/CHANGELOG-2.0.md
https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.0/reference/logging.html

### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.0.0-beta1

#### Summary

Doctrine\ODM\MongoDB\Configuration::setLoggerCallable is no longer available and it is not clear how to replace it. There is no mention in UPGRADE notes or CHANGELOG and documentation does not exist.

**Comment by alcaeus** [comment]
Thanks for reporting this! We've noticed a couple of other BC breaks as well, which means that we'll need to do another pass to make sure we document all deprecations and removals.

I played around with [`roave/backward-compatibility-check`](https://github.com/Roave/BackwardCompatibilityCheck) this morning and will try to use that to figure out what else we missed.

**Comment by alcaeus** [comment]
Closing in favour of #2009 where I finally got to running `roave/backward-compatibility-check`.

**Comment by mstaack** [comment]
@alcaeus 
was wondering what is a good approach to add a somehow simliar logging functionality in 2.x .
any hints?

thank you

**Comment by mstaack** [comment]
whats the preferred approach now for logging?

**Comment by alcaeus** [comment]
The [APM features of the MongoDB driver](https://www.php.net/manual/en/mongodb.tutorial.apm.php) should be used to log commands that are run. The Symfony bundle for MongoDB ODM already incorporates this into the Symfony profiler. If not using Symfony, you can use the [`Doctrine\ODM\MongoDB\APM\CommandLogger`](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/APM/CommandLogger.php) class and base your logic on that.
