### ISSUE TITLE
Wrong behavior when using sortMeta

### ISSUE THREAD

**Issue by Mihail0v** [doctrine/mongodb-odm#1964]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    |no
| Version     | 2.0.0-beta1

#### Summary
When you use sortMeta of Query\Builder it causes a wrong behavior of DocumentPersister::prepareSort 

#### Current behavior
sortMeta creates a new sorting with array as a value, but the DocumentPersister waits for sort direction(desc/asc).

#### How to reproduce
```
 $builder = $this->dm->createQueryBuilder(Document::class);
 $builder->sortMeta('score', 'textScore');
 $builder->getQuery()->getQuery();
```
throws array to string conversation.

#### Expected behavior
If the value of sorting field is array, DocumentPersister::prepareSort should not try to get sort direction

**Comment by malarzm** [comment]
#1965 was merged, closing here
