### ISSUE TITLE
add DateImmutableType

### ISSUE THREAD

**Issue by rieschl** [doctrine/mongodb-odm#1975]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

It would be nice if `DateTimeImmutable` would be supported natively, as using immutable dates is usually better than mutable ones.
So I suggest implementing a `DateImmutableType`.
It's probably as easy as using the current `DateType` type and converting the Date to DateTimeImmutable.
That's my current implementation:

```
final class DateImmutableType extends DateType
{
    public const DATE_IMMUTABLE = 'date_immutable';

    public static function getDateTime($value): \DateTimeInterface
    {
        $dateTime = parent::getDateTime($value);
        if ($dateTime instanceof \DateTimeImmutable) {
            return $dateTime;
        }
        if (!$dateTime instanceof \DateTime) {
            throw new \InvalidArgumentException(
                \sprintf(
                    'Value has to be instance of DateTime, got %s',
                    get_class($dateTime))
            );
        }
        return \DateTimeImmutable::createFromMutable($dateTime);
    }
```
It's not yet fully tested, so use at your own risk.

**Comment by malarzm** [comment]
Closing as #2118 was merged
