### ISSUE TITLE
How to use "allowDiskUse" in aggregationBuilder ?

### ISSUE THREAD

**Issue by InternalServerError** [doctrine/mongodb-odm#1979]
|    Q        |   A
|------------ | -----
| Version     | 3.4

### Support Question

Hi,
Is it possible to use the allowDiskUse: true in aggregationBuilder please ?

**Comment by Steveb-p** [comment]
You can pass `$options` when calling `execute`.

See execute method excerpt:
```php
    /**
     * {@inheritdoc}
     */
    public function execute($options = [])
    {
        // Force cursor to be used
        $options = array_merge($options, ['cursor' => true]);

        $cursor = parent::execute($options);

        return $this->prepareCursor($cursor);
    }
```

**Comment by InternalServerError** [comment]
You're a rockstar man, thank you for the quick and clear answer.
I did not see that, thanks again !
