### ISSUE TITLE
less strict constraint for discriminator-mapping values in 2.0

### ISSUE THREAD

**Issue by rieschl** [doctrine/mongodb-odm#1980]
It's not really a feature request but more retaining backwards compatibility.
When testing version 2 I noticed that the syntax checks for XML mappings are more strict than in version 1. Using a FQCN as `discriminator-mapping` `value` now throws a `Doctrine\ODM\MongoDB\Mapping\MappingException` for it not being a `xs:NMTOKEN` type.

While I totally understand the necessity of breaking BC from time to time, this break causes a whole other set of issues: Version 1 supported partial discriminator maps and automatically created the discriminator mapping when it's not defined in the mapping. Funny enough the automatically set value of the mapping is the FQCN 😄
So, when upgrading to 2.0 I don't just have to add the missing discriminator mappings but also migrate existing documents to use a legal name, because currently they're all FQCNs now.
That can be very complicated on busy environments so I kindly ask to rethink this current constrain for the upcoming version 2.
Also, (I didn't check) probably the annotation mapping doesn't have this kind of constraint, so it would be reasonable to have the same behavior in both mapping drivers. I'm sure lots of people want to upgrade to version 2 as soon as it's released because we don't have to use compatibility layers for the old PHP5 `mongo` driver anymore.

**Comment by rieschl** [comment]
btw: also `index` `key` values have to be `xs:NMTOKEN`s, which is not really necessary because mognodb itself doesn't have that kind of restriction on it's indexes.

**Comment by alcaeus** [comment]
I've scheduled this for 1.3 since invalid mapping files cause deprecation warnings in 1.3. It makes sense to loosen the rules before people try to change mappings to be compatible with 2.0 where the changes wouldn't have been necessary.

**Comment by rieschl** [comment]
In `1.x` are not yet invalid, are they? Or are they invalid but accepted anyways?

**Comment by alcaeus** [comment]
In 1.2.x, they are invalid but accepted anyways. In 1.3, we're deprecating mapping files that are invalid according to the schema, with 2.0 refusing to load such mapping files. Thus, when upgrading to 1.3 you'd receive a deprecation warning that your mapping file is invalid and you'll no longer be able to load it after moving to 2.0.

This is why I want to fix this in 1.3 to ensure the mapping files are valid there already.

**Comment by alcaeus** [comment]
#2007 was merged, closing.
