### ISSUE TITLE
Proxy ID field not filled with id value

### ISSUE THREAD

**Issue by strobox** [doctrine/mongodb-odm#1982]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | dev-master 62ca36c

#### Summary

ID null while hydration (not set)

#### Current behavior

Bad query to mongodb happen (with _id null)

#### How to reproduce

I've compared Proxies generated by 2.0.0-beta1 and dev-master 62ca36c

2.0.0-beta1:
```php
    private static $protectedProperties08063 = [
        'firstName' => 'App\\Document\\Customer',
        'lastName' => 'App\\Document\\Customer',
        'nickname' => 'App\\Document\\Customer',
        'email' => 'App\\Document\\Customer',
        'name' => 'Xapapi\\Model\\LinkNodeModel',
        'path' => 'Xapapi\\Model\\LinkNodeModel',
        'itemOf' => 'App\\Document\\LinkNode',
        'nodeType' => 'Xapapi\\Model\\LinkNodeModel',
```
62ca36c:
```php
    private static $protectedPropertiesfb7a2 = [
        'id' => 'Xapapi\\Model\\LinkNodeModel',
        'firstName' => 'App\\Document\\Customer',
        'lastName' => 'App\\Document\\Customer',
        'nickname' => 'App\\Document\\Customer',
        'email' => 'App\\Document\\Customer',
        'name' => 'Xapapi\\Model\\LinkNodeModel',
        'path' => 'Xapapi\\Model\\LinkNodeModel',
        'itemOf' => 'App\\Document\\LinkNode',
        'nodeType' => 'Xapapi\\Model\\LinkNodeModel',
```
Maybe it is desired behavior that *id* begin appear in 62ca36c, but it cause bug i think.

I should note that my document entity use inheritance:

```php
/**
 * / @MongoDB\Document(repositoryClass="App\Repository\CustomerRepository")
 */
class Customer extends LinkNode
{
    /**
     * @MongoDB\Id
     */
    private $id;
```

```php
/**
 * @HasLifecycleCallbacks
 * @MongoDB\MappedSuperclass(repositoryClass="App\Repository\LinkNodeRepository")
 * @MongoDB\InheritanceType("COLLECTION_PER_CLASS")
 * @MongoDB\DiscriminatorField("nodeType")
 * @MongoDB\DiscriminatorMap({
 *     "folder"=App\Document\Folder::class,
 *     "comment"=App\Document\Comment::class,
 *     "customer"=App\Document\Customer::class
 *  })
 * @MongoDB\DefaultDiscriminatorValue("folder")
*/
class LinkNode extends LinkNodeModel
{

    /** @MongoDB\PreLoad */
    public function preLoad(PreLoadEventArgs $eventArgs): void
    {
        $this->initNodeType();
    }
    public function __construct(string $name = "")
    {
        parent::__construct(array('name'=>$name,'path'=>[]));
        $this->nodeName = $name;
        $this->items = new ArrayCollection();
        $this->initNodeType();
    }

    /**
     * @MongoDB\Id
     */
    protected $id;
```

```php
class LinkNodeModel 
{
    /**
     * @var string|null
     *@SerializedName("id")
     * @Assert\Type("string")
     *@Type("string")
     */
    protected $id;
```

**Comment by alcaeus** [comment]
I wanted to reproduce this as you've posted it, but it doesn't make any sense: `$id` can't be protected in the parent and private in the child class. Could it be that it's declared as private in all classes?

**Comment by strobox** [comment]
Yes, it can't. It is my mistake. Maybe I've copy-pasted that piece of code while make experiments with id field access levels. I will try and check all again now.

**Comment by strobox** [comment]
So, of course `private $id;` in `class Customer extends LinkNode` is was my mistake in provided sample. But I can confirm that issue still exits (no matter public or protected is used). Also I would note that `public` or `protecetd` can not be used for parent class `LinkNodeModel` because it is generated model by openapi-generator tool. Even so, I think library should work with any field access levels.

**Comment by alcaeus** [comment]
I just wanted to confirm the access levels. So the property is protected in both classes? I’ll try to reproduce it that way.

**Comment by strobox** [comment]
There is three classes:

|   | Superclass | Sub-class | Sub-sub-class|
| ------------- | ------------- | ------------- |------------- |
| **Class name**  | LinkNodeModel  | LinkNode  | Customer  |
| **Field access level**  | protected  | protected  | protected*  |
| **Is in project source**  | No**  | Yes  | Yes  |
| **Extra info**  | Is POPO class  | Is Mongodb MappedSuperclass  |  one of three mongodb inheritance subclasses (see DiscriminatorMap) |

* I also tried to relax access level to public but it does not affect issue
** this class is from separate composer module. It is server stubs generated from openapi specification

**Comment by strobox** [comment]
Here is the project sources with issue (if  change 2.0.0-beta1 => dev-master): http://gg.wseb.cf/afram/xap_pback (have docker-compose to run it) but now (at dev stage) it have two local filesystem dependencies) If it will make sense I can publish them to VCS.

**Comment by strobox** [comment]
I found some time to research issue by myself. I try reproduce issue from scratch and provide repo.

**Comment by strobox** [comment]
I decided to create new issue and close that because I found more details and prepared reproduce repo https://github.com/doctrine/mongodb-odm/issues/1990
