### ISSUE TITLE
[mapping, xml] field-name argument ignored for embedded document id

### ISSUE THREAD

**Issue by ychanan** [doctrine/mongodb-odm#1987]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | n/a
| Version     | 2.0.0@beta

#### Summary

When mapping an ID of an embedded document to a property not called "id", an exception is thrown in "Property id does not exist at ClassMetadata.php:1940". I suspect that the new "field-name" XML argument is ignored in this specific case.

#### Current behavior & how to reproduce

```
<embedded-document name="AcmeBundle\Document\Foo">
    <id field-name="name" type="string" strategy="none" />
    <field field-name="value" type="string"/>
</embedded-document>
```

Results in an exception:
```
An error occurred in AcmeBundle\Document\Foo" at /app/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php line 106 {"exception":"[object] (Doctrine\\ODM\\MongoDB\\Mapping\\MappingException(code: 0): An error occurred in AcmeBundle\\Document\\Foo at /app/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php:106, ReflectionException(code: 0): Property id does not exist at /app/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php:1940)
```

When I add the following at the top of the [XmlDriver::addFieldMapping()](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php#L266) method, everything works fine.
```
if (isset($mapping['field-name'])) {
    $mapping['fieldName'] = $mapping['field-name'];
}
```

**Comment by etshy** [comment]
Using `fieldName="name"` instead of `field-name="name"` should work.
[See this line](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php#L270)

**Comment by ychanan** [comment]
But you can't use that as it fails XML schema validation. It's no longer supported.

**Comment by etshy** [comment]
Sorry, I didn't know it was not supported anymore, I didn't try the 2.0 beta yet.

I just read the `<field id="true"/>` is removed too so I don't see any other way to do that.

It seems to be a bug, then.
The `field-mapping` attribute appears in xsd [here](https://github.com/doctrine/mongodb-odm/blob/master/doctrine-mongo-mapping.xsd#L134) but maybe it's not handled in code.

**Comment by alcaeus** [comment]
The new `id` mapping doesn't allow using a different name, as an identifier in MongoDB is always mapped to the `_id` field in the database. However, this `_id` field doesn't really exist for embedded documents, at least not with the special handling normally associated with it (even when you don't specify it while inserting a document, it will always be added). This handling does not exist for embedded documents. Furthermore, embedded documents normally don't have an identifier in the sense that regular documents have one. I'm not sure if ODM even adds a unique index on the identifiers of embedded documents in a collection, but I don't think that it does. I'll have to take a deeper look at that later. As for the ID mapping, the fact that people used `id="true"` on fields in embedded documents was an oversight when adding the new `id` field, as was the fact that you're able to map an `id` field in an embedded document.

I'll have to take a look at the current behaviour, but I think the best solution here is deprecating the use of identifiers in embedded documents and removing that functionality in 2.0. If you want to store an ObjectId in a field, you can always map a field with the `ObjectId` type and an arbitrary name. This has the downside that there are no ID generators, but then embedded documents have different requirements for identifiers from regular documents, so a separate feature or special handling should be considered for that.

**Comment by alcaeus** [comment]
After discussion within the team, we've decided to keep things the way we have them at the moment. Identifiers will always map from any property name to an `_id` field in the database. While this may seem unnatural for embedded documents, I would suggest not using identifiers for embedded documents at all. Instead, if you want to store an ObjectId, map it as a regular field with the `ObjectId` type. While such fields don't have any autogeneration logic built in (which can be worked around during `prePersist` events), the upside is that the mapping no longer suggests that the field is an identifier like for a regular document. This assumption is wrong, as there will not be a unique index on an identifier mapped in an embedded document, which is contrary to what an identifier suggests.

At the same time, we will not disallow using the new `id` mapping in embedded documents just yet: the changes necessary to the XSD would far exceed the scope of changes I'm willing to do for 2.0 release and it would also not cover any other drivers. We'll be deprecating this kind of mapping in a further 2.x release for removal in 3.0.
