### ISSUE TITLE
[pagerfanta] The latest Pagerfanta adapter does not appear to be compatible with the library

### ISSUE THREAD

**Issue by ychanan** [doctrine/mongodb-odm#1988]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.0.0@beta

#### Summary

The library is no longer compatible with latest Pagerfanta adapter.

#### Current behavior

The `Pagerfanta\Adapter\DoctrineODMMongoDBAdapter`, when used with the beta version throws an exception in `getNbResults()` method, and in some cases has the wrong query type set in `getSlice()` method.

#### getNbResults()

The `getNbResults()` method invokes:
```
$this->queryBuilder->getQuery()->count()
```

But `count()` method no longer exists on the query, so an exception is thrown. It works when the line is changed to:
```
$this->queryBuilder->count()->getQuery()->execute();
```

#### getSlice()

This method had to be changed to explicitly specify the query type ("find"), as in some cases, when `$this->queryBuilder->getType()` was inspected, it returned `Query::TYPE_COUNT`.

```
return $this->queryBuilder
            ->limit($length)
            ->skip($offset)
            ->getQuery()
            ->execute();
```
Changed to:
```
return $this->queryBuilder
            ->find()
            ->limit($length)
            ->skip($offset)
            ->getQuery()
            ->execute();
```

Though the `getSlice()` issue might be unrelated, hadn't had the chance yet to create a clean reproducible environment.

**Comment by malarzm** [comment]
Thanks for the report! I'd say that this is Pagerfanta that needs to adapt its code to work with ODM 2.0, they have an adapter written - not us.

**Comment by dkarlovi** [comment]
Thanks @malarzm, we just wanted to confirm this is expected behaviour on your end, not an unexpected BC break, @alcaeus said there are still some parts in need of cleanup.

**Comment by alcaeus** [comment]
Correct - we dropped the `count` method from the `Query` class without properly deprecating and dropping it, which is why I wanted to take a good look at this.

I also want to take a look at the `find` query since you mentioned you needed to explicitly add the `find()` call when building it, which shouldn't be necessary.

**Comment by alcaeus** [comment]
The BC break is taken care of in #2009. As for the `find` behaviour, there is nothing to suggest you need to add explicit `find()` calls to query builders in 2.0. If you can provide more information regarding that, I'd be happy to take another look.
