### ISSUE TITLE
Empty server configuration value results in an exception

### ISSUE THREAD

**Issue by ychanan** [doctrine/mongodb-odm#1992]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.0.0@beta

#### Summary

An exception is thrown when an empty string is provided in configuration for:
```
doctrine_mongodb:
    connections:
        default:
            server: "<EMPTY>"
```

Exception:
```
Failed to parse MongoDB URI: ''. Invalid URI Schema, expecting 'mongodb://' or 'mongodb+srv://'.
```

This is important because it occurs during cache clearing and warmup and breaks the application if the server value is to be resolved dynamically or is not provided for some other reason.

**Comment by alcaeus** [comment]
Without having a trace for the exception, I can only speculate, but here goes.

The exception is thrown when constructing a `MongoDB\Manager` instance: https://github.com/mongodb/mongo-php-driver/blob/d0cc6bd9b0fd70073cc3c7c9fcb661dee9fd06c8/php_phongo.c#L1376. This instance is constructed when creating a `DocumentManager` instance. I would assume that upon cache warmup, proxy classes are generated, which requires a `DocumentManager` instance, triggering the chain mentioned above.

However, no connection should be established for that entire process, so as long as the URI given to the manager is syntactically correct, you should be fine. `<EMPTY>` won't work, but `null` or an empty string should trigger fallback handling where the default URI (`mongodb://127.0.0.1/`) is used: https://github.com/mongodb/mongo-php-driver/blob/d0cc6bd9b0fd70073cc3c7c9fcb661dee9fd06c8/src/MongoDB/Manager.c#L321.

**Comment by alcaeus** [comment]
@ychanan did you try using a semantically valid URL instead of `<EMPTY>`?

**Comment by ychanan** [comment]
Semantically valid URLs work, `mongodb://127.0.0.1/` is ok.

Btw, to clarify, when I wrote `<EMPTY>`, I meant either an empty string, or a parameter containing an empty string. Not a literal `"<EMPTY>"` string.

**Comment by alcaeus** [comment]
I see. An empty string will not trigger the fallback to the default URI set in the driver (see comment above for references to the code in question). This is something that shouldn't change IMO, so it's up to your configuration to properly pass `null` instead of an empty URL. If using environment variables, you may want to use the [new `default` env var processor](https://symfony.com/blog/new-in-symfony-4-3-default-and-trim-env-var-processors#default-env-var-processor) being added in Symfony 4.3 (which you can back port to previous versions if you want):
```yaml
doctrine_mongodb:
    connections:
        default:
            server: '%env(default::MONGODB_SERVER)%'
```

Note that the two colons after `default` are intended and will yield a default value of `null` which is what you want in this case.

**Comment by alcaeus** [comment]
@ychanan did the above work for you?

**Comment by ychanan** [comment]
This is how we currently use it, and this works.
```
parameters:
    env(WAREHOUSE_DSN): 'mongodb://127.0.0.1/'

doctrine_mongodb:
    connections:
        default:
            server: "%env(resolve:WAREHOUSE_DSN)%"
```

These two do not:
```
parameters:
    env(WAREHOUSE_DSN): '%env(default::WAREHOUSE_DSN)%'
```
```
parameters:
    env(WAREHOUSE_DSN): '%env(default::'')%'
```

```
In EnvPlaceholderParameterBag.php line 46:
                                                                               
  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]   
  Invalid env(default::WAREHOUSE_DSN) name: only "word" characters are allowe  
  d.     
```

This worked:
```
parameters:
    env(WAREHOUSE_DSN): ~
```

It could be just our specific setup that manifests these issues - trying to use an empty string as a default, when we could use a `null` value.

**Comment by alcaeus** [comment]
I believe changing the `server` parameter to the following should do the trick:

`server: "%env(resolve:default::WAREHOUSE_DSN)%"`. Could you give that a shot?

**Comment by ychanan** [comment]
Thanks, we'll give that a try once we upgrade to Symfony 4.3, we're currently on 4.2.7 and `default` is not supported yet.

**Comment by alcaeus** [comment]
> Thanks, we'll give that a try once we upgrade to Symfony 4.3, we're currently on 4.2.7 and `default` is not supported yet.

If you don't want to wait, you can always register your own `default` env var processor and use the upcoming class to do so.

Either way, closing this here as there's nothing we can do when we're given an invalid connection string: we're merely passing it on to the underlying library.
