### ISSUE TITLE
Support metadata class name resolution in ResolveTargetDocumentListener

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#1993]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | yes

#### Summary

The `ResolveTargetEntityListener` in ORM not only supports changing the `targetEntity` attribute for associations but also doing a secondary ClassMetadata lookup in case the original class was not found. This secondary behaviour is not supported in the `ResolveTargetDocumentListener` yet because of the missing `onClassMetadataNotFound` event handling.

This functionality should be added to ODM as well, but it requires several changes:
* Introduce the `onClassMetadataNotFound` event along with its object
* Add support for the `onClassMetadataNotFound` event in `ResolveTargetDocumentListener`
* Change `ResolveTargetDocumentListener` to be an event subscriber instead of an event listener (BC break)

**Comment by emulienfou** [comment]
Hi @alcaeus just made the changes here:
* `ResolveTargetDocumentListener` has an event subscriber in this branch [here](https://github.com/emulienfou/mongodb-odm/tree/listener-event-subscriber)
* Introducing class `onClassMetadataNotFound` in this branch [here](https://github.com/emulienfou/mongodb-odm/tree/introducing-class-metadata-not-found)

I also update the **DoctrineMongoDBBundle** to register the service as an event_subscriber [here](https://github.com/emulienfou/DoctrineMongoDBBundle/tree/event-subscriber)

> I will made Pull Requests about this 3 modifications

**Comment by emulienfou** [comment]
Hi @alcaeus however I think there is something I missed, I cannot figured out why the `getSubscribedEvents()` method is not triggered.

Here is the cache result for the service after updating the ODM bundle:
```
<service id="doctrine_mongodb.odm.listeners.resolve_target_document" class="Doctrine\ODM\MongoDB\Tools\ResolveTargetDocumentListener" public="false">
      <tag name="doctrine.event_subscriber"/>
      <call method="addResolveTargetDocument">
        <argument>Symfony\Component\Security\Core\User\UserInterface</argument>
        <argument>App\Document\User</argument>
        <argument type="collection"/>
      </call>
    </service>
```

When debugging the event manager, no listeners are registered. Cannot figured out why.
If you got some times to check that?

**Comment by emulienfou** [comment]
Never mind, I figured out my issue

**Comment by alcaeus** [comment]
Sorry for the delay, the past couple of days have been extremely stressful. Please create pull requests for the respective branches and I'll review them either tonight or in the next couple of days. Thank you!

**Comment by alcaeus** [comment]
Both PRs have been merged with support in the bundle coming soon. Closing here.
