### ISSUE TITLE
Doctrine matching collection in mongodb-odm

### ISSUE THREAD

**Issue by etshy** [doctrine/mongodb-odm#1994]
|    Q        |   A
|------------ | -----
| Version     | 2.0

### Doctrine Common Feature Question

That's not really a support question, but a question about v2.0.

I recently saw the matching method on Collection in ORM documentation. (https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/working-with-associations.html#filtering-collections)

As this matching method seems to be in Doctrine\Common\Collection, I guess it should be possible to use it (or implement it, if it need a bit of work inside this repo) in mongodb-odm, so I wanted to know if it's planned to add it  ?

ps : I admit I didn't try if it was already available before posting this, but as I didn't see anything in the doc related too that, I thought abour asking the question directly.

**Comment by alcaeus** [comment]
This is tracked in #929 and currently scheduled for a 2.x release, meaning that it won't happen in 2.0 but is also not scheduled for any other release. I've built something like this for an app of mine, but it doesn't really deal with edge cases (e.g. how does `matching()` work with inverse references using a `repositoryMethod`?

I'm closing this in favour of #929 - if you are willing to work on this, please let me know as I'd greatly appreciate it!

**Comment by etshy** [comment]
I didn't see the previous issue, sorry.

I'll read the other issue, and will test a bit of things about it.
