### ISSUE TITLE
Problem with proxy permission due to Ocramius possible bug?

### ISSUE THREAD

**Issue by josefsabl** [doctrine/mongodb-odm#1999]
Hey guys, it's me again :-) The problem with write permissions for proxy directory is ironed out I guess. Here comes problem with write permissions for proxy FILE :-)

### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | dev-master

#### Summary

Although strictly not a bug in Doctrine ODM, the new version introduces dependency on Ocramius/ProxyManager so I suppose this counts as BC break.

Please see this bug report on Ocramius page:
https://github.com/Ocramius/ProxyManager/issues/459

**Comment by josefsabl** [comment]
Looks like Ocramius already has this patched in dev-master.

**Comment by alcaeus** [comment]
Confirmed to be a bug in `ocramius/proxy-manager` - nothing to do here. Closing as there's nothing we should fix.

Also, bugs in other libraries are no BC break, and even if: this is 2.0 where they are to be expected.

**Comment by josefsabl** [comment]
Okay, fair enough. Thank you.

Ocramius seems to have this fixed is his 2.3 that requires PHP 7.4. I see that there is a request to backport this to php 7.3 so let's hope it gets fixed soon.

Btw, BC break bugs that make the library unusable for some people are not a good bread of BC break and I think they require some special attention ;-)

**Comment by josefsabl** [comment]
Will be fixed with: https://github.com/Ocramius/ProxyManager/issues/458
