### ISSUE TITLE
Add package name to deprecations

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#2010]
As suggested by @nicolas-grekas in https://github.com/doctrine/DoctrineBundle/pull/951#discussion_r272850188 and @greg0ire in https://github.com/doctrine/mongodb-odm/pull/2005#discussion_r275119872, we should make sure to add the package name to all deprecations messages. Currently, some simply say "will be removed in 2.0", others use some variation of "ODM 2.0". To allow users to quickly pinpoint where those deprecations are coming from, we should always use the full package name, like "in doctrine/mongodb-odm 2.0".

**Comment by greg0ire** [comment]
I should have quoted my source for this idea: a discussion with @nicolas-grekas on the train to the EUC hackathon :)

**Comment by alcaeus** [comment]
It's a great idea. The way we have many deprecation notices set up right now, people might not realise what package is causing it without looking at the trace. They shouldn't have to do that.
