### ISSUE TITLE
Hash indexes with digits are populated as integers 

### ISSUE THREAD

**Issue by dossorio** [doctrine/mongodb-odm#2028]
I have looked for a similar issue everywhere but couldn't find anything related, apologies if its been asked somewhere else.

When using `Field(type="hash")` lets say to store the following object:
```javascript
aField: {
  2019: 1234,
  anotherIndex: 5678
}
```

`2019` and `anotherIndex` are properties of that object, but when the object is hydrated and the associative php array created, `2019` is created as an integer:
```php
array(2) {
  [2019]=>
  int(1234)
  ["anotherIndex"]=>
  int(5678)
}
```

|    Q        |   A
|------------ | -----
| Version     | 1.1.2

### Support Question

We were expecting the indexes to all be strings, in order to be consistently checking by type as well. Is this expected?

**Comment by alcaeus** [comment]
How do you store the document? I created a functional test to check and the behaviour is what we expect: https://gist.github.com/alcaeus/30592b53acbd96d35d57391c515807bd.

**Comment by Drygba** [comment]
This is expected behavior. 
https://www.php.net/manual/en/language.types.array.php

> The key can either be an integer or a string. The value can be of any type.
> 
> Additionally the following key casts will occur:
> 
>Strings containing valid decimal integers, unless the number is preceded by a + sign, will be cast to the integer type. E.g. the key "8" will actually be stored under 8. On the other hand "08" will not be cast, as it isn't a valid decimal integer.
