### ISSUE TITLE
Cannot use object of type MongoId as array in unitOfWork.php

### ISSUE THREAD

**Issue by kailashkds** [doctrine/mongodb-odm#2029]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.2.9

#### Summary

 ```
  /**
     * @Document
     * @InheritanceType("SINGLE_COLLECTION")
     * @DiscriminatorField("type")
     * @DiscriminatorMap({"person"="Person", "employee"="Employee"})
    */
   class Person
  {
    // ...
  }

   /**
    * @Document
    */
    class Employee extends Person
    {
       // ...
    }`
```

   **now if I use**
   ```
    /**
      * @MongoDB\ReferenceOne(targetDocument="Person", simple=true)
      */
      private $createdBy;
```
  or```

     /**
      * @Document
      */
      class Logs
      {
        ......
        ......
         /**
          * @MongoDB\ReferenceOne(targetDocument="Employee", simple=true)
         */
         private $createdBy;
      }
```
this gives an error while I am using FindBY on Logs. Below is the error
Cannot use object of type MongoId as array
in UnitOfWork.php below line
      ```
  if (isset($discriminatorField, $data[$discriminatorField])) {
            $discriminatorValue = $data[$discriminatorField];
        } elseif (isset($mapping['defaultDiscriminatorValue'])) {
            $discriminatorValue = $mapping['defaultDiscriminatorValue'];

```
I have used 
https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2/reference/inheritance-mapping.html#single-collection-inheritance

**Comment by malarzm** [comment]
@kailashkds I believe your issue stems from using a `simple=true` on a reference to a discriminated document. I'm not 100% sure though so if you could please prepare a failing test case that would clear things up for me as I'm also not sure what is the BC break you're facing. You can take a look at out [functional tests](https://github.com/doctrine/mongodb-odm/tree/master/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket) and write one alike.

**Comment by Steveb-p** [comment]
@malarzm I believe @kailashkds just set it as BC break unknowingly.
