### ISSUE TITLE
Doctrine\MongoDB\LoggableCollection::aggregate deprecation

### ISSUE THREAD

**Issue by xNarkon** [doctrine/mongodb-odm#2030]
`The "Doctrine\MongoDB\LoggableCollection::aggregate()" method will require a new "array $op" argument in the next major version of its parent class "Doctrine\MongoDB\Collection", not defining it is deprecated.`

**Comment by alcaeus** [comment]
The upcoming 2.0 version has entirely different methods here, as it no longer uses `doctrine/mongodb`. Also, please refrain from creating multiple issues for the same topic across repositories. Thanks!
