### ISSUE TITLE
CommandLogger doesn't collect commands data 

### ISSUE THREAD

**Issue by markitosgv** [doctrine/mongodb-odm#2037]
### Bug Report

CommandLogger doesn't collect commands data 

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.0.0-RC1

#### Summary

Using Symfony 4 with MongoDBBundle, I see that CommandLogger is subscribed to MongoDB monitoring but after that commandStarted or commandSucceeded never be triggered. 

#### Current behavior

It doesn't get any data

#### How to reproduce

Using symfony 4 mongodbbundle, mongodb extension 1.5.3

#### Expected behavior

Gets command queries data

**Comment by alcaeus** [comment]
After checking, this is an error in the registration of command subscribers in the bundle. Registering them manually works as expected, so I'm closing this since the fix is in the bundle. Thanks for the report!
