### ISSUE TITLE
Type error when data from database is incompatible with mapping

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#2044]
This is the root cause for the issue described in https://github.com/doctrine/DoctrineMongoDBBundle/issues/564: a property was mapped as an embedded document, but the data received from the database was a scalar value. In order to avoid type errors, the hydration logic needs to better assert expected types.

**Comment by malarzm** [comment]
FWIW have no idea we can fail gracefully if we expect an object and get a scalar. Unless more gracefully as throw an exception instead of a type error? :)

**Comment by alcaeus** [comment]
Fixed in #2073
