### ISSUE TITLE
Documentation for migration to 2.x

### ISSUE THREAD

**Issue by eopaquette** [doctrine/mongodb-odm#2045]
#### Summary

Please provide a documentation for the migration from 1.x to 2.0 concerning all changes up to namespaces. 

Thx.

**Comment by alcaeus** [comment]
Cross-referencing https://github.com/doctrine/mongodb-odm/pull/2038#issuecomment-509716753 for completeness.

I can add a section to the UPGRADING docs to explain this process, but in theory, it will be straightforward. Alongside ODM 2.0, we'll also release ODM 1.3, which is available to everyone currently running on 1.2. This release will trigger deprecation notices for all BC breaks when updating to 2.0. One of the main components will be the driver upgrade, which requires users to migrate from `Mongo*` classes to their `MongoDB\Driver` equivalents. This will be explained in more detail in https://jira.mongodb.org/browse/PHPLIB-455, which I hope to tackle soon. Once that documentation is complete, we'll link it in the UPGRADE document for ODM 2.0.

**Comment by alcaeus** [comment]
I've written a little about the upgrade process in a blog post on the Doctrine website: https://www.doctrine-project.org/2019/09/30/mongodb-odm-1.3.0-and-2.0.0-RC2.html. The UPGRADE document also contains all BC breaks that you'll encounter. This list was compiled using [roave/backward-compatibility-check](https://packagist.org/packages/roave/backward-compatibility-check) to make sure that we catch all BC breaks. The list of BC breaks from 1.3 to 2.0 is also available as a gist: https://gist.github.com/alcaeus/b8c1b38e297cc957e991683bef069771.

Unfortunately, the BSON type migration documentation isn't done yet. I'll bring the relevant ticket up again at our triage meeting today and try to get it scheduled. In the meantime, I'm closing this as this is outside of the scope of ODM documentation.

**Comment by jmikola** [comment]
PR for BSON type migration is in https://github.com/mongodb/mongo-php-library/pull/685. I'll aim to get this reviewed, merged, and deployed soon.

@eopaquette Feel free to follow that issue for updates. Once the changes are deployed, you should find them on https://docs.mongodb.com/php-library/current/upgrade/.
