### ISSUE TITLE
$toInt aggregation operator unavailable?

### ISSUE THREAD

**Issue by arevai** [doctrine/mongodb-odm#2047]
Is $toInt aggregation operator available?

**Comment by jcaillot** [comment]
let's say our document has already a 'price' (decimal) field, we can extract some new fields:

```
$builder = $dm->createAggregationBuilder(OurDocument::class);

// Caution: the single quotes are absolutely required here to allow the use of the $ sign:

$builder->addFields()
             ->field("to_int")
             ->expression(  ['$toInt' => '$price' ]  )
            ->field("double")
            ->expression(  ['$multiply' => ['$price', 2 ] ]  );

$result = $builder->execute();

```
All. available operators are detailed here : https://docs.mongodb.com/manual/reference/operator/aggregation/

**Comment by Steveb-p** [comment]
That would make a nice addition to docs actually.

**Comment by arevai** [comment]
Awesome, thanks!

**Comment by alcaeus** [comment]
Using `expression` is the preferred way to use new operators that don't have a native method yet.

As for the `$toInt` operator itself, we will work on aggregation improvements in 2.1, which includes adding all new operators and new stages added since we last worked on aggregation here.
