### ISSUE TITLE
Tools for working with GridFS

### ISSUE THREAD

**Issue by nimleaf** [doctrine/mongodb-odm#2049]
|    Q        |   A
|------------ | -----
| Version     | 2.0

### Support Question

Hi, does doctrine 2 supports mongo tools for working with GridFS? I want to store file with many versions, then get its history.

**Comment by alcaeus** [comment]
GridFS is supported both in 1.x as well as 2.0, however the APIs are very different. With respect to multiple versions, these are stored as individual documents as per the [GridFS spec](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst). Accessing older revisions varies greatly between versions.

In 1.x, there is no built-in way to access older revisions. Instead, you query files by filename and then select the appropriate revision to open.
For 2.0, you should be able to specify the `revision` when opening a download stream for a file by filename. However, the `DefaultGridFSRepository` class shipped in 2.0 does not have an accessor for this, so you have to either build this yourself or again query all documents, then retrieving the identifier of the revision you want to look at and then call `openDownloadStream` or `downloadToStream` with the identifier.

I've created #2050 to track adding an API to access older revisions of a file directly without having to query for all revisions of a file.
