### ISSUE TITLE
Getting PHP value in `Type::convertToPHPValue()`

### ISSUE THREAD

**Issue by petr-buchin** [doctrine/mongodb-odm#2098]
I'm not sure, whether this is a bug or expected behavior, so I'll try to explain an issue first.

I have my custom mapping type, which looks like this:

```php
namespace App\MongoDB\Type;

use App\ValueObject\DocumentId;
use Doctrine\ODM\MongoDB\Types\ClosureToPHP;
use Doctrine\ODM\MongoDB\Types\Type;
use MongoDB\BSON\ObjectId;

class DocumentIdType extends Type
{
    use ClosureToPHP;

    /**
     * @param ObjectId $value
     *
     * @return DocumentId
     */
    public function convertToPHPValue($value): DocumentId
    {
        return DocumentId::fromString((string)$value);
    }

    /**
     * @param DocumentId $value
     *
     * @return ObjectId
     */
    public function convertToDatabaseValue($value): ObjectId
    {
        return new ObjectId($value->toString());
    }
}
```

I also use **Symfony Messenger** component, and one of my message handlers returns a document, which has field with this `DocumentIdType`.

However, when I run my application, I get an exception. Long story short - my method `DocumentIdType::convertToPHPValue()` receives `DocumentId` (which is already PHP value) instead of `ObjectId`.

So the question is: is this an expected behavior for custom types to recieve "php values" in `convertToPHPValue()` method? Should I add check for that to my method, or is this a bug?

If this is a bug - I will be happy to reproduce this with a minimal set of dependencies and will create a report in an appropriate repository (which depends on what is in charge for that behavior).

**Comment by alcaeus** [comment]
Looking at usages of `convertToPHPValue`, the only place it is used for is [`ClassMetadata::getPHPIdentifierValue`](https://github.com/doctrine/mongodb-odm/blob/56408ed68687a6d826230881d87720dccf54f4e4/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php#L1391), which is called in a few places in the document lifecycle. I've examined a few of the calls, and they seem to call `getPHPIdentifierValue` with the value received from the database before converting it, so this may indeed be an issue. A trace of a call where you expect an `ObjectId` but receive a string would be helpful in analysing this.

That said, all of the built-in types don't make assumptions about the type of what they receive, since the data may not be of the type they initially expect. I assume this was a deliberate decision at the time this was implemented, as a field in MongoDB may have very different types that can't really be enforced. However, you don't expect to receive an instance of a PHP object that has no place in the database, so I'd definitely like to take a deeper look at this.

**Comment by petr-buchin** [comment]
@alcaeus thank you very much for the quick reply!

I've looked at the stack trace attentively and figured out that this behavior is the result of me calling `DocumentManager::getReference()` with a php value (`DocumentId`) instead of db value (`ObjectId`).

`StaticProxyFactory` then calls `ClassMetadata::setIdentifierValue()`, which tries to convert value to its PHP representation.

Here's part of my stack trace:

```
  at /var/www/html/src/MongoDB/Type/DocumentIdType.php:21
 App\MongoDB\Type\DocumentIdType->convertToPHPValue() at /var/www/html/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php:1395

 Doctrine\ODM\MongoDB\Mapping\ClassMetadata->getPHPIdentifierValue() at /var/www/html/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php:1421

 Doctrine\ODM\MongoDB\Mapping\ClassMetadata->setIdentifierValue() at /var/www/html/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Proxy/Factory/StaticProxyFactory.php:56

 Doctrine\ODM\MongoDB\Proxy\Factory\StaticProxyFactory->getProxy() at /var/www/html/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentManager.php:586

 Doctrine\ODM\MongoDB\DocumentManager->getReference() at ...
```

This means that I created issue in a wrong repository. This should have been created in ODM repository itself - sorry for that.

However, I'd say that as a user of ODM I expect method `DocumentManager::getReference()` to accept PHP identifier value, not DB value.

At least it should be documented, that this method accepts DB value.

**Comment by alcaeus** [comment]
In general, we expect that users may pass PHP types wherever they interact with ODM, as it's the job of ODM to convert this to the appropriate types. So passing a PHP type to `DocumentManager::getReference()` is definitely correct. If we take a closer look at that method, there are two different code paths.

The first path takes us into `DocumentManager::tryGetById()`, where the ID is converted to a database identifier: https://github.com/doctrine/mongodb-odm/blob/1e5806a96e36890e9d804fa366ed771c41dd5bed/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L1492
So `tryGetById()` (and, by extension, `getReference()`) definitely expects a PHP identifier for the document.

The second code path takes us into `ProxyFactory::getProxy()` followed by `UnitOfWork::registerManaged()`. The former calls `ClassMetadata::setIdentifierValue()`, which converts the identifier to a PHP value: https://github.com/doctrine/mongodb-odm/blob/1e5806a96e36890e9d804fa366ed771c41dd5bed/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php#L1421

`UnitOfWork::registerManager()` also converts the identifier to PHP value before storing it in the identifier list: https://github.com/doctrine/mongodb-odm/blob/1e5806a96e36890e9d804fa366ed771c41dd5bed/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L2727

Based on those findings, the code underlying `DocumentManager::getReference()` is equipped to handle both cases, which is in line with many other places where we handle type conversion from database types to PHP types and back if necessary. For example, the following two builder snippets end up with the same query:
```php
$builder->field('id')->equals('123456789012345678901234');
$builder->field('id')->equals(new ObjectId('123456789012345678901234'));
```

If we take a look at the default ODM type classes, we can see that most of them are equipped to handle both PHP and database types in the `convertToDatabaseValue()` and `convertToPHPValue()` methods:
* `BinDataType`: https://github.com/doctrine/mongodb-odm/blob/1e5806a96e36890e9d804fa366ed771c41dd5bed/lib/Doctrine/ODM/MongoDB/Types/BinDataType.php#L30 and https://github.com/doctrine/mongodb-odm/blob/1e5806a96e36890e9d804fa366ed771c41dd5bed/lib/Doctrine/ODM/MongoDB/Types/BinDataType.php#L43
* `DateType`: https://github.com/doctrine/mongodb-odm/blob/1e5806a96e36890e9d804fa366ed771c41dd5bed/lib/Doctrine/ODM/MongoDB/Types/DateType.php#L87 and https://github.com/doctrine/mongodb-odm/blob/1e5806a96e36890e9d804fa366ed771c41dd5bed/lib/Doctrine/ODM/MongoDB/Types/DateType.php#L42
* `ObjectIdType`: https://github.com/doctrine/mongodb-odm/blob/1e5806a96e36890e9d804fa366ed771c41dd5bed/lib/Doctrine/ODM/MongoDB/Types/ObjectIdType.php#L19 and https://github.com/doctrine/mongodb-odm/blob/1e5806a96e36890e9d804fa366ed771c41dd5bed/lib/Doctrine/ODM/MongoDB/Types/ObjectIdType.php#L28

So from those example, I would suggest that both these methods should expect to receive **any** value and be able to convert it to the requested format. The type should make a best effort to convert to the formats, but it is ok to throw an exception if this can't be done. Prior art for exceptions during type conversion can be found in `DateType`: https://github.com/doctrine/mongodb-odm/blob/2.0.x/lib/Doctrine/ODM/MongoDB/Types/DateType.php#L65

I agree that the documentation is very vague or outright wrong when explaining this. I've created #2101 to clarify this in the documentation and to potentially create a section in the manual about how to create a custom type. I hope the above clarifies the problem a bit.

**Comment by petr-buchin** [comment]
@alcaeus thanks for such a detailed explanation!
I am closing this issue in favor of #2101.
