### ISSUE TITLE
Some documentation pages don't show up in the table of contents

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#2099]
### Bug Report

While looking up some documentation, I noticed that the [Reference mapping documentation](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.0/reference/reference-mapping.html#mixing-document-types) is not linked in the table of contents of the website. We should add this and double-check to make sure all documentation is accessible on the website.

**Comment by malarzm** [comment]
This is weird, I see the link in https://github.com/doctrine/mongodb-odm/blob/2e1d0bfd4b325449030c0bfde2ebd273cefba10a/docs/en/sidebar.rst but not on the website

**Comment by SenseException** [comment]
Maybe there's something wrong with the page itself or the rst build. This needs further investigations.

**Comment by maxgorovenko** [comment]
Wow! Found some very-very useful pages! I think you underestimate this bug.

**Comment by maxgorovenko** [comment]
Can someone say how this doc builds? Did not find any scripts|configs inside this repo. Have some ideas, did fix, but can't check :(

**Comment by jcaillot** [comment]
The doc surely needs some love. I guess one can assume it is built with sphinx? Should not the doc be versioned in the repo and come with it? Twig does that. It might result in too may PR though... (just thinking out loud)

**Comment by alcaeus** [comment]
Pinging @SenseException for help with the docs system.

**Comment by maxgorovenko** [comment]
Trying to build with this extensions, but still got problems with toc in sidebar:
```
extensions = [
    'sensio.sphinx.configurationblock',
    'sensio.sphinx.phpcode',
    'sphinxcontrib.fulltoc'
]
```

**Comment by SenseException** [comment]
The node injected in `Doctrine\RST\Directives\Toctree::process()` contains the list of the files, but some of them already have a borked format.

```
/reference/introduction
/reference/architecture
/reference/console-commands
/reference/basic-mapping
/reference/custom-mapping-types
/reference//reference-mapping
/reference/bidirectional-/references
...
```

It seems it's not a problem of the rst toctree, but of the parser. The ones like `/reference//reference-mapping` and `/reference/bidirectional-/references` are missing as far as I can see on the website.

**Comment by malarzm** [comment]
@SenseException any idea how could that be happening? Links in https://github.com/doctrine/mongodb-odm/blob/2.3.x/docs/en/sidebar.rst are correct :/

**Comment by maxgorovenko** [comment]
I guess the problem could be in word `reference` which can be kind of reserved word. But I didn't find out how the doc has been generated :(

**Comment by malarzm** [comment]
@maxgorovenko I think that might be partially true! But I think it's not a reserved word but a wrong search-and-replace, something like `reference` to `/reference` which doesn't stop after first replacement. @SenseException does it ring any bell for the build process?

**Comment by malarzm** [comment]
Got it! https://github.com/doctrine/doctrine-website/blob/c6c909842136085cb05f202b03a7d56387ce0d8e/lib/Docs/RST/RSTCopier.php#L171

**Comment by SenseException** [comment]
You were faster. :-D
