### ISSUE TITLE
Replace generators with IteratorIterator in custom iterators

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#2105]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | improvement
| RFC         | no
| BC Break    | no

#### Summary

The `HydratingIterator` and `CachingIterator` classes use generators to wrap the given traversable. As described in #2092 and fixed in #2100, this can leak memory if the iterator class is destroyed while the generator isn't exhausted completely.

`IteratorIterator` can be used instead, but since there are some changes to generators with respect to rewind, the change shouldn't be done in a patch release.

**Comment by soyuka** [comment]
What's the status on this @alcaeus ?

**Comment by alcaeus** [comment]
The status is the same as five years ago, except that I have no recollection of what the issue was 🤦‍♂️ 

Did you encounter an issue around iterators that needs addressing?

**Comment by soyuka** [comment]
I think we should close this, I'll open a new one if I can reproduce!

**Comment by alcaeus** [comment]
No complaints from me 😊
