### ISSUE TITLE
First file will not be stored in GridFS if database does not exist

### ISSUE THREAD

**Issue by blakyris** [doctrine/mongodb-odm#2109]
I stored music tracks in GridFS and when I test my app I always delete the DB before trying a new upload of a song just to be sure the data I flush is correctly stored in DB
But when I upload the first file all the metadata and file chunks are stored but not the file ref in fs.file.
So my API is returning an error.

Here is my function that add a song in my DB :

```
    public function addFileToLibrary(String $path)
    {
        $tagger = new TagEditor();

        $file = $this->documentManager->getRepository(File::class)->uploadFromFile($path);

        $tags = $tagger->getTags($path);

        $track = new Track();

        if ($artist = $this->isArtistInLibrary($tags['tags']['albumArtist'])) {
            $albumArtist = $artist;
        } else {
            $albumArtist = new Artist();
            $albumArtist->setName($tags['tags']['albumArtist']);
            $this->documentManager->persist($albumArtist);
        }

        $artists = array(); 
        foreach($tags['tags']['artists'] as $artist) {

            if ($a = $this->isArtistInLibrary($artist)) {
                $artists[] = $a;
            } else {
                $a = new Artist();
                $a->setName($artist);
                $this->documentManager->persist($a);
                $artists[] = $a;
            }
        }   

        if ($albumObj = $this->isAlbumInLibrary($tags['tags']['album'], $albumArtist)) {
            $album = $albumObj;
        } else {
            $album = new Album();
            $album->setName($tags['tags']['album']);
            $album->setArtist($albumArtist);
            $this->documentManager->persist($album);
        }

        $track->setFile($file);
        $track->setTitle($tags['tags']['trackTitle']);
        $track->setArtists($artists);
        $track->setAlbum($album);
        $track->setAlbumArtist($albumArtist);
        $track->setTrackNumber((int) $tags['tags']['trackNumber']);
        $track->setGenre($tags['tags']['genre']);
        $track->setFormat($tags['fileInfo']['format']);
        
        $this->documentManager->persist($track);
        $this->documentManager->flush();
    }
```

**Dev environnment :**

Windows 10 1909 + WSL Ubuntu + PHP7.2 + NGINX + MongoDB latest + MongoDB PHP Driver 1.6

**Test environnement :**

Ubuntu 18.04 + PHP7.2 + NGINX + MongoDB latest + MongoDB PHP Driver 1.6

**Comment by malarzm** [comment]
Transfering the issue to ODM repository as bug is about it, not the bundle itself.

**Comment by alcaeus** [comment]
I've tried to reproduce this by removing the test database and running the test for `uploadFromFile` ([link to code](https://github.com/doctrine/mongodb-odm/blob/92e4514d9ec4928710edd0381da89fe7c1e9cbc5/tests/Doctrine/ODM/MongoDB/Tests/Repository/DefaultGridFSRepositoryTest.php#L167)). This worked as expected, with content being stored in both `fs.files` and `fs.chunks` collections, so the upload works as expected.

Please clarify what data is present in the database after that action, along with any error messages you encounter ("my API is returning an error"). If you can come up with a small, reproducible test case it would help in fixing this.

**Comment by blakyris** [comment]
I don't know how to reproduce your case. I tryed to flush after adding the file and it doesn't solve the issue. I don't do checking with assert after inserting my documents because I don't want to do it now but I'm not sure it comes from that. (the only difference between the test code and my code.)

**Comment by blakyris** [comment]
And also I don't force Doctrine to set a filename, because I dont want one.
I'm doing a One-to-One relation between tracks and files.
My track contains A file.

**Comment by blakyris** [comment]
![image](https://user-images.githubusercontent.com/10896518/69346612-60060100-0c73-11ea-9431-4f45a4afb88f.png)
