### ISSUE TITLE
Allowing version 5.0 for Symfony components

### ISSUE THREAD

**Issue by petr-buchin** [doctrine/mongodb-odm#2120]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

For now ODM users cannot update to a new major version of Symfony framework - `v5.0`, since odm's `composer.json` requires versions of a few symfony components, bumped to `^3.4` or `^4.1`.

We should update `composer.json` to allow version `^5.0` for this dependencies.

**Comment by SenseException** [comment]
Symfony 5 support was introduced in PR #2115. Thank you.
