### ISSUE TITLE
Deprecate integer and boolean types

### ISSUE THREAD

**Issue by malarzm** [doctrine/mongodb-odm#2124]
And suggest to use `int` and `bool` instead. FTR I'm not sure if we should switch those types at runtime as somebody might have overridden built-in type (or is that too far fetched?)

**Comment by antonintouron** [comment]
Documentation not updated (boolean instead bool) => https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.2/reference/basic-mapping.html

![image](https://user-images.githubusercontent.com/37710765/155495383-c639284f-5677-4772-b75b-b7046e62d468.png)
