### ISSUE TITLE
Proxy generation and autoloading

### ISSUE THREAD

**Issue by olvlvl** [doctrine/mongodb-odm#2132]
|    Q        |   A
|------------ | -----
| Version     | 2.0

### Support Question

I originally created this issue over here: https://github.com/Ocramius/ProxyManager/issues/531.

We recently upgraded  to `mongodb-odm` v2 and we're facing an issue with the proxy generation. You see, we generate the hydrators and proxies before building our docker images, and the _cache_ folder is readonly after this point. `ProxyManager\Factory\AbstractBaseFactory::generateProxy()` uses `class_exists()` to determine if a proxy needs to be generated or not, and after this point it seems there's nothing that checks that the file actually needs to be generated, and the application crashes when the proxy manager tries to move the temporary file into the readonly cache folder.

https://github.com/Ocramius/ProxyManager/blob/4d7be24018475d2627ab74078e912ca9ef5887d2/src/ProxyManager/Factory/AbstractBaseFactory.php#L70

Ocraminus recommended using `classmap` to autoload the proxies. It works, but it makes working with our application complicated because we need to run `compose dump --no-dev` before we generate the proxies (so the classmap doesn't contain outdated references) and run it again after so the classmap includes the generated files.

We don't have to do any of this for hydrators, could there be a nicer solution that doesn't involve using `classmap`?

**Comment by alcaeus** [comment]
Do you use DoctrineMongoDBBundle for Symfony or do you configure ODM yourself? If you use Symfony and the bundle, you can change this by updating the proxy generation strategy to not auto-generate proxies. This will register an autoloader for proxies in the bundle: https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/DoctrineMongoDBBundle.php#L63..L70.

Then, you can pair this with the `doctrine:mongodb:generate:proxies` command to generate proxies while building your docker container.

If you don't use Symfony, use the `odm:generate:proxies` command to dump proxies and register the autoloader yourself.

**Comment by olvlvl** [comment]
We don't use Symfony, we configure the ODM ourselves, and we use [this package](https://github.com/olvlvl/doctrine-generators) to generate the hydrators and the proxies. I'll have a look at `odm:generate:proxies`, but are you suggesting we should register an additional autoloader for the proxies? We're not doing anything special for the hydrators, and the proxies used to work fine. Would you be so kind to point me to an example in the documentation?

**Comment by alcaeus** [comment]
Hydrators and Proxies work significantly different: Hydrators are required manually, while the proxy manager depends on an autoloader. It's just a different concept of dealing with generated code.

The [Setup documentation](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.0/reference/introduction.html#setup) has a section on how to configure proxies, along with a message (typo included):
> The last call to `spl_autoload_regiter` is necessary to autoload generated proxy classes. Without this, the proxy library would re-generate proxy classes for every request. See the tuning for production chapter in ProxyManager's documentation.

FWIW, the functionality in your package is already provided by ODM itself via the `odm:generate:hydrators` and `odm:generate:proxies` commands. There's also a `odm:generate:persistent-collections` command to generate classes for custom collections, as those will suffer from the same problem as hydrators.

**Comment by olvlvl** [comment]
Thank you very much @alcaeus, this is much simpler. I'll have a look at these commands.
