### ISSUE TITLE
Incorrect `persist` method behavior

### ISSUE THREAD

**Issue by TheHett** [doctrine/mongodb-odm#2134]
It's normal that I can pass `managed` document to another `DocumentManager`?
As I understand it, the `persist` method should only accept new documents?

Next code works fine:
```
        $dm1 = $this->dmFactory->createDocumentManager();
        $dm2 = $this->dmFactory->createDocumentManager();

        $fo1 = new FileObject();
        $fo1->setName("xxx");
        $dm1->persist($fo1);
        $dm1->flush();

        $fo1->setName("yyy");
        $dm2->persist($fo1);
        $dm1->flush();
```

**Comment by alcaeus** [comment]
The two object managers don't know each others' documents, so while `$fo1` is managed in `$dm1`, `$dm2` sees it as unmanaged entity. Even then, `persist` also accepts already managed documents and is used in explicit change tracking strategies to mark objects for update.

**Comment by TheHett** [comment]
hmm, I thought the proxy contains information about this.
Is it normal that programmers use `persist` to translate an entity state into `managed` from one DM to another?

**Comment by alcaeus** [comment]
No, but we have no way of preventing this.

**Comment by TheHett** [comment]
Code must lock like this, right ?

```
        $dm1 = $this->dmFactory->createDocumentManager();
        $dm2 = $this->dmFactory->createDocumentManager();

        $fo1 = new FileObject();
        $fo1->setName("xxx");
        $dm1->persist($fo1);
        $dm1->flush();
   
        $fo2 = $dm2->merge($fo1);
        $fo2->setName("yyy");
        $dm1->flush();
```
