### ISSUE TITLE
Annotation Driver deprecation error after doctrine/persistence upgrade to 1.3.2

### ISSUE THREAD

**Issue by binary-data** [doctrine/mongodb-odm#2136]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.0.3

#### Summary

I ran ```composer update``` and I see that ```doctrine/persistence``` was updated to version **1.3.2** just recently. And without any changes to my code I see an exception:
```
The Doctrine\Common\Persistence\Mapping\Driver\AnnotationDriver class is deprecated since
doctrine/persistence 1.3 and will be removed in 2.0. Use 
 Doctrine\Persistence\Mapping\Driver\AnnotationDriver instead.
```

I was using the Annotation Driver. Here is a code snippet:

```
use Doctrine\ODM\MongoDB\Configuration;
use Doctrine\ODM\MongoDB\Mapping\Driver\AnnotationDriver;

$config = new Configuration();

// skip setting proxies, db and hydrators

// Here I get the deprecation error
$config->setMetadataDriverImpl(AnnotationDriver::create(APPROOT . 'Entity'));

```

**As a workaround**, I manually installed ```doctrine/persistence``` 1.2.0 via Composer, and the Annotation Driver seems to be working as before.

#### Current behavior

Annotation Driver doesn't work, throwing a deprecation error described above.

#### How to reproduce

1. Install Doctrine MongoDB ODM v2.0.3.
2. Create it's configuration using docs: https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.0/tutorials/getting-started.html#persistent-models or https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.0/reference/introduction.html#setup
3. Pass return value of the \Doctrine\ODM\MongoDB\Mapping\Driver\AnnotationDriver::create to the \Doctrine\ODM\MongoDB\Configuration::setMetadataDriverImpl method

#### Expected behavior

The Annotation Driver should not throw deprecation error.

**Comment by alcaeus** [comment]
If you see an exception for a deprecation error, please reconsider whatever tool you are using to convert PHP warnings into exceptions: a warning should never cause an exception to be thrown.

That said, we'll update ODM to work with persistence 1.3 soon. Until then, either use 1.2 or apply the solution above.

**Comment by binary-data** [comment]
@alcaeus Thanks, this was the case.
