### ISSUE TITLE
1.3.0 is declared to work in ^5.6 || ^7.0 composer.json but uses PHP 7 feature

### ISSUE THREAD

**Issue by AronSzigetvari** [doctrine/mongodb-odm#2138]
### BC Break Report

After updating from 1.2, on php 5.6.40 the following error occurred: 
Doctrine\ODM\MongoDB\Mapping\MappingException::__construct() must be an instance of Throwable, instance of ReflectionException given

Composer updated to this version because composer.json contains:
```    "require": {
        "php": "^5.6 || ^7.0",
```

However, `Throwable` is a PHP 7 feature, so either PHP 5.6 or Throwable should be removed. 

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.3.x

#### Summary

`composer.json` is inconsistent with PHP version usage of `Throwable`

#### Previous behavior

Doctrine job `odm:generate:documents` works.

#### Current behavior

PHP Catchable fatal error:  Argument 3 passed to Doctrine\ODM\MongoDB\Mapping\MappingException::__construct() must be an instance of Throwable, instance of ReflectionException given, called in /var/www/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php on line 187 and defined in /var/www/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php on line 33

#### How to reproduce

`doctrine-cli.php odm:generate:documents --generate-annotations=1`

**Comment by malarzm** [comment]
@AronSzigetvari do you want to write a PR fixing this? Removing type (or making it same as exception in 5.6) should be sufficient

**Comment by alcaeus** [comment]
Fixed in #2139.
