### ISSUE TITLE
Check index integrity

### ISSUE THREAD

**Issue by rbaarsma** [doctrine/mongodb-odm#2163]
### Feature Request

I recently had an issue, caused by an UniqueIndex annotation on a field that did not exist.

Is there any way we can check the indexes or perhaps fail schema:update when they are invalid?

I had this mapping
```
* @ODM\UniqueIndex(keys={"streamCode"="asc", "revision"="desc"})
```

And the field $streamCode did not exist (it was renamed to $code).
But the index was created without any problems..

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

Not sure what's the best solution. Either hard error (or warning) on schema:update. Or a separate command (?) to check index integrity. Hard errors/warnings on schema:update would be BC breaking.. but could also potentially help people who have silent errors. Warnings could be an option, although currently I would miss them in the CI. Still it's something I could filter in my CI, so that's not really a problem. 

Also perhaps adding a `--strict` option to schema:update is a good idea. Because then it's more of a feature, and less of a BC break.

**Comment by alcaeus** [comment]
Whenever ODM reads field names from mapping, we silently fall back to using the provided name where possible. This is the case for queries or schema operations. In this case, we can't find a field named `streamCode`, so we'll fall back to using that as literal name in case you're dealing with an unmapped field. Given the flexibility in schema design for MongoDB this is the best way to handle such schema differences.

I'm not sure what a strict mode like that should do, and what it should apply to. Treating this one case differently doesn't seem like a good idea, and adding a strict mode to every place where we silently fall back to using literal names would be a huge undertaking. I'm not sure the effort is worth it.

**Comment by rbaarsma** [comment]
Okay I have no idea as to the impact. It's more of a nice-to-have feature that prevents problems downstream. As you noted on slack once to me: mongodb is not schemaless and especially because we use doctrine ODM, we are expecting a schema. That we silently fall back on literals is never my intention, although there's probably use-cases for it. 

Thanks for the quick reaction. I still think a strict mode that prevents the silent fallback would be a very nice feature, but if the impact is too big, then probably it's not worth the effort.

**Comment by alcaeus** [comment]
Closing here, I don't think this is an idea worth exploring at this time. Please bring the issue up again in a little while if the use-case is still there. Thanks!
