### ISSUE TITLE
How to install doctrine/mongodb-odm on symfony 4.2 (windows)?

### ISSUE THREAD

**Issue by SzymonB** [doctrine/mongodb-odm#2165]
Hi there, 

I'm trying to install mongodb-odm but with no result.

`λ composer require doctrine/mongodb-odm-bundle
Using version ^4.1 for doctrine/mongodb-odm-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.2.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/mongodb-odm-bundle ^4.1 -> satisfiable by doctrine/mongodb-odm-bundle[4.1.0].
    - doctrine/mongodb-odm-bundle 4.1.0 requires symfony/console ^4.3.3|^5.0 -> no matching package found.`

I'm using  a php 7.3.5, mongodb 4.2.2 and symfony 4.2.
Anyone can help me? :)

**Comment by Steveb-p** [comment]
As my colleague once said: "Read the error" :)

> doctrine/mongodb-odm-bundle 4.1.0 requires **symfony/console ^4.3.3**|^5.0

> I'm using a php 7.3.5, mongodb 4.2.2 and **symfony 4.2**.

There you have it. You're using a Symfony version (lower) that is no longer supported by `doctrine/mongodb-odm-bundle` you're asking for. Either upgrade Symfony or use one of the earlier bundle versions.
