### ISSUE TITLE
Bad structure document type file from old mongoDB to new

### ISSUE THREAD

**Issue by robert0770** [doctrine/mongodb-odm#2168]
we update, our mongoDB and doctrinemongo, but now other fileds in document type file must be stored in metadata when we use "uploadFromFile" function but my database collection "offerPhotos.files" has fields like this:

> 
> {
>     '_id': ObjectId("5c6bcf50572b9463328b4573"),
>     'offerId': 0,
>     'length': 66472,
>     'filename': 'dc8139f41ec3ab236f0f72285655f7e1.jpg',
>     'orgFilename': 'e4465c31f3f45f3548513a42cf1036fa37d61eec.jpg',
>     'batch': 'bbe154e945521d4e44baef8a80f21889',
>     'group': '5c6bcf502d447',
>     'size': 'big',
>     'mimeType': 'image/jpeg',
>     'uploadDate': ISODate("2019-02-19T09:41:36.0Z"),
>     'chunkSize': 261120,
>     'md5': '6d65a1c34c21cbee61c57d2ea7cbbe24'
> }

how to fix it?

when now i set metadata offerId and others this is store like this:

> {
>     '_id': ObjectId("5e7476d267359329643eaa03"),
>     'chunkSize': 261120,
>     'filename': 'phpcwRZIG',
>     'metadata': {
>         'offerId': 'test',
>         'orgFilename': 'e4465c31f3f45f3548513a42cf1036fa37d61eec.jpg',
>         'batch': 'bbe154e945521d4e44baef8a80f21889',
>         'group': '5c6bcf502d447',
>         'size': 'big',
>         'mimeType': 'image/jpeg',
>     },
>     'length': 125373,
>     'uploadDate': ISODate("2020-03-20T07:54:58.568Z"),
>     'md5': 'f0fe4c40e6b4332c929f6017d250ea8d'
> }

**Comment by malarzm** [comment]
@robert0770 there's no automated way to fix this. As per [upgrade notes](https://github.com/doctrine/mongodb-odm/blob/master/UPGRADE-2.0.md#gridfs) you need to manually migrate the data.

**Comment by alcaeus** [comment]
Note that this is as easy as submitting a single `update`:
```
db.fs.files.update({}, {$rename: { 'orgFilename': 'metadata.orgFilename', 'offerId': 'metadata.offerId', ...}})
```

Then, move all those properties into an embedded document and use it as `metadata` mapped field in the file.
