### ISSUE TITLE
Bidirectional one-to-many don't save relation in both sides

### ISSUE THREAD

**Issue by lcavero** [doctrine/mongodb-odm#2169]
|    Q        |   A
|------------ | -----
| Version     | 2.0.5

### Support Question

Hi, I have a simple one-to-many relationship

<pre><code>
/**
 * Class ProductType
 * @package App\Document\Product
 * @MongoDB\Document()
 */
class ProductType
{
    /**
     * @var string
     * @MongoDB\Id
     */
    public $id;

    /**
     * @var ProductSubType[]|Collection
     * @MongoDB\ReferenceMany(targetDocument="App\Document\Core\Product\Type\ProductSubType", storeAs="ref")
     */
    private $productSubTypes;

}

/**
 * Class ProductSubType
 * @package App\Document\Product
 * @MongoDB\Document()
 */
class ProductSubType
{
    /**
     * @var string
     * @MongoDB\Id
     */
    public $id;

    /**
     * @var ProductType
     * @MongoDB\ReferenceOne(targetDocument="App\Document\Core\Product\Type\ProductType", storeAs="ref")
     */
    private $productType;
}

</code></pre>

When I make something like the code above, ProductSubType has a reference of ProductType but ProductType has NO reference of ProductSubTypes. What I am doing bad? In the documentation https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.0/reference/bidirectional-references.html it says: "When I persist some instances of the above classes the references would exist on both sides!", but I only have one side reference.

<pre><code>
foreach ($values as $key => $value){
            $type = new ProductType();
            $dm->persist($type);

            foreach ($value as $key2 => $item){
                $subtype = new ProductSubType();
                $subtype->setProductType($type);
                $dm->persist($subtype);
            }
        }
        $dm->flush();
}

</code></pre>

Thanks!

**Comment by malarzm** [comment]
The reference will exist on both sides once you load your documents from the database. Before that you must link the objects yourself.
