### ISSUE TITLE
Querybuilder return always only one document

### ISSUE THREAD

**Issue by robert0770** [doctrine/mongodb-odm#2174]
when im use

> return $this->dm->getRepository(OfferPhoto::class)->findAll();

return 101 documents...

> $qb = $this->dm->createQueryBuilder(OfferPhoto::class);
> return $qb->getQuery()->execute();

return 1 document...

why?

**Comment by TomHAnderson** [comment]
ORM uses `getResult()`  Does that function exist in ODM?

**Comment by jcaillot** [comment]
Doctrine\ODM\MongoDB\Query\Query::Execute will return an iterator object that wraps a Mongo Cursor and only caches a (Proxied version of) the first item. One need to traverse it in order to get the results. Try :

`$qb->getQuery()->execute()->toArray()`

**Comment by robert0770** [comment]
toArray works, thanks
