### ISSUE TITLE
Deleting referencing documents?

### ISSUE THREAD

**Issue by Cypaubr** [doctrine/mongodb-odm#2176]
### Support Question

I have two documents, one is referencing the other like that:

The User class:
```php
<?php

namespace App\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

/**
* @MongoDB\Document(repositoryClass=UserRepository::class)
* @MongoDB\HasLifecycleCallbacks
*/
class User
{
  /**
  * @var string
  * @MongoDB\Id
  */
  protected $id;

  /**
  * @var string
  * @MongoDB\Field(type="string")
  */
  protected $email;

  //... and getters, setters
}
```

And the Account class:
```php
<?php

namespace App\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

/**
* @MongoDB\Document()
* @MongoDB\HasLifecycleCallbacks
*/
class Account
{
  /**
  * @var string
  * @MongoDB\Id
  */
  protected $id;

  /**
  * @var User
  * @MongoDB\ReferenceOne(targetDocument=User::class)
  */
  protected $user;

  /**
  * @var Business
  * @MongoDB\ReferenceOne(targetDocument=Business::class)
  */
  protected $business;

  //... and getters, setters
}
```
An User can have multiple Accounts for multiple Business (but an user can not have 2 accounts for the same business).

When I delete the User, the Account(s) remains in the database which causes error in Sonata (for example).

How can I make it to delete the Accounts referencing the user when this on is deleted?

**Comment by malarzm** [comment]
Please read available documentation before opening a support ticket: https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.0/reference/reference-mapping.html#cascading-operations

**Comment by Cypaubr** [comment]
@malarzm Thanks for your useful support but cascading operations don't work.

**Comment by malarzm** [comment]
Please open a PR with a failing test case demonstrating how exactly cascading is not working. You can base your test on our [functional tests](https://github.com/doctrine/mongodb-odm/tree/master/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket)
