### ISSUE TITLE
Get the total count given a limit (...\Cursor replacement) 

### ISSUE THREAD

**Issue by younesdiouri** [doctrine/mongodb-odm#2179]
### BC Break Report

Hi :smiley_cat: , we've been experiencing an issue in our mongodb-odm 2.X upgrade process (from 1.X).
We've been using the `Cursor` interface to count all results from a Query with limits. 

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.X

#### Summary

Indeed, in the changelog , we read that : 
> Methods that previously returned a MongoCursor instance no longer return a cursor directly but rather compose the cursor in iterators implementing the Doctrine\ODM\MongoDB\Iterator\Iterator interface. This class provides a toArray method in addition to the methods provided in PHP core's Iterator interface.
The Doctrine\ODM\MongoDB\Cursor, Doctrine\ODM\MongoDB\EagerCursor, and Doctrine\ODM\MongoDB\CommandCursor classes has been dropped without replacement. You should always use the iterator interface mentioned above in type hints.

#### Previous behavior

As we used `cursor->count` with its default `$foundOnly = false`, we can with one call get the results with the given limit, and the total count.

#### Current behavior

`\Doctrine\ODM\MongoDB\Cursor` does not exist anymore.

I am wondering if there is another way to get the full count of a query (given a limit), or is it necessary to do two different calls in this case? 

Thank you very much for your help & time. 

Younes

**Comment by alcaeus** [comment]
This was changed in the MongoDB extension a while back. You can read a detailed explanation here: https://github.com/mongodb/mongo-php-driver/issues/195#issuecomment-169405194.

This always was two separate calls, except they were hidden. Calling `count` on a cursor issued a `count` command to the server, which could produce different results. If you want to know the total number of documents in the collection, you should issue a separate `count` query.

**Comment by younesdiouri** [comment]
Many thanks for your quick reply :), we will use a separate query for the count.
Have a good day.
