### ISSUE TITLE
schema:create fails with single collection inheritance

### ISSUE THREAD

**Issue by malarzm** [doctrine/mongodb-odm#2182]
### Bug Report

As per https://stackoverflow.com/questions/61615412/odm-inheritance-document-with-type-single-collection-schema-create-error the `odm:schema:create` fails with an error if the collection already exists. This is the case when single collection inheritance is used.

#### Expected behavior

The command finishes successfully.

**Comment by Vladnev** [comment]
@alcaeus Hi it also actual for 2.2.0 version. As i see 2.1 Roadmap not supproted.

**Comment by malarzm** [comment]
@Vladnev thanks for noticing! It must have somehow stay in 2.1 when we were retriaging issues :) Would you like to try fixing the issue since it seems to affect you as well?

**Comment by malarzm** [comment]
Fixed with #2392
