### ISSUE TITLE
int64 support

### ISSUE THREAD

**Issue by Romaxx** [doctrine/mongodb-odm#2190]
|    Q        |   A
|------------ | -----
| Version     | 2.1.0

I want to use int64 fields in my db to do a 64 bitmask permission system (32bits it's quite short for some rare cases, but it append..), by default Field(type="integer") are int32 (checked with mongodb compass), and I need to change it manually to int64.
My server is under Php 64bits version so I can use MongoDB\BSON\Int64, is there an option field or a thing to specify int64 in schema ? Thank you

**Comment by malarzm** [comment]
I believe the best would be adding a new type to handle `int64` since it requires specjal care. You could take a page from #2128 where we've added decimal type. Also we will appreciate a PR adding the type to ODM!

**Comment by alcaeus** [comment]
On 64-bit platforms, the driver will store integer values as int32 bson type as long as its value fits into 32 bits. Once the value exceeds the maximum size for 32-bit integers, it is stored as int64 type: https://github.com/mongodb/mongo-php-driver/blob/master/src/bson-encode.c#L33..L37

On 32-bit platforms, the driver always stores integer values as 32-bits. The `MongoDB\BSON\Int64` class is to allow the driver to correctly return int64 values (that may have been stored in the database on a different platform) by wrapping them in a value object and storing them as a string internally. There is no special handling necessary to get the driver to store a 64-bit value, as long as you are running on a 64-bit platform.
