### ISSUE TITLE
Undocumented: Move DocumentRepository to Repository namespace 

### ISSUE THREAD

**Issue by ondrejmirtes** [doctrine/mongodb-odm#2198]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.0.0

#### Summary

Class DocumentRepository was moved to Repository namespace (https://github.com/doctrine/mongodb-odm/commit/682aa792cffc344f931a8b1a0ac82ffb2cd8d492) but this change isn't documented in the changelog.

**Comment by malarzm** [comment]
It is mentioned in the UPGRADE file: https://github.com/doctrine/mongodb-odm/blob/master/UPGRADE-2.0.md#repository :)

**Comment by ondrejmirtes** [comment]
Thanks and sorry, I just checked the changelog and it's not mentioned there at all :)

**Comment by malarzm** [comment]
That's true, we used changelog for listing all issues/prs but now with automated release process we put all that in the release description instead. If you're looking for things that have changed between 1.x and 2.0, UPGRADE.md is your file :)
