### ISSUE TITLE
persist & flush take up lots of memory, without clearing it properly

### ISSUE THREAD

**Issue by rbaarsma** [doctrine/mongodb-odm#2215]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 2.1.2  (php 7.4.4, mongo server 4.0.19)

#### Summary

The following code:

```
        $stream = new Stream($publication, $metadata);
        dump('created Stream object '. memory_get_usage(true) / 1024 / 1024);

        $this->dm->persist($stream);
        dump('persisted '. memory_get_usage(true) / 1024 / 1024);

        $this->dm->flush();
        dump('flushed '. memory_get_usage(true) / 1024 / 1024);

        $this->dm->detach($stream);
        gc_collect_cycles();
        dump('detached '. memory_get_usage(true) / 1024 / 1024);

        $this->dm->clear();
        gc_collect_cycles();
        dump('cleared '. memory_get_usage(true) / 1024 / 1024);
```

Has this output:

```
"created Stream object 124.51171875 MB"
"persisted 197.01171875 MB"
"flushed 427.12890625 MB"
"detached 427.12890625 MB"
"cleared 414.62890625 MB"
```

#### How to reproduce

Unfortunately my `Stream` document is a fairly complex object with lots of Embedded documents, which is hard to just copy here for reproduction. It includes lots of both EmbedOne and EmbedMany statements, and obviously normal fields such as string, collection, date. It also has several cases of an EmbedMany to target itself (to create tree structures)

A small snippet of it:

```
/**
 * @ODM\Document(repositoryClass="App\Repository\StreamRepository")
 */ 
class Stream
{
    // more fields..

    /**
     * @ODM\Id(strategy="NONE")
     */
    private string $id;

    /**
     * @ODM\EmbedOne(targetDocument="App\Document\Metadata")
     */
    private Metadata $metadata;
}
```

```
/**
 * @OA\Schema()
 * @ODM\EmbeddedDocument()
 */
class Metadata
{
    // more fields..

    /**
     * @ODM\EmbedOne(targetDocument="App\Document\SmartMetadata")
     */
    protected ?SmartMetadata $navigationMetadata = null;

    /**
     * @ODM\EmbedMany(targetDocument="App\Document\Metadata")
     */
    protected ?iterable $children = null;

}
```

```
/**
 * @OA\Schema()
 * @ODM\EmbeddedDocument()
 */
class SmartMetadata
{
    /**
     * @ODM\EmbedMany(targetDocument="App\Document\MboCategory")
     */
    protected ?iterable $mboQualifications = null;

    /**
     * @ODM\EmbedMany(targetDocument="App\Document\MboCategory")
     */
    protected ?iterable $mboCourseStructure = null;
}
```

```
/**
 * @OA\Schema()
 * @ODM\EmbeddedDocument()
 */
class MboCategory
{
    use ParsableTrait;

    /**
     * @ODM\Field(type="string")
     */
    protected ?string $category = null;

    /**
     * @ODM\EmbedMany(targetDocument="App\Document\MboCategory")
     */
    protected ?iterable $items = null;
}
```

#### Expected behavior

I would expect:
 - the persist to take some memory (but perhaps not as much as 70 MB), 
 - the flush to not take any additional memory
 - the detach() to clear all the memory back to 124 MB, although I know this method is deprecated
 - the clear() to at least really clear the memory back to 124 MB

But instead:
 - persist takes 73 MB
 - flush takes another 230 MB
 - detach does nothing whatsoever
 - clear only clears 13 MB of memory

**Comment by rbaarsma** [comment]
Probably related (or duplicate of) https://github.com/doctrine/mongodb-odm/issues/2162

**Comment by alcaeus** [comment]
@rbaarsma you are correct, this does look like the linked issue. The interesting thing is that I've observed this using `HydratingIterator`, which isn't used in your case. The fact that memory usage significantly goes up after `flush` makes me think that UnitOfWork is leaking somewhere. I'm closing this, but have added a note to #2162 to note that it may be UoW internals.
