### ISSUE TITLE
"ocramius/proxy-manager": "^2.*" now requires composer 2

### ISSUE THREAD

**Issue by douglasjam** [doctrine/mongodb-odm#2219]
I'm currently using dev-master since a release with setRewindable hasn't been released yet.

In master, you guys use the following composer dependency
"ocramius/proxy-manager": "^2.2",

This means we get the latest 2.x, and currently, the latest is 2.9.1

And if you look there, they now require composer 2.0 since 2.9
https://github.com/Ocramius/ProxyManager/blob/2.9.1/composer.json

Can you set the max version to i.e.: 2.8.*?

I could also fix on my side, easy job for me, but just wanted to share this.

**Comment by Steveb-p** [comment]
@douglasjam as far as I know 2.1 has `setRewindable` already.

see https://github.com/doctrine/mongodb-odm/pull/2116

**Comment by malarzm** [comment]
I don't think it's feasible as limiting this on our end would mean folks with newer Composer won't be able to get newer proxy-manager versions. I believe this should be handled at composer level, would you @douglasjam mind opening issue there?

**Comment by douglasjam** [comment]
Thanks @Steveb-p, I missed totally this release, I just tested locally here 2.1 and it works, no more dev-master 👏 

I'll check in my production if memory explodes, and if it does I come back here.

About the versioning, ocramius instructed me how to proceed, basically I was running with --ignore-platform-reqs, but without this option composer is smart enough to take the latest compatible version, that is the one without composer 2.

https://github.com/Ocramius/ProxyManager/issues/626
