### ISSUE TITLE
Update ocramius/proxy-manager to prevent abandoned packages notices with composer

### ISSUE THREAD

**Issue by chrisdejager** [doctrine/mongodb-odm#2225]
When I use this great (!) plugin in my project, composer complains on every install/update that abandoned packages are installed:

> Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
> Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.

> composer why zendframework/zend-code
> ocramius/proxy-manager  2.2.3  requires  zendframework/zend-code (^3.3.0)  
> composer why ocramius/proxy-manager
> doctrine/mongodb-odm  2.1.2  requires  ocramius/proxy-manager (^2.2)  

This issue is solved in the latest proxy-manager code (from version 2.6+).

Thanks!
Chris

**Comment by alcaeus** [comment]
Please run `composer why-not ocramius/proxy-manager 2.6.0` to see why a version that no longer requires abandoned package can't be installed. ProxyManager 2.3.0 drops support for PHP < 7.4, so if you're running any older PHP release you're pretty much screwed. This is also the reason why we can't bump the dependency to this package.

**Comment by chrisdejager** [comment]
Yes: ocramius/proxy-manager  2.6.0  requires  php (7.4.* but 7.3.22 is installed)

Darn, I didn't think to check that! Then its logical, thanx!
