### ISSUE TITLE
Support OrderBy / Sort for DocumentRepository findOneBy()

### ISSUE THREAD

**Issue by nottoohigh** [doctrine/mongodb-odm#2226]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break         | no
| Version    | Since 2.1

#### Summary

Unlike `findBy`, `Doctrine\ODM\MongoDB\Repository\DocumentRepository::findOneBy` does not currently support `$sort` as a parameter.

**Current**
```
 /**
   * Finds a single document by a set of criteria.
 */
public function findOneBy(array $criteria) : ?object
{
  return $this->getDocumentPersister()->load($criteria);
}
```

**Propose adding support for $sort:** 
```
/**
   * Finds a single document by a set of criteria.
*/
public function findOneBy(array $criteria, ?array $sort = null) : ?object
 {
     return $this->getDocumentPersister()->load($criteria, null, [], 0, $sort);
 }
```

**Comment by malarzm** [comment]
@nottoohigh sounds reasonable :) would you mind sending us a PR with addition and some tests?

**Comment by nottoohigh** [comment]
@malarzm Ok will do as soon as I can. Thank you!

**Comment by malarzm** [comment]
Closing as https://github.com/doctrine/mongodb-odm/pull/2264 was just merged
