### ISSUE TITLE
Discriminator with new GridFS

### ISSUE THREAD

**Issue by etshy** [doctrine/mongodb-odm#2247]
|    Q        |   A
|------------ | -----
| Version     | 2.1.2

### Support Question

Is there a way to add discriminator with the new GridFS system ?
In my case I wanted to make a generic File class with basic fields (about the same as in the example) and sime others like Image, Archived, etc. that will have more fields at the root or inside the metadata.

The problem is, without discriminator when i `find()` a File that was an Image, it load a File object, not an Image object, so some infos are missing.

With the old GridFS, as it was document like anything else it was possible, but it seems it's not anymore. is it intended ?

**Comment by alcaeus** [comment]
The file itself can't have a discriminator mapping, as there can't be additional fields in the root document of a GridFS bucket. You can however use a discriminator when mapping the metadata document: this is what will vary between different file "types", the rest is always the same.

**Comment by etshy** [comment]
Yeah didn't think about that.
I even forgotten discriminator on embeddedDocument was possible.

Thanks, I'll manage with that.
