### ISSUE TITLE
PartialFilterExpression with value set to null creates an index with value set to the string "null"

### ISSUE THREAD

**Issue by GregRbs92** [doctrine/mongodb-odm#2254]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | any

#### Summary

I wanted to create an index with a partial filter expression to index only the documents having a specific field set to `null`. Unfortunately, when using the XML mapping, the values are cast as `string`, therefore the index is created for the documents having the specific field set to the string `"null"`.

#### Current behavior

Currently, only booleans and numbers are handled as specific types. https://github.com/doctrine/mongodb-odm/blob/3bdfe97be472160ebbc924d5882ce61bd640a515/lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php#L525-L531

#### How to reproduce

```
<index>
    <key name="parent" />
    <partial-filter-expression>
        <field name="parent" operator="eq" value="null" />
    </partial-filter-expression>
</index>
```

#### Expected behavior

Adding an exception for null values might be useful.
```php
if ($value === 'true') { 
    $value = true; 
} elseif ($value === 'false') { 
    $value = false; 
} elseif (is_numeric($value)) { 
    $value = preg_match('/^[-]?\d+$/', $value) ? (int) $value : (float) $value; 
} elseif (strtolower($value) === 'null') {
    $value = null;
}
```

**Comment by malarzm** [comment]
This sounds like a reasonable thing to do. What you like to implement the change @GregRbs92?

**Comment by malarzm** [comment]
Although to be on par with true/false handling I'd give up on the `strtolower` call

**Comment by GregRbs92** [comment]
@malarzm With pleasure, do you have any contribution guide I can refer to for the development?

**Comment by malarzm** [comment]
@GregRbs92 depends what you're looking for :) but bare minimum is to add a test along with the change, so we won't break added behaviour accidentally. If you don't have MongoDB installed locally you can count on running tests through GitHub actions, that's happening for each commit. Also we have automated checks for coding standards and static analysis, so if there's anything off with our standards, the checks will let you know. So summing up:
- you need to base your work on `2.1.x` branch as you're fixing a bug
- add `null` handling along with test that proves this works as intended
- make all checks for the PR pass
- if needed, squash all your work into 1 commit (we may do that for you when merging, but having 1 commit in PR will make our life easier :) )
