### ISSUE TITLE
How to update one document , when updating another one.Two document have same fields.

### ISSUE THREAD

**Issue by rameesps** [doctrine/mongodb-odm#2255]
|    Q        |   A
|------------ | -----
| Version     | x.y.z

**Comment by malarzm** [comment]
@rameesps I have no clue what are you asking about. Also please consider posting your question on [StackOverflow under the `doctrine-odm` tag](https://stackoverflow.com/questions/tagged/doctrine-odm) as are trying to keep github for actual issues with the library.
