### ISSUE TITLE
Compound Index not recognized for deletion if order changed

### ISSUE THREAD

**Issue by cgrabenstein** [doctrine/mongodb-odm#2257]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.1.2

#### Summary

We are optimizing indexes in our project and discovered, that switching the order of keys of a compound index does not trigger a deletion of the old index with the previous order. 

#### Current behavior

Say we have a class `User` with an index as following:

```
/**
 * @Document(collection="User")
 *
 * @UniqueIndex(keys={"firstname"="asc", "creation_date"="desc", "lastname"="asc"})
 */
class User {
...
}
```

Running `bin/console doctrine:mongodb:schema:update` will create an index `firstname_1_creation_date_-1_lastname_1`.

When we change the Index to
```
@UniqueIndex(keys={"firstname"="asc", "lastname"="asc", "creation_date"="desc"})
```
and run the same command again, the previously created index will not be deleted. Instead we have a second index `firstname_1_lastname_1_creation_date_-1` now.

#### Expected behavior

I would expect that the old index is being detected as no longer in use and deleted by the update command. 

The reason for this behaviour is that the Method `isEquivalentIndexKeys` in the `SchemaManager` does not consider the order of keys. It uses a weak equality check (`==`) between the key arrays which ignores order.

**Comment by malarzm** [comment]
This sounds like a bug indeed. Would you like to try fixing this @cgrabenstein? Re using `==` for the check we tend to use strict checks wherever possible so there had to be good reason to use a weak one this time. If possible, I'd add an additional check for key order instead of changing the equality check.

**Comment by cgrabenstein** [comment]
I'll gladly give it a shot. However I need some help concerning compound text indexes, especially if text index are mixed with non-text indexes. Consider the following cases:

Should `@Index({'foo': 'text', 'bar': 'text'})` be considered equivalent to `@Index({'bar': 'text', 'foo': 'text'})`? [`foo` and `bar` switched]
Should `@Index({'foo': 'text', 'a': 1, 'b': 1})` be considered equivalent to `@Index({'foo': 'text', 'b': 1, 'a': 1})`? [`a` and `b` switched]
Should `@Index({'foo': 'text', 'a': 1, 'b': 1})` be considered equivalent to `@Index({'a': 1, 'foo': 'text', 'b': 1})`? [`a` and `foo` switched]

If you can help me and tell me, which of the cases are considered equivalent and which are not, I will work on a fix for the bug!

**Comment by malarzm** [comment]
@alcaeus mind chiming in? My knowledge is a bit rusty here :)

**Comment by alcaeus** [comment]
Hi,

to elaborate on your questions:

> Should `@Index({'foo': 'text', 'a': 1, 'b': 1})` be considered equivalent to `@Index({'foo': 'text', 'b': 1, 'a': 1})`? [a and b switched]
> Should `@Index({'foo': 'text', 'a': 1, 'b': 1})` be considered equivalent to `@Index({'a': 1, 'foo': 'text', 'b': 1})`? [a and foo switched]
> Should `@Index({'foo': 'text', 'bar': 'text'})` be considered equivalent to `@Index({'bar': 'text', 'foo': 'text'})?` [foo and bar switched]

I'm not entirely sure on the first one but absolutely sure on the other two: those indexes are not equivalent. To quote from the [text index documentation](https://docs.mongodb.com/manual/core/index-text/#text-index-compound):
> If the compound text index includes keys preceding the text index key, to perform a $text search, the query predicate must include equality match conditions on the preceding keys.

I'm not entirely sure about the first case: I'd guess that these indexes are indeed equivalent, as the `$text` operator will search the entire text index for the field. However, the documentation doesn't offer proof of this, and so I think we should err on the side of caution when fixing this and treat them as different indexes.

**Comment by cgrabenstein** [comment]
Thanks for your input @alcaeus. When you refer to "the first one", you are referring to the first Index in my comment, not in your quote, correct? It seems like the order got mixed up somehow. 

Looking further into the `SchemaManager` I found this comment in `isEquivalentTextIndexWeights`:
```
        /* MongoDB returns the weights sorted by field name, but we'll sort both
         * arrays in case that is internal behavior not to be relied upon. */
```

Correct me if I'm wrong, but that would mean that we actually can not tell which order the fields in a compound text index _currently_ have, as the text index field names only appear in the weights. As a result, there's no way to tell if the order of two text indexes has changed or not. 

I just did a quick test and tried to create two indexes
```
db.test.createIndex({foo: 'text', bar: 'text'})
```
and
```
db.test.createIndex({bar: 'text', foo: 'text'})
```
The first command created the index, the second command returned `note: 'all indexes already exist',`. MongoDB Version was 4.4.

So to conclude:
* case 1 (`foo` and `bar` switched) are considered equivalent by the latest MongoDB, and should be considered equivalent here.
* case 2 and 3 (`a` and `b` switched, `a` and `foo` switched) are not considered equivalent.

If that's ok with you I will go ahead and try to implement it accordingly.

**Comment by alcaeus** [comment]
I updated my comment, I thought I had put them in the right order after trying to address them individually but failed.

Thanks for digging deeper into server behaviour, I agree: key order is not important for keys that are part of the text index, but matters for all other keys in the compound index (meaning the behaviour is consistent across compound indexes).

Since we can't tell the original order anyways, I'm pretty sure that there's no difference and no special handling should be given to keys that are part of the text index.

**Comment by malarzm** [comment]
Closing as #2260 was merged
