### ISSUE TITLE
Reset stages in Aggregation Builder

### ISSUE THREAD

**Issue by franmomu** [doctrine/mongodb-odm#2265]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

When paginating an Aggregation Builder, I wanted to use the second method explained here: https://medium.com/finnovate-io/paginating-large-data-sets-with-mongo-aggregation-d4425b48c71e.

The problem comes [in the `facet` stage, when creating a pipeline](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.1/reference/aggregation-builder.html#facet) that it requires to create another Aggregation Builder. Since the Builder passed has the same `$documentName`, instead of creating a new Builder, it would be easier if I clone the current one, but without stages.

One way to solve this I think it is to have a `Builder::resetStages()` method, maybe a more elegant way I guess would be a `Facet::pipelineBuilder()` or something like that, but if this is possible I guess that internally it needs to clone and reset the stages also.

So is there other way to do this? If it's fine I'll create the PR.

**Comment by alcaeus** [comment]
> Since the Builder passed has the same `$documentName`, instead of creating a new Builder, it would be easier if I clone the current one, but without stages.

I don't think this is necessary. Creating a new aggregation builder is simple enough:
```php

$dm->createAggregationBuilder(Document::class)
    ->match()
    // ...
    ->facet()
        ->field('metadata')
        ->pipeline($dm->createAggregationBuilder(Document::class)->count('total')
        ->field('data')
        ->pipeline(...)
;
```

**Comment by franmomu** [comment]
Rereading my issue, I wasn't clear, what I meant is to create a generic solution for paginate an aggregation builder, given an aggregation builder I think there is no way to get the document name necessary for creating the new aggregation builder.

**Comment by alcaeus** [comment]
I see. I currently have no plans to create a generic solution, as returning a single document from the pipeline is not efficient, especially when dealing with larger documents. Depending on the data, the `$facet` solution isn't necessary (e.g. if the data doesn't change frequently).

> given an aggregation builder I think there is no way to get the document name necessary for creating the new aggregation builder

That is correct. Still, I don't believe that the builder should be able to create a new instance of itself. There are a couple of options here:
* allow to create a builder without metadata: metadata is used for field name translation and value conversion based on mapping, which isn't always necessary. Just like the query builder can work without mapping information, so could the aggregation builder. This way, you could create a builder without metadata for use in the `pipeline` method for `$facet`.
* modify the `pipeline` method to not only accept a builder or a stage, but also accept a built pipeline. This is similar to many other expression helpers accepting any array or object (e.g. all helpers in the `Aggregation\Expr` class).

With that said, I'd assume that any piece of code that wraps pagination logic around an existing builder should know the document manager and document that it is working with, which is all that's needed to create a new builder. If you could show an example of what you're working with and what you're trying to do, I'd be happy to come up with a solution for the problem.

**Comment by franmomu** [comment]
Thank you very much for your detailed response! I had in mind to create an adapter in`pagerfanta/pagerfanta` for Aggregation Builders in https://github.com/BabDev/Pagerfanta/tree/a67a44e4dedece5853cd9a7ecbfd2f91a3d5f652/lib/Adapter/Doctrine/MongoDBODM.

> I'd assume that any piece of code that wraps pagination logic around an existing builder should know the document manager and document that it is working with, which is all that's needed to create a new builder.

Truth is that the adapter could be like:

```php
new AggregationBuilderAdapter($aggregationBuilder, $document, $documentManager);
```
I guess the user usually has the repository when paginating, so document and document manager will be availables.

**Comment by alcaeus** [comment]
With the API that the adapter interface requires, it makes no sense to use `$facet` at all. The calls to `getNbResults` and `getSlice` are entirely separate. Quick prototype:
```
    /**
     * @return int
     */
    public function getNbResults()
    {
        $builder = clone $this->aggregationBuilder;

        $iterator = $builder->
            ->count('total')
            ->getAggregation()
            ->getIterator();
        $iterator->rewind();

        return (int) $iterator->current()->total;
    }

    /**
     * @param int $offset
     * @param int $length
     *
     * @return iterable
     */
    public function getSlice($offset, $length)
    {
        $builder = clone $this->aggregationBuilder;

        return $builder->skip($offset)
            ->limit($length)
            ->getAggregation()
            ->getIterator();
    }
```

Using `$facet` makes sense if the library has the capability to handle metadata and result in a single call, which pagerfanta doesn't.

Note that unlike the query builder, the aggregation builder can have multiple sort and limit stages, which is why this implementation also needs to clone the base builder in `getSlice`. You generally also want to first skip, then limit - the reverse doesn't make much sense and will produce unexpected results.
