### ISSUE TITLE
Is ODM 1 compatible with MongoDB 4.4 ?

### ISSUE THREAD

**Issue by chandon** [doctrine/mongodb-odm#2267]
|    Q        |   A
|------------ | -----
| Version     | 1.3.7

### Support Question

I'm using ODM1 with map/reduce. I've upgraded my MongoDB server from 4.2 to 4.4

I've issues with map/reduce (linked to deprecated doctrine/mongodb 1.6.4). When trying to execute the map/reduce query, i got an error message "'map' should be string". Setting back the "setFeatureCompatibilityVersion" of my server to 4.2 resolves the issue, but this means that it's not compatible with MongoDB 4.4 ?

Please note that I can use MongoDB 4.4 by fixing doctrine/mongodb (https://github.com/chandon/mongodb/commit/59052742e5725218dfab4c65030fafd04934acdd)

Thanks for your support

**Comment by malarzm** [comment]
ODM is not compatible or incompatible with any MongoDB version per se as it does not know what version you are running (there is no configuration option for that and no auto-detection). 1.x version of ODM abstracted db-related operations to doctrine/mongodb but that was merely an abstraction over legacy `mongo` driver and that's the first thing that needs to be checked whether will work with newer MongoDB versions (I'm mentioning this only to say that even if it works now it may break at any point in time with next updates). From your description it seems that the driver is kind of OK (although the fact that is stopped accepting `\MongoCode` is not a good sign IMO) and any shortcomings can be fixed by patching doctrine/mongodb. If that works for you then great although we strongly recommend to update ODM to version 2.0. 

Offhand doctrine/mongodb is not only deprecated, we have archived the repository :)

**Comment by alcaeus** [comment]
To follow up on the above: ODM 1.x is built on top of the legacy MongoDB driver (`ext-mongo`) but can be made to work on the new driver using an adapter library. The last MongoDB server version officially supported by the legacy driver is 3.0, although you may have luck running on newer server versions depending on the features you use. To have full compatibility with supported MongoDB versions, we recommend upgrading to ODM 2.0 as mentioned above. This also ensures that you continue to receive feature updates and bug fixes.

**Comment by chandon** [comment]
@alcaeus thanks, i'm on the way to ODM2.0, but a lots of features are no longer supported (like flush($document), map/reduce [thanks to the query->debug() it's still possible...], and even the generate:document command which is not linked to the driver version), so it's not such a simple migration... but you're right, it's almost mandatory to migrate

**Comment by alcaeus** [comment]
> but a lots of features are no longer supported

Yes. Some pointers that may be helpful:

* `flush($document)`: if you want to selectively flush documents, [explicit change tracking](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.1/reference/change-tracking-policies.html#deferred-explicit) is the way to go here. if that seems too daunting, you'll find that some changes may have been persisted despite you not explicitly passing the document in (most notably new document insertions), so you may be able to remove the first argument and find your application still works.
* map/reduce: This is being replaced by aggregation pipelines. I'll refer you to the [MongoDB Docs](https://docs.mongodb.com/manual/reference/map-reduce-to-aggregation-pipeline/) which explain how to migrate. MongoDB 4.4 also includes new aggregation pipeline stages (`$accumulator` and `$function`) that allow you to add custom logic to the aggregation pipeline if needed
* generate:document: this was dropped as we don't want to maintain the generator logic: mapping is relatively straightforward (at least compared to ORM), and your IDE is most likely better at scaffolding document classes. There is a feature request for the MakerBundle (see https://github.com/symfony/maker-bundle/issues/364) to support this there. As a last resort, you can try moving the command and the generator classes into your domain (and maintain them yourself), but I'll be honest and tell you that I don't know the effort involved to make it work with ODM 2.

**Comment by chandon** [comment]
Concerning the `flush($document)` which is for me the biggest issue, i didn't know about explicit change tracking. I've already changed my logic by inserting/detaching then reloading inserted documents. For me, it's perhaps simpler than doing explicit tracking for my whole application code...
