### ISSUE TITLE
Bi-directional reference pulls incorrect document from owning side

### ISSUE THREAD

**Issue by josefsabl** [doctrine/mongodb-odm#2282]
I have something that looks like very bizarre bug. So pardon me if this report is bizarre either. I will try to describe it in as much detail as possible. I just need a bit of help isolating this as the project this appears in is **very** complex. I am trying to remove as much bogus code as possible. I hope I am not removing something relevant.

Let's have a document like this:

```php
/**
 * @ODM\Document
 */
class Group {
  /**
   * @ODM\ReferenceOne(targetDocument=Group, inversedBy="childGroups")
   */
  public $parentGroup = null;

  /**
   * @ODM\ReferenceMany(targetDocument=Group, mappedBy="parentGroup")
   */
  public $childGroups;
}
```

It simply is a tree of groups where any group can have N child groups.

Let's have this example:

- Root
  - Group 1
    - Group 1.1
  - Group 2
    - Group 2.1

We have a code, that flattens this tree (obviously recursively):

- Root
- Group 1
- Group 1.1
- Group 2
- Group 2.1

And sometimes, just sometimes (I will try to describe the situation later), it looks like the tree is actually:

- Root
  - Group 1
    - Group 1.1
  - Group 2
    - Group 2.1
      - Root
        - Group 1
          - Group 1.1
        - Group 2
          - Group 2.1
            - Root
              - ... infinite recursion

I isolated it to the point where I have two documents with same ID (Root), one doesn't have parent group (as expected) and one has parent group set to Group 2.1.

```php
// Pseudo-code

$document1->id === 'root';
$document2->id === 'root';

$document1->parentGroup === null;
$document2->parentGroup->id === 'root';
```

So, when the bug appears? It IS deterministic and I can reproduce it anytimes. But it doesn't make much sense to me.

The application has a robust system for caching.
There are many serial processes (that work with related Doctrine Documents for sure), result of each of them can be cached. Let's say:

- Method 1 (cacheable)
- Method 2 (cacheable)
- Method 3 (cacheable)
- THE Failing method.

There are actually many more and are NOT related, some of them work with other methods that can be cached as well. So this it oversimplified quite a lot.

Now, there are few scenarios:

All cache fresh (works)

- Method 1 - cache fresh
- Method 2 - cache fresh
- Method 3 - cache fresh
- THE Failing method (works).

All cache stale (works)

- Method 1 - cache stale
- Method 2 - cache stale
- Method 3 - cache stale
- THE Failing method (works).

Part of cache stale (FAILS)

- Method 1 - cache fresh
- Method 2 - cache stale
- Method 3 - cache fresh
- THE Failing method (FAILS WITH INFINITE LOOG).

It looks like Method 2 is the problem, but...

- Method 1 - cache fresh
- Method 2 - cache fresh
- Method 3 - cache stale
- THE Failing method (FAILS WITH INFINITE LOOG).

I understand that this information is not enough for you to debug this. As aforementioned, I am just putting something here so you can direct me to improve the description of a problem. Please, tell me where to look.

I humbly assume this must be the Doctrine bug, because it was proved that two documents with same ID have different properties. But I don't know.

I am on 2.2.0 but this stuff was happening on 2.0-dev as well. I also tried few 2.1.* versions.

We also have a strange bug where `$unrelatedDocument->group === null` although the field CONTAINS reference to the group document. I will describe it in more detail in separate thread.

Thank you very much guys for any help! I am quite desperate already :-)

**Comment by malarzm** [comment]
Given you're using references we can cross out weird embedded documents `spl_object_id` collisions. What's the cache doing? Do you clear document manager somewhere in the process? Even if you do, having two documents with same ids but different data looks very strange, `_id` must be unique in the collection. Beside these questions I'd take following steps:
1. Double check if the data in db is correct
2. Step-debug through the tree flattening process and see where the borked doucment is coming from
3. If you're still positive it's ODM bug it'll be way quicker for us to have a PR with a failing test case

**Comment by josefsabl** [comment]
Thank you for prompt response!


> Given you're using references we can cross out weird embedded documents spl_object_id collisions.

Yes, agreed.


> What's the cache doing?

It's a separate cache than what doctrine uses.

It caches general random pieces of information. Mostly pre-calculated fragments of html so that expensive calculations don't need to be run repeatedly without data being actually changed. Oversimplified: There is a list of users, it is cached and cache item is tagged as "Domain\User\Document". When any Domain\User\Document is changed the doctrine event is caught and cache is invalidated.

There is no write operation when the circular reference bug occurs so no cache is invalidated in that request.

The problem here is that when everything is cached => works. Nothing is cached => works. Something is cached => bug. I tried to isolate which cache item needs to be invalidated. But it seems to "travel". There obviously are some side effects and something somewhere needs to happed OR must not happen to break the internal state od Doctrine.

I even fixed the problem temporarily by loading one whole collection at the beginning of a script. But the bug resurfaced later somewhere else.

Note: We are not caching whole Documents (afaik). Sometimes we cache document IDs and then "rehydrate" by pulling form repository by these IDs. Could caching whole documents be a problem here?


> Do you clear document manager somewhere in the process?

No


> Even if you do, having two documents with same ids but different data looks very strange, _id must be unique in the collection.

Yes, of course. The Document was the same stuff from the database, same _id, same name, same everything except for the parent group (null vs 'root').

I know that MongoIDs are practically GUIDs, there is no conflict.


> Double check if the data in db is correct

Double, triple, quadruple checked. Also colleagues were looking over my shoulder (Rubber ducking) when I tried to debug this.


> Step-debug through the tree flattening process and see where the borked doucment is coming from

Already did that. Let's simplify it a bit: Let's say there are only two documents.

```
Root->parent === null
Group->parent === Root

Root->children[0] === Group
Root->children[0]->children[0] === Root // Should be unset
```

It's coming from the children array, that is auto-populated by Doctrine by bi-directional reference.


> If you're still positive it's ODM bug it'll be way quicker for us to have a PR with a failing test case

I understand and would really love to do that. But I cannot imagine how that would be possible as the problem is pretty complex and affected by some side effects.

I understand you cannot fix that without knowing what is going on.

I created this issue so that maybe you can direct me to specific feature or tell where to look.

I'll try to describe the second a bit similar WTF bug in a separate thread. It is a bug that my colleague encountered so it will take some time before I research it a bit.

**Comment by josefsabl** [comment]
Please ignore, error on our side, of course 🙄 .
