### ISSUE TITLE
Custom Array_ (similar to Hash) type not working with query builder.

### ISSUE THREAD

**Issue by josefsabl** [doctrine/mongodb-odm#2293]
|    Q        |   A
|------------ | -----
| Version     | 2.2.0

### Support Question

We implemented our own Array_ type. We need to store some data as classic BSON array (hash converts them to objects).

It basically is ripped of hash with slightly changed conversion logic. It looks like this:

```php
final class Array_ extends \Doctrine\ODM\MongoDB\Types\HashType
{
    /** {@inheritDoc} */
    public function convertToDatabaseValue($value)
    {
        if ($value !== null && !is_array($value)) {
            throw \Doctrine\ODM\MongoDB\MongoDBException::invalidValueForType(
                'Array',
                ['array', 'null',],
                $value
            );
        }

        return $value !== null ? array_values($value) : null;
    }

    /** {@inheritDoc} */
    public function convertToPHPValue($value)
    {
        return $value !== null ? (array)$value : null;
    }
}
```

The code is working well and we have it in production for quite long. Now, however we encountered this weird behavior:

```php
$this->documentManager->createQueryBuilder(\Document::class)
            ->field('labels')->equals('myLabel')
            ->count()
            ->getQuery()
            ->execute();
```

This code worked in 2.0-dev days. But with upgrade to 2.2.0 it stopped working and throws the exception: `\Doctrine\ODM\MongoDB\MongoDBException::invalidValueForType`. When var_dumped, the `$value` indeed contains `'myLabel'` and not the array. Weirdly, when changing the fields type to `hash` it works again.

I tried changing it to:

```php
$this->documentManager->createQueryBuilder(\Document::class)
            ->field('labels')->equals(['myLabel']) // << see the array?
            ->count()
            ->getQuery()
            ->execute();
```

But it still does not work.

I also made sure the `Array_ extends HashType`.

I guess that [this stuff](https://github.com/doctrine/mongodb-odm/blob/2.2.x/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php#L1188) may be the problem? Somehow?

I couldn't find any other use of the Hash type and handled in any special way.

**Comment by malarzm** [comment]
This doesn't solve the problem that working code broke, but why won't you use [`collection` type](https://github.com/doctrine/mongodb-odm/blob/2.2.x/lib/Doctrine/ODM/MongoDB/Types/CollectionType.php)?
