### ISSUE TITLE
XML mapping doesn't take account of the attribute `nullable` for embedded document

### ISSUE THREAD

**Issue by wuchen90** [doctrine/mongodb-odm#2295]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.2.0

#### Summary

I use XML to map the documents.
When I set the attribute `nullable=true` to a property, which is an embedded document (`embed-*`), the `ClassMetadata` resulted always set this property to `ClassMetadata->isNullable() === false`.
By the way, mapping with annotations works well.

Here is an example of the mapping:
```
<document name="Model\Cart" collection="carts">
        <embed-one field="shippingAddress" target-document="Model\ShippingAddress" nullable="true"/>
```

#### Current behavior

Whatever the attribute `nullable` is, when it's set to an embedded document property, the `ClassMetadata->isNullable()` always returns `false`.
For annotation mapping, there is no problem because all the metadata provided in annotations are merged to build the `ClassMetadata`.
But for XML, the metadata are built attribute by attribute and there is no part dealing with `nullable`.
See https://github.com/doctrine/mongodb-odm/blob/8069ded252ff457c481b4da7464ff9db00be41ba/lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php#L354-L395

#### Expected behavior

If the `nullable` attribute is set to `true` to an embedded document property, the `ClassMetadata->isNullable()` must returns `true`.

**Comment by malarzm** [comment]
@wuchen90 thanks for the report! Would you be up for fixing the issue? Taking a look at the XML driver it seems to me that `nullable` is not handled not only for embed one/many but also for normal fields and references. It'd be great to investigate this all and fix if I'm right.

**Comment by wuchen90** [comment]
@malarzm 
Here is my PR: https://github.com/doctrine/mongodb-odm/pull/2297.
You were right about normal fields and references.
