### ISSUE TITLE
Add the possibility to set the timezone to dateToString

### ISSUE THREAD

**Issue by Chocob0b** [doctrine/mongodb-odm#2303]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | no

#### Summary

Could it be possible to add the possibility to set the timezone to dateToString like this :

```
public function dateToString(string $format, $expression, string $timezone): self
{
    return $this->operator('$dateToString', ['format' => $format, 'date' => $expression, 'timezone' => $timezone]);
}
```

**Comment by malarzm** [comment]
Given the `$timezone` argument is optional and original behaviour is preserved I see no downsides 👍 While we're at it we could also add the optional `onNull` argument. @Chocob0b would you be up for sending as a PR?
