### ISSUE TITLE
Extend from `AbstractLazyCollection` in `PersistentCollection`

### ISSUE THREAD

**Issue by franmomu** [doctrine/mongodb-odm#2323]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | hopefully no

#### Summary

The current [`PersistentCollection`](https://github.com/doctrine/mongodb-odm/blob/ccf26d9e023387e9aae86951186c043b3222fe70/lib/Doctrine/ODM/MongoDB/PersistentCollection.php) uses [`PersistentCollectionTrait`](https://github.com/doctrine/mongodb-odm/blob/ccf26d9e023387e9aae86951186c043b3222fe70/lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php) for the implementation. 

Looking at [`doctrine/orm` `PersistentCollection`](https://github.com/doctrine/orm/blob/ee19cf5cfd265b4ea7710c047cf77e8a30a4c3fd/lib/Doctrine/ORM/PersistentCollection.php#L54), it extends from [`AbstractLazyCollection`](https://github.com/doctrine/collections/blob/94918256daa6ac99c7e5774720c0e76f01936bda/lib/Doctrine/Common/Collections/AbstractLazyCollection.php) (implemented in https://github.com/doctrine/orm/pull/1274), I guess the same could be done here and remove some code.

**Update**: I didn't see https://github.com/doctrine/mongodb-odm/blob/2.2.x/lib/Doctrine/ODM/MongoDB/PersistentCollection/DefaultPersistentCollectionGenerator.php so it may not be that easy.

**Comment by malarzm** [comment]
Yes, due to the fact we allow users to have custom collections our persistent collection needs to extend user's class so the typing is happy. Also that's the reason we have an interface for a persistent collection. I don't think we'll be able to change that in any way, is it blocking you from doing something?

**Comment by malarzm** [comment]
Ah, is this related to #2324?

**Comment by franmomu** [comment]
> Yes, due to the fact we allow users to have custom collections our persistent collection needs to extend user's class so the typing is happy. Also that's the reason we have an interface for a persistent collection. I don't think we'll be able to change that in any way, is it blocking you from doing something?

Not at all, while doing https://github.com/doctrine/mongodb-odm/pull/2324 just realised of that difference with the `ORM` and then after posting it, I found out about the custom persistent collections.

Thanks for answering!
