### ISSUE TITLE
Add missing generic annotations

### ISSUE THREAD

**Issue by franmomu** [doctrine/mongodb-odm#2358]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

We've been adding some support for generics lately, `ClassMetadata` is generic, but there are some places as pointed out by @IonBazan

https://github.com/doctrine/mongodb-odm/blob/34a3cf8c8ce1d05ced9ce3d123ac8db602630c36/lib/Doctrine/ODM/MongoDB/Query/Filter/BsonFilter.php#L70

That annotations are missing and phpstan and psalm will complain, we should add them.

In cases where it isn't generic, we can use just `@psalm-param ClassMetadata<object>`.

**Comment by IonBazan** [comment]
Closed by #2367
