### ISSUE TITLE
Type::convertToPHPValue($value) doesn't actually get called

### ISSUE THREAD

**Issue by housebolt** [doctrine/mongodb-odm#237]
Recently creating a custom type I ran across an issue regarding type conversions. I created a type that ciphers plain text, but I need to be able to decrypt the data after it's been pulled from the database. Turns out that convertToPHPValue() never actually gets called. This is different from the Doctrine ORM because I know that it definitely gets called for ORM types.

``` php
/**
 * Ciphered data type
 */
class CipheredStringType extends Type {

    protected $cipher;

    public function convertToDatabaseValue($value) {
        return $value !== null ? $this->getCipher()->encrypt((string) $value) : null;
    }

        //This never actually gets called, so I get the encrypted text after database pull
    public function convertToPHPValue($value) {
         return $value !== null ? $this->getCipher()->decrypt((string) $value) : null;
    }

    public function getCipher() {
        //Cipher created here
    }

}
```

I know there are other ways to handle this but it would be nice if I could do it transparently via a type. This is confusing for new people to the Doctrine ODM because the documentation implies that convertToPHPValue() will actually get called at some point in the process.

**Comment by CedrickOka** [comment]
Hi @housebolt

Here is a temporary solution since there has been no progress on the subject

```php
public function closureToPHP() :string
{
    return '$type = \Doctrine\ODM\MongoDB\Types\Type::getType(\'type_name\'); $return = $type->convertToPHPValue($value);';
}
```

**Comment by malarzm** [comment]
Actually there's a `\Doctrine\ODM\MongoDB\Types\ClosureToPHP` which provides exactly that function. We recommend using it along with implementing `convertToPHPValue` method. It's also showcased in the docs: https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/custom-mapping-types.html. If there is still something off please do open a new issue instead of resurrecting an eight years old one.
