### ISSUE TITLE
Support wildcard indexes

### ISSUE THREAD

**Issue by jseparovic1** [doctrine/mongodb-odm#2371]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Mongodb supports adding [wildcard Indexes](https://docs.mongodb.com/v4.4/core/index-wildcard/) but it is not possible to configure it via mongodb-odm mappings.

Using following mapping:
```xml
<indexes>
    <index name="field.$**">
        <key name="field_wildcard"/>
    </index>
</indexes>
```

Results in error `Line 27:0: Element '{http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping}index', attribute 'name': 'tenants.$**.configured' is not a valid value of the atomic type 'xs:NMTOKEN'.`

**Comment by IonBazan** [comment]
Thanks for your bug report @jseparovic1. Let me know if #2372 fixes the issue for you.

**Comment by IonBazan** [comment]
@jseparovic1 According to XSD schema, it is actually possible to create an index with wildcard keys - only the index name is currently limited to `xs:NMTOKEN`. If you don't mind renaming your index, you can always use:
```xml
<indexes>
    <index name="field_wildcard_1">
        <key name="field.$**"/>
    </index>
</indexes>
```
until 2.2.3 is released.
