### ISSUE TITLE
open_basedir restriction in effect. File(/tmp) is not within the allowed path.

### ISSUE THREAD

**Issue by schaabez** [doctrine/mongodb-odm#2389]
On some shared hosts / webspaces **the sys_get_temp_dir()** is not accessable / writeable.

Creating new MongoDB/Configuration will throw exception.

#### Possible solution

Propably removing setAutoGenerateProxyClasses from constructor of MongoDB/Configuration.php, to be able change the path.

**Comment by malarzm** [comment]
> Propably removing setAutoGenerateProxyClasses from constructor of MongoDB/Configuration.php, to be able change the path.

I'm afraid we can't do that as that'd break configuration for folks relying on AUTOGENERATE_FILE_NOT_EXISTS mode as we'd need to change it to eval to have any default strategy in place. That'd fix your issue, but technically is a BC break.

> On some shared hosts / webspaces the sys_get_temp_dir() is not accessable / writeable.

I guess complaining about it to the provider doesn't help? Or according to https://www.php.net/manual/en/function.sys-get-temp-dir.php there's an INI setting to chnage the value?

**Comment by malarzm** [comment]
Closing as fixing the issue doesn't seem feasible on our end and a workaround exists.
