### ISSUE TITLE
Support for PHP 8.1 enums

### ISSUE THREAD

**Issue by IonBazan** [doctrine/mongodb-odm#2404]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

We could add native support for PHP 8.1+ enums by adding a new parameter to the mapping that allows to define the enum class name like it's done in ORM: https://github.com/doctrine/orm/pull/9304

**Comment by ozahorulia** [comment]
I'm already using this feature in the latest doctrine ORM. It would be great to have the same functionality for the ODM.

**Comment by malarzm** [comment]
Referencing ORM's PR we could base our work on: https://github.com/doctrine/orm/pull/9304

**Comment by malarzm** [comment]
Merged in #2440
