### ISSUE TITLE
After upgrading  odm into 2.3.0+ faced with the issue with doctrine:mongodb:schema:update command

### ISSUE THREAD

**Issue by runtothefather** [doctrine/mongodb-odm#2405]
since 2.3.0+ doctrine:mongodb:schema:update command start execute validators on the schema also and it can't be skipped, beforehand only indexes were applied, are there any chances to add option or parameter into the command to skip this?

**Comment by malarzm** [comment]
What's the problem with executing validators? We're only aware of #2402 so far

**Comment by runtothefather** [comment]
for instance we wouldn't like to grant these type of permissions for deploy|prod user

**Comment by malarzm** [comment]
In my opinion `collMod` is a perfectly fine permission for a deploy user. I believe that adding a skip option will bite folks who few months from now will forget about it, wonder why validators aren't created and open issues that their validators aren't created. Last but not least, adding an opt-out requires user action anyways.

Having said all that I do get that a new and unused feature broke command that used to work "just fine". To mitigate the issue automatically for everybody we could make a check in schema manager that would first retrieve validation rules from a collection, and if both that and document rules are empty will skip running `collMod` command. This will however add `n` more queries where `n` is a number of collections.

**Comment by ksowa** [comment]
@malarzm the lack of the ability to turn off validators update also causes problem with AWS DocumentDB (v4.0.0 in my case), which is MongoDB-compatible, but in the same time has a few features turned off. 

The output of `doctrine:mongodb:schema:update` using AWS DocumentDB is as follows:

```
Updated indexes for all classes
Feature not supported: Document Validaton
```

Here is a list of supported MongoDB operations: https://docs.aws.amazon.com/documentdb/latest/developerguide/mongo-apis.html

**Comment by malarzm** [comment]
We're not supporting DocumentDB, but given we can solve more than 1 issue with a feature switch I'm open to adding a `--disable-validators` (not that I like it or changed my opinion about it tho) in a bugfix version. Command with disabled validators should throw an exception if it encounters a document with defined validators. @ksowa up for a PR?

**Comment by ksowa** [comment]
@malarzm sure, I’ll be happy to create one. Thanks!

**Comment by ksowa** [comment]
I've created the PR, however it does not include the `Command with disabled validators should throw an exception if it encounters a document with defined validators` part. These are the reasons:

1. I'm not sure if users would expect any exceptions regarding validation rules if they disable their update by an option.
2. The flow could be confusing if they wanted to clear existing rules from the DB by removing them from the mappings.
3. The change would need to go as deep as into the `SchemaManager` class, probably with 2 additional methods, like `ensureNoValidators` and `ensureNoDocumentValidators`. I'm not sure if you want to follow this way. 

If you don't agree with the approach, please decline the PR and I'll make it the other way.
