### ISSUE TITLE
Update command copies index from parent class

### ISSUE THREAD

**Issue by ozahorulia** [doctrine/mongodb-odm#2406]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | unknown
| Version     | 2.3.1

#### Summary
I have two documents: **Job** and **ScheduledJob extends Job**.

```php
class Job
{
    protected \DateTime $created;
}

class ScheduledJob extends Job
{
    protected string $status;
    protected \DateTimeImmutable $sendAt;
}
```

And I have two separate mappings for both documents, with different sets of indexes:

```xml
<document name="Job" collection="job">
        <field field-name="created" type="date" />

        <indexes>
            <index>
                <key name="created_1"/>
                <option name="expireAfterSeconds" value="2678400" /> <!-- 31 days -->
            </index>
        </indexes>
</document>
```

```xml
<document name="ScheduledJob" collection="scheduled_job">
        <field field-name="created" type="date" />
        <field field-name="sendAt" type="date_immutable" />
        <field field-name="status" type="string" />

        <indexes>
            <index name="sendAtStatus">
                <key name="sendAt" />
                <key name="status" order="desc"/>
            </index>
        </indexes>
</document>
```

#### Current behavior

When I use command `odm:schema:update`, collection **scheduled_job** is getting two indexes: **created_1** and **sendAtStatus**. If I remove index declaration from Job mapping, command creates only one index **sendAtStatus** for collection **scheduled_job**.

#### Expected behavior

Command `odm:schema:update` creates only one index **sendAtStatus** for collection **scheduled_job** and ignores indexes from Job mapping.

**Comment by malarzm** [comment]
What you see is an expected behaviour - child classes inherit everything from their parent classes. If you don't want this to happen (and I assume your `Job` class has some logic inside that `ScheduledJob` needs to have as well) you need to have following structure:

```
#[MappedSuperclass]
abstract class AbstractJob
{
    // common logic and fields
}

class Job extends AbstractJob
{
    // only Job stuff, here you'll have index for createdAt
}

class ScheduledJob extends AbstractJob
{
    // only ScheduledJob stuff
}
```

You can read more about inheritance here: https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.2/reference/inheritance-mapping.html

**Comment by ozahorulia** [comment]
Got it, thank you.
