### ISSUE TITLE
ReferenceOne, MappedSuperclass and DiscriminatorField

### ISSUE THREAD

**Issue by madhatter42** [doctrine/mongodb-odm#241]
The DocumentManager::getClassMetadata() method doesn't seem to be constructing correct meta-data objects for a class that is included as a reference (using @ReferenceOne) in another class, and then is declared as a @MappedSuperclass with @DiscriminatorField and @DiscriminatorMap; the ClassMetadataInfo::$fieldMappings field is empty.

This is what our classes look like: 

```
    /**
 * @ODM\Document(collection="users")
 */
class User {
    /**
     * @ODM\ReferenceOne(name="company", targetDocument="Documents\Company")
     * @var Document\Company
     */
    protected $company;
}

/**
 * @ODM\MappedSuperclass
 * @ODM\InheritanceType("SINGLE_COLLECTION")
 * @ODM\DiscriminatorField(fieldName="type")
 * @ODM\DiscriminatorMap({"seller"="Documents\SellerCompany", "buyer"="Documents\BuyerCompany"})
 */
abstract class Company extends Document
{   
    ...
}
```

Here's the text of the exception that is being thrown:

InvalidArgumentException thrown in /Users/madhavkrishna/src/ADstruc/vendor/doctrine/lib/Doctrine/ODM/MongoDB/Mapping/Types/Type.php on 120 (code 0) Invalid type specified "".
[Mon Jan 23 17:55:13 2012] [error] [client ::1] #0 /Users/madhavkrishna/src/ADstruc/vendor/doctrine/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php(1242): Doctrine\ODM\MongoDB\Mapping\Types\Type::getType(NULL)\n#1 /Users/madhavkrishna/src/ADstruc/_application/tmp/cache/DocumentsUserHydrator.php(127): Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo->getPHPIdentifierValue(Object(MongoId))\n#2 /Users/madhavkrishna/src/ADstruc/vendor/doctrine/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php(394): Hydrators\DocumentsUserHydrator->hydrate(Object(Documents\User), Array, Array)\n#3 /Users/madhavkrishna/src/ADstruc/vendor/doctrine/lib/Doctrine/ODM/MongoDB/UnitOfWork.php(2399): Doctrine\ODM\MongoDB\Hydrator\HydratorFactory->hydrate(Object(Documents\User), Array, Array)\n#4 /Users/madhavkrishna/src/ADstruc/vendor/doctrine/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php(492): Doctrine\ODM\MongoDB\UnitOfWork->getOrCreateDocument('Documents\User', Array, Array)\n#5 /Users/madhavkrishna/src/ADstruc/vendor/doctrine/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php(379): Doctrine\ODM\MongoDB\Persisters\DocumentPersister->createDocument(Array, NULL, Array)\n#6 /Users/madhavkrishna/src/ADstruc/vendor/doctrine/lib/Doctrine/ODM/MongoDB/DocumentRepository.php(168): Doctrine\ODM\MongoDB\Persisters\DocumentPersister->load(Array)\n#7 /Users/madhavkrishna/src/ADstruc/_application/ADStruc/Models/UserModel.php(28): Doctrine\ODM\MongoDB\DocumentRepository->findOneBy(Array)\n#8 /Users/madhavkrishna/src/ADstruc/_application/ADStruc/Services/UserService.php(65): ADStruc\Models\UserModel->findOneBy(Array)\n#9 /Users/madhavkrishna/src/ADstruc/_application/controllers/app/test.php(15): ADStruc\Services\UserService->getInfoByIdOrEmail('john@adstruc.co...')\n#10 [internal function]: Test->index()\n#11 /Users/madhavkrishna/src/ADstruc/vendor/codeigniter/system/core/CodeIgniter.php(359): call_user_func_array(Array, Array)\n#12 /Users/madhavkrishna/src/ADstruc/vendor/codeigniter/index.php(202): require_once('/Users/madhavkr...')\n#13 /Users/madhavkrishna/src/ADstruc/app/index.php(40): require_once('/Users/madhavkr...')\n#14 {main}

This is observed when we're calling findOneBy() on the repository for the User object.

**Comment by vdoria** [comment]
+1 on this matter. I want a abstract class that gives basic fields to child classes. This class shouldn't be accessible and i would like to have the inheritance information stored in this class. This imho makes the most sense from a implementer view.

Creating a class in between just to be able to set inheritance settings isn't nice besides the DOC say you should add this class to the map which basically would have either no or just the stub fields from the abstract. That doesn't seem to make sense imho...

**Comment by malarzm** [comment]
`@ReferenceOne` (and `@ReferenceMany`) can only target mapped documents - anything else is (or will) be forbidden. Annotating an abstract class as a document is a valid solution IMO.

**Comment by vdoria** [comment]
Just tested it it's working indeed (just missed the Document annotation in the child).
