### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'MongoWriteConcernException' with message 'localhost:27017: Unknown modifier: $pushAll.

### ISSUE THREAD

**Issue by HuzaifaBinZahoor** [doctrine/mongodb-odm#2429]
|   I don't know what seems to be the problem here. I installed doctrine in a folder where there was no other package other than doctrine and then performed the ODM CRUD operation without any error. When I installed the Symfony 2 project installed the same doctrine package that was working fine I am getting errors.        |   A
|------------ | -----
| Symfony2     | Doctrine 1.0.0

### Support Question

PHP Fatal error:  Uncaught exception 'MongoWriteConcernException' with message 'localhost:27017: Unknown modifier: $pushAll. Expected a valid update modifier or pipeline-style update specified as an array' in C:\xampp\htdocs\ORM_CRUD\vendor\doctrine\mongodb\lib\Doctrine\MongoDB\Collection.php:1427        
Stack trace:

**Comment by sanjyotpanure** [comment]
The $pushAll operator is no longer supported in Mongo in version 3.5 and above.

Try replacing .push with .unshift to deal with this error.

**Comment by malarzm** [comment]
Both Symfony2 and 1.0.0 version of ODM are not supported for a long time, please update. Also please don't repost [StackOverflow questions](https://stackoverflow.com/questions/71902564/fatal-error-uncaught-exception-mongowriteconcernexception-with-message-local) here.

**Comment by HuzaifaBinZahoor** [comment]
Hey Guys, just for your knowledge, even though it's not been supported for a long time, the error was not the version. It was some manual configuration that I was required to set up. 
I was able to resolve it;')
Thanks
KR
