### ISSUE TITLE
Nullable embedded documents not initialized

### ISSUE THREAD

**Issue by p-golovin** [doctrine/mongodb-odm#2453]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.4.2

#### Summary

Problem is quite similar to https://github.com/doctrine/mongodb-odm/issues/2301, but we try to configure not with xml, but with attributes.

#### Current behavior

```
class Publication
{
    #[ODM\EmbedOne(targetDocument: Image::class, nullable: true)]
    private ?Image $image;

    public function getImage(): ?Image
    {
        return $this->image;
    }
}

class Image
{
    #[ODM\Field]
    private string $url;

    public function getUrl(): string
    {
        return $this->url;
    }
}
```

On loading document without Image subdocument we get error
`Typed property Publication::$image must not be accessed before initialization`
on request
`
$pub->getImage();
`

#### Expected behavior

Get null.

**Comment by malarzm** [comment]
> but we try to configure not with xml, but with attributes.

I don't think this is related as nothing mapping related changed in #2302. I'd rather guess that your document has no `null` field stored in the database?

**Comment by p-golovin** [comment]
We tried both cases:

1. Without null stored in database.
Get error.

2. With null stored in database.
Get no error in case of requesting full field 'image' in query builder projection:
`$qb->select('title', 'pub_date', 'image')`
And get error in case of requesting 'image.url' subfield:
`$qb->select('title', 'pub_date', 'image.url')`

I think, that field need to be initialised with null even in case of absence in database document (In case we embed collection of documents, it is initialised with empty collection in any case, even if there is no such key in database). Or there are another ways to deal with this?

**Comment by malarzm** [comment]
> Or there are another ways to deal with this?

Try making `null` a default value: `private ?Image $image = null;`. That way the field will be initialized with null even though ODM didn't hydrate the field.

> With null stored in database. [...] And get error in case of requesting 'image.url' subfield:

Is the error coming from hydration as well?

**Comment by p-golovin** [comment]
1. In case of storing null in database and use 'image' in projection:
![image](https://user-images.githubusercontent.com/7702213/184686269-4f7f6783-6d1f-40d4-b5a2-8ef65a2ada6b.png)
All works at this point. But there is problem with document serialisation: we get `'image': null` in json instead of absence image field.

2. In case of storing null in database and using 'image.url' in projection:
![image](https://user-images.githubusercontent.com/7702213/184686983-258a6c09-6e7c-40c5-9044-7a70c0b369d7.png)
No errors on hydration, but no 'image' field in document. So error `Typed property Publication::$image must not be accessed before initialisation`.

3. If we use `private ?Image $image = null;` then we have field in serialised document again:
![image](https://user-images.githubusercontent.com/7702213/184687453-e6b93265-caf2-4654-a900-3b8ceb761a18.png)
We can solve this with options of serialisation context.

So only question with projection is actual.

**Comment by malarzm** [comment]
> In case of storing null in database and using 'image.url' in projection:

Using 3 should still make projection "work" as the `image` will be initialized to null, no? Generally speaking if there's no `image` object in stored document projection will not return it. Same goes for `null`:

```
> db.test.find();
{ "_id" : ObjectId("62faa4f3417246422135f933"), "name" : "Withembed", "embed" : { "test" : "aaa" } }
{ "_id" : ObjectId("62faa50d417246422135f934"), "name" : "Noembed" }
{ "_id" : ObjectId("62faa589417246422135f935"), "name" : "Nulled", "embed" : null }
> db.test.find({}, {"name": 1, "embed.test": 1});
{ "_id" : ObjectId("62faa4f3417246422135f933"), "name" : "Withembed", "embed" : { "test" : "aaa" } }
{ "_id" : ObjectId("62faa50d417246422135f934"), "name" : "Noembed" }
{ "_id" : ObjectId("62faa589417246422135f935"), "name" : "Nulled" }
```

**Comment by p-golovin** [comment]
Thank you! This works well.
