### ISSUE TITLE
Running `odm:schema:update` produces deprecation warning

### ISSUE THREAD

**Issue by ivan-wolf** [doctrine/mongodb-odm#2454]
Running `odm:schema:update` (https://github.com/doctrine/mongodb-odm/blob/2.4.x/lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/UpdateCommand.php) on PHP `8.1.8` produces the following warning:

`Deprecated: Return type of MongoDB\Model\IndexInfoIteratorIterator::current() should either be compatible with IteratorIterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/mongodb/mongodb/src/Model/IndexInfoIteratorIterator.php on line 60`

**Comment by malarzm** [comment]
The class causing the deprecation you're seeing comes from the MongoDB's library, as the error's filepath is pointing. From what I can tell the `#[ReturnTypeWillChange]` is already [there](https://github.com/mongodb/mongo-php-library/blob/5d48a1ed3e3700fb4b53d623977244c461ad699c/src/Model/IndexInfoIteratorIterator.php#L61) so probably you just need to update your dependencies.
