### ISSUE TITLE
Compatibility fix mapping drivers is not working.

### ISSUE THREAD

**Issue by rimvislt** [doctrine/mongodb-odm#2458]
include_once(Doctrine/Persistence/Mapping/Driver/AnnotationDriver.php): Failed to open stream: No such file or directory

..vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/Driver/CompatibilityAnnotationDriver.php:12

```

use Doctrine\Persistence\Mapping\Driver\AnnotationDriver as PersistenceAnnotationDriver;
use Doctrine\Persistence\Mapping\Driver\MappingDriver;

use function class_exists;

if (class_exists(PersistenceAnnotationDriver::class)) {  // line 12

```

adding into composer.json

**"doctrine/orm": "2.11.*",**

fixes it temporary but not sure why that compatibility fix is needed if it is not working.
So now I can not use correct MappingDriver.

Can we have version without compatibility fix?

**Comment by greg0ire** [comment]
Sounds more like you are using a buggy autoloader. One should be able to use `class_exists()` on a class that does not exist without getting a crash, but `false`, agree? You use Composer, right? If yes, what version?

**Comment by malarzm** [comment]
Closing due to lack of response.
