### ISSUE TITLE
How to construct a match expr() comparing two fields in the same collection

### ISSUE THREAD

**Issue by stephen-swsm** [doctrine/mongodb-odm#2463]
Hi 

We have a collection, in which there are 2 date fields, _timestamp_ and _userCreatedAt_,  and we want to match rows where _timestamp_ is less than 1 minute after the _userCreatedAt_ date. 

i.e. 
```
[
    '$match' => [
        '$and' => [
            ['clientId' => 1 ],
            [ '$expr' => [ '$lte' => ['$timestamp', [ '$add' => [ '$userCreatedAt', 60000] ] ] ] ]
        ]
    ]
],

```
1. A logical solution might be as follows, but we get error presumably because the return of the expression is in milliseconds
    
```
    ->match()
        // (attempt 1) error : Could not convert object to a date value !!
        ->field('timestamp')->lte($ab->expr()->add('$userCreatedAt', 60000))
```

2. Using addFields before the match we can create the timestamp in milliseconds, but although this does not throw an error it also does not return any results 

```
    ->addFields()->field('msTimestamp')->millisecond('$timestamp')
    ->match()
                      
        // (attempt 2, using added field msTimestamp - query runs but no results
        ->field('msTimestamp')->lte($ab->expr()->add('$userCreatedAt', 60000))
```

3. Based on the structure mongo expects the following might work, but there does not seem to be a way to have it return a MatchExpression, instead we get an error that group() is not a function of Expr. It also appears match()->expr()->lte() expects 1 parameter, where as Builder->expr()->lte() expects 2 parameters. It would seem more logical that match()->expr()->lte() expected 2.

```
    ->match()
        ->expr()->lte($ab->expr()->lte('$msTimestamp', $ab->expr()->add('$userCreatedAt', 60000)))

    ->group() 
```

Any help greatly appreciated, Stephen

N.B. The full repository method : 

```
   /**
     * @throws Exception
     */
    public function countUsersOptedInAtRegistration(int $waterClientId, DateRanges $dateRange) : Iterator
    {
        $ab = $this->createAggregationBuilder();

        $ab

//           ->addFields()->field('msTimestamp')->millisecond('$timestamp')

            ->match()
                ->field('waterClientId')->equals($waterClientId)
                ->field('timestamp')->gte($dateRange->getStartDate())
                ->field('timestamp')->lte($dateRange->getEndDate())
                ->field('update.agree_to_messaging')->equals(true)

                // (attempt 1) error : Could not convert object to a date value !!
//              ->field('timestamp')->lte($ab->expr()->add('$userCreatedAt', 60000))

                // (attempt 2), using added field msTimestamp - query runs but no results
//              ->field('msTimestamp')->lte($ab->expr()->add('$userCreatedAt', 60000))

               // (attempt 3), try to build following raw query as a guide, but expr() only returns instance of Expr 
//             ->expr()->lte($ab->expr()->lte('$msTimestamp', $ab->expr()->add('$userCreatedAt', 60000)))

           ->group()
                ->field('_id')->dateToString('%Y-%m-%d', '$timestamp')
                ->field('count')->sum(1)

            ->addFields()->field('id')->expression('$_id.id');

        return $a->getAggregation()->getIterator();
    }
```

**Comment by malarzm** [comment]
I'm afraid I'm not able to provide much insight into this, you may have more luck asking on StackOverflow and tagging your question with [doctrine-odm](https://stackoverflow.com/questions/tagged/doctrine-odm).

Also you may inspect the pipeline constructed with a builder using `\Doctrine\ODM\MongoDB\Aggregation\Builder::getPipeline` - maybe that'll help you :)

**Comment by stephen-swsm** [comment]
Thanks but unfortunately that's not much use, in fact in one of the scenarios postman kills the request because the output from getPipeline is to large - possibly a recursion issue?

As much as I'd love to keep up the trial an error approach I think we're just going to have to put this down as an unsupported query construct.

It can be achieved as follow using [facile-it/mongodb-bundle](https://packagist.org/packages/facile-it/mongodb-bundle)

```
    $query = [
        [
            '$match' => [
                '$and' => [
                    ['client' => 1 ],
                    ['timestamp' => [ '$gte' => 1 ] ],
                    ['timestamp' => [ '$lte' => 1 ] ],
                    ['update.agree_to_messaging' => true ],
                    [ '$expr' => [ '$lte' => ['$timestamp', [ '$add' => [ '$userCreatedAt', 60000] ] ] ] ]
                ]
            ]
        ],
        [
            '$group' => [ '_id' => '$timestampTrunc', 'count' => [ '$sum' => 1 ]]
        ]
    ];
```
Cheers
