### ISSUE TITLE
[RFC] Bump minimal PHP version to 7.4

### ISSUE THREAD

**Issue by malarzm** [doctrine/mongodb-odm#2464]
https://packagist.org/packages/doctrine/mongodb-odm/php-stats#2 shows that ~95% of 2.x users are using at least PHP 7.4 while the minimum required version in 7.2. Given 7.2 -> 7.4 is not bumping for the sake of bumping but would allow us to modernize our code this is a minimum bump we should consider for next minor version.

- [x] Bump minimal PHP version in composer.json
- [x] Remove PHP version checks for PHP 7.x
- [x] Add typed properties and default values where applicable
- [x] Migrate the code to use latest syntax features (arrow functions, etc)

**Comment by IonBazan** [comment]
By all means! Bumping to 7.4 would give us many syntax improvements but some breaking changes may occur when using covariance/contravariance.

**Comment by franmomu** [comment]
is anything else missing here? 🤔 

It would be nice to release 2.5 to unlock other libraries to add support for new `doctrine/*` package versions (like DoctrineMongoDBBundle).

We can finish https://github.com/doctrine/mongodb-odm/pull/2489 and leave the removal of annotation dependency for 2.6.

**Comment by alcaeus** [comment]
No objections from my end. Happy to defer making use of additional 7.4 features (i.e. typed properties) in a future minor version.

**Comment by IonBazan** [comment]
Closing as implemented in linked PRs.
