### ISSUE TITLE
Custom _id for GridFS documents

### ISSUE THREAD

**Issue by andrey-tech** [doctrine/mongodb-odm#2487]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         |  no
| BC Break    | no
| Version | 2.4.x

#### Summary

I would like to have a way to set custom file document identifier (`_id`) for GridFS document, when I insert a new file into GridFS bucket by methods `uploadFromFile()` or `uploadFromStream()` of [GridFSRepository](https://github.com/doctrine/mongodb-odm/blob/2.4.x/lib/Doctrine/ODM/MongoDB/Repository/GridFSRepository.php) interface.

This important functionality is required when migrating from MongoDB using old `doctrine/mongodb-odm` **v1.x** to a new MongoDB using `doctrine/mongodb-odm` **v2.x**. I need to have the same document identifiers (`_id`) for GridFS documents in old and new MongoDB.

Used MongoDB library (`mongodb/mongodb:^1.2.0`) supports this functionality in method `uploadFromStream()` of class [Bucket](https://github.com/mongodb/mongo-php-library/blob/master/src/GridFS/Bucket.php).

I suggest to add the parameter `_id` as a new property of class [UploadOptions](https://github.com/doctrine/mongodb-odm/blob/2.4.x/lib/Doctrine/ODM/MongoDB/Repository/UploadOptions.php) and update method `prepareOptions()` of class [DefaultGridFSRepository](https://github.com/doctrine/mongodb-odm/blob/2.4.x/lib/Doctrine/ODM/MongoDB/Repository/DefaultGridFSRepository.php) to support new option `_id`. So, no big changes are required.

```php
final class UploadOptions
{
    /** @var object|null */
    public $metadata;

    /** @var int|null */
    public $chunkSizeBytes;

    /** @var mixed */
    public $_id;
}
```

**Comment by malarzm** [comment]
@andrey-tech this sounds like a good idea! While we're tweaking `UploadOptions` we could also add this missing options

https://github.com/mongodb/mongo-php-library/blob/4c090a88821db2665bf77a0742ae81efec121380/src/GridFS/Bucket.php#L610-L611

@andrey-tech would you be up for a PR?

**Comment by djkoza** [comment]
We need this feature too! A nice improvement would be converting values to a database via mapping type.
With the @andrey-tech tweak, we need to self-convert the UUID object to the Binary object.

`$uploadOptions->_id = new \MongoDB\BSON\Binary($uuid->getBytes(), Binary::TYPE_UUID);`

with mapping

`<id field-name="uuid" strategy="NONE" type="ramsey_uuid_binary" />`

**Comment by andrey-tech** [comment]
@malarzm Yes, https://github.com/doctrine/mongodb-odm/pull/2489

**Comment by alcaeus** [comment]
#2489 was merged, closing here.
