### ISSUE TITLE
References to removed documents

### ISSUE THREAD

**Issue by drhd54** [doctrine/mongodb-odm#2522]
|    Q        |   A
|------------ | -----
| Version     |  2.5.0
| Support Question | yes 
| Feature Request (Documentation) | yes

## Description 

I have a problem with references to non-existent documents occurring after referenced documents are removed. Example: If a Document A references one Document B and Document B is removed, Document A keeps its reference to the now non-existing Document B. You can find a more detailed example below.

I was unable to find a definitive answer on whether this is a bug or an intended behavior in the documentation. I have read the following pages carefully: 
https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/reference-mapping.html
https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/bidirectional-references.html#bi-directional-references
https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/complex-references.html#complex-references

So if this is not a problem, you can see this issue as a feature request to include the expected behavior in the documentation.

## Detailed Example

To make things more clear, here is a simple example, that defines a relation between a product and a manufacturer. Each product references one manufacturer,  a manufacturer is referencing many products:

``` php
/**  
 * @MongoDB\Document  
 */  
class Product  
{  
    // id 
	
    /**  
     * @var Manufacturer  
     * @MongoDB\ReferenceOne(targetDocument=Manufacturer::class, inversedBy="products")  
     */    
     protected Manufacturer $manufacturer;  
     
     // getters & setters
}

/**  
 * @MongoDB\Document  
 */  
class Manufacturer  
{  
    // id 
	
    /**  
     * @var Collection<Product>  
     * @MongoDB\ReferenceMany(targetDocument=Product::class, mappedBy="manufacturer")  
     */    
     protected Collection $products;  
     	
     // getters & setters
}
```

Here is my issue: I create a manufacturer and two products referencing that manufacturer. Then I remove the manufacturer via document manager. The products keep their references to the deleted manufacturer:
```json
{  
  "_id": {"$oid": "642ac3b84040c7d05508229a"},  
  "manufacturer": "{ \"$ref\" : \"Manufacturer\", \"$id\" : \"642ac3b84040c7d055082298\" }"
}
```

What I want to archive is that the reference at the product-document is automatically set to null, as soon as the referenced manufacturer is removed. Is that even possible? I tried to resolve this by updating the relation in the manufacturer document:

- cascade "delete" or "detach": manufacturer is deleted, references still present
- orphanRemoval=true: manufacturer and products are removed, not what I want to archive.

I tried the same at the product document, without success. Everytime I delete the manufacturer, the product still contains the reference to the deleted manufacturer. Is this behaviour intended? Am I overlooking something in the documentation or missing any best-practice on how to deal with this problem? Thanks!

**Comment by malarzm** [comment]
ODM does not provide any tools to do what you want automatically, maintaining referential integrity in a no-relational database is on the user :) You have two options:

1) if the number of product of a manufacturers is acceptable to load into memory, do so and unlink manufacturer through PHP and the flush changes
2) fire additional query that will update products in the database, after removing the manufacturer. In-memory state will not have the change reflected though

**Comment by drhd54** [comment]
All right, thanks for the answer and explanation!
