### ISSUE TITLE
Deprecation notice when calling DocumentRepository->clear() since 2.4.0

### ISSUE THREAD

**Issue by TranquilCapybara16493** [doctrine/mongodb-odm#2526]
|    Q        |   A
|------------ | -----
| Version     | 2.4.0+

### Support Question
Since in 2.4.0 deprecation notices were introduced in https://github.com/doctrine/mongodb-odm/commit/b2618849e4d162cdaad6b7779d34c3e08a5ec696

Following deprecation notice is triggered 
`PHP Deprecated: Since doctrine/mongodb-odm 2.4: Calling Doctrine\ODM\MongoDB\DocumentManager::clear() with any arguments to clear specific documents is deprecated and will not be supported in Doctrine ODM 3.0. in /var/www/project/vendor/symfony/deprecation-contracts/function.php on line 25`

whenever DocumentRepository->clear() method is called because it passes an argument to DocumentManager
https://github.com/doctrine/mongodb-odm/blob/cdb60e2db3aed1de630bb1cd077e6ff2f3d45a4b/lib/Doctrine/ODM/MongoDB/Repository/DocumentRepository.php#L93-L96
https://github.com/doctrine/mongodb-odm/blob/cdb60e2db3aed1de630bb1cd077e6ff2f3d45a4b/lib/Doctrine/ODM/MongoDB/DocumentManager.php#L706-L717

Is there any intent to either deprecate DocumentRepository->clear() or what should be a proper course of action in this case?

**Comment by malarzm** [comment]
> Is there any intent to either deprecate DocumentRepository->clear() or what should be a proper course of action in this case?

Yes, `DocumentRepository::clear` should have been deprecated in 2.4 along with the original deprecation, not doing so was our bad. We'll add the deprecation in 2.5.x :)

**Comment by alcaeus** [comment]
I've opened #2584 to deprecate this in 2.6.0, as required by Semver.
