### ISSUE TITLE
Support creating time series collections

### ISSUE THREAD

**Issue by nicklaw5** [doctrine/mongodb-odm#2533]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

As far as I can tell, this ODM doesn't yet support creating [time series collections](https://www.mongodb.com/docs/manual/core/timeseries-collections/#time-series-collections).

It doesn't appear to me that it would be too difficult to implement this. Seems we'd need to add the [`timeseries`](https://www.mongodb.com/docs/manual/reference/method/db.createCollection) option on [`Document::$collection`](https://github.com/doctrine/mongodb-odm/blob/2.6.x/lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Document.php#L41) like we already do for the `capped`, `size` and `max` collection options.

The end goal for my team and I would be to have the ability to create time series collections using the [DoctrineMongoDBBundle](https://github.com/doctrine/DoctrineMongoDBBundle) `schema:create` command:

```
bin/console doctrine:mongodb:schema:create --collection
```

**Comment by malarzm** [comment]
> Seems we'd need to add the [timeseries](https://www.mongodb.com/docs/manual/reference/method/db.createCollection) option on [Document::$collection](https://github.com/doctrine/mongodb-odm/blob/2.6.x/lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Document.php#L41) like we already do for the capped, size and max collection options.

That'd be the way to go IMO. Possible it'll turn out that instead of array-based configs it'll be better to have dedicated `CappedCollection` and `TimeSeriesCollection` VOs :)

> It doesn't appear to me that it would be too difficult to implement this.

Are you willing to give it a go?

**Comment by bradroc** [comment]
> Are you willing to give it a go?

I'd be willing to make a stab at this @malarzm.  Is there any preference on direction re: using the same Collection definition or having a separate decorator for TimeSeriesCollection?

**Comment by malarzm** [comment]
> I'd be willing to make a stab at this @malarzm.

Awesome! Thank you 🎉 

FWIW there's work started in a draft PR here: #2542

>  Is there any preference on direction re: using the same Collection definition or having a separate decorator for TimeSeriesCollection?

For now we've decided to follow in the footsteps of capped collection as it made sense, however I really like the idea of having `#[Collection]`, `#[CappedCollection]` and `#[TimeSeriesCollection]`! That would clearly separate what setting goes where. If I'm not mistaken this can be done as a separate step though, so:

1. Finish #2542 or open new one
2. Have it merged
3. Introduce new attributes/xml syntax in a BC manner, deprecate old properties

**Comment by cyildirim** [comment]
HI @bradroc, it would be great to collaborate on this. We need to rerun/fix/add some tests on the project. I've shared some progress on Symfony's new-doctrine-contributors slack channel. If you can join us there it would be great.

**Comment by nicklaw5** [comment]
Seeing some progress on this in #2687

**Comment by alcaeus** [comment]
This feature has been implemented and will be released in 2.10.0!
