### ISSUE TITLE
Replace $ref with actual object upon serialization.

### ISSUE THREAD

**Issue by SinisterGlitch** [doctrine/mongodb-odm#2534]
Whenever i deserialise a repository call in Symfony framework i see $ref instead of the object. 

I understand they are not embedded and thus showing a reference to another table.

Question: How can i replace the references on output with the actual objects and still keep my referenceOne relation.

![Screenshot 2023-05-22 at 09 58 29](https://github.com/doctrine/mongodb-odm/assets/134267616/cca718a4-ed9d-4ac3-9167-a3a6eb761572)

PS. i tried googling but nothing could help me. Any help is very appreciated!

- mongo doctrine left join reference
- mongo doctrine replace reference with objects

**Comment by malarzm** [comment]
@SinisterGlitch we use GH issues to track ODM's development, not as a help channel. Please ask your question on [StackOverflow ](https://stackoverflow.com)using `doctrine-odm` (and other appropiate tags) or try our [Slack](https://doctrine.slack.com).
