### ISSUE TITLE
Add option to exclude collection from creating via doctrine:mongodb:schema:create command 

### ISSUE THREAD

**Issue by amirreza1994** [doctrine/mongodb-odm#2540]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

I have 2 bounded context and both have Shipment entity associated with one Shipment collection but they look at data in different angle, When I'm running ```doctrine:mongodb:schema:create``` I got ```Collection already exists``` for the second Entity and its clear because doctrine try to create same collection for second entity and its already created for the first entity but I need an option to exclude collection creation for one of these Entity. 
note that View and QueryResultDocument does not work for me because I want to update these 2 Shipment entity too.

**Comment by malarzm** [comment]
Sharing a collection between bounded contexts sounds like a violation of a boundary :) This doesn't sound like something we want to support
