### ISSUE TITLE
Add optional parameters to `nearSphere` and `near` GeoFuntions

### ISSUE THREAD

**Issue by AlexMinaev19** [doctrine/mongodb-odm#2545]
### Feature Request

Currently, `mongodb-odm` supports only the required parameters of  `nearSphere` and `near` GeoFuntions: `GeoJson point` or `legacy coordinate point`.
For example, `nearSphere` function (same for `near`):
```php
$this->createQueryBuilder()
    ->field('location')
    ->nearSphere(GeoJson\Geometry\Point(<longitude>, <latitude>))
```

```php
$this->createQueryBuilder()
    ->field('location')
    ->nearSphere([
        'type' => 'Point',
        'coordinates' => [<longitude>, <latitude>]
    ])
```
or

```php
$this->createQueryBuilder()
    ->field('location')
    ->nearSphere(<longitude>, <latitude>)
```
According to the latest documentation of [`nearSphere` operator](https://www.mongodb.com/docs/manual/reference/operator/query/nearSphere/#mongodb-query-op.-nearSphere) and [`near` operator](https://www.mongodb.com/docs/manual/reference/operator/query/near), in addition, to the required parameters, you can also use optional `$maxDistance` and `$minDistance`. They needed to limit the result set of operators, but currently `mongodb-odm` doesn't support them.

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

I suggest the next:
1. Add optional parameters to `Builder::nearSphere()` and `Builder::near()` methods:
```diff
- public function nearSphere($x, $y = null): self
+ public function nearSphere($x, $y = null, $maxDistance = null, $minDistance = null): self
{
-    $this->expr->nearSphere($x, $y);
+    $this->expr->nearSphere($x, $y, $maxDistance, $minDistance);
     
     return $this;
}
```

2. Add optional parameters to `Exrp::nearSphere` and `Expr::near` methods:
```diff
- public function nearSphere($x, $y = null): self
+ public function nearSphere($x, $y = null, $maxDistance = null, $minDistance = null): self 
{
-     if ($x instanceof Point) {
-         $x = $x->jsonSerialize();
-     }

-     if (is_array($x)) {
-         return $this->operator('$nearSphere', ['$geometry' => $x]);
-     }

-     return $this->operator('$nearSphere', [$x, $y]);

+     $optional = [];

+     if ($x instanceof Point) {
+         $x = $x->jsonSerialize();
+     }

+     if ($maxDistance !== null) {
+         $optional += ['$maxDistance' => $maxDistance];
+     }

+     if ($minDistance !== null) {
+         $optional += ['$minDistance' => $minDistance];
+     }

+     if (is_array($x)) {
+         return $this->operator('$nearSphere', ['$geometry' => $x] + $optional);
+     }
        
+     $expr = $this->operator('$nearSphere', [$x, $y]);
        
+     if ($maxDistance !== null) {
+         $expr = $expr->operator('$maxDistance', $maxDistance);
+     }

+     if ($minDistance !== null) {
+         $expr = $expr->operator('$minDistance', $minDistance);
+     }

+     return  $expr;
}
```
It will allow us to use optional parameters and filter result set better.

**Comment by malarzm** [comment]
@alcaeus any thoughts on this one? :)

**Comment by alcaeus** [comment]
See #2583
