### ISSUE TITLE
ReferenceMany without targetDocument throws error in ClassMetadataFactory

### ISSUE THREAD

**Issue by leek** [doctrine/mongodb-odm#258]
I have a `@ReferenceMany` defined like this:

```php
    /**
     * @MongoDB\ReferenceMany(mappedBy="post")
     */
    protected $activity;
```

This works great until I try to serialize the object (using `JMSSerializerBundle`) as the MongoDB ODM throws the following error:

> Warning: class_parents() [function.class-parents]: object or string expected in ...\\doctrine-mongodb-odm\\lib\\Doctrine\\ODM\\MongoDB\\Mapping\\ClassMetadataFactory.php line 336

Following the stack trace leads me to line 693 of DocumentPersister.php:

```php
        $targetClass = $this->dm->getClassMetadata($mapping['targetDocument']);
```

`$mapping['targetDocument']` in this instance is `null`.

**Comment by malarzm** [comment]
#1136 was merged manually in https://github.com/doctrine/mongodb-odm/commit/c659449fac9bbbf37fcfe056098ffb0bc829f196
