### ISSUE TITLE
MongoDB-ODM & Spiral framework.

### ISSUE THREAD

**Issue by solguru310** [doctrine/mongodb-odm#2611]
Hello. everybody.
I have one problem.
I have to integrate mongodb-odm to Spiral framework but I can't config.
Anybody help me?

**Comment by malarzm** [comment]
I don't know what Spiral is but I'm sure following the docs will work for you just fine https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.5/reference/introduction.html#setup
