### ISSUE TITLE
Add CI workflow to check documentation

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#2640]
While writing docs for #2630, I was looking for some way to validate RST files within the PR. I asked about this in Slack (see: [thread](https://doctrine.slack.com/archives/GERFT2W5T/p1716228434425089)) and @greg0ire pointed me to a workflow in the ORM repository that utilizes [phpDocumentor/guides-cli](https://github.com/phpDocumentor/guides-cli): https://github.com/doctrine/orm/blob/3.1.x/.github/workflows/documentation.yml

This issue can serve as a tracking ticket to look into that and see if we can adapt it for the ODM repo.

**Comment by GromNaN** [comment]
Fixed by #2646
