### ISSUE TITLE
Inability to list search indexes is not properly detected

### ISSUE THREAD

**Issue by ivan-wolf** [doctrine/mongodb-odm#2674]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.8.1

#### Summary

Inability to list indexes is not properly detected anymore by the following lines of code:

https://github.com/doctrine/mongodb-odm/blob/2.8.1/lib/Doctrine/ODM/MongoDB/SchemaManager.php#L1060-L1063

#### Current behavior

With MongoDB `7.0.14`, the error message is `$listSearchIndexes stage is only allowed on MongoDB Atlas`.

It does not contain `Search index`, so it's not recognized as unsupported command.

As such, the `odm:schema:update` command fails, even when there are no search indexes defined.

#### How to reproduce

Run the `odm:schema:update` command.

#### Expected behavior

The `odm:schema:update` does not fail when there are no search indexes defined.

**Comment by alcaeus** [comment]
Fixed in #2673.
