### ISSUE TITLE
odm:schema:drop command does not drop search indexes

### ISSUE THREAD

**Issue by pkowalski700lm** [doctrine/mongodb-odm#2684]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.9.0

#### Summary

odm:schema:drop does not drop  search indexes.

#### Current behavior

After running odm:schema:create while having mapped document with search index defined & mapped,  odm:schema:drop does not drop search index. While trying to drop it it outputs error: Cannot use object of type stdClass as array.

It succesfuly drops normal indexes, collections and databases after that.

#### How to reproduce
1. Add some search index to mapped document
2. run odm:schema:create
3. run odm:schema:drop

#### Expected behavior

Search index should be succesfully dropped.

**Comment by GromNaN** [comment]
Testing this with this document class, I reproduce the error. I'm not able to get the stack trace of the error using `-vvv`, that makes debugging more difficult.

```php
namespace App\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations\{Document, Field, Id, SearchIndex};
use MongoDB\BSON\ObjectId;

#[Document, SearchIndex(dynamic: true)]
class Article
{
    #[Id] public ObjectId $id;
    #[Field] public string $title;
}
```

I noted an other similar issue when none of `dynamic` or `fields` parameter is set and running the creation command `doctrine:mongodb:schema:create`:
> `BSON field 'createSearchIndexes.indexes.definition' is the wrong type 'array', expected type 'object'`
