### ISSUE TITLE
Filter on linked datas.

### ISSUE THREAD

**Issue by armetiz** [doctrine/mongodb-odm#275]
Hi there,
I think that Doctrine MongoDB Mapper is an great project !
But, I have a question about Referenced Collection.

Documentation says that we can load referenced collection and doctrine links X collection between each other.
Thanks to this feature we can work with referenced objects.

Here an example with prime.

``` php
$qb = $dm->createQueryBuilder('User')
    ->field('accounts')->prime(true)
    ->limit(100);
$query = $qb->getQuery();
```

Right now,
I have not find how to "filter" or "query" related datas. 
Simple example, If some account aren't enabled, how can I remove them from result.

Here an example of what I need :

``` php
$qb = $dm->createQueryBuilder('User')
    ->field('accounts.enabled')->equals(true)->prime(true)
    ->limit(100);
$query = $qb->getQuery();
```

The problem is, that it's not working because Doctrine considere that account.enabled is a sub-document of user and not a referenced collection.

Be able to filter reference could be a really awesome feature for Doctrine MongoDB Mapper. Don't you think ?

To be able to get this feature, I think Doctrine MongoDB have to introduce a new function on Query : "join" or something like that to be able to work on the sub-query made be Doctrine.

I have understand that Doctrine make primary request, and then do X sub-requests for X referenced collections.
The only thing to do is to be able to work with the sub-requests.

If we're able to work with the sub-request as we're work with Query API, we can add many thing like "equals", or "sort" and "limit" to sub-request. It will be really really awesome !

What do you think about it ?

**Comment by alcaeus** [comment]
Filtering across references in queries is not supported by MongoDB, but the new `$lookup` stage in combination with hydrated aggregation results can be used to achieve the same thing. Closing this.
