### ISSUE TITLE
findBySomething($object) doesn't work

### ISSUE THREAD

**Issue by kusmierz** [doctrine/mongodb-odm#292]
I've field with ReferenceOne annotate:

```php
class Article
{
// ...
    /**
     *
     * @ODM\ReferenceOne(targetDocument="Document\Category", inversedBy="articles", simple=true, cascade={"all"}, nullable=true)
     */
    protected $category;
// ...
}
```

Now in its repository I'm trying:

```php
class ArticleRepository extends DocumentRepository
{
    // ...
    public function findByCategory(Category $category)
    {
        return parent::findByCategory($category->getId());
    }
    // ...
}
// ...
```

Yes, I know, it's stupid, but because of DocumentPersister::prepareQuery I can't do it like:

```php
return parent::findByCategory($category);
```

Maybe DocumentPersister::prepareQuery should check if first param is array or not (object!) and tries to find getId method (or id attribute). What do you think, @jwage?

Then it will be possible to do annotation like:

```php
class Category
{
    // ...
    /**
     * @ODM\ReferenceMany(targetDocument="Document\Article", mappedBy="category", repositoryMethod="findByCategory", simple=true, cascade={"all"}, nullable=true)
     */
    protected $articles;
    // ...
}
```

nice, isn't it?

**Comment by malarzm** [comment]
Long time passed but now there's #1363 :)

**Comment by malarzm** [comment]
#1363 has been merged manually in https://github.com/doctrine/mongodb-odm/commit/fbbe096078943cb13941ceb013b8cc693bc8a87e
