### ISSUE TITLE
Unique constraint (from DoctrineMongoDBBundle) doesn't work with embedded document

### ISSUE THREAD

**Issue by pierrre** [doctrine/mongodb-odm#295]
I'm trying to use the "unique validator" from the DoctrineMongoDBBundle, but  I get this error:
[BadMethodCallException] Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo::getAssociationTargetClass($assocName) is not implemented yet.

Am I doing something wrong?

I use Symfony 2.1, and latest bundles/projects versions.

**Comment by davidloubere** [comment]
Issue looks still relevant early 2016.
Can we have a status please?

**Comment by malarzm** [comment]
@davidloubere: as denoted by label status is "needs test" - please feel free to create a failing unit test and submit is a PR, this will speed up working on the issue

**Comment by malarzm** [comment]
According to my tests from #1363 `DocumentRepository::findBy()` already accepted embedded documents and was working properly - call for tests is still open

**Comment by alcaeus** [comment]
Closing - if anyone can provide a failing test case, please do.
