### ISSUE TITLE
Duplication of generated methods / attributes with Traits

### ISSUE THREAD

**Issue by khepin** [doctrine/mongodb-odm#297]
When a class is set to use a given trait as for example the one provided by
[DoctrineExtensions](https://github.com/l3pp4rd/DoctrineExtensions/blob/master/lib/Gedmo/Timestampable/Traits/TimestampableDocument.php),
the properties and methods defined in the trait file are re-created in the file 
defining the class even though they already exist in the Trait definition.

For example here's what I get for a comment thread class in a SF project if I use
the `doctrine:mongodb:generate:documents` command:

    <?php
    namespace Xxx\CommentBundle\Document;

    use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
    use Gedmo\Mapping\Annotation as Gedmo;

    /**
     * @ODM\Document
     */
    class Thread
    {
        use \Gedmo\Timestampable\Traits\TimestampableDocument;

        /**
         * @ODM\Id
         */
        private $id;

        /**
         * @ODM\ReferenceMany(targetDocument="Comment")
         */
        private $comments;

        public function __construct()
        {
            $this->comments = new \Doctrine\Common\Collections\ArrayCollection();
        }
        
        /**
         * Get id
         *
         * @return id $id
         */
        public function getId()
        {
            return $this->id;
        }

        /**
         * Add comments
         *
         * @param Xxx\CommentBundle\Document\Comment $comments
         */
        public function addComments(\Xxx\CommentBundle\Document\Comment $comments)
        {
            $this->comments[] = $comments;
        }

        /**
         * Get comments
         *
         * @return Doctrine\Common\Collections\Collection $comments
         */
        public function getComments()
        {
            return $this->comments;
        }
        /**
         * @var date $createdAt
         */
        protected $createdAt;

        /**
         * @var date $updatedAt
         */
        protected $updatedAt;

        /**
         * Set createdAt
         *
         * @param date $createdAt
         */
        public function setCreatedAt($createdAt)
        {
            $this->createdAt = $createdAt;
        }

        /**
         * Get createdAt
         *
         * @return date $createdAt
         */
        public function getCreatedAt()
        {
            return $this->createdAt;
        }

        /**
         * Set updatedAt
         *
         * @param date $updatedAt
         */
        public function setUpdatedAt($updatedAt)
        {
            $this->updatedAt = $updatedAt;
        }

        /**
         * Get updatedAt
         *
         * @return date $updatedAt
         */
        public function getUpdatedAt()
        {
            return $this->updatedAt;
        }
    }

**Comment by malarzm** [comment]
#988 has been merged in https://github.com/doctrine/mongodb-odm/commit/32912d1e8e94d0d26fc89e5544eaf59cdc61adb0
