### ISSUE TITLE
Duplicate document referenced when parent is an EmbeddedDocument

### ISSUE THREAD

**Issue by jamesnait** [doctrine/mongodb-odm#303]
Hello is my first comment.

I think that I have found a bug when you "flush" embedded in a document that refer to other documents. Before "flush" I have the correct object, but after the "flush" the reference to the document is duplicated. In summary, the document is not duplicated but the reference of this document is duplicated.

This is an example of MongoDB

<pre>
{
   "_id": ObjectId("4fa7e9236b23b47c1400000c"),
   "pages": {
     "0": {
       "content": {
         "title": "Contact"
      },
       "sections": {
         "0": {
           "articles": {
             "0": {
               "$ref": "Article",
               "$id": ObjectId("4fa7e9236b23b47c14000002"),
               "$db": "ged",
               "_doctrine_class_name": "Ged\\CMSBundle\\Document\\Article"
            },
             "1": {
               "$ref": "Article",
               "$id": ObjectId("4fa7e9236b23b47c14000002"),
               "$db": "ged",
               "_doctrine_class_name": "Ged\\CMSBundle\\Document\\Article"
            }
          }
        }
      }
    }
  }
}
</pre>

regards,

**Comment by malarzm** [comment]
Given structure mismatch, no test case and long time passed I'm closing this issue. If anyone encounter similar issue please reopen.
