### ISSUE TITLE
Priming not working with mapped references

### ISSUE THREAD

**Issue by khepin** [doctrine/mongodb-odm#319]
If references are `mapped_by` rather than held directly in the class itself then priming the query does not have any effect. I created a small project to verify this and explain myself better. So the documents are here: https://github.com/khepin/test-priming/tree/master/src/Khepin/PrimingBundle/Document

Where the relevant part is:

```
class BlogPost
{
    //...
    /**
     * @ODM\ReferenceMany(targetDocument="Comment", mappedBy="blog_post")
     */
    private $comments;
    //...

class Comment
{
    //...
    /**
     * @ODM\ReferenceOne(targetDocument="BlogPost", inversedBy="comments")
     */
    private $blog_post;
    //...
```

The controller then queries to get the blog posts and tries to prime the reference
to the comments:

```
public function indexAction()
{
    $dm = $this->get('doctrine.odm.mongodb.document_manager');
    $qb = $dm->createQueryBuilder('KhepinPrimingBundle:BlogPost')
            ->field('comments')->prime(true)->limit(200)
        ;
    $posts = $qb->getQuery()->execute();

    return array('posts' => $posts);
}
```

If I run this and then check the page, the debug toolbar informs me that a query
is executed for each blog post in order to get the comments. In other words, no 
priming happened.
- Is this an expected behavior and you don't want to change it?
- Is this planned for the version 1 of the ODM?
- Is someone working on this?
- Are you looking for someone to work on this?

**Comment by alcaeus** [comment]
I came across this a few times. Now that priming is no longer done in the query class but deferred to a cursor (see #1068), there are multiple ways this can be done:
* Using ```mappedBy``` along with ```repositoryMethod``` now allows you to safely call ```prime()``` on a field without having a massive performance impact
* Even better, I thought of possibly defining fields to be primed in the reference mapping itself:
```
@ReferenceMany(targetDocument="BlogPost", mappedBy="blog_post", primedFields=["user"])
```
When creating the query, the document persister could apply primers to the cursor just like it normally applies limit and skip options. I'm not sure this could support custom primers, but it's a start.

**Comment by metanav** [comment]
I think priming on mapped_by references is a much-needed feature. Many developers are using some workarounds (which involved extra calls with re-mapping overhead) to overcome this limitation. How about prioritising this?

**Comment by alcaeus** [comment]
It is currently scheduled for the 1.x milestone and I haven't gotten to it yet. If you want to you can also get started on this and create a PR.
