### ISSUE TITLE
MongoDB ODM Profiler

### ISSUE THREAD

**Issue by dextervip** [doctrine/mongodb-odm#352]
Hi,

It would be nice if mongodb odm has a complete profiler(queries, time, etc), As long I see there is only a simple logger available.

**Comment by alcaeus** [comment]
I think this is outside the scope of this project. The corresponding Symfony Bundle has a light-weight "profiler" that records queries and displays them in the developer toolbar. I recommend the [Monitoring documentation](https://docs.mongodb.com/manual/administration/monitoring/index.html) at MongoDB and using a more professional tool to do this.
