### ISSUE TITLE
Fatal error: Class 'Doctrine\ODM\MongoDB\Mapping\Driver\DriverChain' not found

### ISSUE THREAD

**Issue by MDrollette** [doctrine/mongodb-odm#371]
Running dev-master on everything... just updated and am getting this...

```
Fatal error: Class 'Doctrine\ODM\MongoDB\Mapping\Driver\DriverChain' not found in
.../app/cache/dev/appDevDebugProjectContainer.php on line 403
```

Cleared cache, of course, and newly generated ProjectContainer still contains this class that doesn't exist.

What's a sane composer.json config for staying current and keeping all the doctrine packages in sync besides dev-master?

```
    "php":">=5.3.2",
    "symfony/symfony":"2.1.*",
    "doctrine/orm":"dev-master",
    "doctrine/doctrine-bundle":"dev-master",
    "doctrine/mongodb-odm":"dev-master",
    "doctrine/mongodb-odm-bundle":"dev-master",
    "doctrine/doctrine-fixtures-bundle":"dev-master",
    "gedmo/doctrine-extensions":"dev-master",
    "stof/doctrine-extensions-bundle":"dev-master",
```

**Comment by honeynettechnocratscom** [comment]
hi
i want to use mongodb with symfony 
for this i follow the link 
"http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html"

and i got an error
"Fatal error: Class 'Doctrine\ODM\MongoDB\Mapping\Driver\AnnotationDriver' not found in C:\xampp\htdocs\testing\app\autoload.php on line 10"

can any one help me to resolve it
or please tell me the steps to connect the mongodb with symfony and simple demo use.

**Comment by honeynettechnocratscom** [comment]
Hey stof  plz help me
