### ISSUE TITLE
[AnnotationDriver] error in hydration classes when the property name is not equal to the attribute name

### ISSUE THREAD

**Issue by idetia** [doctrine/mongodb-odm#394]
This generate a bad hydrated class:

    /**
     * @ODM\EmbedMany(
     *     targetDocument="UserBundle\Document\Message",
     *     name="incoming_messages"
     * )
     */
    protected $incomingMessages = array();

And changing the attribute works fine:

    /**
     * @ODM\EmbedMany(
     *     targetDocument="UserBundle\Document\Message",
     *     name="incomingMessages"
     * )
     */
    protected $incomingMessages = array();

**Comment by malarzm** [comment]
This is used at least few times across tests, everything seems to be fine now
