### ISSUE TITLE
The "Proxies\__CG__\<document_path>" document with identifier "<id>" could not be found. 

### ISSUE THREAD

**Issue by afgar** [doctrine/mongodb-odm#396]
HI,
I am using Symfony 2.0.16 with this versions of doctrine:

[doctrine-common]
    git=http://github.com/doctrine/common.git
    version=2.2.2

[doctrine-dbal]
    git=http://github.com/doctrine/dbal.git
    version=2.2.2

[doctrine]
    git=http://github.com/doctrine/doctrine2.git
    version=2.2.2

[doctrine-mongodb]
    git=http://github.com/doctrine/mongodb.git

[doctrine-mongodb-odm]
    git=http://github.com/doctrine/mongodb-odm.git

[DoctrineMongoDBBundle]
    git=http://github.com/doctrine/DoctrineMongoDBBundle.git
    target=/bundles/Symfony/Bundle/DoctrineMongoDBBundle
    version=origin/2.0

I have a document (A) with a referenced document (B). Document B represents an image and  it removes the image file from disk in postremove method. When I remove Document A i get this error. This error refers to document B. The document B is referenced by cascade={"all"}, but when I try to remove , this time, with cascade={"persist"} calling document manager remove methosd for document A and document B, I also get this error.
It is a mongodb-odm error? How i could solve it?

**Comment by malarzm** [comment]
I don't believe this would still happen in current dev-master however if anyone stumbles upon similar problem please submit a failing test case
