### ISSUE TITLE
repositoryMethod for ReferenceOne

### ISSUE THREAD

**Issue by bazo** [doctrine/mongodb-odm#399]
hi, 

odm doesnt support repositoryMethod for ReferenceOne annotation. i just recently found out about these repository methods and find them very useful. 

but i am disappointed that it doesnt work with reference one.

use case:

user has many cars, but only one default. so i would like to do

```
/** @ODM\ReferenceMany(targetDocument="Car", repositoryMethod="getDefaultCar") */   
$defaultCar,    
```

of course i can work around it by annotating it with reference many but that is not true. could this be added?

**Comment by wodka** [comment]
This feature would be really helpful (http://stackoverflow.com/questions/29492965/doctrine2-how-to-handle-missing-relation-documents/29494298)

In the annotation definition I can already define a repositoryMethod, but it is never called

**Comment by alcaeus** [comment]
I'm going to close this in favor of #1397. Lazy-loading `referenceOne` mappings would allow using repositoryMethod for those as well, as loading the document is deferred until it's actually used.
