### ISSUE TITLE
Convert DateTime to MongoDate within Hash types

### ISSUE THREAD

**Issue by defrag** [doctrine/mongodb-odm#421]
Hello,
currently there isnt possiblity to store DateTime fields in Hash Type, cuz it always casts
to array. Would it make sense to be able to store DateTime fields in Hash? 
If i could get liitle guidence how to change it, I would gladly do it.

**Comment by alcaeus** [comment]
Elaborating on previous comment, the `hash` and `collection` types are raw types that don't have specific mapping information and thus, don't attempt type conversion. This is not something i intend to change. If you need type conversion, use an embedded document.
