### ISSUE TITLE
Support simple reference with discriminator maps

### ISSUE THREAD

**Issue by Bilge** [doctrine/mongodb-odm#432]
Although not documented, currently the following attributes are mutually exclusive.

* discriminatorMap
* simple=true

Trying to use them together causes errors.

A typical discriminatorMap field must therefore be similar to the following.
```
"foo" : {
    "$ref" : "Bar",
    "$id" : ObjectId("123"),
    "$db" : "MyDb",
    "type" : 'bar'
}
```

However, Doctrine only needs to know the class and ID. Everything else it can infer from the class's metadata. Therefore there is no reason not to support simple references on discriminator fields.

```
"foo" : {
    "$id" : ObjectId("123"),
    "type" : 'bar'
}
```

**Comment by malarzm** [comment]
We'll use #802 to to track stop storing $db
