### ISSUE TITLE
Add support for atomic updates

### ISSUE THREAD

**Issue by jgornick** [doctrine/mongodb-odm#437]
The ODM doesn't support a single document update for all fields and embedded documents. The current implementation will run different queries for updating a single document and it's embedded documents.

This would certainly help remove queries between the ODM and Mongo and also remove the need to implement rollback functionality if an embedded document fails to insert.

I've created a repository with some scenarios @ https://github.com/jgornick/doctrine-atomic-test.

After speaking with @jwage and @jmikola, it would be nice to be able to specify an atomicUpdate option in the relationship annotation:

```
/** @ODM\EmbedMany(…, atomicUpdates=true) */
```

**Comment by malarzm** [comment]
Closing thanks to https://github.com/doctrine/mongodb-odm/pull/1096
