### ISSUE TITLE
Bidirectional Mapping with multiple targetDocuments not automatically updated on flush

### ISSUE THREAD

**Issue by alexcasalboni** [doctrine/mongodb-odm#442]
I've reproduced my situation [here](https://github.com/alexcasalboni/OneToManyMixedMapping): I need a bidirectional mapping between a document (let's say, a Person) and multiple documents (let's say Car and Computer) as a ReferenceMany field called *$items*, therefore I cannot specify the targetDocument and I should have simple=false in order to keep the collection reference.
Person is mapped as *owner* in the other documents (with *simple=true*, *inversedBy="items"*, etc).
I need to keep track of the items of a Person and in general let's say that the owner of an item could change quite often, so I'd like to call *setOwner($person2)* and dynamically remove the item from the old Person's items and add it to the new one's.

I've both *addItems* and *removeItems* methods, that are used inside the setOwner methods of the different items and correctly update the objects status.

Here's the problem: this mechanism could be realized through a form submission and in my specific case I don't want to manually persist the 3 involved objects (since the controller belongs an external repo), so I'd like to persist only the modified object (the item) and automatically update both the new and the old associated person.

If I only persist the item what I get is a consistency problem, since the old Person is not updated and still has the binded item, while the item and the new Person are correctly updated.
Another problem is that the new Person is configured with a *PreUpdate* method (in order to update other fields, such as lastUpdateTime, etc), that is not triggered before the flush.

In order to let the configuration without *targetDocument* work, I had to remove the *mappedBy* attribute from the ReferenceMany relationship: could it be a cause? (I did it because If I keep mappedBy="owner" the collection is not stored/updated at all!)

Thank you

**Comment by malarzm** [comment]
> So now the question becomes: why doesn't the UnitOfWork logic mark documents as updated in case of updated collection(s)? 

In case anyone would get here this was fixed in https://github.com/doctrine/mongodb-odm/commit/4ab0fbc6165dc83d9b957b4363d1719c6c110c56

**Comment by alexcasalboni** [comment]
Thank you @malarzm.
