### ISSUE TITLE
Version/Lock fields not honored by XML/YAML drivers

### ISSUE THREAD

**Issue by ianunruh** [doctrine/mongodb-odm#466]
Setting up a version or lock field is not supported by the XML or YAML driver

**Comment by malarzm** [comment]
It is supported now by both [XML](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php#L138-L142) and YAML (which simply forwards field settings to ``ClassMetadataInfo::mapField``)

**Comment by jmikola** [comment]
Indeed. XML supported was added in #997, which is now available in 1.0.0-BETA12.
