### ISSUE TITLE
Support priming references on non-hydrated results

### ISSUE THREAD

**Issue by kevou84** [doctrine/mongodb-odm#468]
Hi all,

I'm trying to get raw results when using prime(true) option on referenced objects like this :

```
    $dm = $this->get('doctrine_mongodb')->getManager();
    $qb = $dm->createQueryBuilder('MyBundle:Document');
    $qb->field('documentSimpleReferences')->prime(true);
    $query = $qb->hydrate(false)->getQuery();
    // 2 larger queries are performed eagerly to fetch documents and documentSimpleReferences
    $results = $query->execute();
```

It triggers the following error message :

Warning: get_class() expects parameter 1 to be object, array given in C:\Users...\sf\vendor\doctrine\mongodb-odm\lib\Doctrine\ODM\MongoDB\Persisters\DocumentPersister.php line 522 

It seems that hydration should occur before prime and is globally disabled by hydrate(false) option... Or something like that... Looks like you had issues upon this matter before : https://github.com/doctrine/mongodb-odm/pull/300

DocumentPersister:primeCollection() works fine if hydration enabled, but I'd like a flat array as result...

Thanks for your feedback,

**Comment by alcaeus** [comment]
Closing this - priming references when hydration is disabled doesn't make any sense.
