### ISSUE TITLE
Excessive proxy and hydrator generation causes Bus errors

### ISSUE THREAD

**Issue by Bilge** [doctrine/mongodb-odm#484]
When proxy and hydrator generation is enabled, as is typical for a dev environment, they are excessively regenerated even when the source file has not changed. The upshot of this is that the proxy or hydrator class may frequently be being written to at the same time as it is being accessed for reading by PHP. This not only causes a PHP fatal error but potentially multiple Apache Bus exceptions.

> [error] [client 0.0.0.0] PHP Fatal error:  Class 'Hydrator\\DocumentsFooHydrator' not found in mongodb-odm/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php on line 146
> [notice] child pid 12345 exit signal Bus error (7)
> [notice] child pid 12347 exit signal Bus error (7)
> [notice] child pid 12350 exit signal Bus error (7)

This will happen even on a single-developer system merely by accessing a page which has multiple assets that invoke Doctrine, e.g. images. If I refresh a page that has 20 assets on it, typically at least one will fail every time while the proxy or hydrator is being regenerated.

**Comment by malarzm** [comment]
EVAL strategy for Proxies is available since https://github.com/doctrine/mongodb-odm/pull/804 and for Hydrators it was implemented in https://github.com/doctrine/mongodb-odm/pull/953
