### ISSUE TITLE
Referencing Embedded document

### ISSUE THREAD

**Issue by babarinde** [doctrine/mongodb-odm#500]
Hi Guys,
First Thanks for the great job.
I need to ask,
Say I have a document A and a collection of embedded document B in A

```
/** @Document */
class A {
    /** @Id */
    protected $id;

    /** @EmbedMany(targetDocument="B") */
    protected $b;
}

/** @EmbeddedDocument */
class B {
    /** @Id */
    protected $id;

    /** @String */
    protected $string;
}
```

Is it possible For a new document C to reference an embedded document B from a document of A?
Thanks

**Comment by alcaeus** [comment]
Closing this in favor of #1705: we're going to start throwing exceptions if you reference embedded documents.
