### ISSUE TITLE
Deep cloning a document and it's embedded documents

### ISSUE THREAD

**Issue by vmattila** [doctrine/mongodb-odm#509]
I have recently encountered some strange behavior regarding cloning a document object that contains embedded documents. The use case here is to create a copy of the original document with new identity, but exactly same details.

It seems that `$newDocument = clone $originalDocument` does not clone the embedded documents. `$documentManager->persist($newDocument);` works find and also embedded documents are copied at that point. However, if an embedded document of `$newDocument` is modified before (or after persisting), the change is coupled also to the `$originalDocument`.

Consider the following test case (added to be a part of EmbeddedTest.php)

```php
	public function testCloneParentAndModifyEmbeddedWithoutChangeInOriginal()
    {
        $address = new Address();
        $address->setAddress('20780 Kaarina');

        $user = new User();
        $user->setUsername('vmattila');
        $user->setAddress($address);

        $this->dm->persist($user);
        $this->dm->flush();
        $this->dm->clear();

        $user = $this->dm->createQueryBuilder('Documents\User')
            ->field('id')->equals($user->getId())
            ->getQuery()
            ->getSingleResult();
        $this->assertNotNull($user);
        
		// Cloning user
		$newUser = clone $user;
		$newUser->setId(null); // Nulling identity of the user
		$this->assertEquals('20780 Kaarina', $newUser->getAddress()->getAddress());
		
		// Changing address for the new user
		$newUser->getAddress()->setAddress('20100 Turku');
		$this->dm->persist($newUser);
        $this->dm->flush();
		
		$this->assertEquals('20100 Turku', $newUser->getAddress()->getAddress());
		$this->assertEquals('20780 Kaarina', $user->getAddress()->getAddress());
    }
```

The test fails, because `$newUser->getAddress()->setAddress('20100 Turku');` will couple the change also to `$user->getAddress()->setAddress('20100 Turku');`.

This behaviour might be expected (is it?) - but a little bit confusing. It would be useful if Doctrine would provide helpers to make a "deep copy" of the document.

**Comment by malarzm** [comment]
#1252 aims to make situation better but is not enough given there's no Doctrine in provided scenario between reusing same embedded document and changing it's value.

**Comment by malarzm** [comment]
#1259 is closest we can get to it automatically, as soon as document is persisted the changes to reused embedded documents are no longer shared.
