### ISSUE TITLE
Associative references cannot be read

### ISSUE THREAD

**Issue by Bilge** [doctrine/mongodb-odm#515]
With `strategy="pushAll"`, a `@ReferenceMany` will only store `array_values($array)`. However, with `strategy="set"` it is possible to store associative arrays. However, despite being stored correctly, Doctrine cannot fetch associative array references, instead throwing the following errors.

>Warning: Illegal offset type in mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php on line 665

>Notice: Array to string conversion in mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentNotFoundException.php on line 33

>exception 'Doctrine\ODM\MongoDB\DocumentNotFoundException' with message 'The "Example" document with identifier "Array" could not be found.' in mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentNotFoundException.php:33

**Comment by malarzm** [comment]
Out of curiosity I hacked this test case and it is passing now:

```
    public function testAssociativeRefMany()
    {
        $d = new Strategy();
        $t = new Task('Task #1');
        $t2 = new Task('Task #2');
        $d->tasks['important'] = $t;
        $d->tasks['todo'] = $t2;
        $this->dm->persist($t);
        $this->dm->persist($t2);
        $this->dm->persist($d);
        $this->dm->flush();
        $this->dm->clear();

        $d = $this->dm->find(get_class($d), $d->id);
        $this->assertCount(2, $d->tasks);
        $this->assertNotNull($d->tasks['important']);
        $this->assertNotNull($d->tasks['todo']);
    }
```

**Comment by Bilge** [comment]
Thanks @malarzm!

**Comment by Bilge** [comment]
Although collections are persisted with named keys they are still hydrated as numeric indexes.

**Comment by malarzm** [comment]
@Bilge has my test started failing or have I missed something in it?

**Comment by Bilge** [comment]
@malarzm Grepping for your test does not seem to return any results.

**Comment by Bilge** [comment]
@malarzm The error is my own. I was retrieving the wrong record when I did the hydration! Indeed, it does seem to work now, however your test is still missing or I simply cannot find it.

**Comment by malarzm** [comment]
Oh, I just posted it as a comment above (https://github.com/doctrine/mongodb-odm/issues/515#issuecomment-153842714) as at the moment both reference many and embed many are handled in the same way (both lists and maps) and I can't see these two diverging anyhow and for associative embeds we have tests :)

**Comment by Bilge** [comment]
As long as there is a test case for this somewhere all is well, however you cannot expect me to run the test in your comment since I do not have access to all of its dependencies, e.g. `Strategy` and `Task`!

**Comment by malarzm** [comment]
`I do not have access to all of its dependencies, i.e. Strategy and Task!`

Right, I could have pasted whole test case, however if you'd take a look into ODM tests themselves you'll easily spot these two beings living in the `Documents` namespace ;)

**Comment by Bilge** [comment]
Although persist and retrieve works correctly the first time, I find am finding that updates to associations annotated like `@EmbedMany(targetDocument="Foo", strategy="set")` are not detected by Doctrine, thus leaving it perpetually in the state of the first write.

In my particular case, I have this relationship type (embedded document using *set* strategy) nested two levels deep, but I'm not sure if that makes a difference or not.

**Comment by malarzm** [comment]
@Bilge could you put together failing test case and submit as a PR?

**Comment by Bilge** [comment]
@malarzm No, I don't think so. I don't know how to write ODM tests, but I'd be happy to help someone he does.

**Comment by malarzm** [comment]
It's not that hard, you can check https://github.com/doctrine/mongodb-odm/blob/master/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1225Test.php as a starter and mimic that :)

**Comment by Bilge** [comment]
You say it's not very hard, but that is from your perspective, as someone who has a good grasp of how Doctrine works even internally. I am not very good at PHP codes :\^)

**Comment by malarzm** [comment]
I'm just trying to motivate you, you just need to do what your app is doing in isolation ;)

> I have this relationship type (embedded document using set strategy) nested two levels deep, but I'm not sure if that makes a difference or not.

So you have something like: document -> collection_1 -> collection_2 and if you change something in collection_2 then it's not saved?

**Comment by Bilge** [comment]
@malarzm That's exactly it. :+1:

**Comment by malarzm** [comment]
Oh, subsequent flushes sounds interesting. Could you open new issue?

**Comment by Bilge** [comment]
I think our discussion elsewhere concluded that flushing the object manager was the source of all woes on this occasion, therefore an issue should not need to be created after all, as we may assume that feature still works correctly under normal circumstances.
