### ISSUE TITLE
Doctrine unable to update rows after a change of strategy for the _id field.

### ISSUE THREAD

**Issue by adurieux** [doctrine/mongodb-odm#522]
Hi all, 

After hours of bug tracking, I finally found out what was happening. I want to share here this bug for future reference.

## Symptoms

I was using the Doctrine ODM to update some objects in a very classic way. 
- The ODM was able to retrieve the documents from the DB
- Calling persist() and flush() was working fine
- The operations were correctly added to the UnitOfWork.
- A log was written by the Doctrine Logger
- But still, no update was performed on the DB !

## What happened

When I first configured my documents with annotations, for some reason, I decided to use the "INCREMENT" strategy. During 1 month, I thus created documents with an _id that was an integer. 

At some point, I decided to migrate to the "AUTO" strategy. I changed the annotation in the class, and, from this point on, my _id fields were thus of type ObjectId.

Thus, there is a mismatch between what Doctrine retrieves from the DB (an integer for the oldest records), and what it expects (an ObjectId). When you try to persist such a buggy object, Doctrine generates an update query with a non-existing ObjectId that it somehow computes from this integer. Provided this ObjectId does not exist, the update query does not work, thus leaving the DB unchanged...

## Is this a problem ? 

I am still wondering if this is a bug or a feature. IMO, Doctrine should warn about inconsistencies between the Model and the Data in this case.

**Comment by malarzm** [comment]
We introduced sanity checks for wrong values passed as AUTO identifiers in #1190 wchich will warn developer about problems during persisting.
