### ISSUE TITLE
Remove unused convert/closure methods in type classes

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#542]
* `closureToMongo()` is never used and should likely be removed across the board.
 * `convertToPHPValue()` is only used for identifier fields (called by `ClassMetadataInfo::getPHPIdentifierValue()`).

Earlier discussion on this subject: #237

**Comment by malarzm** [comment]
@jmikola citing part of https://github.com/doctrine/mongodb-odm/issues/237#issuecomment-39916549

> I know he [@jwage] has plans to ultimately generate code for persister classes as well, so that explains why we have a pair of closure methods.

do we still want to remove `closureToMongo`? Personally I don't think we'll do generated persisters before 2.0.0 :)

/cc @jwage

**Comment by jmikola** [comment]
I don't see the harm in leaving it in place for the existing types, especially since the base Type class includes it. Theoretically, generated Persister classes shouldn't require a major version bump since it'd just be a new feature; however, I think removing the method for 1.0.0 would require a bump to 2.0.0 if we need to introduce the method to the base Type class (which may as well be our interface).

**Comment by malarzm** [comment]
I think that we should leave them, maybe they'll come in handy one day :)
