### ISSUE TITLE
mongo 2.4 support

### ISSUE THREAD

**Issue by bazo** [doctrine/mongodb-odm#551]
does the library support mongo 2.4 new features yet? i'm especially interested in the new multi location document support(that was new in 2.0) and 2dsphere indexes. 

the documentation looks like it hasn't been updated a while, so i'm at a loss here

**Comment by malarzm** [comment]
Cross referencing SO question with @jmikola's answer: http://stackoverflow.com/questions/12181320/multi-location-document-in-mongo-odm

**Comment by malarzm** [comment]
as for 2dsphere it is implemented in https://github.com/doctrine/mongodb/issues/102 and there's also issue for ODM https://github.com/doctrine/mongodb-odm/issues/631
