### ISSUE TITLE
Implementation of DiscriminatorMapProvider to provide dynamic mapping of inherited classes

### ISSUE THREAD

**Issue by vmattila** [doctrine/mongodb-odm#553]
Without knowing the deep architecture of mongodb-odm, I was wondering whether it would be possible to implement a feature like `@DiscriminatorMapProvider` instead of list of in-class-defined `@DiscriminatorMap`. Related to this, a `@DiscriminatorField` could be another "normal" field in the document object (currently not allowed).

A use case for this behavior would be a simple address document, where the exact address fields vary between countries. The example below is far from a real and working code, but hopefully clarifies what do I mean by this suggestion.

The similar feature would be useful also in `@EmbedMany`, when the collection may contain more than one type of documents.

``` php
<?php

/**
 * @Document
 * @InheritanceType("SINGLE_COLLECTION")
 * @DiscriminatorField(fieldName="country")
 * @DiscriminatorMapProvider("AddressDiscriminatorMapProvider")
 */
class Address {

    /**
     * @String
     */
    protected $country;

}

class AddressDiscriminatorMapProvider {
    public static function getDocumentClass($discriminatorFieldValue) {
        if ($discriminatorFieldValue == 'US') {
            return 'USAddress';
        } else {
            return 'EUAddress';
        }
    }
}

/**
 * @Document
 */
class EUAddress {
   /**
    * @String
    */
   protected $zip;

   /**
    * @String
    */
   protected $city;

   public function getZipCityLine() {
      return $this->zip.' '.$this->city;
   }
}

/**
 * @Document
 */
class USAddress {
   /**
    * @String
    */
   protected $zip;

   /**
    * @String
    */
   protected $city;

   /**
    * @String
    */
   protected $state;

   public function getZipCityLine() {
      return $this->city . ' ' . $this->state . ' ' . $this->zip;
   }
}
```

**Comment by malarzm** [comment]
#1512 was proposing same thing and was later closed by OP as he found some [other ways](https://github.com/doctrine/mongodb-odm/issues/1512#issuecomment-254190743) of achieving similar results
