### ISSUE TITLE
Doctrine\ODM\MongoDB\Mapping\Annotations\CustomIdGenerator doesn't exist

### ISSUE THREAD

**Issue by dalu** [doctrine/mongodb-odm#555]
Can i set the strategy to NONE and query the db from inside the document for an existing id or does that break things?

I tried:
- copy from ORM and adjust namespace:
complains about missing interface annotation (because there isn't one)
- remove interface annotation from class declaration:
Compile Error: Cannot redeclare class Doctrine\ODM\Mapping\CustomIdGenerator

**Comment by malarzm** [comment]
The docs are now improved: http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/basic-mapping.html#basic-mapping-identifiers

**Comment by dalu** [comment]
wow. it has been a while since I last used Doctrine or PHP. Hey it only took 2 1/2 years, what are the odds lol
Trip down memory lane.
Well, good for you :)
