### ISSUE TITLE
Hydrator for extended document contents extended fields only

### ISSUE THREAD

**Issue by ryabenko-pro** [doctrine/mongodb-odm#589]
I have "composer update" yesterday and after this all goes wrong.
I did some debug, and found that all hydrators created two times. First time hydrator are right, and contents all inherited fields. But later it is rewrote with wrong one. First and second files are here: https://gist.github.com/nord-ua/5656327

**Comment by malarzm** [comment]
As far as I can say Hydrators are working properly :) The gist file no longer exists so I can't see what was wrong, please feel free to reopen if the issue persists
