### ISSUE TITLE
Relocate LoggableCursor $loggerCallable argument

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#591]
Currently, the required `$loggerCallable` argument appears after the optional `$numRetries` argument, which has a default value. Compare with the base [LoggableCursor class](https://github.com/doctrine/mongodb/blob/master/lib/Doctrine/MongoDB/LoggableCursor.php).

**Comment by malarzm** [comment]
`LoggableCursor` has been removed in https://github.com/doctrine/mongodb-odm/commit/504c9d69c5dfb70568fcebc94c4ea69afcf2c394
