### ISSUE TITLE
Inverse-side PersistentCollections may get stale as documents are inserted/updated

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#595]
See 0d042ec2688f569af25bcc80891e5c225e7b4cd4, which is a test for #566.

This is likely a feature request, instead of an outright bug. The work-around is to manually call `setInitialized(false)` to require the PersistentCollection to be reinitialized.

**Comment by malarzm** [comment]
There is a related discussion in #1172, let's keep it there
