### ISSUE TITLE
Is it possible to remove documents by references field with empty object?

### ISSUE THREAD

**Issue by vkartaviy** [doctrine/mongodb-odm#621]
I have document with $groupActions reference many field.

```PHP
/**
 * @Mongo\ReferenceMany(targetDocument="Action", simple=true)
 */
private $groupActions;
```

I want to remove documents where { groupActions: {} }

I tried something like this:

```PHP
$qb->remove()->field('groupActions')->equals(new \stdClass());
$query = $qb->getQuery();
$result = $query->execute();
```

But when I looked into $query->query array I found something interesting:

![$query->query](https://f.cloud.github.com/assets/648039/661561/69ecb732-d736-11e2-8e3b-1c8814bb1bc8.png)

I suppose this is a bug?

**Comment by malarzm** [comment]
It's still happening, `simple=true` is triggering wrong behaviour
