### ISSUE TITLE
RemoveElement on sorted collection

### ISSUE THREAD

**Issue by dan19** [doctrine/mongodb-odm#623]
I have a document Whatever with a collection "users" which reference many User. 
This collection is sorted with an annotation.

    /**
    * @ODM\ReferenceMany(targetDocument="User", simple=true, sort={"lastname"="asc", "firstname"="asc"})
    */
    protected $users = array();

If I try to delete one user reference from the collection. 
```php
$whatever->getUsers()->removeElement($user);
```
The user deleted is not the one I want to delete. There is an issue with the key here because of the sort annotation. The removeElement method should remove the element at the key x based on the order in the database.

Log :
<code>doctrine.INFO: MongoDB query: {"update":true,"query":{"_id":{"$id":"51c4a13ffa4634362a000061"}},"newObj":{"$unset":{"users.2":true}},"options":{"safe":true,"fsync":false,"timeout":30000},"db":"something","collection":"Whatever"}</code>

**Comment by Jimgitsit** [comment]
Am am also experiencing this issue. Has there been any resolution to this?

**Comment by malarzm** [comment]
@Jimgitsit I believe most important part is @jmikola's 

> Sort should really only be used on the inverse side of a ReferenceMany relationship

and maybe we should throw exception if owning side tries to use this combination? If you really want to stick with sort here try using `setArray` or `atomicSetArray` for your collection, it should do the trick. I think I've seen a PR that would fix removing sorted references using `addToSet` or `pushAll` strategies but I need to find it (that wasn't sole purpose of that PR but it will be enough for us)

**Comment by malarzm** [comment]
For the record PR I had in mind is https://github.com/doctrine/mongodb-odm/pull/524

**Comment by malarzm** [comment]
#1191 has been merged manually in https://github.com/doctrine/mongodb-odm/commit/56796fa0b74d3a4b68fc0b266bcee942b4f8b3c3
