### ISSUE TITLE
Support priming references in embedded documents

### ISSUE THREAD

**Issue by intellix** [doctrine/mongodb-odm#624]
I have an Entity structure which looks like the following:

**Category embedsMany CategoryGame**
**CategoryGame referencesOne Game**

So, when looping through my data, I suffer the dreaded n+1 problem, as everytime I get to categryGame->getGame(); it has to do another call.

I read about priming which looks pretty awesome and attempted to give it a go with this:

```php
$categories = $this->getDocumentManager()
            ->createQueryBuilder('Application\Entity\Category')
            ->field('categoryGames.game')->prime(true)
            ->getQuery()->execute(); 
```

The problem is that as far as I'm aware, priming currently only works if the Reference is directly within the first class like:

**CategoryGame referencesOne Game**

I did a little digging/dumping inside MongoODM to see what I could find and it seems to fall down here:

**Doctrine\ODM\MongoDB\Persisters\DocumentPersister@primeCollection();**

It looks for "categoryGames.game" as a mapping and then dies when it doesn't exist. I was able to get this working by exploding by "." and looking through the mapping like that, but failed to do it all programmatically as I don't fully understand Doctrine as of yet.

```php
$fieldNames = explode(".", $fieldName);
$fieldMapping = $collectionMetaData->fieldMappings[$fieldNames[0]];
```

etc etc.

Thanks, Dominic

**Comment by malarzm** [comment]
#970 has been merged implementing the feature
