### ISSUE TITLE
orphanRemoval missing in docs

### ISSUE THREAD

**Issue by phoenix741** [doctrine/mongodb-odm#632]
Hi,

In my project i have a document that ReferenceMany other object. I can't use EmbedMany because the destination document is a GridFS document but the association is like an embedded document. 

So i want that : 
- when i delete the document, referencemany are deleted too. cascade={"remove"} is good for that.
- when i delete an element from the list, or clear the list, i want element attached to be removed too. 

It's for the last point that i don't find how to do that. There is an orphanRemoval in the ORM but not in the ODM.

My question is, how can i remove gridfs document when i delete element in my RefenceMany list.

Thanks.

**Comment by malarzm** [comment]
Can't find any reference to `orphanRemoval` in the docs so marking this as a documentation issue

**Comment by alcaeus** [comment]
Fixed in #1447.
