### ISSUE TITLE
@Index can be configured without explicitly defining "asc" or "desc", causing compatibility issues with MongoDB 2.4

### ISSUE THREAD

**Issue by vmattila** [doctrine/mongodb-odm#641]
It seems that ODM allows one to configure a composite @Index annotation without defining explicitly the direction of the key, like:

    `@MongoDB\Index(keys={"first_field"="asc", "second_field", "last_field"="asc"})`

(note `second_field` in the middle).

The actual key definition sent (and accepted - prior 2.4) by MongoDB server is `{"first_field": 1, "0" : "second_field", "last_field" : 1}`. As described in http://docs.mongodb.org/manual/release-notes/2.4-index-types/#index-type-validation , this kind of index configuration causes problems compatibility issues when upgrading to 2.4.

ODM could warn if somebody ever uses such a faulty syntax to define indexes for documents before 2.4... (yes it's already too late for me ;)

**Comment by malarzm** [comment]
Given @jmikola response I'm closing the issue, if someone would have idea how to tackle this feel free to reopen
