### ISSUE TITLE
Explicit clone is required when an embedded document is set to another document

### ISSUE THREAD

**Issue by vmattila** [doctrine/mongodb-odm#648]
It seems that if you "copy" an embedded document from inside a persisted document into newly created document, the embedded document is not persisted to the new document.

In terms of OOP principles, need for explicit `clone` is the most logical choice - and it works. However, I would prefer that an exception ("You try to persist an embedded object that belongs to another object") is thrown instead of ODM silently ignoring the embedded document at the target document.

Some code to clarify the issue:

```php
/**
 * @EmbeddedDocument
 */
class Address {
    /**
     * @String
     */
    public $addressline;
}

/**
 * @Document
 */
class Person {
    /**
     * @EmbedOne(targetDocument="Address")
     */
    public $address;
}

$person1 = $personRepository->get('person1-id');
$person2 = new Person();

// Following does not set address to $person2
$person2->address = $person1->address;
$this->dm->persist($person2);
$this->dm->flush();

// Following sets address to $person2
$person2->address = clone $person1->address;
$this->dm->persist($person2);
$this->dm->flush();
```

**Comment by malarzm** [comment]
Funny thing, I just wanted to use first code snippet as a failing test case for #1252 but it works just fine o.O

**Comment by malarzm** [comment]
Things seemed to work before and now #1252 and #1259 are both merged so I'm closing the issue
