### ISSUE TITLE
Implement result caching

### ISSUE THREAD

**Issue by intellix** [doctrine/mongodb-odm#653]
Hey, more of a question. Within ORM there is 3 caches: Query, Result and Metadata.

I see in ODM there is currently only Metadata. Is there any plan to implement the other caches here or is it not required for ODM?

**Comment by coudenysj** [comment]
Any news on this?

**Comment by malarzm** [comment]
@coudenysj we haven't given it a thought yet (or I'm not aware of it). Personally I'm hiding `DocumentManager` in my own classes to which I can inject additional stuff (like Cache) - exactly what @solocommand written above. At the moment there are more important things (like PHP 7) so probably we won't devote time to the feature as of now... but we (or at least I) can offer some guidance if somebody would like to implement the caching :)

**Comment by coudenysj** [comment]
@malarzm I think some default caching options (as supplied in the ORM) would be a great addition the the mongo-odm repository. I think of `read-only` entities, result caching, etc...

I think I should start a separate ticket for this.

**Comment by malarzm** [comment]
@coudenysj :+1:

**Comment by manuelbcd** [comment]
+1

**Comment by coudenysj** [comment]
I started to play around with caching repository calls for a while, and the biggest hurdle is the Cursor object. Just a reminder when I start working on this :).

**Comment by alcaeus** [comment]
Just a heads up: the Cursor class will be vastly different in 2.0 once we're done with the migration to the new driver.

**Comment by manuelbcd** [comment]
May be we can implement the cache in the appropiate branch. @alcaeus could you tell me the branch of ODM focused on new driver?

**Comment by teseo** [comment]
looking forward to this!

**Comment by alcaeus** [comment]
@manuelbcd it took a little longer than I'd hoped, but your new target branch is `master`. It requires `ext-mongodb` and is the basis for the upcoming 2.0 release.
