### ISSUE TITLE
When a file type is removed from a document, everything else is also deleted.

### ISSUE THREAD

**Issue by teu** [doctrine/mongodb-odm#668]
There is a problem with the gridfs files deletion.
going by description in https://doctrine-mongodb-odm.readthedocs.org/en/latest/reference/storing-files-with-mongogridfs.html?highlight=file

I created a document, the problem is, most of the times, the file is just temporary in mongodb (in my app anyway), and gets deleted after. The deletion (or $document->setFile(null) ) on the @MongoDB\File also removes all other fields in that document, besides the data itself. I have a bunch of statistical information in that document, and it all gets removed when I just remove the file. What's left is just the Id. This might be the way it was intended, however doesn't not really seam like the mapping is accurate here, as it obviously removes a lot more from the database, than I from the object.

The operation should just remove the data that has been removed from the object.

Crosspost from http://www.doctrine-project.org/jira/browse/MODM-175

**Comment by alcaeus** [comment]
Closing this issue, as it's just a documentation problem. The implementation of GridFS in ODM didn't make it clear, but the file was actually the main content, with other fields mapped in the document being metadata belonging to the file. This is one of the reasons GridFS support is being rewritten for 2.0, to make this more clear.
