### ISSUE TITLE
Updating of nested object's _id doesn't work as expected

### ISSUE THREAD

**Issue by lotar** [doctrine/mongodb-odm#672]
There's an issue with updating nested object's _id in following scenario:

Classes:
```php
/*
Document(
    db="sample",
    collection="sampleA"
)
*/
class A 
{
private $prop;
public function setProp($prop) 
    {
    $this->prop = $prop;
    }
}

/*
Document(
    db="sample",
    collection="sampleB"
)
*/
class B 
{
/*
EmbedOne
*/
private $a
public function setA($a)
    {
    $this->a = $a;
    }
}
```

Usage:
```php
$a = new A();
$a->setProp('test');
$dm->persist($a); // $dm is instance of DocumentManager
$dm->flush();

$a2 = new A()
$a2->setProp('test2');
$b = $loadedB; // $loadedB already has some other class A attached to it 
$b->setA($a2); // Replace A with new instance with new _id for document A
$dm->persist($b);
$dm->flush();
```

Usage code from above will persist A as expected, persist B with its properties, including nested document A with 'prop' set to 'test2', but _id of nested class will not update.

Issue is within mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php:169 as class A is seen as own document, not nested because of persisting it before nesting it. And since it's illegal operation to update _id of the document in Mongo it's being stripped from query although it IS legal to update _id on nested document.

P.S. In case anyone is looking for a workaround you can use $dm->clear() after persisting class A to own collection.

Update: added annotations to the documents used in sample

**Comment by malarzm** [comment]
Right now the suggested way is creating `@MappedSuperclass` annotated class with common properties and later extend it by one `@Document` and one `@EmbeddedDocument`. I'm using exactly this structure in ecommerce application as @KingCrunch mentioned :)
