### ISSUE TITLE
http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping.xsd redirect to beta3 version

### ISSUE THREAD

**Issue by Begi** [doctrine/mongodb-odm#674]
The url http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping.xsd still redirect to the beta3 version :/

**Comment by malarzm** [comment]
We have changed this with @beberlei, now http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping.xsd will point to master branch. If anybody would like to lock to specific tag it can be done with http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping-1.0.0-BETA11.xsd or by providing any other valid tag in place of "1.0.0-BETA11". I will amend the documentation shortly.
