### ISSUE TITLE
Reference management(DBRefs) and performance

### ISSUE THREAD

**Issue by randombitstudio** [doctrine/mongodb-odm#675]
Currently the ODM makes reference performance a bit of a pain. Loading a full object in a state recognizable via the documentIdentifiers hash table seems to be required for a reference to be correctly stored. Is there a specific reason not to allow referencing via a holder document by ID field type, thus removing the need for merge/refresh?
I'd gladly submit a pull request, but I'd like to know if there is an intention behind this choice as the trade off doesn't seem to be worth it.

**Comment by malarzm** [comment]
Closing as this issue seems to be not relevant now in 2017. Please re-open if it's still valid
