### ISSUE TITLE
@MongoDB\ReferenceMany : persist references does not work anymore

### ISSUE THREAD

**Issue by maphe** [doctrine/mongodb-odm#681]
From the commit [cc4960a](https://github.com/doctrine/mongodb-odm/commit/cc4960a581463e6a78beb981499d5e09d1257189), we can't persist a document with reference

See [this gist](https://gist.github.com/maphe/6810339) to reproduce

Result in Mongo (odm_test_user document) :
 - before commit :

```json
{
    "_id": ObjectId("524d6c2ce04ccacf5f4d0a29"),
    "addresses": {
      "0": ObjectId("524d6c2ae04ccacf5f4d0a28") 
   },
    "name": "user test 1" 
}
```

- after commit :

```json
{
   "_id": ObjectId("524d6e8be04ccaf862494fce"),
   "name": "user test 3" 
}
```

**Comment by malarzm** [comment]
The test I've pulled together from https://gist.github.com/maphe/6810339 is passing as expected, closing the issue
