### ISSUE TITLE
Index applied to self-referenced document (not current document).

### ISSUE THREAD

**Issue by tjlytle** [doctrine/mongodb-odm#682]
For this:

    /**
     * @MongoDB\Index(keys={"coord"="2d"})
     */
    class Document
    {
        /**
         * @MongoDB\EmbedOne(targetDocument="Coord") 
         */
        protected $coord;

        /**
         * @MongoDB\ReferenceOne(targetDocument="Document")
         * @var Document
         */
        protected $parent;
    }

`Coord` is a document with lat / lng properties. I'd expect an index like this:

    { key: { "coord": "2d" }, v: 1, ns: "database.collection", sparse: false, name: "parent_coord_2d" }

But I get this: 

    { key: { "parent.coord": "2d" }, v: 1, ns: "database.collection", sparse: false, name: "parent_coord_2d" }

Manually creating the index makes things work, just seems like I'm either missing something, or there's an issue with the annotation.

**Comment by malarzm** [comment]
This seems to be working fine now, here's passing test:

```
<?php

namespace Doctrine\ODM\MongoDB\Tests\Functional\Ticket;

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

class GH682Test extends \Doctrine\ODM\MongoDB\Tests\BaseTest
{
    public function testIndex2D()
    {
        $class = $this->dm->getClassMetadata(__NAMESPACE__.'\GH682Document');
        $sm = $this->dm->getSchemaManager();
        $indexes = $sm->getDocumentIndexes($class->name);
        $this->assertSame(array('coord' => '2d'), $indexes[0]['keys']);
    }
}

/** 
 * @ODM\Document 
 * @ODM\Index(keys={"coord"="2d"})
 */
class GH682Document
{
    /** @ODM\Id */
    public $id;

    /**
     * @ODM\EmbedOne(targetDocument="GH682Coord") 
     */
    public $coord;

    /**
     * @ODM\ReferenceOne(targetDocument="GH682Document")
     * @var Document
     */
    public $parent;
}

/** @ODM\EmbeddedDocument */
class GH682Coord
{
    /** @ODM\Float */
    public $lat;
    
    /** @ODM\Float */
    public $lng;
}
```
