### ISSUE TITLE
[class metadata] The property mapping is skipped if fieldName is wrong

### ISSUE THREAD

**Issue by makasim** [doctrine/mongodb-odm#685]
If the fieldName defined (in xml mapping for example) is not matched any property it is just silently skipped [here](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php#L82).

It is not like ORM work. It would throw an exception and force me to correct mapping:

```
ReflectionException: Property Payum\Paypal\ExpressCheckout\Nvp\Bridge\Doctrine\Entity\PaymentDetails::$tokenNotExist does not exist
```

If it is a bug I could try to fix.

**Comment by alcaeus** [comment]
Fix was merged in https://github.com/doctrine/mongodb-odm/commit/58e001e5cea4b7b8fa4ec9c94c9d3e1dac686a3e.
