### ISSUE TITLE
[mapping type] What about to add ObjectType like ORM has?

### ISSUE THREAD

**Issue by makasim** [doctrine/mongodb-odm#687]
Something like [DBAL ObjectType](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/ObjectType.php). I have to store simple serializable object to mongo. For now I created a custom ObjectType (almost same as DBAL one) in the lib. It works fine. 

Is there any change to add it to mongo-odm as standard one? I could work on it.

**Comment by alcaeus** [comment]
As per previous discussion, use embedded documents. If you don't want to, serialise data and use a binary type. If you want serialisation to be taken care of for you, extend one of the binary types and update the corresponding methods. Closing here.
