### ISSUE TITLE
Ability to use ArrayCollection as PHP type for @Collection field

### ISSUE THREAD

**Issue by vmattila** [doctrine/mongodb-odm#690]
I am used to use [`ArrayCollection`](https://github.com/doctrine/collections/blob/master/lib/Doctrine/Common/Collections/ArrayCollection.php) around my application whenever working with arrays. ODM provides a nice `@Collection` field type that converts to an associative array in PHP.

Would it be possible to create a parameter for `@Collection` type to allow automatically use of `ArrayCollection`? It could be combined with `nullable`, which would allow empty collections not to be stored at all and also automatically convert not existing field to initiate as an empty `ArrayCollection` - very much similar what `@EmbedMany` already works (despite explicit initialization of an empty collection object in the constructor).

**Comment by roman-1983** [comment]
+1

**Comment by malarzm** [comment]
Closing in favour of #1453
