### ISSUE TITLE
Abstraction of database, collection (and server connection) definitions

### ISSUE THREAD

**Issue by vmattila** [doctrine/mongodb-odm#700]
I've recently encountered two separate issues during my experiments that led me to think about this topic. 1) Due improper schema design that all document collections locate inside one and only database, MongoDB's database-level write-lock causes extensive lock wait times. 2) Two document classes got the same base name (in different namespaces) -> by default they got the same collection name.

I started to think whether it's possible to somehow abstract `@Document`'s `db` and `collection` definitions to allow another strategy instead the default. Of course, I can explicitly define `db` and `collection` for each class, but by abstracting and delegating this work to a custom component would allow more custom setups. I do also somehow think that document's metadata is not the correct location for this information.

I went further with my thinking and thought that this layer could also include the server connection definition, making it to fully resolve "where a document is". Currently, if some documents are wanted to another server, it requires (in my understanding) a completely different DM instance.

**Comment by alcaeus** [comment]
I don't think having two different server connections in one DocumentManager make a lot of sense: queries won't be able to link different documents, so it makes more sense to just use two different entity managers for this use case.
