### ISSUE TITLE
Delete DBRefs when referenced document is removed.

### ISSUE THREAD

**Issue by comensee** [doctrine/mongodb-odm#709]
Maybe this point has already been treated, but i can't find infos on it.
The thing is that i have two documents A and B.
A has a dbrefs containing B.
But B can be deleted. 

What happens for A ?
Currently with the dev-master branch.
If i do a query retrieving A documents and B DBRefs is referencing a "non existing anymore" document, it obviously throw a documentnotfound error.

So how properly remove the dbrefs from the document ?

Could we create a referencedIn property for the Document Annotation ?

Thanks

**Comment by Nolwennig** [comment]
+1 for this feature.
@smilesrg thanks for tips !

**Comment by smilesrg** [comment]
@jmikola @malarzm this issue has been opened since 2013... Maybe it's worth to implement it?

**Comment by malarzm** [comment]
@smilesrg I won't have time in upcoming month as right now I'm focused on making 1.0 a real thing, however I can provide some help if it'd be needed (read as PR is welcome and feel free to ping me in case of troubles ;) ).

Two cents from me:

1. I think this should be an opt in feature
2. "Association dependencies are currently handled to some degree when calculating commit orders" is no longer true as we have removed commit order calculator.

**Comment by Alsatian67** [comment]
Do you dnow that this feature is implemented by DoctrineExtensions ?

https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/reference_integrity.md

**Comment by malarzm** [comment]
Cool! That takes feature off our plate then :)

**Comment by comensee** [comment]
:+1:
