### ISSUE TITLE
Store @Hash type strange bug

### ISSUE THREAD

**Issue by Webixel** [doctrine/mongodb-odm#712]
Hello, I have a strange bug with doctrine and mongodb-odm when I save my document.

```
/** 
  * @MongoDB\Hash
*/
protected $activity = array();

public function setActivity($activity){
  $this->activity = array("Football","Tennis");
}
```

After the persist and flush execution, I launch query to find this document.

```
$activityQuery = array('activity' => 'Tennis');
$cursor = $collection->find($activityQuery);
foreach ($cursor as $doc) {
    var_dump($doc);
}
```

But the cursor is empty.

I go in genghis for edit document and save the document without modifications.
If I relaunch the activityQuery, the cursor contains my document.

Strange ? Have you got some ideas for this bug ?
Thanks.

**Comment by mdjaman** [comment]
@jmikola Always thought that @collection and @hash annotation setters were "add" and "remove" prefixes eg. addInterests and removeInterests

**Comment by malarzm** [comment]
@mdjaman ODM doesn't really care how you are modifying the document, stored data is what counts in the end

**Comment by mdjaman** [comment]
@malarzm thanks for replying but what i meant is using hydrator magic for persistence

**Comment by malarzm** [comment]
Hydrators are populating fields using Reflection
