### ISSUE TITLE
Modified document data is replaced when @ReferenceMany has "sort" attribute

### ISSUE THREAD

**Issue by vkartaviy** [doctrine/mongodb-odm#729]
Modified document data is replaced when that document is in PersistentCollection mapped by @ReferenceMany with "sort" attribute

Test case:

```php
class Foo {
    /**
     * @Mongo\ReferenceMany(targetDocument="User", simple=true, strategy="addToSet", sort={"updated"="desc"})
     *
     * @var PersistentCollection|ArrayCollection|User[]
     */
    protected $users;

    public function getUsers() {
        return $users;
    }

    public function addUser(User $user) {
        $this->users->add($user);
    }

    public function removeUser(User $user) {
        $this->users->removeElement($user);
    }
}

// Create relations at first...

$user1 = $dm->find(1);
$user2 = $dm->find(2);

$user1->addUser($user2);
$user2->addUser($user1);

$dm->persist($user1);
$dm->persist($user2);

$dm->flush();
$dm->clear();

// Try to remove relations

$user1 = $dm->find(1);
$user2 = $dm->find(2);

$user1->removeUser($user2);

var_dump($user1->getUsers()->isInitialized()); // true
var_dump($user1->getUsers()->isDirty()); // true

$user2->removeUser($user1); // NOTE: Bellow description is about that line

var_dump($user1->getUsers()->isInitialized()); // false
var_dump($user1->getUsers()->isDirty()); // false

$dm->persist($user1);
$dm->persist($user2);

$dm->flush();

```

When ``PersistentCollection`` of ``$user2`` is ``initialized`` then as you can find here https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php#L591 it checks for ``Proxy`` documents and ``sort`` attribute in mapping metadata and then load documents and replace their data even if them already loaded and modified before, so ``$user1`` is restored to original state and all modifications are gone...

**Comment by malarzm** [comment]
@vkartaviy any chance for a failing test case? :)

**Comment by vkartaviy** [comment]
@malarzm Sorry, I hanged out with customer project :( Will try to add it within this week...

**Comment by malarzm** [comment]
@vkartaviy thanks :+1:

**Comment by malarzm** [comment]
I believe this was addressed with https://github.com/doctrine/mongodb-odm/pull/1191 by forbidding combining sort with strategies that are not using `$set` operator. @vkartaviy please feel free to reopen if I'm mistaken :)
