### ISSUE TITLE
Do not allow child classes to override identifiers into regular fields

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#745]
See GH435Test in https://github.com/doctrine/mongodb-odm/commit/afe6e92543eac6104694048fb6a1b49cd1cc7f91. It's a bit weird that we allow a child class to override a parent such that there is no longer an identifier field mapping. The child class still tracks an identifier field in its `$identifier` property and there is a generator. This could lead to undefined behavior.

There's no problem with children changing the ID mapping, but the field should remain an identifier.

**Comment by malarzm** [comment]
#1147 was merged manually in https://github.com/doctrine/mongodb-odm/commit/b1e83f340dc9f992c8c26946feafd2642325e11b
