### ISSUE TITLE
Populating lazy proxy objects with field data

### ISSUE THREAD

**Issue by vmattila** [doctrine/mongodb-odm#747]
I have been working with the search layer of our application. Currently I'll do search against ElasticSearch, fetch document id's and do a query for these documents from MongoDB with the help of Doctrine.

Roundtrip to MongoDB is unnecessary if we have all details available in the ES document, consider for example just a simple listing. 

What came to my mind is a concept of "read-only" proxy objects. We could create a new proxy object when going through the search results, populate it with some data and use it like a normal object. If we'd need some other (non-cached) fields, Doctrine could lazily load the document from the MongoDB.

Would this be possible in general or is it too much mis-using proxies?

**Comment by alcaeus** [comment]
This is similar to what #1527 intends to do, except from a different data source. With proxy logic being rewritten in 2.0, we can tackle this in 2.x. Regardless, closing this in favour of the PR.
