### ISSUE TITLE
UnitOfWork identityMap can conflict with inherited classes

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#757]
The identity map stores identifiers grouped by the root class name of the inheritance hierarchy. ClassMetataFactory sets the parent classes from `$nonSuperclassParents`. Hypothetically, if a concrete document class extends another concrete document class and both use separate collections, documents in both collections could share the same identifier. This would clash if UnitOfWork attempted to manage both objects.

**Comment by malarzm** [comment]
This was fixed in https://github.com/doctrine/mongodb-odm/commit/7f73de3efa4d9adc313274ae2b55ad7e68ef60a3
