### ISSUE TITLE
requireIndexes not working when findBy or findOneBy methods are used

### ISSUE THREAD

**Issue by dwieeb** [doctrine/mongodb-odm#760]
The following does **not** throw a Doctrine\ODM\MongoDB\MongoDBException with message "Cannot execute unindexed queries on..." (and it should):

``` php
$post = $dm->getRepository('Posts')
    ->findOneByPostText('test');
```

The following does:

``` php
$post = $dm->getRepository('Posts')
    ->createQueryBuilder()
    ->field('postText')->equals('test')
    ->getQuery()
    ->execute();
```

**Comment by malarzm** [comment]
`requireIndexes` is now deprecated and will be removed in 2.0
