### ISSUE TITLE
Compound index order not respected

### ISSUE THREAD

**Issue by dwieeb** [doctrine/mongodb-odm#761]
Given [this explanation of how mongo uses compound indexes](http://docs.mongodb.org/manual/core/index-compound/#prefixes), a Doctrine\ODM\MongoDB\MongoDBException should be thrown with message "Cannot execute unindexed queries on..." if I attempt to do this:

```php
$item = $dm->getRepository('Item')
    ->createQueryBuilder()
    ->field('location')->equals('something')
    ->getQuery()
    ->execute();
```

or

```php
$item = $dm->getRepository('Item')
    ->createQueryBuilder()
    ->field('stock')->equals('something')
    ->getQuery()
    ->execute();
```

or

```php
$item = $dm->getRepository('Item')
    ->createQueryBuilder()
    ->field('location')->equals('something')
    ->field('stock')->equals('something')
    ->getQuery()
    ->execute();
```

And does not.
(It does of course for fields that are not indexed.)

**Comment by malarzm** [comment]
I will have to revisit #812 but this is generally something bigger to be built after 1.0 given pending changes in PR

**Comment by malarzm** [comment]
For the moment being I'm more in favour of dropping requireIndexes feature in 2.0 so I'd rather declare it's broken and won't be fixed.
