### ISSUE TITLE
UoW::scheduleOrphanRemoval() is called with an array argument

### ISSUE THREAD

**Issue by vmattila** [doctrine/mongodb-odm#796]
A new strange bug encountered with the latest `master`: an array gets passed to `UnitOfWork::scheduleOrphanRemoval()` instead of the proper embedded document object. The array itself seems to be a presentation of the embedded document in question. This eventually leads to PHP error `spl_object_hash() expects parameter 1 to be object, array given` inside `scheduleOrphanRemoval()`.

This seems to be related to situations where we mix ORM and ODM (as documented in http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/cookbook/blending-orm-and-mongodb-odm.html#event-subscriber) and upon persisting an Entity, we use the `Document` in the ORM's `prePersist` listener.

**Comment by jmikola** [comment]
@alcaeus: Any progress on creating a standalone test case? If you want to gist it and reply in a comment, I'll re-open this issue.

**Comment by alcaeus** [comment]
Sorry about the delay, we ended up changing the logic to avoid the issue. I've written the test - if you want I'll write a PR for it in order to track changes. I'm not quite sure about a solution for the issue though.

**Comment by jmikola** [comment]
@alcaeus: Sorry, but I just saw your reply. If you can still cook up a PR, feel free to re-open this and link it to a corresponding PR. I'd definitely like to attempt a fix it if we can reproduce the error.
