### ISSUE TITLE
Make setting of $db in DBRef objects optional

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#802]
See: https://github.com/doctrine/mongodb-odm/issues/432#issuecomment-34008793

**Comment by coudenysj** [comment]
Any progress on this?

**Comment by malarzm** [comment]
@coudenysj right now we're not working on the feature but there's a PR for which @alcaeus posted list of issues that need to be resolved https://github.com/doctrine/mongodb-odm/pull/807#issuecomment-122551710 - if you want to help it'd be awesome :)

**Comment by coudenysj** [comment]
Owkay! Thanks.

**Comment by coudenysj** [comment]
Working on this in #1349.

**Comment by malarzm** [comment]
Closing as #1349 was merged and is already available in 1.1.0
