### ISSUE TITLE
client-mode generate mappings info like with ORM

### ISSUE THREAD

**Issue by GuidoDubois** [doctrine/mongodb-odm#811]
Dear all,

How can I generate xml mapping files with ODM? With ORM it's easy with 
```
doctrine-cli.php orm:convert-mapping xml ./models/Mappings --from-database --force
```
But I can't find such functionality for Mongo ODM.

Thnx allready

**Comment by malarzm** [comment]
@GuidoDubois sorry for long time for response. If I understand correctly you wanted to generate documents from database to kickstart development? I'm afraid it's not possible here, ORM can check database schema and reverse engineer that to mapping while Mongo doesn't have anything alike as it's schemaless.
