### ISSUE TITLE
PostUpdate event occurs even if database operation is not performed in bi-directional references on the inverse side

### ISSUE THREAD

**Issue by kovagoz** [doctrine/mongodb-odm#817]
[In this example](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/bidirectional-references.html#one-to-one) if I have a Customer and link it to a Cart instance, a postUpdate event generated on Customer too.

Documentation says: "The postUpdate event occurs _after the **database update**_ operations to document data."

But database update occurred only on Cart (owning side, holding the reference), not on Customer (inverse side).

Is it a bug or the documentation is wrong? Events should reflect document or database operations?

**Comment by malarzm** [comment]
@kovagoz we've straighten out firing and ordering events for 1.0.0, could you confirm this is fixed?

**Comment by alcaeus** [comment]
Fix was merged in https://github.com/doctrine/mongodb-odm/commit/790110e33b638fb1e16bed617056bf507499e7fb, thanks!
