### ISSUE TITLE
Get the document referenced via DRef with run a findAll() request

### ISSUE THREAD

**Issue by Solidary** [doctrine/mongodb-odm#831]
Hi,

I have a document which embedded many others documents. The problem is that in one embedded document i put a reference one to another embedded document.

Survey (document) => many  Item
Item (embedded document) => reference one Item

The problem is when I run this query 

```
$this->getServiceLocator()
    ->get('doctrine.documentmanager.odm_default')
    ->createQueryBuilder('Survey\Document\Survey')
    ->field('id')->equals($id)
    ->hydrate(false)
    ->getQuery()
    ->getSingleResult();
```

to get a survey I don't have the referenced one document. The field there over is empty.

How to get at least the id of the referenced document ?

Thanks.

**Comment by malarzm** [comment]
Closing issue since question was answered
