### ISSUE TITLE
Embedded documents containing references

### ISSUE THREAD

**Issue by Bilge** [doctrine/mongodb-odm#834]
This pattern used to work but since I updated to HEAD it's broken. I asked @jwage if he's ever used this pattern before and he said not. I created this pattern as a more flexible alternative to #515 and because #515 is broken. Unfortunately this is also broken, now.

This pattern keeps data about a referenced document in the owning document rather than in the referenced document. I create an embedded "ref" document that holds a reference to the referenced document as well as the metadata that the owning document wishes to keep.

Example:
```php
/** @Document */
class Foo {
	protected
		/** @Id */
		$id,

		/** @EmbedMany(targetDocument="BarRef") */
		$barRefs = []
	;
}

/** @EmbeddedDocument */
class BarRef {
	protected
		/** @String */
		$metadata,

		/** @ReferenceOne(targetDocument="Bar", simple=true, cascade="all") */
		$bar
	;
}

/** @Document */
class Bar {
	protected
		/** @Id */
		$id,

		/** @ReferenceOne(targetDocument="Foo", simple=true) */
		$owner
	;
}
```

Trying to persist a new `BarRef` containing a new `Bar` to an existing `Foo` throws the following error on flush:

>'RuntimeException' with message 'Cannot create a DBRef without an identifier. UnitOfWork::getDocumentIdentifier() did not return an identifier for class Bar' in Doctrine/ODM/MongoDB/DocumentManager.php:692

**Comment by AronSzigetvari** [comment]
Probably this bug is related to the one I found: https://github.com/doctrine/mongodb-odm/issues/1017

**Comment by gistya** [comment]
In case it might help, take a look at the recursive method of [#970](https://github.com/doctrine/mongodb-odm/pull/970)... I remember when writing this that I had the sneaking suspicion that such a recursive method might be useful in other types of situations where drilling down through levels of references that involve embedded documents was currently either not possible at all or prone to errors. It might not be useful, but just in case.

**Comment by grEvenX** [comment]
@gistya thanks, I will try to checkout that one in my project and see if it solves my issue related to this.
I'm currently stuck on BETA9 since one of my behat tests fails on this issue when I use a newer version of doctrine/mongodb-odm (so it's easy for me to reproduce it).

**Comment by gistya** [comment]
@grEvenX OK, I look forward to seeing your findings here. I do wonder if a recursive method like that could be used to make any metadata load automatically past an arbitrary number of nesting layers.

**Comment by grEvenX** [comment]
@gistya @robholmes hm, I would be a bit careful about merging that change. I tried it out on my codebase and quickly got into an issue where one of my `Document`'s stored an array of strings as a object property using `Doctrine\ODM\MongoDB\Mapping\Annotations\Collection`. In my behat tests the tests failed for some reason when running two scenarios after each-other that tried to use this Collection property (object was `null` on the second run instead of an array/ArrayCollection that I would initialize it as in the `Document`'s constructor.

**Comment by BernardoSilva** [comment]
I was having this same issue and I've found out I was not persisting one of the objects.
```sh
RuntimeException: Cannot create a DBRef without an identifier. UnitOfWork::getDocumentIdentifier() did not return an identifier for class Partnermarketing\UserBundle\Document\User
```

I had something like this:
```php
$user = new User()
    ->setFirstName('Jon')
    ->setLastName('Doe')
    ->setEmail('jon.doe@friedfries.com');
        
// Added this line and the issue was fixed. 
$this->dm->persist($user);

$leadList = new LeadList()
    ->setName('My lead list')
    ->setOwnerUser($user);
```

Hope this help. :)

**Comment by popovsergiy** [comment]
Maybe it will help someone.
In my case main problem was that after validation ZF2 return empty string for identifier.
Doctrine generate new identifier only when default value is NULL https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L1017.

Simplified example of my code:

```php
$project = new Project();
#$project->setId(''); // if this string uncomment you get error "RuntimeException: Cannot create a DBRef..."
$project->setName('Test Project');
$project->setCode('test');

$webServer = new WebServer();
$webServer->setGroup('nginx');
$webServer->setServer($server);

$webApp = new WebApp();
$webApp->setHosts('test.com.ua');
$webApp->setMode('magento');
$webApp->setWebServer($webServer);
$webApp->setProject($project);

$dm->persist($webApp);
$dm->flush();
```

**Comment by malarzm** [comment]
I believe this bug report was about `cascade` not working properly from embedded document, which is no longer a case in current dev-master, here's passing test case:

```
<?php

namespace Doctrine\ODM\MongoDB\Tests\Functional\Ticket;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

class GH834Test extends \Doctrine\ODM\MongoDB\Tests\BaseTest
{
    public function testCascadeFromEmbeddedDocument()
    {
        $d = new GH834Document();
        $d->refs->add(new GH834RefDoc('meta', new GH834AnotherDocument()));
        $this->dm->persist($d);
        $this->dm->flush();
        $this->dm->clear();

        $d = $this->dm->getRepository(get_class($d))->find($d->id);
        $this->assertCount(1, $d->refs);
        $this->assertEquals('meta', $d->refs[0]->meta);
        $this->assertInstanceOf(__NAMESPACE__ . '\GH834AnotherDocument', $d->refs[0]->ref);
    }
}

/**
 * @ODM\Document
 */
class GH834Document
{
    /** @ODM\Id */
    public $id;

    /** @ODM\EmbedMany(targetDocument="GH834RefDoc") */
    public $refs;

    public function __construct()
    {
        $this->refs = new ArrayCollection();
    }
}

/**
 * @ODM\EmbeddedDocument
 */
class GH834RefDoc
{
    /** @ODM\String */
    public $meta;

    /** @ODM\ReferenceOne(targetDocument="GH834AnotherDocument", simple=true, cascade="all") */
    public $ref;

    public function __construct($meta, GH834AnotherDocument $ref)
    {
        $this->meta = $meta;
        $this->ref = $ref;
    }
}

/**
 * @ODM\Document
 */
class GH834AnotherDocument
{
    /** @ODM\Id */
    public $id;
}
```
