### ISSUE TITLE
@HasLifecycleCallbacks is obsolete by design

### ISSUE THREAD

**Issue by Bilge** [doctrine/mongodb-odm#835]
One of the frustrations I have switching between my ancient but mostly working branch of ODM and HEAD is that I have to go back and forth adding and removing the @HasLifecycleCallbacks annotations to every document that uses callbacks. However, this annotation should be obsolete by nature of its design.

According to the documentation, @HasLifecycleCallbacks should be added to any class that includes one or more of the following annotations: @PreFlush, @PreLoad, @PostLoad, @PrePersist, @PostPersist, @PreRemove, @PostRemove, @PreUpdate, or @PostUpdate.

By virtue of this design @HasLifecycleCallbacks should be obsolete: according to a very strict and simple rule, namely: *does this class include any annotations in this short list*, I must systematically remember to include the @HasLifecycleCallbacks annotation.

As a human I should not be having to program against strict rules. The programmer's job is to write the parts of the system that the computer cannot figure out. A stringent rule like this should be solvable by the computer. 

When Doctrine parses the class's metadata and sees one of the pre/post annotations on one or more of its members it should automatically flag the class as having callbacks. There should not even be an impact on performance since the parsed metadata is subsequently cached.

Despite my lack of knowledge of Doctrine internals I believe that from a high-level view one can still prove that this annotation must be obsolete.

I understand that @jwage reintroduced this annotation in #428 (to fix #427) so would appreciate your commentary.

**Comment by malarzm** [comment]
Closing the issue given @jmikola's explaination
