### ISSUE TITLE
Inherited document Reference connection is broken

### ISSUE THREAD

**Issue by Picobacsi** [doctrine/mongodb-odm#836]
It's not easy to explain, so here is an example (it used to work with 1.1.3):

```php
namespace BaseBundle;

class Foo
{
  /** @ODM\ReferenceOne(targetDocument="Fighter") */
  protected $fighter;
}
```
```php
namespace AcmeBundle;

class Foo extends BaseBundle/Foo
{
  // inherits $fighter;
}
```
```php
namespace BaseBundle;

class Fighter
{
  // some attributes, but not $acmeString
}
```
```php
namespace AcmeBundle;

class Fighter extends BaseBundle/Fighter
{
  /** @ODM\String */
  protected $acmeString;
}
```

Getters and Setters are included, just not written in the example code.
The problem is when you ask for AcmeBundle::Foo::getFighter()->getAcmeString(), it says "Call to undefined method", and AcmeBundle::Foo::getFighter() gives back a BaseBundle::Fighter class document.
Previously when $fighter was set, it was an AcmeBundle class.

**Comment by malarzm** [comment]
Closing issue since question was answered, feel free to re-open if something is still unclear
