### ISSUE TITLE
Split index options between SchemaManager and ClassMetadata

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#841]
Index options specific to the creation of indexes should be handled exclusively by SchemaManager and the related index commands. This includes:
- `background`
- `dropDups`
- `safe` (deprecated in favor of `w`)
- `timeout` (possibly deprecated in favor of `socketTimeoutMS`; see [PHP-1045](https://jira.mongodb.org/browse/PHP-1045)).
- `w`

Other index options that relate to the type/properties may be considered part of the schema and do belong in metadata (e.g. annotations, XML, YAML):
- `default_language` (for text indexes)
- `expireAfterSeconds` (for TTL indexes)
- `language_override` (for text indexes)
- `name`
- `order` (not a real option, but used for field-level mappings)
- `sparse`
- `unique`
- `weights` (for text indexes; not easily supported in XML)

For reference:
- http://docs.mongodb.org/manual/reference/method/db.collection.ensureIndex/
- http://php.net/manual/en/mongocollection.ensureindex.php
- https://jira.mongodb.org/browse/PHP-1045

**Comment by jmikola** [comment]
Bumping this from 1.0.0, since it's not a trival refactoring. When implementing this in a minor version, we can then deprecate the execution options (e.g. `background`, `w`) from being specified in the class metadata. For BC, we should still have SchemaManager read those options; however, commands should also take these options at runtime.

There's room for debate on this, but I think the commands that create indexes in ODM should have their own defaults (e.g. `{w:1}`) and any execution options specified on the metadata should supersede those defaults. If there are options specified at runtime (e.g. console command parameters), those should supersede everything.

**Comment by jacobchristensen79** [comment]
Jmikola, I have searched for a while how to define in XML the "weight" index property. DO you have the link for the doc or a sample? Thanks a lot.

**Comment by jmikola** [comment]
I only alluded to the [`weights` option](https://docs.mongodb.com/manual/reference/method/db.collection.createIndex/#options-for-text-indexes) in my original post for completeness' sake. There is no reference to it in [`XMLDriver::loadMetadataForClass()`](https://github.com/doctrine/mongodb-odm/blob/1.1.0/lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php#L48) and I believe it still unsupported in XML mappings. This is currently supported in annotations, YAML, and PHP mappings because they're very liberal in what they accept for options.

I said "not easily supported in XML" above because the documentation noted the type is a document, which I thought might have nested documents within it. The only example of a `weights` option value I found in the MongoDB docs is on [this page](https://docs.mongodb.com/manual/tutorial/control-results-of-text-search/), which hints that it may just be a flat document (i.e. only string keys and numeric values); however, that example only refers to top-level fields. I'm not certain, but I assume the weight for a nested field would still use a string key in dotted form (e.g. `foo.bar`). If this is the case, I suppose its XML implementation could mimic how we declare indexed fields.

**Comment by alcaeus** [comment]
Moving to 2.0.0: some options have been dropped in 2.0, but the main part still needs to be done.

**Comment by jmikola** [comment]
From our discussion today, I think we want to do the following:

 * Remove `timeout` option, since socket timeouts are no longer configured per-option in `ext-mongodb`. Instead, SchemaManager (or the CLI command that invokes it) can take an option to set `socketTimeoutMS` on the driver client created for the command.
 * Move `maxTimeMS` and `writeConcern` options to SchemaManager, as they are only used when executing the createIndexes command and don't end up in the index specification (unlike `background`).
 * Consider adding `background` 
 * Remove `dropDups` option, which MongoDB no longer supports
 * Leave UniqueIndex class in place as a convenience, but refrain from introducing new classes (e.g. GeospatialIndex)
 * While annotations are flexible and can support ad-hoc, non-scalar options (e.g. `collation`), users can't do that with XML. Consider whether you want to introduce syntax for those options and likely handle that in a separate 2.x ticket when requested.

SchemaManager::isMongoIndexEquivalentToDocumentIndex() may want to consider `background`, geospatial options, and any other options that are missing. Currently, that method checks for specific options but we should look at whether the logic can be simplified to detect differences.
