### ISSUE TITLE
implement odm naming_strategy option in ODM

### ISSUE THREAD

**Issue by cordoval** [doctrine/mongodb-odm#842]
similar to doctrine orm naming strategy:
naming_strategy: doctrine.orm.naming_strategy.underscore

http://elnur.pro/how-to-enable-the-underscore-naming-strategy-for-doctrine-orm-in-symfony/

let's implement the stuff but in ODM

:+1:

**Comment by alcaeus** [comment]
Closing this: I believe it's better to explicitly map the field name. Making this a config option would allow userland code to change it, which can then cause serious issues (as has happened to me in an ORM project).
