### ISSUE TITLE
Method addPropertyChangedListener load the object

### ISSUE THREAD

**Issue by phoenix741** [doctrine/mongodb-odm#844]
Hi, 

In the proxy of my class with the NOTIFY changeTrackingPolicy, the method addPropertyChangedListener load the class.

    public function addPropertyChangedListener(\Doctrine\Common\PropertyChangedListener $listener)
    {
        $this->__load();
        return parent::addPropertyChangedListener($listener);
    }

This has as consequence that when i loaded my object that have a referenceone to another object, this another object is loaded too, even if i don't use it.

Is it possible to not load the object when adding the listener (added by the UnitOfWork) ?

Thanks,

**Comment by Ocramius** [comment]
Looks like correct behavior to me. You are interacting with an object that is yet to be loaded, and therefore it should be loaded *before* that interaction.

**Comment by beberlei** [comment]
This is triggered by the UnitOfWork internally when notify policy injects the listener. The proxy generator should exempt this method. I am a bit confused this has never occured in the ORM before (or nobody reported it). Maybe we inject the listener specifically after proxy load.

**Comment by malarzm** [comment]
Indeed ORM seem to omit uninitialized Proxies (for instance https://github.com/doctrine/doctrine2/blob/1e7e8f216a899ad2ae4f38e208b5b26ce7f503ec/lib/Doctrine/ORM/UnitOfWork.php#L3104-L3106), we need to make ODM better here :)

**Comment by malarzm** [comment]
#1160 was merged manually in https://github.com/doctrine/mongodb-odm/commit/e3468b2d2a8895bc2b560b69272e75772f08c815
