### ISSUE TITLE
DocumentRepository->matching(Criteria $criteria) expression error

### ISSUE THREAD

**Issue by lazycommit** [doctrine/mongodb-odm#847]
Criteria supports optional `\Doctrine\Common\Collections\Expr\Expression` in `__construct`
But. \Doctrine\ODM\MongoDB\DocumentRepository->matching($criteria) does not.
```
Catchable fatal error: 
Argument 1 passed to Doctrine\Common\Collections\Expr\ExpressionVisitor::dispatch()
must implement interface Doctrine\Common\Collections\Expr\Expression, null given,
called in /<vendor>/Doctrine/ODM/MongoDB/DocumentRepository.php on line 269 and
defined in /<vendor>/Doctrine/Common/Collections/Expr/ExpressionVisitor.php on line 66
```

**Comment by malarzm** [comment]
I believe we should stick with interface. @lazycommit, your original issue seems to be fixed now as [null can be passed everywhere](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/DocumentRepository.php#L271-L286), but if there's something more please feel free to reopen :)
