### ISSUE TITLE
Ensure Cursor::toArray() specifies false for $useKeys

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#854]
Calling `toArray()` when documents in a result set have non-scalar keys invites PHP errors. There are several places where we call `toArray()` on possible cursors:

* [x] `DocumentPersister::loadReferenceManyCollectionInverseSide()`
* [x] `DocumentPersister::loadReferenceManyCollectionOwningSide()`
* [x] `DocumentPersister::loadReferenceManyWithRepositoryMethod()`
* [x] `DocumentRepository::matching()`
* [x] `EagerCursor::initialize()`
* [x] `ReferencePrimer::__construct()`

**Comment by malarzm** [comment]
Outstanding calls were fixed in https://github.com/doctrine/mongodb-odm/commit/b6aa8620e4f29d2952fffe4209b49acff39f1547

**Comment by jmikola** [comment]
![](http://www.reactiongifs.com/r/vhpy.gif)
