### ISSUE TITLE
Specifying anything other than AUTO generator strategy overrides type mapping

### ISSUE THREAD

**Issue by gerryvdm** [doctrine/mongodb-odm#857]
I'm not sure if this is expected behaviour, but I did find it very confusing. When specifying a generator strategy and a type in the mapping, the type mapping information is lost if the strategy is anything other than AUTO, eg. strategy NONE.

The reason is clear when looking at the code in Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo::mapField()

	if ($generatorType !== self::GENERATOR_TYPE_AUTO) {
	    if (isset($this->generatorOptions['type'])) {
	        $mapping['type'] = $this->generatorOptions['type'];
	    } elseif ($generatorType === ClassMetadata::GENERATOR_TYPE_INCREMENT) {
	        $mapping['type'] = 'int_id';
	    } else {
	        $mapping['type'] = 'custom_id';
	    }

	    unset($this->generatorOptions['type']);
	}

I found this very confusing, and maybe it should check first if a type was explicitly configured in the mapping, although I'm not sure how. Other possible solution is also excluding GENERATOR_TYPE_NONE from the condition?

**Comment by malarzm** [comment]
@gerryvdm any chance you could provide a failing test case?

**Comment by malarzm** [comment]
Retriaged because of no further details

**Comment by malarzm** [comment]
Heh actually I just got hit by the issue while working on #1183, fix is on its way :)

**Comment by malarzm** [comment]
Also for the record @alcaeus raised valid point that using generator option's type will be sufficient.
