### ISSUE TITLE
Document modified on event listener not flushed correctly

### ISSUE THREAD

**Issue by szappacosta** [doctrine/mongodb-odm#861]

**Comment by jmikola** [comment]
Per discussion in https://github.com/Atlantic18/DoctrineExtensions/issues/1152, this issue was not resolved by #985 and is still outstanding.

**Comment by malarzm** [comment]
#1121 was merged manually in https://github.com/doctrine/mongodb-odm/commit/c055530e236b12ef29a22937e9ebc3d14ef0959a

As for https://github.com/Atlantic18/DoctrineExtensions/issues/1152 we came to conclustion that ODM is [not guilty](https://github.com/Atlantic18/DoctrineExtensions/issues/1152#issuecomment-110708307)

**Comment by jmikola** [comment]
> ODM is not guilty

![](http://i.giphy.com/i6HL5xMo5EuZO.gif)
