### ISSUE TITLE
Cascade on flush

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#869]
See #301 for context.

When dealing with single-document flush operations, it's possible to cascade inserts thanks to the `persist` cascade, but referenced documents may be left out during an update.

**Comment by alcaeus** [comment]
Note: the solution to this is dropping `flush($document)`, which we're doing in 2.0.0. If you want fine-grained control over what is being stored, switch to [explicit change tracking](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/change-tracking-policies.html#deferred-explicit).

**Comment by malarzm** [comment]
Flushing single document was removed in #1715
