### ISSUE TITLE
Events not dispatched when changes are made to a ReferenceMany field

### ISSUE THREAD

**Issue by solocommand** [doctrine/mongodb-odm#883]
When making a change to a ReferenceMany field, no update/remove events are dispatched. It looks like this is intentional, as the events are dispatched in the executeUpdates method of the UoW, but changes to collections do not use this method (instead using the collectionPersister after the document updates are executed).

It doesn't look like it will be easy to change without reworking how refmany collection changes are handled.

If this is intentional, can it be documented somewhere that events will not be fired when modifying only a ReferenceMany field?

**Comment by jmikola** [comment]
#985 is merged, so I believe this can be closed.
