### ISSUE TITLE
Non-existing document fields are not handled by hydrator (but null values are)

### ISSUE THREAD

**Issue by vmattila** [doctrine/mongodb-odm#887]
`HydratorFactory` does comparison `isset($data['fieldname'])` before passing the database value to a corresponding *Type class for conversion. If the DB document does not contain at all the field, the hydrated value is always null.

I'd prefer that Type could decide how null values should be handled. Now there is no possibility to do that.

The Type could also tell Persister that it can remove the field from the document. If Type returns null, an explicit null value is currently persisted to the database (even it might not needed).

**Comment by MidnightDesign** [comment]
I also need this functionality. My custom type is supposed to return a special null object if the value stored in the database is `null`. Unfortunately, it doesn't even get called.

Until this is "fixed" I'll just do the following in my entity:

```php
public function getFoo() {
    if($this->foo === null) {
        $this->foo = new MySpecialNullObject;
    }
    return $this->foo;
}
```

**Comment by malarzm** [comment]
Just for the record delegating decision is not enough, as lately I've learned when doing #1466 the type would also need to know mapping: for instance `null` passed to `string` type should normally result in an empty string unless `nullable` is set to true when we in fact want `null` as the result of conversion.
