### ISSUE TITLE
HydratorFactory only autogenerates cache files "always" or "never"

### ISSUE THREAD

**Issue by kperry42** [doctrine/mongodb-odm#889]
Re-generating a hydrator class file every single time you want to read it seems wasteful (and messes with the file modification tracking in my IDE), but I'd certainly like to be able to generate them when necessary, so "never" isn't often enough.  It would be great if you could configure the HydratorFactory so it would generate a class file "if ( ! file_exists($fileName) )".

**Comment by malarzm** [comment]
#953 has been merged implementing the feature
