### ISSUE TITLE
Doubled sort and limit parts of query statement ...

### ISSUE THREAD

**Issue by dmarko484** [doctrine/mongodb-odm#898]
I'm using the lastest Doctrine/MongoDB ODB in Symfony 2.5 and in query log (in debugbar) I can see that limit and sort parts of query statement  are mentioned twice e.g. 

db.comp.find().sort({ "CompanyName": "DESC" }).sort({ "CompanyName": "DESC" }).limit(20).limit(20);

**Comment by GijsL** [comment]
I have noticed the same behaviour in Symfony 2.3. Cant upgrade right now so not sure if this is fixed in a future version.

**Comment by acrozes** [comment]
+1
Sample:

db.Profile.find({ "account": ObjectId("5568e6a99f51723811000031") }).sort([ ]).limit(1).limit();

**Comment by aRn0D** [comment]
Same here, I get that `db.collection.find({ "_id": 12641 }).limit(1).limit(); when I use `DocumentRepository::find`

The `doctrine/mongodb` version is 1.2.1

**Comment by gnsimoes** [comment]
Hello,

Do you have any solution for that?
I have the same problem: ".limit(1).limit();"

**Comment by malarzm** [comment]
Could someone please create a failing test case?

**Comment by malarzm** [comment]
Added tests in bundle which is responsible for formatting queries: https://github.com/doctrine/DoctrineMongoDBBundle/pull/394
