### ISSUE TITLE
UnitOfWork issue with Embedded Documents

### ISSUE THREAD

**Issue by ClementGautier** [doctrine/mongodb-odm#910]
Hi,

I have several blocking issues with events on EmbeddedDocument:

* getParentAssociation don't work with EmbeddedDocument in Pre* events, it return null as parent.
* PreRemove or PostRemove aren't triggered on EmbeddedDocument

Is it supposed to work ?

**Comment by malarzm** [comment]
> PreRemove or PostRemove aren't triggered on EmbeddedDocument

This should be fixed now, please feel free to reopen if it is not.
