### ISSUE TITLE
Document embeding Document embeding document with GridFS inside.

### ISSUE THREAD

**Issue by broiniac** [doctrine/mongodb-odm#911]
Um, hello :)

I've got a bit of a problem...  it's a  bit nippy... 

Some background:
Three are a three documents. Four actually - Lets call them BaseDocument, Game, Map and Media.
- BaseDocument is MappedSupperClass, with fields like Id, CreatedAt, UpdatedAt, and some callbacks for them. (dont know is this a good practice...)
- Game extend BaseDocument and has Name field and Maps field, which embedMany Maps.
- Map has Name field and Media field, which embedOne Media.
- Media has one field (File) and many callbacks.

Above schema was working in my head, but after project start it fail. I wasn't able to embed Games. When I've figure it out I was still taking "zero-length keys are not allowed, did you use $ with double quotes?" error.
I've find out in this topic (only one I've found: http://stackoverflow.com/questions/11857975/gridfs-using-mongo-odm-not-working dated at Feb 6) that embedding anything, which use GridFS Isn't (wasn't?) possible. 

So in general my questions are: 
- Is this possible (at current mongodb-odm project state) to build document tree like above? 
- Is it possible to embed Media/Class with GridFS at all (even on first level)?

I'm asking, because I'm just curious - my project is barely started and I know perfectly how to solve this issue with references, but I've figure it out, that using my Media class an embed document will be best solution for this project.

**Comment by alcaeus** [comment]
This is something we want to change with the new GridFS implementation in 2.0: a file will likely no longer just be a property in a document but will be treated as the root-level object it actually is in MongoDB, with all other fields being `metadata` for that file.
