### ISSUE TITLE
Version number does not increment when you remove an embedded collection

### ISSUE THREAD

**Issue by blockjon** [doctrine/mongodb-odm#922]
I have a Doctrine ODM document that uses the `@Version` feature. One of the properties on my document is an embedded collection.

I notice that when I make additive updates to my document, the version number is incremented via this Doctrine code:

https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php#L348-L362

However, I also noticed that when I remove from my document the embedded collection value, the version does not increment.

This is likely due to the differences deletions are triggered via this code:

https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php#L73-L88

I would like to be able to have my version number increment when items are removed from my document even when the item is an embedded collection.

How do I make my version number increment when I remove my embedded collection from my document?

Example test which demonstrates the problem:
https://gist.github.com/blockjon/857d7cba7cdb4c865cf9

**Comment by jmikola** [comment]
#985 is merged, so this should be fixed.
