### ISSUE TITLE
Raise an exception if a same name is defined for multiple fields

### ISSUE THREAD

**Issue by vmattila** [doctrine/mongodb-odm#924]
Consider following document

``` php
/**
 * @MongoDB\Document
 */
class Person
{

    /**
     * @MongoDB\String(name="a")
     */
    public $address;

    /**
     * @MongoDB\Boolean(name="a")
     */
    public $active;
}
```

Even `a` is set as a name for two fields, ODM silently ignores this and takes the last field in use. It would be useful if a `MappingException` or some other suitable exception was thrown.

**Comment by alcaeus** [comment]
I'm against adding an option to allow overriding, but moving to the respective drivers would make sense. I've scheduled this for 2.0.0 as it constitutes a BC break and it should come with appropriate deprecation warnings in 1.3.

**Comment by malarzm** [comment]
I think that instead of throwing exceptions and introducing new options, we could add feature to the schema validator (introduced in #1519) to inspect field names. In such case we have #1557 to track the feature. @alcaeus @jmikola any thoughts on this?

**Comment by alcaeus** [comment]
IMO, this is something that should be reported as an error. Regardless of schema validator, the schema doesn't make any sense, so we shouldn't try to work with it.

**Comment by jmikola** [comment]
It's been a while since I last looked at this issue, but I concur with having drivers throw exceptions. That should allow us to report an error if duplicate names are found in the same mapping "file", but still allow mappings to be overridden by children.
