### ISSUE TITLE
ClassMetadata: associationMapping is not filled for association inherited from documents

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb-odm#927]
We have the following use case:
```php
/** @ODM\Document */
class ParentDocument
{
    /** @ODM\Id */
    protected $id;

    /** @ODM\ReferenceOne(targetDocument="ReferencedDocument") */
    protected $reference;
}

/** @ODM\Document */
class ChildDocument extends ParentDocument
{
}

/** @ODM\Document */
class ReferencedDocument
{
    /** @ODM\Id */
    protected $id;
}
```

When looking at the classMetadata for the child document, there is no associationMapping recorded for the reference association. When changing ParentDocument to a mapped superclass, the associationMapping is recorded correctly.

Update: Test for the error: https://github.com/VoycerAG/mongodb-odm/commit/57be9c58c21f0dbfd1ae728bdb2d6d5871d7413d

It might be enough to add the associationMapping when adding an inherited field. However, there are differences in the handling between documents and mapped superclasses, so I wasn't quite sure where to add this.

**Comment by data219** [comment]
:+1:

**Comment by malarzm** [comment]
#958 has been merged in https://github.com/doctrine/mongodb-odm/commit/55ce2b3ad32fcf3eef1e8a733d8a479c966501d3
