### ISSUE TITLE
Passing null as id in qb->remove() drops the whole collection

### ISSUE THREAD

**Issue by TomiS** [doctrine/mongodb-odm#928]
Hi. 

Let's say I make the query in following snippet. The result is that whole collection will be dropped. I'd like to ask if this is intended or not.

```
$qb = $dm->createQueryBuilder('MyClass')
                ->remove()
                ->field('id')->equals(null)
                ->getQuery()
                ->execute();
```

This can easily happen if I'm, for example, using $myArray['id'] in place of null and the value of $myArray['id'] just happens to be null for some reason (corner case, etc). It feels a bit harsh for document manager to react by emptying the whole collection :)

**Comment by malarzm** [comment]
@TomiS passing test case [was added](https://github.com/doctrine/mongodb-odm/blob/49fbc3e037a50d4cb22f710be8bcd70e24e648bf/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH928Test.php) to the code base, feel free to submit an update to make it fail.
