### ISSUE TITLE
If I call a referenced object more than one time it's not initialized twice

### ISSUE THREAD

**Issue by dVaffection** [doctrine/mongodb-odm#950]
Suppose I have **Project** and **Task**. Project was deleted while a bunch of tasks still exist in db referencing to the same non-existing project. 

When I fetch these tasks and iterate through them I ask for a project object the current task references to. For the first time when I call any method different from `getId` on a task Doctrine loads it using `Doctrine\ODM\MongoDB\Proxy\ProxyFactory` and in case it doesn't exist in db throws `Doctrine\ODM\MongoDB\DocumentNotFoundException` exception. So far so good. 

Now when I proceed to another task (which also references to the same non-existing project)  `Doctrine\ODM\MongoDB\Proxy\ProxyFactory` asks for a proxy object if it was initialized. And it actually was because `$proxy->__setInitialized(true);` is called prior to exception indicating that actual object was never loaded from the db.

**Comment by malarzm** [comment]
#1336 aims to address the issue
