### ISSUE TITLE
__PHP_Incomplete_Class error when trying to access object referenced by one object and has been stored in session

### ISSUE THREAD

**Issue by vineetvermait** [doctrine/mongodb-odm#955]
Hi,

I have a document which i do not want to access again and again from the db, when i retrieve the object for the first time from the db and use it,..the system works fine, but when i save the object into session variable, and then try to retrieve it later, the object gives me __PHP_Incomplete_Class error.

```
/** @ODM\Document */
class foo {
/** @ODM/ReferenceMany(targetDocument="bar")*/
$attrib;
}

/** @ODM\Document */
class bar {
/** @ODM/Field(type="string")*/
$value;
}
```

when i retrieve the object foo from db...it has the values of bar as well.

i save the same object into session and then when i retrieve it, the error comes up

**Comment by malarzm** [comment]
Hopefully @vineetvermait your issue is solved by now, if not please use StackOverflow/IRC for support questions.

**Comment by vineetvermait** [comment]
Hi,

I made a few changes in the core code by taking a fork and then making the changes,.. Also i have raised a pull request for the same but it seems that there is some build issue.

Please check if u find the code changes ok...?

may be my code may be missing something..

after my changes the code was working fine

**Comment by malarzm** [comment]
Sad to hear that but hopefully it serves you well :)
