### ISSUE TITLE
$elemMatch operator with a datetime inside is not converted to the database value

### ISSUE THREAD

**Issue by monteiro** [doctrine/mongodb-odm#957]
The problem I think could be in file DocumentPersister->prepareQueryOrNewObj(array $query)
**$and = [ 0 => [ myElemCollection => $elemMatch => [ mydate => [$lte => new \DateTime()] ] ] ];**

If I use a datetime inside an elemMatch, that is not converted to the database value which is a \MongoDate.

Can anyone confirm this bug?

**Comment by malarzm** [comment]
Everything seem to be working fine, this test passes on 1.0.3:

```
    public function testDateInElemMatch()
    {
        $qb = $this->dm->createQueryBuilder('Documents\User');
        $qb->addAnd(
            $qb->expr()->field('meh')->elemMatch(
                $qb->expr()->field('date')->lte(new \DateTime())
            )
        );
        $this->assertInstanceOf('MongoDate', $qb->getQuery()->debug()['query']['$and'][0]['meh']['$elemMatch']['date']['$lte']);
    }
```
