### ISSUE TITLE
Allow custom repositories to be resolved externally & setter inject environment.

### ISSUE THREAD

**Issue by atrauzzi** [doctrine/mongodb-odm#962]
*( see here: https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/DocumentManager.php#L518 )*

Currently, when  `getRepository` is called on instances of `DocumentManager`, it calls `new` internally, passing environment information in as constructor arguments.

I'm reasonably certain that users might be better served by having this system changed in two ways:

 - Allow for the configuration of a resolve callable which receives the fully qualified class name as a `string` parameter.
 - Assign `$this`, `$this->unitOfWork` and `$metadata` via setter methods so that the constructor is free to be leveraged by the subclass and the implementer's IoC ecosystem.

Right now, binding repositories to my container is a very manual process because Doctrine assumes some of the duty of the IoC.  Depending on what I would have normally constructor-injected into my repository, the code I write ends up being a lot of manual intervention and boilerplate.

By allowing the system to be pluggable and flipping Doctrine's interest around, Doctrine can specifically address it's concerns while leaving the more desirable constructor touchpoint to the developer.  If the container supports reflection for automatic injection, 100% of the code is eliminated because it is now resolving all dependencies transparently.

**Comment by malarzm** [comment]
#892 has added ``RepositoryFactory`` which should be enough to solve the issue, please feel free to reopen if it is not sufficient.
