### ISSUE TITLE
PersistentCollection count, isDirty and initialize

### ISSUE THREAD

**Issue by redthor** [doctrine/mongodb-odm#963]
Hi there,
I'm doing the following:
1. Adding an object to PersistentCollection
2. Saving PersistentCollection
3. Attempting to get the object out of the PersistentCollection

What I find is that `$this->pColl->count()` is returning 1, which is what I expect. Note `count()` does not call `initialize()`.

When I call `toArray()` `initialize()` is called and the `isDirty` is false, so the collection is cleared and the object I added is lost. I get zero members back and now `count()` is zero.

The PersistentCollection is being saved to the DB.

I'm using the latest "dev-master".

Any help is appreciated.
Thanks.

**Comment by rubenrua** [comment]
In https://gist.github.com/rubenrua/55ed88c087311542c563 you can found a test to debug this error.

**Comment by malarzm** [comment]
https://github.com/doctrine/mongodb-odm/pull/981 seems to be fixing this error as well

**Comment by jmikola** [comment]
Fixed by #981, which was merged in https://github.com/doctrine/mongodb-odm/commit/b00177ce241214cfaf2eb2a01885d964a55a8ed8.
