### ISSUE TITLE
Embed Many object not being embedded in the DB

### ISSUE THREAD

**Issue by vineetvermait** [doctrine/mongodb-odm#965]
I have a class structure as below:
class A{ /** @ODM\EmbedMany(targetDocument="K")*/ private $k=array();}
class K{ /** @ODM\EmbedMany(targetDocument="K")*/ private $s=array();}

when there are not nesting K objects in the map i get the field stored as "s":[]

but when the same var $s has some value the entire field it self is missing in the DB. Till recently it was working fine but now after some composer update i have lost the proper functioning.
Composer require String: 

        "doctrine/mongodb-odm": "1.0.0-BETA11",

**Comment by malarzm** [comment]
@vineetvermait any chance for update?

**Comment by vineetvermait** [comment]
Hi,

Please close the hug as I am not able to replicate or predict when it
occurs...I guess the use case in which I was using has been overwritten by
another logic...

Thabks for the support
