### ISSUE TITLE
Embedded document and Query::HINT_REFRESH

### ISSUE THREAD

**Issue by vkartaviy** [doctrine/mongodb-odm#968]
It looks like refresh queries using ``Query::HINT_REFRESH`` are creating a new embedded document instead of updating values of existing one.

For example:

```php
$embed = $document->getEmbed();
// ... do query with HINT_REFRESH
echo $embed === $document->getEmbed() ? "Same" : "Not";
```
Outputs: **Not** :cry:

**Comment by malarzm** [comment]
Please see https://github.com/doctrine/mongodb-odm/pull/995#issuecomment-87244576 for details why this won't be fixed for now
