### ISSUE TITLE
Changes before manual computeChangeSet are not saved to db

### ISSUE THREAD

**Issue by malarzm** [doctrine/mongodb-odm#977]
Lately I was trying to find a way to know if my document's data has been changed in my own event listener (which is working before DocumentManager's flush) and I decided to use UnitOfWork's ``computeChangeSet`` method. Changes are calculated properly but later if I change something else in document then these changes are lost and only latest are saved to database (unless I explicitly call ``recomputeSingleDocumentChangeSet``). I believe this is happening because UnitOfWorks always calculates changes, never recalculates them even if changeSet already exists. Is there any reason for this?

Here's test case failing on dev-master:
```
<?php

namespace Doctrine\ODM\MongoDB\Tests\Functional;

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Doctrine\ODM\MongoDB\Tests\BaseTest;

class ManualComputeChangeSetTest extends BaseTest
{
    public function testAutoRecompute()
    {
        $d = new Document();
        $d->value1 = "Value 1";
        $this->dm->persist($d);
        $this->dm->flush();
        $this->dm->clear();
        $d = $this->dm->getRepository(get_class($d))->findOneByValue1("Value 1");
        $d->value1 = "Changed";
        $this->uow->computeChangeSet($this->dm->getClassMetadata(get_class($d)), $d);
        $changeSet = $this->uow->getDocumentChangeSet($d);
        if (isset($changeSet['value1'])) {
            $d->value2 = "v1 has changed";
        }
        // with next line uncommented test passes
        // $this->uow->recomputeSingleDocumentChangeSet($this->dm->getClassMetadata(get_class($d)), $d);
        $this->dm->flush();
        $this->dm->clear();
        $d = $this->dm->getRepository(get_class($d))->findOneByValue1("Changed");
        $this->assertNotNull($d);
    }
}

/** @ODM\Document */
class Document
{
    /** @ODM\Id */
    public $id;
    
    /** @ODM\String */
    public $value1;
    
    /** @ODM\String */
    public $value2;
}
```

**Comment by jmikola** [comment]
> Lately I was trying to find a way to know if my document's data has been changed in my own event listener (which is working before DocumentManager's flush) and I decided to use UnitOfWork's `computeChangeSet` method.

On which event were you listening? Is there a reason you weren't able to use `getDocumentChangeSet()` to access the changeset and instead thought to calculate it?

AFAIK, `computeChangeSet()` will always end up resetting the original document data, which means you'll lose the original changeset. `recomputeSingleDocumentChangeSet()` is most certainly what you'd like to use, since it will pass the necessary boolean to `computeOrRecomputeChangeSet()` and ensure the new changes are merged atop the existing changeset (see: [here](https://github.com/doctrine/mongodb-odm/blob/d305acad9307a9f7419ec8a6f904de2fae38f770/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L808)).

**Comment by malarzm** [comment]
For the background I'm not using any of Doctrine events, I'm dispatching my own events when I'm about to save something and calling `flush()` at the very end of flow. Problem is that I have called manually `computeChangeSet` to take advantage of having something that actually can calculate change set instead of rolling my own implementation and later during `flush()` UoW calls `computeChangeSets()`

**Comment by alcaeus** [comment]
#1306 was merged, closing ticket.
