### ISSUE TITLE
Alternative to APC in PHP5.6

### ISSUE THREAD

**Issue by bensquire** [doctrine/mongodb-odm#993]
Hi Guys,

I'm looking to upgrade our systems to PHP5.6, but I noticed that APC (which we use) has been removed and replaced with opCache. What would be the recommended course of action? Install [APCu](https://github.com/krakjoe/apcu) or xCache or have I missed something?

Thanks
Ben

**Comment by malarzm** [comment]
I think now we all know about APCu, closing issue :)
